### ISSUE TITLE
OpenAL causing huge numbers of compilation errors

### ISSUE THREAD

**Issue by accursedCursive** [endless-sky/endless-sky#3592] opened 2018-01-20 13:18 UTC
I know that this isn't a game issue and thus is the sort of thing that should be on SPUD, but even when I replied to someone else's thread regarding this issue it resulted in the thread being locked.

I had 50 compilation errors, 1 undefined SDL function and 49 undefined OpenAL functions.
I solved the SDL one by adding the following flags in "other linker options":
-lSDL2
-lSDL2main

So, 49 errors to go.
I'm guessing the OpenAL solution is similar, but I don't know the flags.

**Comment by comnom** [comment] 2018-01-20 13:33
Your paths are incorrect. Don't use relative paths, and don't copy my paths as they're all specific to my environment, but verify the following under Project->Build Options:


![cap1](https://user-images.githubusercontent.com/22107649/35183955-6134ea7c-fdbc-11e7-9085-fe4948a2097e.png)
![cap2](https://user-images.githubusercontent.com/22107649/35183957-6344ff82-fdbc-11e7-8c3f-91890515ded3.png)
![cap3](https://user-images.githubusercontent.com/22107649/35183960-6502fee6-fdbc-11e7-9b5b-ebbac29999e9.png)

**Comment by accursedCursive** [comment] 2018-01-20 13:37
Why would you have something linked manually and with a search directory?

**Comment by comnom** [comment] 2018-01-20 13:39
No good deed goes unpunished as they say. You have your answer, close the issue please. I don't have the patience for more.

**Comment by Wrzlprnft** [comment] 2018-01-20 15:45
We can't really help.

You customize your installation to something other than default => we have bo idea where your stuff is.

so, you'll have to customize your paths too. all libraries are give in either the dev-folder to download, or are part of the mingw-install.

i am sorry if this is not the answer you are looking for, since it is basically the same as said on steam, without the offer to help you via a more direct way of commincation

**Comment by accursedCursive** [comment] 2018-01-20 20:19
@Wrzlprnft Everything I need is in a search directory.

**Comment by jafdy** [comment] 2018-01-20 20:36
The evidence would suggest otherwise.

**Comment by Wrzlprnft** [comment] 2018-01-20 22:12
Ah, my bad, i just scanned through.
it's kinda hard not to fall into the “wolf - boy - town“ story thing.

though, the answer is probably the same, at least from my side: if you customize your setup, it's easier to help in a 1 on 1 chat, because here it would be slow, riddled with misconceptions, probably on both sides.

**Comment by accursedCursive** [comment] 2018-01-20 22:52
This isn't an issue unique to me, and people refusing to help outside of a one-on-one chat is exactly why I couldn't just look up the answer to this issue.
Additionally, a solution that is more public and exposed for a longer duration will be more likely to end up in documentation.
This problem should be thus be discussed and solved in a thread.

Also, chat should not be necessary for anyone who actually understands the issue, fast messaging just encourages worse answers.

**Comment by warp-core** [comment] 2018-01-20 22:57
Compilation issues are usually unique to whoever is having them. The only constant is generally an inability to correctly follow the instructions provided. They clearly work if followed correctly.

Anyway, with regards to your issue, why don't you start by showing us screenshots of the linker settings and search directories you have as well as the entirety of your compiler log.
(That last part might need to be copied into a pastebin or something.)

**Comment by accursedCursive** [comment] 2018-01-20 23:58
That's the kind of answer that anyone can provide.
_Of course_ it will work if everything is set up in the exact same way as it is for someone it works for.
But then that means that everyone has to work with that exact setup, and no one actually knows why that exact setup is necessary other than it being the only known setup that works.

If this problem is approached as it should be, by identifying the exact cause of it, then it becomes possible to use cleaner setups with a higher toleration for system differences.

I can compile it fine if I use the exact setup other people have, but why should I have to do that when I should just be able to use search directories? Something's clearly wrong.

**Comment by TheUnfetteredOne** [comment] 2018-01-21 00:12
Stop. Just... Stop.

**Comment by kikotheexile** [comment] 2018-01-21 01:29
Your
Build
Issues
Are
Specific
To
You
And
You
Alone
Meaning
Issues
And
Forum
Threads
Are
Counter
Productive
And
Help
No
One

**Comment by jafdy** [comment] 2018-01-21 08:13
If it is a problem with the linker then you should probably ask the person who created the linker (similar with problems caused by other part of the process). Quite frankly, the need to compile the game is to test gameplay changes so the fact that you can't do it _your_ way is completely irreverent if you can do it another way (like the way someone else has already used).

**Comment by Wrzlprnft** [comment] 2018-01-21 09:15
Once we find an answer in a one on one chat with more information, without delay of half a day of answers (you pretty fast forget things if you have to wait half a day on the answer of what version of x someone is using) we DO normally post this stuff. In a forum it is just inconvenient. Voice chat would even be better. it's not like we'd post git gud or get linux or leave you alone. the past has shown that troubleshooting is time consuming on custom setups, so we have a preffered way, which makes it easier for us to help you.

the google group would probably be the right place if you insist on a forum based solution. too rare (2 cases?) for github, too technical for steam

**Closed** 2018-01-24 01:43 UTC
