### ISSUE TITLE
Captured escort is stuck landing then taking off

### ISSUE THREAD

**Issue by quantumandan** [endless-sky/endless-sky#1489] opened 2016-08-23 21:57 UTC
I captured a small pirate ship, had enough crew this time, I lost one guy, the pirates lost one guy (I had 3 extra to take over and pilot the craft) -- no msgs about either ship not having enough crew. However, now I am trying to take the ship to another system to sell it but it seems to be stuck in the landing cycle (visually, I can see the ship landing and taking off, ad-nauseum). I have tried shooting the escort (while I can't target the ship via the keyboard, I can use the mouse to select it), and have tried disabling the ship in between landing cycles, boarding, repairing; but no luck, the ship just keeps cycling. I've also tried interupting the cycle by saving and reloading and trying a gather or a fight command. (reposted from steam)

**Comment by Amazinite** [comment] 2016-08-23 22:30
Duplicate of #1290. 
Check for duplicates before reporting.

**Closed** 2016-08-28 00:06 UTC
