### ISSUE TITLE
Tactical settings for escorts

### ISSUE THREAD

**Issue by Karirawri** [endless-sky/endless-sky#5910] opened 2021-04-28 15:32 UTC
Currently, escort ships apparently choose their targets at random, based on whatever is closest to them. This can result in ships getting lost in deep space fights with no backup, and lots of micromanagement on a fight that makes it difficult to focus on killing.

While playing Pokémon Mystery Dungeon, a completely unrelated game, i got an idea. There, you can choose tactics and skills for each of your followers, such as making them focus on attacking the target with lowest HP, or the ones that give more experience, or spread out an attack individually, via their individual "IQ" level. Some of those skills are even straight up buffs, like a higher chance to dodge, but some buffs are mutually exclusive to other buffs, to prevent it being OP.

Something similar can be implemented on Endless sky, with options that modify the AI of the escort ships to focus on attacking the ships that are closest to the player (to increase survival odds without spreading out), or focus on attacking the ships with lowest health (to end combat quickly with more risk), attack from the furthest range possible, flee into deep space if low on health, or toggle missile boat AI if low on health, and possibly more.

These tactics could even be unlocked one by one based on the player's combat rating, giving it another purpose, and a feeling of "leveling up", and if we go that route, similar buff skills could be added as well, like more energy efficiency, or a chance to take no damage, but the main suggestion is the tactics.

These could be applied indidually to each ship in the ship info screen, with check boxes for tactics, or in the settings globally, but ideally they should be separate from orders, like attacking or holding position.

**Comment by Amazinite** [comment] 2021-05-02 00:37
I think I'd consider this basically a duplicate of #802.

**Comment by Zitchas** [comment] 2021-05-02 00:41
Mmmm, it doesn't match how 802 starts out, but it does seem to be the same sort of idea.

**Closed** 2021-05-15 18:16 UTC
Labels: duplicate
