### ISSUE TITLE
Job Board list showing payment

### ISSUE THREAD

**Issue by damccull** [endless-sky/endless-sky#4374] opened 2019-06-16 14:18 UTC
Hello,

I'm loving the game and hope to see more storylines and content created over time. In the meantime, however, I am wondering if it'd be possible to have the job board list the payment next to its name so it isn't required to read through all the text of each mission, and players can mentally filter out jobs that pay too little for them to want to accept.

Is this something that's doable?

**Comment by tehhowch** [comment] 2019-06-16 15:37
Duplicate of #236

See also #1507, #2260, #3189 and others.

Please refrain from ignoring the issue templates. They are there for a reason.

**Closed by tehhowch** 2019-06-16 15:37 UTC

**Comment by jostephd** [comment] 2019-06-16 17:01
To be fair, @damccull wasn't asking for sorting. He was asking to show the payment more clearly. That could possibly be done without sorting. However, I think that's not _quite_ so straightforward to implement, since a mission may pay more, or less, than it promises the player up front, like the April fools' day job does. (That's not a good example, probably, but you can imagine a pirate job where 90% of the time it pays what it says on the tin and 10% of the time it spawns a war fleet that double crosses you and tries to disable you and loot the cargo without paying.) The engine knows how much the mission will _actually_ pay, but doesn't know how much the mission description _claims_ it will pay, so it can't present that information, never mind sort by it.
