### ISSUE TITLE
[Bug report] Missing player details, config files and save directory

### ISSUE THREAD

**Issue by mdziczkowski** [endless-sky/endless-sky#6306] opened 2021-10-28 13:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the folder structure (after extracting the AppImage file), there are missing following important files and folders:

- configuration files
- save dir folder
- player related configurations (player info, ships, etc.)

### Steps to Reproduce

1. Extract the AppImage file
2. Search for the things mentioned in the "bug description"

### Expected Behavior

Finding the mentioned filers and folders

### Operating System

Debian 10 (64-bit)

### Game Source

GitHub Releases

### Game Version

0.9.14

**Comment by mdziczkowski** [comment] 2021-10-29 19:37
@tehhowch That why I had offered in the issue #6305 to flaten the directory structure and replace the AppImage with an compressed archive, so you could launch it from example from a USB stick :-)

**Comment by MCOfficer** [comment] 2021-10-29 19:55
> 
> 
> @tehhowch That why I had offered in the issue #6305 to flaten the directory structure and replace the AppImage with an compressed archive, so you could launch it from example from a USB stick :-)

The problem is that the game is also installed on systems where writing to the install directory is impossible (for example, when you install from the ubuntu repos). Offering possibilities where it is possible doesn't eliminate those where it isn't.

**Comment by mdziczkowski** [comment] 2021-10-29 20:04
That why I'm trying to find an workaround for it.

I think that in the case of Debian and it's deverative systems, there is a possibility to make it run from the same directory as the game, but it would need (as suggested) to flatten the folder structure (example bellow) and distribute it as an compressed archive instead of an AppImage or installer.

Example structure:

[game root]
|
|--[bin]
|--[config]
|--[data]
|  |--[images]
|  |--[sound]
|  |--[text]
|
|--[plugins]
|
|-- other files

**Comment by MCOfficer** [comment] 2021-10-29 20:11
> 
> 
> That why I'm trying to find an workaround for it.
> 
> I think that in the case of Debian and it's deverative systems, there is a possibility to make it run from the same directory as the game, but it would need (as suggested) to flatten the folder structure (example bellow) and distribute it as an compressed archive instead of an AppImage or installer.
> 

The structure of the game's files are irrelevant. *As long as we support installing to system folders - which we do - saving to the install directory cannot be done*.

**Comment by warp-core** [comment] 2021-10-29 20:25
Not entirely sure that this is what you're asking, but if you want to be able to put the game executable in a folder and have the save files, preferences, etc, stored in the same place for portability, I think you can use the argument `-c` or `--config` followed by the path you want it to use when launching the game and it'll use that location instead of the default.
https://github.com/endless-sky/endless-sky/blob/de854aeb6e37128f03e60869c9deb39d7b22edf3/source/main.cpp#L369

**Comment by mdziczkowski** [comment] 2021-10-31 18:50
Let me try to explain since I that there is some confusion here.

note: The mentioned apply only for Linux systems.

After extracting the AppImage (because a compressed archive for Linux is unavaliable for now), the folder structure (inside the squashfs folder) is like for instalation propouses.

My goal was to make it the way that it could be run from any place (for example: USB stick) without messing up with the system folders. Note that some Linux may be configured that only few folders may be writable for users and that may prevent the game from working.

My solution would allow to run it independently from this folders

**Comment by tehhowch** [comment] 2021-10-31 19:40
> Let me try to explain since I that there is some confusion here.
> 
> note: The mentioned apply only for Linux systems.
> 
> After extracting the AppImage (because a compressed archive for Linux is unavaliable for now), the folder structure (inside the squashfs folder) is like for instalation propouses.
> 
> My goal was to make it the way that it could be run from any place (for example: USB stick) without messing up with the system folders. Note that some Linux may be configured that only few folders may be writable for users and that may prevent the game from working.
> 
> My solution would allow to run it independently from this folders

You can do that with the files you have there already: create a wrapper shell script that invokes the binary with the `--resources` and `--config` flags set to the desired directories.

**Comment by mdziczkowski** [comment] 2021-11-01 12:50
Thanks. That's a good solution too ;-)

Did anyone checked why for the Linux is only a AppImage created and no compressed archive?

If someone manages to make the archive creation then the both of our ideas could become implemented that other persones would have lighter ;-)

**Comment by tehhowch** [comment] 2021-11-03 01:59
> Did anyone checked why for the Linux is only a AppImage created and no compressed archive?

It's because there is no corresponding stage in the actions workflow file. I don't particularly see a reason to add one, either, since anyone who packages Endless Sky for a storefront / distro will be compiling it themselves anyway, to ensure the required libraries are present for the target system.
That said, feel free to contribute the necessary modification if you feel strongly enough about it.

**Comment by tehhowch** [comment] 2021-11-03 02:02
Closing since there is not actually an issue, and the questions are answered.

**Closed** 2021-11-03 02:01 UTC
Labels: question
