### ISSUE TITLE
[question/content] James vs. Earth/Midgard descriptions

### ISSUE THREAD

**Issue by toilethinges** [endless-sky/endless-sky#1709] opened 2016-10-14 02:23 UTC
To sum it up, James says that Earth has a population of ten billion, but the Earth spaceport says that it has a population over 10x as much as any other inhabited planet, and Midgard has a population of four billion, therefore, Earth should have forty billion plus.

**Comment by Lineth** [comment] 2016-10-14 03:25
I think ten billion is more reasonable for Earth's population. Industrialization lowers birth rates, and the ~7B on Earth is a little crowded as is. Assuming the rate of development doesn't crash through the floor, ~10B is a reasonable-enough point of stabilization for the world population.

I'm just spit-balling and giving my opinion, though, so take that for what little it's worth.

**Comment by retrue** [comment] 2016-10-14 08:23
At Lineth. The problem is that the Earth of this game is not a world with a reasonable stabilized population. It is a overcrowded bad place that everybody wants to leave. So it could have a population around 30B or more.

**Comment by KiLEdEnNis** [comment] 2016-10-14 09:08
or James is getting too old

**Comment by DingusShingleton** [comment] 2016-10-14 11:08
Also keep in mind, earth irl is a bit crowded but we only have one planet to supply us with food and resources... earth in ES has a whole belt of planets to supply it, and presumably a host of advanced construction techniques and technologies that could drastically increase population density in new and existing cities alike.

**Comment by Disiuze** [comment] 2016-10-14 11:44
It could also be a hyperbole.

**Comment by toilethinges** [comment] 2016-10-14 13:28
@DingusShingleton, @Amazinite and I discussed the population of Earth before finding this James quote (I've only done the James quests once or twice on Shuttle), and thought about the same thing.

@Disiuze, why, hyperboles, why?

**Comment by Amazinite** [comment] 2016-10-14 16:22
"Back in my time, earth only had 10 billion people on it."

**Comment by MessyMix** [comment] 2016-10-14 17:15
@Disiuze It could also be a hyperbola.

**Comment by warp-core** [comment] 2016-10-14 21:24
Overall, Earth isn't overcrowded right now, it's just that the population isn't using all the space stainable and we're definitely not using it as effectively as possible. In 1000 years the population could easily reach 10s of billions of inhabitants. Both India and China have extremely high populations in relatively low total areas, in comparison to the entire area of the Earth and there are still vast swathes of land in places like Russia, Canada and the US that are empty. Imagine the possibilities when almost everywhere has skyscrapers since there would be little need for farmland at that point.
@Amazinite that could work but I'm not sure if the population could double or triple in half a century. Maybe considering how many people there are to start with.

**Comment by Amazinite** [comment] 2016-10-14 22:04
@warp-core I know, it was mainly a joke. But now I'm going to logic/math it out.

- The UN estimates that we'll have just under 11 billion people by 2100.
- Earth is estimated to only have the carrying capacity for 10 billion people.
- So the population of the world is eventually going to level out at around 10 to 11 billion, dipping above and below that number over the years.
- Assuming no nuclear wars that wipe the slate clean (while also irradiating it), Earth would be stuck at that number until other planets can support Earth to make it hold more people.

Jumping into the Endless Sky Timeline
- The Hyperdrive isn't created until 2210, so it isn't until then that there is the chance for Earth to carry more people.
- Humanity focuses on colonizing more worlds, so they have to support themselves more than anything. Maybe Earth's population grows a bit, but not much.
- Turf and Alpha wars happen, people are more worried about war, dark ages probably stop any extra food getting to Earth, etc.
- 2620: caravan era.
- Only now does Earth probably have the chance to grow its population beyond its capacity.
- But, the Dirt Belt isn't inhabited yet. Most inhabited worlds are either the Deep, Paradise Worlds, or Syndicate mining and industry worlds, so there isn't enough of an abundance of food to push Earth very far.
- Colonization increases in 2770, space renaissance begins at 2800.
- 2900: pretty much everything is inhabited now.
- Let's assume that Earth has gotten to about 15 billion people at this point. Due to the Dirt Belt now being pretty much fully inhabited, lets assume that they provide enough food for Earth to grow its population. 
- Using some good old math and assuming that the population grows 1% every year (about what it does right now), 100 years could see Earth's population growing to 40.57 billion people.
- If Earth started at 10 billion at this point it would take 141 years to reach the same number, and starting at 12 billion (maybe a more reasonable number) it would take 121 years (which fits pretty nicely into the timeline).

So, considering that space merchants are probably the wealthiest people next to corporations, they would likely be able to buy all sorts of things to extend their lifetime. Leaving out any time-shenanigans about how merchants could probably live for hundreds of years due to all the hyperspace jumping, I wouldn't be surprised if James did live in a time where Earth's population was at about 10-15 billion.

**Comment by warp-core** [comment] 2016-10-15 12:01
@Amazinite I agree, I can't argue with your maths or logic, it makes sense that the population would rise at a similar rate to today since there may be lowered death rates due to better medical technologies but this would also result in the number of children a family has being lower on average. If anything, I'd expect the rate of population growth to be higher. Assuming that James would have been referring to 'his day' being when he as in his 20s or 30s, it does indeed work well since he could probably last 200 years.

**Comment by toilethinges** [comment] 2016-10-18 03:14
Hooray, it's fixed.

**Comment by Amazinite** [comment] 2016-10-18 11:51
**8 billion**

**Comment by MessyMix** [comment] 2016-10-18 19:44
uh... that's not a lot.

**Comment by Amazinite** [comment] 2016-10-18 20:56
Barely more than today. And today isn't such a bad place in time when it comes to global population.

**Comment by toilethinges** [comment] 2016-10-19 00:43
It could be more - we don't know that Midgard is the second most populous planet in human space, do we?

**Comment by Amazinite** [comment] 2016-10-19 01:18
Well James still says only 10 billion. 

Midgard has 4 billion.
Valhalla is older than Midgard; 5 billion is feasible.
Charon was the first planet outside of Sol to be colonized, (supposedly) older than Valhalla, so 5 billion there as well seems a bit low, unless we account for the theory that Valhalla was colonized during the middle ages.

**Comment by retrue** [comment] 2016-10-19 10:05
Changing the description of population of Earth from ten times to double was too conservative. Maybe three times is a better quantity. That would leave Earth population around 15B.

**Comment by Amazinite** [comment] 2016-10-19 11:46
I had a whole bit about the size and possible population density of the planet in Alpha Centauri in that edited comment, given that it was the first planet to be colonized and would thus likely have the second highest population, but I decided to remove it because of how the Deep would probably have the second highest population planets anyways due to being the most advanced for the longest.

**Comment by endless-sky** [comment] 2017-01-18 23:38
Closing this because 0.9.5 is released now.

**Closed by endless-sky** 2017-01-18 23:38 UTC
Labels: content
