### ISSUE TITLE
0.95 end of current Wanderer Mid storyline - can no longer capture Kor Sestor ships

### ISSUE THREAD

**Issue by solardawning** [endless-sky/endless-sky#2039] opened 2017-01-20 00:26 UTC
At the end of the Wanderer Mid storyline, Kor Sestor fleets are now only located in Korath Exile space. While these Sestor ships can still be captured, there is nowhere to land them to equip a Jump Drive.

This isn't explicitly a bug (it makes sense in the context of the story and gameplay), however I think it's worth an issue post as it can feel crummy to the end user in an open-ended game to take away access to a feature/usable thing that they had prior access to.

**Comment by Bladewood** [comment] 2017-01-20 02:01
I don't think this will be addressed until 0.9.7 (0.9.6 is just a bunch of bug fixes, and Michael's probably not gonna release a hotfix for something this big. I mean, it's not exactly large, but still.), so there's not much of a point in bringing it up now.

**Comment by solardawning** [comment] 2017-01-20 02:03
Sure there is - to mention it so that he's aware of it and can do what he will with that information in 0.9.7 (or whenever) =)

**Comment by Amazinite** [comment] 2017-01-20 02:53
I'm pretty sure he realizes what he's done through the current story and things will change in the end of the Wanderer story. Just hold tight. :)

**Comment by KiLEdEnNis** [comment] 2017-01-20 08:21
I already see it happen; Exiles invade, attack Efret w/ the drones, maybe the Mereti become hostile, and you have to eliminate the Exiles (maybe links open to exile space for the Wanderers), in the end the Efret make both Mereti & Sestor ships as military

**Comment by Pointedstick** [comment] 2018-11-20 22:14
Yep, this should be resolved by writing more of the storyline. For now, consider it to be as intended. :)

**Closed by Pointedstick** 2018-11-20 22:14 UTC
Labels: content
