### ISSUE TITLE
Have different Factions fine for different outfits and for different amounts.

### ISSUE THREAD

**Issue by Red-57** [endless-sky/endless-sky#5453] opened 2020-10-16 13:30 UTC
**Is your feature request related to a problem? Please describe.**
Currently when any faction scans you they all fine you the same amount and for the same outfits, it seems odd to me that every race in the galaxy has the exact same list of illegal outfits. 

**Describe the solution you'd like**
I think that you could put something in the government data about what they fine for, something like this

```
government "Navy Intelligence"
	swizzle 0
	"crew attack" 1.2
	"crew defense" 2.2
	"attitude toward"
		"Syndicate" -.1
		"Pirate" -.3
	"atrocity"
		"Drak Antimatter Cannon"
	"fine"
		"Nerve Gas" 1000000
		"Handheld Flamethrower" 4000000

```
 would let the individual government decide what to fine for instead of the outfit itself.

**Comment by Amazinite** [comment] 2020-10-18 08:38
Duplicate of #1429,

**Closed** 2020-10-18 08:38 UTC
Labels: duplicate
