### ISSUE TITLE
[question] Inconsistency with Pug Wormhole

### ISSUE THREAD

**Issue by MarcelineVQ** [endless-sky/endless-sky#1334] opened 2016-07-16 22:44 UTC
The difference between the Pug Wormhole and Wormhole Alpha is that Alpha has a `planet` entry which allows it to be marked as visited but also has the effect of displaying the wormhole link. Given the length of the link for the Pug wormhole a `planet` entry is probably not currently desirable but it does mean you can't complete Deneb as a 'visited' system.

Would it be reasonable for the display of wormhole links in general to have maximum distances so that the `visited` behavior of Alpha and Pug can be unified, and as future-proofing against further out-of-galaxy links?

Huh... _Pug_ Wormhole and _Alpha_ Wormhole, curious coincidence.

**Comment by KiLEdEnNis** [comment] 2016-07-17 11:27
I used to think that it had a max range, since human space coordinates are around 0, +- 1000 at max, but the Pleiades (Pug space) is at 10000 7000, and having such a long line may be annoying
maybe make it show if you click the system (if it's range is too far) so you can see where it leads

**Comment by LocalGod79** [comment] 2016-07-17 17:01
the planet entry will draw a purple line between the wormhole linked systems.

i believe this is undesired in the case of the Deneb Wormhole...

**Comment by Wrzlprnft** [comment] 2016-07-17 17:57
The issue is about systems with wormholes that don't have planet entries cannot be marked as 100% visited.

I'd say, since the game can already detect wormholes, exclude them for the visited mechanic completely?

**Comment by endless-sky** [comment] 2016-07-20 23:43
Fixed in d120832 (by making wormholes not count when checking whether a system is fully visited).

**Closed** 2016-08-02 06:19 UTC
Labels: bug
