### ISSUE TITLE
Mission not triggering

### ISSUE THREAD

**Issue by dwRchyngqxs** [endless-sky/endless-sky#8981] opened 2023-07-02 15:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The mission "expedition to hope 2" doesn't trigger when republic is hostile.

### Steps to Reproduce

1. Make two copies of the save file, one edited to have positive reputation with the republic
2. Go to Hope
3. Watch the mission not triggering when hostile to republic

### Expected Behavior

The mission should trigger or the mission line should not have triggered.

### Link to save file

[PEPSI MAAAAAAN DUNDUNDUNDUNDUN~bugged save.txt](https://github.com/endless-sky/endless-sky/files/11929962/PEPSI.MAAAAAAN.DUNDUNDUNDUNDUN.bugged.save.txt)

### Operating System

Arch Linux

### Game Source

Other (please describe)

### Game Version

Latest arch package (0.10.2)

**Comment by warp-core** [comment] 2023-07-03 00:20
It looks like the issue is not just that the Republic are hostile but that the Free Worlds and Neutral governments are also hostile.

#8984 should fix it.

**Comment by warp-core** [comment] 2023-07-09 15:56
Should be fixed by https://github.com/endless-sky/endless-sky/commit/6bb5eaa316634aeea869eb21f58d5df7c39ef024

**Closed by warp-core** 2023-07-09 15:56 UTC
Labels: bug
