### ISSUE TITLE
Scanning Outfits Seems Excessively Difficult in v0.10.0

### ISSUE THREAD

**Issue by mathwhiz1212** [endless-sky/endless-sky#8492] opened 2023-03-03 11:18 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I started the FW campaign in v0.10.0. In the initial recon missions I found myself equipping 15 outfit scanners because I couldn't get close enough to the navy cruisers for long enough to get a read otherwise.

These missions normally take a bit of maneuvering to scan the cruisers, but this seems excessive.

### Steps to Reproduce

1. Start the FW campaign.
2. Try to do the recon missions with 1 or 2 outfit scanners.

### Expected Behavior

1. Start the FW campaign.
2. Complete the recon missions with 1 or 2 outfit scanners without more than mild difficulty and a little time.

### Operating System

Mac OS Ventura

### Game Source

GitHub Releases

### Game Version

v0.10.0

**Comment by Zitchas** [comment] 2023-03-03 13:44
Thank you for reporting this problem and how it affects you.

As is this is a duplicate of https://github.com/endless-sky/endless-sky/issues/7640 , further comments/discussion should take place in that issue. Thanks!

**Closed by Zitchas** 2023-03-03 13:44 UTC
Labels: bug, duplicate

**Comment by mathwhiz1212** [comment] 2023-03-03 19:08
It seemed like there should have been an existing issue, but I didn't see it. Thanks.
