### ISSUE TITLE
Running into issues with latest build

### ISSUE THREAD

**Issue by SirStigII** [endless-sky/endless-sky#2465] opened 2017-04-30 15:43 UTC
Might be something wrong with my compiler settings, but this is what I get when I take escort missions. The ship never shows up in the system either.
![untitled](https://cloud.githubusercontent.com/assets/26936987/25565683/056ac2c4-2d89-11e7-8218-9796a003258b.png)

**Comment by Elyssaen** [comment] 2017-04-30 15:51
Ah, I was just saying on the Discord yesterday that I was getting this, but it must be something wrong with my game files as I hadn't seen it reported by anyone as a bug.

I first noticed it trying to look at a Void Sprite by making a test mission:

```
	npc kill
		government "Team A"
		personality heroic staying
		fleet
			names "pirate"
			variant
				"Void Sprite" 1		
```

and it didn't work. It seems to be when you've got that fleet >> variant >> "[ShipClass]" set-up, which is used in the Escort jobs for the ship you're escorting, e.g.

```
	npc accompany save
		government Merchant
		personality escort timid
		fleet
			names "civilian"
			variant
				"Bulk Freighter"
```

**Comment by SirStigII** [comment] 2017-04-30 15:56
Good to know it's not a problem with the install

**Comment by Elyssaen** [comment] 2017-04-30 15:57
Well... might be too early to say that. Like I said, out of practice. I rebased to upstream/master late last night and spent all of a few minutes trying to get a Void Sprite in the game. I'll check the install first. : )

**Comment by Elyssaen** [comment] 2017-04-30 17:09
I've put up a pull request, https://github.com/endless-sky/endless-sky/pull/2466, which on my copy fixes the problem. Word of caution: I haven't taken the time to learn _why_, so I've put the PR up somewhat speculatively and to draw attention to the issue. MZ will know if it's the right fix or not.

**Comment by MCOfficer** [comment] 2017-04-30 18:09
@SirStigII what OS are you running? Elyssaen has win10, already know that.

we just checked this on the discord server, and i don't have this problem on linux. since the only difference between our installations is the OS, so we figured this might be the cause.

**Comment by SirStigII** [comment] 2017-04-30 21:18
I'm also on windows 10,so that might be it.

**Comment by Elyssaen** [comment] 2017-04-30 21:27
I think @MCOfficer just recently discovered that it _is_ a problem on his system too.

We've worked out what's causing the problem now, we think. My PR does fix it, but might not be the way MZ will want to fix it. I can see about half a dozen ways now, but there's no obvious 'best' so it's up to him. See the PR for technical discussion, if you're interested.

**Comment by EndrosG** [comment] 2017-04-30 21:29
I posted what I think might be the explanation / source of the issue in the PR of @Elyssaen.
But I didnt test / confirm it, since I was busy the whole day with creating my generation 1 ships and testing them a bit. I still need to model my gen 1 carrier :-/

**Comment by Elyssaen** [comment] 2017-04-30 21:41
MZ fixed it a different way in 413fcf237b60775364f80e80b9fc3172d02d8f8e. And for once I'm not heartbroken he didn't use my PR, either! In this case the PR probably wasn't the best way to do it, once I'd figured out what was going on.

**Comment by SirStigII** [comment] 2017-05-01 03:55
Is that change in the build now? I downloaded it after your last post but it's still happening...

**Comment by Elyssaen** [comment] 2017-05-01 04:03
I haven't actually downloaded it myself, I just saw the commit, the logic made sense so I forgot about it and went off to do something else. Will check, possibly not tonight.

**Comment by MCOfficer** [comment] 2017-05-01 05:55
just compiled it and it seems to work, i couldn't find anything. only problem i had was right after loading the game, but iirc jobs offered on the planet you have landed on are part of the savegame, which was from before the fix.

also thanks @Elyssaen for pointing stuff out while i was sleeping, i kinda forgot about yesterday

**Comment by SirStigII** [comment] 2017-05-01 13:46
I'll recompile and double check

**Closed** 2017-07-21 20:56 UTC
Labels: bug
