### ISSUE TITLE
Ship modules that attach like fighters.

### ISSUE THREAD

**Issue by mdsmestad** [endless-sky/endless-sky#1071] opened 2016-05-13 11:46 UTC
For the sake of creating more diversity in ships (alien and human) I prose adding ship modules to the outfitter. Ship modules would modify attributes to a ship (like adding fighter bays to haulers, Turret mounts, gun ports, mass increasing armor, etc.) Modules would have to be ship specific to avoid looking weird, and should have a fixed over or under attribute like fighters. This system would allow greater ship customization, and would easily allow for more ship variation without have to create a whole new model. This would allow moders to create a whole new element to the game too, instead of just adding boat loads of new ships.

**Comment by Wrzlprnft** [comment] 2016-05-13 14:31
>  Modules would have to be ship specific to avoid looking weird

> without have to create a whole new model. 

The problem is, that you would still ned to create a whole new model for each module. Aside from changing the ships unique hull attributes.

**Comment by Isaacssv552** [comment] 2016-05-13 16:07
Being able to install modules in fighterbays would be cool, it would allow for a cargo container that increases flagship, not fleet, cargo and doesn't deploy with your fighters. You could also have modules that added additional gunports/turret mounts. They wouldn't need to be ship unique, just within the size-limits for fighters.

**Comment by OmegaZanicus** [comment] 2016-05-13 22:26
My questions are: 

1. They will be visible, yes? How will we attach them?
2. Will they be unique for _every_ ship?

**Comment by toilethinges** [comment] 2016-05-13 22:57
@OmegaZanicus - You wouldn't HAVE to have them for every ship, just a few, like freighters.

**Comment by mdsmestad** [comment] 2016-05-14 01:30
@Wrzlprnft Ya I've thought about it and your mostly right..You just have to addon to existing models..In theory it'd still takes less time than making something unique

**Comment by LocalGod79** [comment] 2016-05-14 01:35
i think that beyond the issue that @Wrzlprnft has raised, you've just rephrased the old "i want to convert my fighter bays" request, to which M.Z. has repeatedly said (i paraphrase) "hulls should have attributes that are unique to themselves - adding this type of change would 'flatten' hull variation"

plus, it's a lot of coding for something as simple as creating more hulls...

so, i counter your proposal with another: make some ships that have the changes that you would offer, and create a pull request.

**Comment by Isaacssv552** [comment] 2016-05-14 12:58
It would have the benefits of working for any new or modded ships. Also, we're already going to be able to attach cargo containers with engines attached, why not be able to attach some engineless versions?

**Comment by jafdy** [comment] 2016-05-14 20:21
The best use for something like this I can think of is to mix and mach Hauler cargo pods and fighter pods.

**Comment by toilethinges** [comment] 2016-05-14 23:32
A single Hauler hull, and you can attach 1-3 cargo/fighter pods, @jafdy?

**Comment by jafdy** [comment] 2016-05-15 06:58
That's the one.

**Comment by LocalGod79** [comment] 2016-05-15 16:10
i think the point of #995 is that you would buy the Nest, Roost, or Skein, and then augment your fleet's cargo capacity with Boxwings instead of having dedicated cargo containers mixed with 'Type F's.

i think that the idea of "modular ships" is an interesting one, but it would produce unique challenges, if ship hull balance and character were to be maintained...i'm not sure that it's possible...

as i currently understand it, you would like a ship with say six module spaces, three front, three rear.
said modules could have:
•a fighter bay
•two drone bays
•some outfit space and engine/turret mounts(rear)
•some outfit space and gun ports/turret mounts (front)
•cargo space.

the player could then customize their ship?

tbh, i don't really see how this system is tremendously different than the current one (except that the module layouts are determined for you, and spread out over human space)...

**Comment by jafdy** [comment] 2016-05-15 18:16
I agree with @LocalGod79. It seams like a lot of effort for something that would be detrimental to the game if not done perfectly.

**Comment by mdsmestad** [comment] 2016-05-16 00:50
@LocalGod79 Well the idea was really more for visual appeal for the players. I really like the concept of putting together different ships with standard chassis. Like a custom ship, with say, a leviathan chasis .

**Comment by LocalGod79** [comment] 2016-05-16 05:06
i'm afraid that i'm still not seeing what this actually adds to Endless Sky.

from your last comment, it now sounds like you'd like to make "Marauderizing" an in-game element.

i think at the bottom line, everything you asked for in the o.p. has specifically been addressed by M.Z. (fighter bays, turret mounts, gun ports, armour; as outfits/modules) as "undesired" in the past - i'm not sure why you believe those ideas are now more appealing.

**Comment by mdsmestad** [comment] 2016-05-17 03:44
@LocalGod79 Sigh.. :) I guess your right. Just for some reason I really like the idea.

**Closed** 2016-08-28 02:16 UTC
Labels: enhancement
