### ISSUE TITLE
System search in map screen

### ISSUE THREAD

**Issue by lucapton** [endless-sky/endless-sky#5200] opened 2020-08-02 16:47 UTC
**Is your feature request related to a problem? Please describe.**
Sometimes a system is referenced but no marker is placed on it, e.g. Free Worlds Bounty Hunting missions will say a pirate was last seen in some system. It can be hard to find it as there are so many systems. The problem is not just resticted to missions like this, sometimes a forum post will suggest going to a system for some reason, resulting in the same problematic situation.

**Related Issue Links**
N/A

**Describe the solution you'd like**
It would be really helpful to allow for a search function in the map screen. Type in the name of a system (or just part of it) and anything that doesn't match it is temporarily grayed out (or something equivalent).

**Describe alternatives you've considered**
You could add another type of marker for systems relevant to mission but not specific destinations. It wouldn't solve the more general problem I'm describing, but might still be a nice addition.

**Additional context**
I think the idea is pretty clear as is. If requested, I'll create a mock-up.

**Comment by beccabunny** [comment] 2020-08-02 17:05
Press F while in the map screen

**Comment by Amazinite** [comment] 2020-08-02 17:09
As becca has mentioned, this feature already exists by pressing F while on the map.

> You could add another type of marker for systems relevant to mission but not specific destinations. It wouldn't solve the more general problem I'm describing, but might still be a nice addition.

#5145

**Comment by lucapton** [comment] 2020-08-02 17:18
Okay, I'm glad to hear it's already there. In that case, I'd suggest making it clearer. Even just a text hint in the map screen. I just checked and it's not even listed in the controls menu so there is no way for someone to learn about this feature besides random button presses.

**Comment by tehhowch** [comment] 2020-08-02 21:14
Plugins can override (not extend) the game's interface definitions and thus display a button for this functionality as desired; I had previously proposed the interface definition in https://github.com/endless-sky/endless-sky/pull/3431/commits/14901ad25707f8fd05251d54e45e053a7c3209bd as a part of #3431.

Closing this as a duplicate of #1893

**Closed by tehhowch** 2020-08-02 21:14 UTC
Labels: question
