### ISSUE TITLE
Player Can Bypass Unlinked Systems Using Jump Drive

### ISSUE THREAD

**Issue by Haravikk** [endless-sky/endless-sky#6477] opened 2022-01-11 18:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm not super familiar with Endless Sky's quest chains so this may affect others as well (I'm not clear on whether they converge or not, and I'm trying to avoid spoilers for future playthroughs).

However, I'm playing the Free Worlds quest chain, and am at the point where Syndacite space is only accessible through a single hyperspace route. Or at least, it is for everyone else, because I got lucky when I was in the galactic north earlier and managed to disable a Korath Raider after it had chewed through a big pirate fleet, giving me a chance to bravely shoot it in the back from a distance and disable it. Long story short, I have a Dreadnought with a Jump Drive (and System Core, Large Heat Shunts and some other goodies).

Having the Jump Drive though means that some of the quest dialogue is strange, as it doesn't recognise the fact that I can just jump wherever I want. I'm also able to jump to certain "inaccessible" systems that I'm probably not supposed to yet.

### Steps to Reproduce

1. Play the Free Worlds questline until just after capturing a Syndacite higher up off a yacht.
2. At some point, gain enough strength to disable a Korath Raider (can be found in the galactic north) and take its Jump Drive (or the whole ship, if you can).
3. Continue the Free Worlds questline.

### Expected Behavior

Either I should not be able to get or use the Jump Drive at all until later in the quest chain, or the quest text should reflect the fact that I can jump freely wherever I like.

Rendering the Jump Drive somehow inaccessible would probably be the simplest solution; such as making it unlootable until some event occurs, or having it unable to be installed in the player's ship until some condition is met?

### Operating System

macOS Catalina 10.15.7

### Game Source

GitHub Releases

### Game Version

0.9.12

**Comment by pilover100** [comment] 2022-01-11 19:58
A lot of parts of the game rely on having jump drives and looting them is the only way of getting more than 1. Also people don't always want to do the FW storyline so blocking JD access until you do the story line seems a bit wrong to me. So I personally see this as a none-issue.

**Comment by Haravikk** [comment] 2022-01-11 22:29
I think it still needs to be addressed somehow; another alternative might be to add more places in the questline the recognise that the player has a Jump Drive.

I noticed that later on when visiting the Syndicate shipyard to be fitted with one, the engineer remarks upon your already having one, and it means you get an extra ship in your escort fleet.

If this kind of check could be added to some of the quest dialogue immediately after systems start being disconnected then that might also address it; i.e- have admirals and such recognise that your ship can jump into Syndicate space even with the routes severed.

This option also feels like it should address the severed systems though, as you can still jump into them and see what's going on before you're supposed to know. Either jumping in should allow you to skip part of the questline (since you already know who's done it) or the systems should be somehow inaccessible?

It just felt really weird doing this questline with people acting like I couldn't get somewhere when I literally jumped into the system from where they told me I couldn't get to.

**Comment by Hurleveur** [comment] 2022-01-19 08:26
> I think it still needs to be addressed somehow; like I say, the other alternative might be to add more places in the questline that recognises that the player has a Jump Drive.

Well, nobody will stop you from doing it, so go ahead and open a pr! (if you want smth done right, ...)
It is quite easy to modify questlines to include the possibility for jump drive, it's just about changing a bit of text and adding a few branches, the wiki has all kind of information you may need on it.

**Comment by Amazinite** [comment] 2022-01-19 21:01
Essentially a duplicate of #989. The campaign is currently intended to be completed without a jump drive, and there are various points in the campaign that don't make sense if you have one (another famous example is when you're asked by the FW Senator to reach Bourne faster than can be done with a hyperdrive), but the intention is to eventually account for alternate situations where the player does have a jump drive.

> Rendering the Jump Drive somehow inaccessible would probably be the simplest solution; such as making it unlootable until some event occurs, or having it unable to be installed in the player's ship until some condition is met?

Unlikely to happen: https://github.com/endless-sky/endless-sky/issues/6156#issuecomment-892986145

**Comment by McloughlinGuy** [comment] 2022-01-28 16:10
I did a lot of stuff with a jump drive before I even started the free worlds storyline. I looted a disabled korath after a remnant mission, and then farmed the pug in deneb. Nothing that out of the ordinary happened, they even have mission text to account for you having a jump drive when you’re supposed to get one from the syndicate.

**Comment by pepoluan** [comment] 2022-04-04 04:35
> gain enough strength to disable a Korath Raider (can be found in the galactic north) and take its Jump Drive (or the whole ship, if you can).

You don't even have to gain enough strength...

Go up north to a dead-end non-inhabited system. Bribe the pirates to not disturb you. Wait until the Syndicate appears. Wait until they managed to disable a Korath Raider. Grab your jump drive. Lather-rinse-repeat.

**Closed** 2022-05-25 20:10 UTC
Labels: duplicate
