### ISSUE TITLE
Limited Turret Rotation

### ISSUE THREAD

**Issue by Mavleg** [endless-sky/endless-sky#1809] opened 2016-11-04 02:09 UTC
I am playing with ideas for a mod (plugin), and I wonder if there is a variable or value I can change so that turrets have a limited arc of fire. for example, a turret that can only turn and fire within the front 90-degree arc of the ship.

Any ideas on how to implement this? Any and all feedback is appreciated.

**Comment by Amazinite** [comment] 2016-11-04 02:18
Duplicate of #1005

**Closed** 2016-11-04 21:38 UTC

**Comment by Elyssaen** [comment] 2017-05-03 01:51
Just for reference, this is implemented in feature/TurretFiringArc here:

https://github.com/Elyssaen/endless-sky/tree/feature/TurretFiringArc

It's up-to-date with the current build as of today. I haven't made a PR yet as I'm still pending feedback or merging of a few other pull requests.
