### ISSUE TITLE
feature: Possiblity for multiple outfits with the same name

### ISSUE THREAD

**Issue by mOctave** [endless-sky/endless-sky#7052] opened 2022-07-24 22:46 UTC
### Problem Description

I've been trying to create an alternate start that occurs several hundred years earlier, and so I need to tweak the outfits (changing descriptions, occasionally changing other things), while still keeping the same name. Unfortunately, there doesn't appear to be a way to have outfits with the same name, and using Unicode characters that don't get rendered by ES causes other problems.

### Related Issue Links

As far as I can tell, this hasn't been addressed anywhere else.

### Desired Solution

I would like for there to be an optional attribute for outfits (and possibly ships) called "name," allowing you to set the name of the outfit as it displays in game, instead of always using the name as defined by whatever comes after "outfit" in the outfit definition.

### Alternative Approaches

I've also considered having variant outfits, like variant ships, although this might be difficult because of the way the save files are set up (each ship being defined, but not each outfit).

**Comment by petervdmeer** [comment] 2022-07-25 07:27
I prefer to use a different solution, where a single outfit can have multiple names and where we choose the correct name based on conditions that are set. (In this example we could use the game-year as a condition to select the right name.)
Such a solution with multiple names likely scales better when we have different missions all trying to set names on outfits. (Since all conditions are visible at 1 single location, the outfit itself.)

**Comment by petervdmeer** [comment] 2022-07-25 07:50
This is technically not a duplicate of #6341, since this is a feature request for modifiable names, while #6341 is about modifiable descriptions.
But the features seem very close to each-other, if we setup a mechanism for modifiable descriptions, then we will likely want to use a very similar mechanism for modifiable names.
So I prefer to close this issue and discuss both features together in #6341.

**Comment by quyykk** [comment] 2022-07-25 07:56
I don't think this is a duplicate. #6341 talks about modifying names/descriptions of one outfit (one outfit, multiple names), but this issue is about having different outfits with the same name (multiple outfits, one name). For example, you can have an outfit with its id being "Hyperdrive Prototype I"  and then give it a `"display name"` of Hyperdrive so that in-game its name is Hyperdrive.

**Comment by petervdmeer** [comment] 2022-07-25 08:12
Good point. I'll re-open this issue then.

**Comment by thvk-net** [comment] 2022-07-28 15:54
Is this something you want to see in game? If yes i could do this.

**Comment by warp-core** [comment] 2022-07-28 15:58
> Is this something you want to see in game? If yes i could do this.

I expect so, that's probably why they opened this issue. I'm sure there are lots of other people who would be interested, too.

**Comment by thvk-net** [comment] 2022-07-28 16:21
I am working on it.

**Comment by Zitchas** [comment] 2022-07-28 17:01
This might have some tie-in with outfit variants, too. https://github.com/endless-sky/endless-sky/issues/927

**Comment by thvk-net** [comment] 2022-07-28 21:38
Hmm, its kund of different to that issue because this issue is about two different outfits same name and the other is same outfit different sprite/other stuff.

**Comment by quyykk** [comment] 2022-10-03 19:42
@tehhowch what would you suggest as an alternative solution to this issue? The only thing I can think of is to not load the base game data for specific saves (or in general), or something similar.

**Comment by warp-core** [comment] 2022-11-20 22:36
Display names for outfits were added by 02e7309.

**Closed by warp-core** 2022-11-20 22:36 UTC
Labels: enhancement
