### ISSUE TITLE
Wormholes break payment calculation behavior

### ISSUE THREAD

**Issue by a-random-lemurian** [endless-sky/endless-sky#6844] opened 2022-05-21 05:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Wormholes break payment calculation behavior. There's a plugin link demonstrating the issue.

### Steps to Reproduce

Create a mission requiring travel through a wormhole. 

This small plugin demonstrates the issue.

[Wormholes-Break-Payments.zip](https://github.com/endless-sky/endless-sky/files/8747019/Wormholes-Break-Payments.zip)

### Expected Behavior

Normal payment calculation behavior, or for the game to treat a wormhole jump as one hyperspace jump.

### Operating System

Ubuntu 20.04.3

### Game Source

Built from source

### Game Version

Git commit SHA feccf71e1d363abe8dbde8b73d93fa5b4b10a276

**Comment by quyykk** [comment] 2022-05-21 10:49
Duplicate of #6281

**Closed by quyykk** 2022-05-21 10:49 UTC
Labels: bug, duplicate
