### ISSUE TITLE
Fighters launched from disabled ship

### ISSUE THREAD

**Issue by piannucci** [endless-sky/endless-sky#4314] opened 2019-05-31 01:41 UTC
**Describe the bug**
I disabled a ship with carried fighters while it was activating its jump drive.  (It had recalled its fighters in order to run away.)  The jump completed normally.  I started jumping to nearby systems searching for the destination of its jump.  When I found the ship, it launched three fighters, despite being disabled.

**Expected behavior**
Disabled ships cannot operate outfits, including fighter bays.

**System (please complete the following information):**
 - OS: macOS 10.14.3 (18D109)
 - Game Source: Steam
 - Version: 0.9.9

**Comment by AlbertNewton** [comment] 2019-05-31 15:04
I'm not sure if this is working as intended. I know that destroyed ships deploy fighters and drones, but I don't know any reason why a disabled ship might do the same.

**Comment by endless-sky** [comment] 2019-05-31 15:17
That's the intended behavior - the idea is that the fighters / drones are not disabled, even if the parent ship is, so they are able to launch themselves away from it.

**Comment by piannucci** [comment] 2019-05-31 17:12
Hm... in sci-fi lore, I suppose there are examples on both sides: UNSC Infinity in the Halo universe carries dreadnoughts that presumably don’t need any help launching themselves, but in BSG, Vipers are launched from a Battlestar by a powered catapult.  Escape pods / captain’s yachts are another example of the former.  Aircraft carriers can launch VTOL craft without power, but not standard jets.  Maybe there ought to be a flag?

**Comment by Pointedstick** [comment] 2019-05-31 19:26
Hmm, I feel like that would make it seem arbitrary and buggy, and we'd get bug reports.

Since this is behaving as intended (though not necessarily as expected), I'm closing the bug report.

**Closed by Pointedstick** 2019-05-31 19:26 UTC

**Comment by jafdy** [comment] 2019-05-31 22:41
I suspect that in the case of BSG, I imagine the vipers would be capable of making it out the hangar as long as there wasn't a door in their way, we can also assume that escape pods will continue to work long after the rest of the ship has given up (not much use otherwise). The most reasonable explanation of a ship being disabled is that the relatively demanding systems of combat/flight are damaged while most internal operations can continue in some form, we know that disabled ships can communicate still so clearly there is some level of operation still available, it then becomes a question of "Can you open that door/release that docking clamp?".
