### ISSUE TITLE
strange behaviour on entering system with hyper/scram drives [intermittent bug]

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#1513] opened 2016-08-31 03:04 UTC
https://groups.google.com/d/msg/endless-sky/NW2OI47P32o/qUEf5ODcBQAJ

and more recently;
https://groups.google.com/d/msg/endless-sky/vNbnFYPVDKY/RdyjcwqNBgAJ

**Comment by IFailAtGaming** [comment] 2016-08-31 08:53
I've actually been experiencing the first bug a lot recently, mostly on shield beetles, certainly made the newest wanderer missions annoying.

**Comment by endless-sky** [comment] 2016-08-31 12:31
Those two sound like completely different bugs. One happens when exiting hyperspace, and the other allows you to enter it more quickly.

@IFailAtGaming, can you clarify what behavior you are seeing?

**Comment by LocalGod79** [comment] 2016-08-31 13:08
@endless-sky i think that if you observe the video carefully, it appears that the Marauder Raven is "bouncing" on enter, but its forward engines provide enough acceleration (you see them firing) that the "bounce" is barely perceptible.

**Comment by IFailAtGaming** [comment] 2016-09-01 07:30
@endless-sky thankfully I actually managed to observe the entirety of the thing, basically rarely when a ship just entered the system through hyperspace (haven't encountered it with jump drive yet, but I can attribute that to not spending much time in places with quarg) they'll randomly start moving backwards and jittering, it kinda looks like the engines are on backwards, because the ships jitter a lot and I don't remember seeing any engine plumes, the first time I observed it it was with 3 shield beetles in one of the new wanderer missions, running the latest version from when the new wandered missions were added (up to the wormhole starting to open)

**Comment by IFailAtGaming** [comment] 2016-09-01 07:33
!on mobile so can't edit! Also those 3 shield beetles all seemed to have popped up at around the same time and area as they were all next to each other

**Comment by endless-sky** [comment] 2016-09-10 17:34
I think this should be fixed with commits 1fdabc2 and fed6097, but since I wasn't able to reproduce the bug myself I can't be certain.

**Comment by endless-sky** [comment] 2017-01-18 23:41
Closing this because 0.9.5 is released now.

**Closed by endless-sky** 2017-01-18 23:41 UTC
Labels: bug
