### ISSUE TITLE
Not all ships shown in list on small screen

### ISSUE THREAD

**Issue by schlamar** [endless-sky/endless-sky#191] opened 2015-11-11 18:39 UTC
On a small screen it can happen that not all ships are shown in the UI:

![screen shot 2015-11-11 at 19 37 49](https://cloud.githubusercontent.com/assets/238652/11099480/d9fa8742-88ab-11e5-828e-d05e1d98b0db.png)

**Comment by endless-sky** [comment] 2015-11-17 02:02
Any ideas how I could reproduce this? If the screen is small enough that it can't show all your ships even if they are all "folded" into a single icon for each type, they are indeed not shown. But I'm having trouble replicating the situation in your screenshot, where it looks like the "folding" ought to have been applied, but somehow it was not.

**Comment by schlamar** [comment] 2015-11-17 20:28
This is 100% reproducible with my current fleet on OSX. Here is my save game: https://gist.github.com/schlamar/1ac8c44d5abc1a314bf3

**Comment by endless-sky** [comment] 2015-11-17 22:36
Thanks, that file was exactly what I needed. It turns out the bug only happens if you have ships of the same type but with different costs, which is why I was unable to reproduce it just by buying a big fleet of identical ships. Fixed in commit 159ef5d.

**Comment by endless-sky** [comment] 2015-11-26 04:38
Test and see if this is fixed in 0.8.8.

**Comment by endless-sky** [comment] 2015-12-02 03:53
This issue is fixed in 0.8.8, and 0.8.8 is now the default on Steam, so I'm closing this issue.

**Closed by endless-sky** 2015-12-02 03:53 UTC
Labels: bug
