### ISSUE TITLE
When taking off, escorts are sometimes scattered far and wide

### ISSUE THREAD

**Issue by johndh** [endless-sky/endless-sky#498] opened 2015-12-22 17:50 UTC
I've seen this happen a few different times with various revisions.  When taking off from a planet, some of my escorts are near my flagship and some are very far away, as seen on the radar here.  Hyperspacing with them to another system puts them back to a manageable distance as usual.

![screenshot from 2015-12-22 11 39 20](https://cloud.githubusercontent.com/assets/692397/11961978/57d8d47a-a8aa-11e5-8522-a70215c6e50d.jpg)

**Comment by brick96** [comment] 2015-12-22 17:54
#481

**Comment by brick96** [comment] 2015-12-22 17:59
Wait taking off from a planet? Ive seen this once and that was yesterday. I was rushing from tarazed to epsilon leonis with a scram drive. Some ships kept up, others didnt. Anyway, I took off after refuelling and say what ship that had kept up get launched away, no pirates were in system

**Comment by endless-sky** [comment] 2015-12-22 18:02
Is this with release 0.8.9, or the latest code? It might just be another
issue where reversing the order of the ships (so that the flagship came
last) messed up the AI and the assumptions it makes.

**Comment by johndh** [comment] 2015-12-22 18:06
@endless-sky the latest code as of a few hours ago

**Comment by jafdy** [comment] 2015-12-22 18:56
The issue is much is much older than 0.8.9 in fact it is at lest as old as 0.8.6

**Comment by endless-sky** [comment] 2016-01-07 03:37
To clarify what your screenshot is showing, are you saying that your fleet took off from empty space rather than the planet? Or is the only bug the ones that are on the very fringes of the radar?

**Comment by johndh** [comment] 2016-01-07 04:41
@endless-sky "Or is the only bug the ones that are on the very fringes of the radar?"  Yes, that.  Most of my fleet appeared above the planet as expected, while some appeared very far away.

**Comment by natangold** [comment] 2016-01-07 06:15
Is it possible that you are landing on the planet while some of your escorts are still warping in to the system?

**Comment by johndh** [comment] 2016-01-07 06:45
@natangold They don't move rapidly toward the center, so I don't believe that to be the case.

**Comment by natangold** [comment] 2016-01-07 07:07
I think that if you land at just the wrong time, the game loses track of the ships’ locations. For example, say you have your ship and three escorts. At the instant that your main ship lands, Escort A is still one system behind you, Escort B is in the system with you, and Escort C just showed up as a green blip on the radar, but hasn’t started slowing down post-warp. If I’m right, then when you lift off, A will still be in the system behind you and will begin the warp process, B will take off from the planet with you, and C will show up as you describe - in the right system but lightyears away from anything else. When you landed, their warp was terminated, so the escort is no longer rapidly moving toward the system’s center; and they weren’t in another system, so they don’t need to warp in now; but they weren’t quite ‘in’ this system yet (i.e., they couldn’t be targeted, hailed, etc.), so the game saved their coordinates as if they were a disabled escort - but their “coordinates" were “the very edge of the map in the direction of the system from which they warped in”.

**Comment by endless-sky** [comment] 2016-01-13 00:38
I think this was due to the fact that if a ship was in mid-jump when you land, it continues to "jump" when you take off. If that was the issue, it is fixed in 64ac8d0.

**Comment by endless-sky** [comment] 2016-02-03 02:03
Closing this, because it's fixed in 0.8.11.

**Closed by endless-sky** 2016-02-03 02:03 UTC
Labels: bug
