### ISSUE TITLE
New Remnant missions require most of main plot line

### ISSUE THREAD

**Issue by jlnxr** [endless-sky/endless-sky#4280] opened 2019-05-14 02:32 UTC
Because the new Remnant missions (involving Taely) require you to give them the catalytic ramscoop, it is impossible to move on to these missions without first completing most of the Free Worlds missions. I noticed this on a save where I rejected the Free Worlds and remained a merchant, but completed most of the side plots lines. Given that possibility as well as the lack of the other main story lines or good knowledge over how those will shake out, it seems to me that the catalytic ramscoop should not be required to move ahead with in the plot line to get the remnant capital license, or another avenue through which to acquire one should be made possible. (placement on Marauders perhaps, as some of the checkmate syndicate tech is?)

**Comment by Amazinite** [comment] 2019-05-15 06:58
Ref: https://github.com/endless-sky/endless-sky/commit/400739af2a28150841974f8df40ef10d96683b76#commitcomment-32056207

Even without #4269, the catalytic ramscoop is not required, as that is only one of three missions that the player is able to complete in order to continue.

**Comment by Zitchas** [comment] 2019-05-15 12:22
Amazinite already provided the answer, but I'll also point out that the second part of your question is already in place.

> or another avenue through which to acquire one should be made possible.

As of the same nightly update that introduced those missions, it is possible to continue using Heavy Lasers or Plasma Cannons, so your problem is already resolved. Right from that point the catalytic ramscoops have always only been one of three possible ways of resolving it.

In PR #4269 , as you point out, the problem is resolved in a much better way as people will actually have a) a much better idea of what they are aiming for, and b) a lot more options of what to bring.

**Closed** 2019-05-17 11:38 UTC

**Comment by Zitchas** [comment] 2019-05-17 13:06
Just noting for the sake of the record here that #4269 has been merged.
