### ISSUE TITLE
New update according to Github but not yet on Steam

### ISSUE THREAD

**Issue by FireWolf74** [endless-sky/endless-sky#3763] opened 2018-06-09 04:12 UTC
Is there going to be an update to Steam?

![screenshot from 2018-06-09 00-13-30](https://user-images.githubusercontent.com/33334258/41187555-b05bbc0e-6b79-11e8-9ad0-5dde83fd7a5c.png)

**Comment by jafdy** [comment] 2018-06-09 04:38
Err . . . GitHub is at 0.9.8 too . . .

**Comment by FireWolf74** [comment] 2018-06-09 04:50
Well when I look in the pull request they keep saying that 0.9.9 is out.  I was wondering.

**Comment by temtemy** [comment] 2018-06-09 04:59
Ah, the "0.9.9: done" label you mean? It means the issue is fixed in the next version (which is 0.9.9). For pull requests, it means the commits have been merged in the master branch, which will become 0.9.9. 0.9.9 is not yet released, but I think it will be released soon (after MZ wrapped up the Wanderer storyline).

**Comment by FireWolf74** [comment] 2018-06-09 05:01
Wanderer Storyline I thought that was going on already.  Like there is mission to find them but I have not found them LOL

**Comment by temtemy** [comment] 2018-06-09 05:42
So, since it seems that your issue is resolved, can you close this issue please?

**Comment by MCOfficer** [comment] 2018-06-09 06:09
btw #3637

**Comment by Amazinite** [comment] 2018-06-09 18:31
https://github.com/endless-sky/endless-sky/releases
v0.9.9 has not been released yet. Please close this issue.

**Closed** 2018-06-09 21:16 UTC
