### ISSUE TITLE
Kor Mereti ALWAYS swamps Kor Sestor

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#1046] opened 2016-05-07 20:09 UTC
is this intentional?

**Comment by endless-sky** [comment] 2016-05-07 20:21
No, I think there' need for better balancing either in the weapon attributes, or in the fleet sizes.

**Comment by thenerdfreak** [comment] 2016-05-07 20:37
I would personally suggest fleet size. Kor Mereti come in HUGE swarms, filling the whole map, and Kor Sestor usually come in groups of 3-4 with some fighters that die instantly attached

**Comment by thenerdfreak** [comment] 2016-05-07 20:43
OR give Kor Sestor a very good weapon vs large swarms, like an upgraded Heavy Missile or something

**Comment by endless-sky** [comment] 2016-05-07 21:01
I've reduced the Kor Mereti fleet sizes by about 20% on average, which brings the two fleets to an equivalent nominal cost. (34591ab) If the Kor Mereti are still overpowered even with that change, it means that their ships are underpriced relative to the Kor Sestor and I need to either boost the prices or reduce their strength.

**Comment by Isaacssv552** [comment] 2016-05-07 21:13
The Kor Mereti are definitely stronger than the Kor Sestor. I think it's because of their "signature" abilities having vastly different levels of utility. The Mereti can practically ignore shields thanks to their disruptor+slicer combo while the Sestor merely disable engines and use fighters. Disabling engines is useful but it doesn't really compare to being able to give the Quarg a decent fight.

**Comment by thenerdfreak** [comment] 2016-05-07 22:25
I agree with @Isaacssv552 the Kor Sestor would be just fine if they had something worth-while (like giving those guns that disable engines the ability to momentarily disable weapons as well/etc)

**Comment by Isaacssv552** [comment] 2016-05-08 06:06
Part of the issue is that while both factions get a form of shield piercing the Mereti get the incredibly powerful disruptor while the Sestor get the lackluster, ammo limited, piercer. Also, the Sestor focus on hull over shield while the Mereti focus on shield over hull, but the Sestor don't get enhanced hull regen to back up the increased amount. In addition, while the Mereti's slicer counters the Sestor with a hull damage specialization, the Sestor have no real counter to shields. In fact, the Mereti actually have the shield counter, making them powerful against both hull and shields (To the point they're the best option in the vanilla game, with the possible exception of archons, for eliminating the Quarg ships in my plugin.)

**Comment by endless-sky** [comment] 2016-05-14 02:29
Commit 5c622a7 makes the disruptor and slicer about 10% less powerful. Along with the fleet changes, that's enough that in the system where the Kor Sestor and the Kor Mereti meet, either fleet can end up ahead. So, I think they're reasonably well balanced now.

**Comment by endless-sky** [comment] 2016-05-30 20:25
Closing this because it's fixed in 0.9.1, which is released now.

**Closed by endless-sky** 2016-05-30 20:25 UTC
Labels: balance
