### ISSUE TITLE
[Enhancement] Unsellable outfits

### ISSUE THREAD

**Issue by Taejang** [endless-sky/endless-sky#6387] opened 2021-12-02 21:58 UTC
### Request Description

In EVN, some outfits could not be sold once installed. I don't see this functionality within ES. Having this property as an option would allow for new variety in outfits while enabling effective balance control or forcing meaningful consequences.

One use case for this, follow EVN, is a cargo space conversion overhaul that swaps cargo space for outfit space, but once done it cannot be undone. The ever popular fighter/drone bay conversion, wherein a bay is removed and converted to something else, would be another good use for this. The [built-in railgun](https://github.com/endless-sky/endless-sky/issues/6383) idea could also use this to maintain balance between ships. The EVN conversions between Starbridge types couldn't be removed either, if memory serves.

The point being, it makes for additional downsides, considerations, or balancing options.

### Desired Enhancement

A simple "Can sell" or "cannot sell" type flag/property, similar to the "cannot be plundered" option.

**Comment by Zitchas** [comment] 2021-12-03 14:12
I saw a plug-in or two for EVN that gave consequences for trying illegal drugs in the form of an unsellable outfit that gave penalties. If I recall correctly, the only way to get rid of it was to eject in an escape pod and spend a few weeks of "cold turkey" drifting in space waiting to be rescued. (so it was unsellable and uninstallable, but would get blown up with the ship when that was destroyed)

**Comment by LordInsane** [comment] 2021-12-04 03:03
> The EVN conversions between Starbridge types couldn't be removed either, if memory serves.
This was actually achieved in an entirely different way (they couldn't be removed because the outfit disappeared the moment you bought it; buying the outfit triggered a control bit that replaced your ship with the ship being converted to in its default outfit setup).  
However, _all_ the EV games used unsellable outfits (EVN used had the largest variety of purchasable unsellable outfits), and of course unsellable outfits are a necessary prerequisite for persistent outfits, so it certainly seems like something that could find use in ES.

**Comment by tehhowch** [comment] 2022-01-10 04:20
Closing as a duplicate of a larger issue, the ability to restrict what a player can do with an outfit or ship.
Ref https://github.com/endless-sky/endless-sky/issues/5311#issuecomment-691045117

Please ensure you search for related issues before creating a new issue

**Closed** 2022-01-12 13:53 UTC
Labels: duplicate
