### ISSUE TITLE
Republic & FW fight during free passage(s)

### ISSUE THREAD

**Issue by KiLEdEnNis** [endless-sky/endless-sky#1469] opened 2016-08-20 14:37 UTC
I haven't paid that much attention to all ceasefires/free passages, but after the first 3 worlds defect and you can either free the prisoners or keep them, I freed them, and on the way back I saw the Republic and FW fight while they were all friendly to me

I think the missions are FW Prisoner Parole(?), FW Prisoner Parole 2 (the one I talked about), and probably the FW Diplomacy missions

**Comment by jafdy** [comment] 2016-08-20 17:34
I think this is intended. Only you (+blackbirds) get the free passage.

**Comment by KiLEdEnNis** [comment] 2016-08-20 18:05
the player is part of the FW though, I did consider that but I'm not sure, I'll see what MZ thinks

**Comment by Bladewood** [comment] 2016-08-20 18:27
You're escorting the ships carrying the prisoners. If you were killed, the carrier ships are defenseless and will get rekt. The Republic does not want to be held responsible for their own casualties.

**Comment by KiLEdEnNis** [comment] 2016-08-20 19:00
I still think that maybe they should have small ceasefires, but it explains that they say "we've arranged ~ time free passage" instead of "~ time ceasefire"

**Comment by MessyMix** [comment] 2016-08-21 04:50
Not sure about the code, but I think it makes government Escort and/or the Player temporarily neutral to the Republic.

**Comment by jafdy** [comment] 2016-08-21 06:57
The blackbirds are assigned to the "Escort" government and the player rep with the Republic is set to 5.

**Comment by KiLEdEnNis** [comment] 2016-08-21 11:32
I think it's working as intended then, but to be sure I'll wait w/ closing until MZ shares his almighty wisdom :3

**Comment by endless-sky** [comment] 2016-08-24 00:20
This is as intended - it's not meant to be a complete ceasefire.

**Closed by endless-sky** 2016-08-24 00:20 UTC
