### ISSUE TITLE
Fighter AI being weird

### ISSUE THREAD

**Issue by kitsunemochi** [endless-sky/endless-sky#1461] opened 2016-08-17 19:24 UTC
I don't know if this is intentional or not, but when capturing enemy fighters, I have noticed that they seem to immediately go suicide, disregarding the hold position, gather around me, and deploy/recall keys completely.  If there are no enemies in the area, they just sit there.  I've noticed this happen with the Far Osk fighters and Korath Chasers, while in a Tek Far 78 Osk, in a Korath Raider, and in a Bactrian, all with fighter bays completely empty.  The Far Lek drones do seem to work fine, immediately joining to a Tek Far 71 Lek or Tek Far 109 and obeying fleet commands.

Edit:  Going to another system, saving, and editing the save file to remove the "system" attributes of the fighters seems to fix them if they're just being dead in the water.

**Comment by tehhowch** [comment] 2017-07-07 21:01
this is the same as #2476 (or rather, that is a duplicate of this one), and should be fixed by https://github.com/endless-sky/endless-sky/commit/af9e646bedeac86e3e164065291087590b5f6d6c and https://github.com/endless-sky/endless-sky/commit/e8a629e11c6d7c2593ae588de7b455d4d009d2d9

**Closed** 2017-07-21 21:01 UTC
Labels: bug
