### ISSUE TITLE
Reloading the game causes missions to complete without all conditions met

### ISSUE THREAD

**Issue by nebulaeandstars** [endless-sky/endless-sky#6117] opened 2021-07-13 16:26 UTC
When a cargo mission (potentially other mission types as well?) can't be completed because ships are in another system, reloading the game will cause it to think that the mission is complete.

**To Reproduce**
1. Get a cargo mission
2. Leave freighters in a neighbouring system (potentially disabled)
3. Trigger the "can't complete mission" popup by landing
4. Immediately reload
5. The "mission complete" popup might appear

**Expected behavior**
The "mission can't be completed because the cargo is in another system" popup should appear, as it did prior to reloading.

**System (please complete the following information):**
 - OS: Linux
 - Game Source: Steam Beta
 - Version: 0.9.13

**Additional context**
When this happened, the freighter was disabled in a neighbouring system. I don't have the logs, save file, etc. as it was a while ago.

The flagship probably had enough space to hold the cargo, so it could also be that saving/reloading causes the game to redistribute everything even across systems. This would make sense if the save file only tracks fleet cargo, rather than cargo per ship.

**Comment by Amazinite** [comment] 2021-07-13 16:37
Duplicate of #1624.

**Closed by Amazinite** 2021-07-13 16:37 UTC
Labels: duplicate
