### ISSUE TITLE
Save games "forget" cargo and passenger space for ships not in the same system

### ISSUE THREAD

**Issue by Laudrin** [endless-sky/endless-sky#3644] opened 2018-02-13 13:49 UTC
When saving a game and ships are not in the same star system / planet / station, the game often "forgets" the cargo and passenger space of those ships.

So after saving a game (where cargo and passengers fit into the existing space) and reloading it, sometimes passenger and cargo space are shown as negative numbers and cargo and passengers are lost if you don't have the funds to buy more ships.

This is especially annoying, when there is mission cargo and passengers. I found no way of choosing, which cargo and passengers to purge.

My OS is Windows 10 64bit, game version is 0.9.8 stable.

**Comment by Amazinite** [comment] 2018-02-13 13:59
Duplicate of #1624, #1945

**Comment by Laudrin** [comment] 2018-02-13 17:45
> Duplicate of #1624, #1945

Thank you Amazinite for informing me about the duplicate and the option to abort missions as long as the bug is not fixed.

Sorry for the duplicate, I was searching the issues/bugs for "safe" and was not expecting that this bug is known (and the issue closed) since more then a year without it being fixed in the most recent (stable) version. I try to circumvent it when possible (saving only when all ships are in the system) and am looking forward to the next version!

**Comment by Laudrin** [comment] 2018-02-13 17:47
I'm not closing the issue myself because I'm not sure if it's on the developer's radar. If someone knows if it will be fixed in the next version, please close the issue. Thank you! :-)

**Comment by KiLEdEnNis** [comment] 2018-02-13 18:22
just a small note: only MZ himself can close this, and if it's a duplicate from those older issues I doubt it'll get fixed

**Comment by Amazinite** [comment] 2018-02-13 18:39
>I'm not closing the issue myself because I'm not sure if it's on the developer's radar.

Well it's a duplicate issue and #1624 is already milestoned, so this should be closed.

**Closed** 2018-06-02 16:05 UTC
