### ISSUE TITLE
Quargs make the game too easy

### ISSUE THREAD

**Issue by Oeleo** [endless-sky/endless-sky#267] opened 2015-11-26 07:03 UTC
All is in the title, for the cost or the effeciency of their stuff, the Quarg make the game too easy. Farming 1 hour of Quarg ship can make about 1.000.000.000 of moneys, and their stuff... My Bactrians do 6000 dps ! No seriously, either it needs to be less effective and less expensive or it needs to be impossible to steal it (maybe both, impossible to steal it and the Quarg can sell you their stuff which would become less effective (and almost the same price). Example : Shield generation 600->300, for 120kg it's 2x more efficient that the best human shield, it's enough no ? But the worse is with the Quarg skylance 3000 dps and 600 ion damage for 60 kg, ok it cost 1800 firing energy/seconde but on a Bactrian you can put 2 Korath Tek'nel Reactor (1626 energy for 140kg) so you can use 2 Quarg skylance without problem. I don't really understand their characteristics when all in the game try to be balanced. Why their stuff don't have characteristics like all the other aliens ? Is the stuff will be forbidden by the human with some Huge penalty or something like that ?

**Comment by naehc** [comment] 2015-11-26 12:24
As I see it, once you are powerful enough to farm Quarg ships, there are no real challenges left in the game anyway... so the power of Quarg outfits doesn't matter much, as what you can achieve with them you can also achieve without them (since, at that stage you are strong enough to beat Quarg ships easily). Of course, once more missions/campaigns are added this "balance" could change drastically; e.g. if Drak (or other alien ships) are added.

**Comment by Oeleo** [comment] 2015-11-26 19:45
I don't really agree with you because I couldn't take tribute from 50% of the Republic's planet and with 8 bactarians with Human/Korath stuff you can easily lost ships against several republic ships and furthermore, it was harder to make money anyway. Because, if you farm the Korath, with their reactors at 14000000 it's already easy but at least the rest of the wasn't at the same prices. And when your ships with ~150 of shield generation  and  ~1700 dps become 600 SG and 6000 dps (and 600 ion dps !), you jump to strong to Godmode. Because it's not so hard to dismiss a Quargship, you can do it with a lot of firebirds too, I didn't tried it but i'm sure that you can do it with ~20 firebirds or less than 8 bactrians if you don't mind to lose 1 or 2, so you don't need to be so rich to do that, just loot several good reactors. And i'm not against best stuff, but I just think that something less better, less expensive and unlootable (or with huge penalty) could be enough. I saw that their reactors and cooler wasn't already lootable and when you look at the description of the Intrusion countermeasures it's write "no one wants to be caught by the Quarg with stolen technology" so I proposed that because I think that their creator already prepared something similar about that.

**Comment by egilburg** [comment] 2015-11-26 20:10
I think the issue is that the Quarg only ever show up in 1-2 ships and generally have indifferent attitude to you plundering their tech.

In the game's storyline, the Quarg even warn you how nobody ever wants to get on their bad side, and its reinforced by description of the Quarg defenses when you try to sell them. But the game never actually follows through with consequences of becoming the enemy of the Quarg.

The consequences should be severe. Quargs should have entire defence fleets like other planets, not just one-off ships. And if you become a Quarg enemy, their scouts should hunt and attack you and your fleet far and wide across the galaxy, not just camp in their home sector.

**Comment by gchapyzh** [comment] 2015-11-27 20:30
The moment you make them angry, they should instantaneously appear with a huge fleet and chase you into human space.

**Comment by endless-sky** [comment] 2015-12-17 03:52
Basically, once you're strong enough to plunder the Quarg, nothing is going to be a challenge for you - you've won the game. The long-term fix for this will be to add a whole bunch of intermediate-strength aliens in between the Hai / Pug / Korath and the Quarg, at which point the Quarg will probably need to be made even more powerful.

**Closed by endless-sky** 2015-12-17 03:52 UTC
Labels: balance
