### ISSUE TITLE
Second log on fight screen / replay when landing; different places for some feedback

### ISSUE THREAD

**Issue by 7eggert** [endless-sky/endless-sky#5181] opened 2020-07-27 20:18 UTC
While fighting, I don't usually have time to read the log. Important messages will get lost by scrolling and/or fading away. Especially if 10 ships scan my about 800 ships, I can't even read the steering feedback.

To change that, I'd like to have a log on the right half of my screen (if screen width permits) containing messages like "Escort xyz has been destroyed" rather than "drone 0815 scanned you" times 1001.

The navigation / landing box can be used to also show boarding commands, too. If there are different planets to land on, a dropdown there might help (it's hard to click on a planet if there is a fleet above). Fleet holding position / gathering might be indicated by a (G) or (H) icon there.

Scanning messages don't currently contain the name of the ship. I suppose it's important which ship would be scanned, otherwise future messages could be suppressed.

While scrolling, less important lines should be sacrificed in favor of more important ones. If a line says "Ship xyz is attempting to scan you", the "Ship xyz finished scanning you" line should replace it. If there is a chat line, a "scanned" line should not scroll from the screen.

Log Lines might be colored on the fight screen: "You sold … for a profit of …" might go green on the right side; "ship destroyed" red to the right, "scanned" blue to the left, chats to the left, too.

After landing, the complete log should be visible on demand.

Sorry for putting a lot into one request, but it's a common goal.

**Comment by Amazinite** [comment] 2020-07-27 20:23
Sounds like a duplicate of #3361 and its duplicates. I'd suggest posting ideas on fixing that issue there instead of opening a new issue. (*Please* use the issue template instead of deleting it and writing whatever you want. The issue template has a "related issues" section for this very reason.)

**Closed by Amazinite** 2020-07-27 20:23 UTC
Labels: duplicate
