### ISSUE TITLE
Endless Sky on Steam does not use new library UI

### ISSUE THREAD

**Issue by Thunderforge** [endless-sky/endless-sky#4641] opened 2019-11-04 04:13 UTC
Valve has been working on a [redesign for Steam](https://www.ign.com/articles/2019/10/30/big-steam-library-redesign-now-live-for-everyone) that had been in beta for several months, but is now available for everyone. Unfortunately, Endless Sky doesn't take advantage it.

<img width="736" alt="image" src="https://user-images.githubusercontent.com/6200170/68099056-fe2d5500-fe85-11e9-800e-8472f99a7286.png">

Note how each game has vertical "box art", except for Endless Sky, which has horizontal art and a black box above and below it.

Moreover, when you click on a game, artwork containing the title is showed in a horizontal way.

<img width="1131" alt="image" src="https://user-images.githubusercontent.com/6200170/68099247-fde18980-fe86-11e9-996e-f05020ac62e2.png">

However, Endless Sky has a screenshot overlaid with simple text.

<img width="1132" alt="image" src="https://user-images.githubusercontent.com/6200170/68099258-10f45980-fe87-11e9-9ddb-269edd1311db.png">

Endless Sky should support this new Steam UI by adding appropriate artwork.

**Comment by Amazinite** [comment] 2019-11-04 04:14
Duplicate of #4541.

**Comment by tehhowch** [comment] 2019-11-04 04:15
Related: https://github.com/endless-sky/endless-sky/issues/3378

**Closed by tehhowch** 2019-11-04 04:15 UTC
