### ISSUE TITLE
Locked out of capturing Kor Sestor ships after wanderer campaign?

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#9841] opened 2024-02-19 16:13 UTC
### Problem Description

After finishing (as far as I can tell from in game dialogue and code) the wanderer storyline, to where the Kor Mereti are friendly and the Kor Sestor no longer spawn outside of korath exile zones and don't have jump drives, it seems Sestor ships are no longer capturable since they can't be taken out of Exile space. Did I miss something or is this intentional? It doesn't seem to be mentioned anywhere else 

### Related Issue Links

N/A

### Desired Solution

Sestor ships obtainable after wanderer storyline

### Alternative Approaches

A single system where they still spawn, even rarely, where they can be taken to an outfitter

**Comment by Saugia** [comment] 2024-02-19 16:57
This is intentional. After the Mereti become friendly they are no longer capturable, and after the Sestor are destroyed they can only be found in possession of the Exiles.

**Comment by Amazinite** [comment] 2024-02-19 17:43
Dupe of #2039.

**Comment by Saugia** [comment] 2024-02-19 18:06
(That too.) So I'd imagine if there are any plans to have them re-obtainable, it would be pending more story, otherwise, intentional.

**Closed by Saugia** 2024-02-19 18:06 UTC
