### ISSUE TITLE
When using Nanobots the game crashes

### ISSUE THREAD

**Issue by Admiral-Danforth** [endless-sky/endless-sky#1672] opened 2016-10-04 02:18 UTC
I was using two Nanobots in the Deneb system, first I clicked on one in the ship menu and it crashed and next I had them attack something and it crashed. 

This may be related to the fact of the issue I had with the merchants, but I do not know code enough to be able to tell.

**Comment by endless-sky** [comment] 2016-10-04 02:24
It shouldn't be possible to have nanobots in your fleet in the first place.

**Comment by Admiral-Danforth** [comment] 2016-10-04 02:26
I edited the code and they did actually work because they did kill a star barge, which I was nowhere near (I was in a Derecho just going about my business)

**Comment by Admiral-Danforth** [comment] 2016-10-04 02:28
Also they do not show up as a ship in the list directly on your screen

**Comment by LocalGod79** [comment] 2016-10-04 03:57
i think the point M.Z. is making is that those "ships" take advantage of loopholes in code to create a specific environment that furthers a plot line: you placing them in a different scenario is bound to cause issues (or they would have been implemented in a fashion that would facilitate your use in the first place).

in short, this is a non-issue: Nanobots belong in Sayaiban and nowhere else.  if you're experiencing bugs related to Nanobots outside of that system, own them.

(please close this issue)

**Comment by KiLEdEnNis** [comment] 2016-10-04 12:55
it's like giving yourself 10^99 Bactrians and complaining the game crashes; you shouldn't do so anyway

**Closed** 2016-10-05 00:38 UTC

**Comment by endless-sky** [comment] 2016-10-07 02:22
Fixed in dccd1d2, just because crashes are bad even if caused by saved-game editing.
