### ISSUE TITLE
new fleet command "hold fire"

### ISSUE THREAD

**Issue by bobafetthotmail** [endless-sky/endless-sky#5257] opened 2020-08-24 23:47 UTC
I would like to have an additional fleet command to tell my minions to NOT SHOOT AT ALL, similar to the "toggle ammo usage" that can be used to make them not shoot missiles at all.

EDIT: Yes this can help capturing ships but quite frankly if I'm out capping ships I'm not bringing a 10+ Hai capital ship fleet with strong forward guns, a couple capital ships with ion cannons is 100% fine for that and I don't need this command if I'm doing that.

My main issue is with missions where sometimes you need to disable or follow or do other things and not just obliterate anything that moves. For many missions I have to just park the fleet and go alone because the AI of my minions is too aggressive. It's really a pain for most campaign missions that don't give you time to park and just thrust you into some situation.

It's also annoying for some flavor things, for example, in the FW mission where you are planting sensors on a planet and you discover that a repubblic corvette is doing the same, if I decide to spare them we get into orbit and my fleet insta-kills the little corvette I decided to spare in the RPG text before I can order them to go take a hike.

Having a keyboard command is better than using mouse as with current command setup I don't have a hand on mouse when in combat (I have one hand on arrows and one hand on the left of the keyboard for the fleet commands).

**Comment by tehhowch** [comment] 2020-08-25 01:47
Order them to go elsewhere in the system, via right-click.

Triaging as unlikely since there are plenty of workarounds and known strategies for maximizing plunder rate, and there is no need to spend dev time making it even easier.

**Comment by Drl-Omniar** [comment] 2020-08-25 04:37
if i knew more about endless sky's initial source code (and a little bit more coding experience) id would work it out. but i can't due to my little experience that i have, and my coding software that i use for personal plugins doesn't have the right plugins yet
(Time to continue to lurk some more)

**Comment by bobafetthotmail** [comment] 2020-08-25 07:46
> Order them to go elsewhere in the system, via right-click.
> 
> Triaging as unlikely since there are plenty of workarounds and known strategies for maximizing plunder rate, and there is no need to spend dev time making it even easier.

If I'm out capping ships I'm not bringing a 10+ Hai capital ship fleet, a couple capital ships with ion cannons is 100% fine for that.

My main issue is with missions where sometimes you need to disable or follow or do other things and not just obliterate anything that moves. For many missions I have to just park the fleet and go alone because the AI of my minions is too aggressive. It's really a pain for most campaign missions that don't give you time to park and just thrust you into some situation.

Having a keyboard command is better than using mouse as with current command setup I don't have a hand on mouse when in combat (I have one hand on arrows and one hand on the left of the keyboard for the fleet commands).

**Comment by Amazinite** [comment] 2020-08-25 10:46
Duplicate of #645.

**Comment by bobafetthotmail** [comment] 2020-08-25 12:15
> Duplicate of #645 and recently mentioned in #5245.

also similar scope (although this is much simpler than these)
https://github.com/endless-sky/endless-sky/issues/3862
https://github.com/endless-sky/endless-sky/issues/802
https://github.com/endless-sky/endless-sky/issues/2266

**Comment by litrevan** [comment] 2020-08-29 17:38
I use either the  g key or the h key to get my escorts to break off. See no need for another key for this when there are other possible uses

**Closed** 2021-03-07 21:43 UTC
Labels: duplicate, unlikely
