### ISSUE TITLE
Feature request: Changeable escort behavior/AI mode/personality

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#2266] opened 2017-03-15 11:05 UTC
I understand this wouldn't be very easy to implement, but still would be nice to have:
Similarly how NPC's have personalities, let's give the player an option to specify behavior of their ships, especially if said ships each have a unique role in player's fleet, because now they storm off to attack anyone nearby and eventually disperse themselves across the system.

Examples:

Unarmed — only for ships without weapons; tries to stay not closer and not farther than certain distance from their flagship, doing their best to stay away from trouble. Repairs friendly ships within allowed radii, but it's low priority.
Non-combatant — similar to timid NPC personality. Like unarmed, but also defends itself with whatever weapons it has (if the ship has missiles, will conserve them until threatened directly, then will start spamming them until threat is gone).
Support — similar to unarmed (for ships w/o weapons the only other option) or non-combat (for armed ships), but will go out of their way (and boundaries) to repair disabled friendlies.
Escort — tends to stay in formation around flagship and attack whatever flagship is attacking or whatever is attacking flagship or her escorts.
Aggressive — what we have now.
Retreat 50% — aggressive until when ship's hit points are at or below (max − hull_disabled) * 0,5; afterwards non-combatant.
Retreat 25% — aggressive until when ship's hit points are at or below (max − hull_disabled) * 0,25; afterwards non-combatant.

For fighters (and drones):
Similar, but they would consider not player's ship but their carrier to be their flagship.
Unarmed — for Boxwings.
Escort — deploy immediately after jump and guard their carrier, get recalled when carrier receives command to prepare to jump. Ignore Deploy/Recall commands, try to dock as per Retreat 50%, return when at full health. Strafe if their carrier is in one of aggressive modes.
Strafe — self explanatory. Try to dock as per Retreat 25%, obey Deploy/Recall.
Circle — self explanatory. Try to dock as per Retreat 25%, obey Deploy/Recall.

Or maybe for fighters would be nice to have these instead:
Unarmed, Escort, Aggressive, Neutral, Evasive
Aggressive vs. Evasive — how much AI prioritizes damaging target vs. avoiding damage themselves (trying to dodge missiles, for example).

Something like that. Is this even real and how far possibilities go?

And one more question: Why do Boxwings even get deployed, seeing as there's nothing useful they can do out there?

**Comment by KiLEdEnNis** [comment] 2017-03-15 14:29
> but I wanted to start discussion about this, so here goes:

just saying; the Steam forum is an area for discussions, the Subreddit may be, GitHub really isn't

an option is to add a customization per ship in the I screen, like "combat: always, when directly attacked", "stay ranged: yes, have all weapons in range, no" and "repair allies: priority, after battle, never"
and being able to link a fighter/drone to a certain fighter/drone bay, and have an option to release all or only a few certain ones

if you want a big discussion though, please go to Steam or Reddit, not here

**Comment by Bladewood** [comment] 2017-03-15 15:29
*ignoring the existence of the google groups forum*

**Comment by Tadrix** [comment] 2017-03-15 16:15
I tend to view this more of an issue than just discussion.

**Comment by KiLEdEnNis** [comment] 2017-03-15 18:54
@Bladewood I forgot, don't get the belt, it won't happen again

**Comment by tehhowch** [comment] 2019-06-19 12:53
Duplicate of #802

**Closed by tehhowch** 2019-06-19 12:53 UTC
Labels: enhancement
