### ISSUE TITLE
Is it possible to alter save(s?) location?

### ISSUE THREAD

**Issue by BuildBruh** [endless-sky/endless-sky#600] opened 2016-01-06 04:56 UTC
I've had endless sky working off a USB stick for a week or two, using a bat file to semi-automate adding/removing the endless-sky folder to %appdata% on windows. I was wondering if it was possible to  specify the save location on the USB itself? 

Frankly, I just don't understand enough about c++ to do much of editing the files in source (though the comments help immensely to understand and learn more about, thank you and any other contributors for that!)

P.S: What/where does std::/using namespace std; call from (what i assume) the g++ library?

**Comment by brick96** [comment] 2016-01-06 07:14
I was look through the code here on to help and I found main.cpp and learned that there was a command line
void PrintHelp()
{
	cerr << endl;
	cerr << "Command line options:" << endl;
	cerr << "    -h, --help: print this help message." << endl;
	cerr << "    -v, --version: print version information." << endl;
	cerr << "    -s, --ships: print table of ship statistics." << endl;
	cerr << "    -w, --weapons: print table of weapon statistics." << endl;
	cerr << "    -t, --talk: read and display a conversation from STDIN." << endl;
	cerr << "    -r, --resources <path>: load resources from given directory." << endl;
	cerr << "    -c, --config <path>: save user's files to given directory." << endl;
	cerr << "    -d, --debug: turn on debugging features (e.g. caps lock slow motion)." << endl;
	cerr << endl;
	cerr << "Report bugs to: mzahniser@gmail.com" << endl;
	cerr << "Home page: <https://endless-sky.github.io>" << endl;
	cerr << endl;
}
Maybe -c is what your looking for? Not sure if this helps sounds like you know more than me

**Comment by BuildBruh** [comment] 2016-01-06 07:19
@brick96 Thanks! I'd have to look into it in the morning. I focused mostly on files and the various dataxxxx files, definitely will read through main for this!

**Comment by endless-sky** [comment] 2016-01-06 13:51
This is a duplicate of #92. In addition to using the command line, as mentioned above, another solution is just to make the endless-sky folder in AppData into a symlink to your desired folder location.

**Comment by BuildBruh** [comment] 2016-01-06 14:21
Damn, my bad. Didn't search for savegames or preferences

**Closed** 2016-01-06 14:24 UTC
Labels: duplicate
