### ISSUE TITLE
Cargo and Passengers Teleported to Flagship on Load of Save Game

### ISSUE THREAD

**Issue by fuzzyTew** [endless-sky/endless-sky#5461] opened 2020-10-18 17:25 UTC
**Describe the bug**
If you land on a planet when members of your fleet are not in the system, and then load your saved game, you cannot depart the planet if some of your mission items were held by the distant ships.

**To Reproduce**
1. Buy a bunch of cargo or passenger ships
2. Get a bunch of jobs exhausting your cargo or passenger space
3. Jump a bunch of systems away, leaving your fleet behind, and land on a planet
4. Take off from the planet and then load your saved game
5. Try to take off from the planet again: the issue is triggered

**Expected behavior**
I should be able to successfully depart the planet, because the out-of-system ships are carrying the cargo and passengers I don't have room for.

**Screenshots**
I failed to take a screenshot before resolving the last time I had this issue.  I'll try to remember to take one next time it happens.

**System (please complete the following information):**
 - OS: Red Hat 7.7
 - Game Source: git sources
 - Version: commit hash c1afeac04f64757780dce6c0a18ecfe5d7777534

**Link to save file**
Again, I'll have to preserve this when the issue happens again.

**Additional context**

**Comment by MCOfficer** [comment] 2020-10-18 18:23
probably a duplicate of #5441

**Comment by tehhowch** [comment] 2020-10-18 19:08
Duplicate of the __pinned issue__ https://github.com/endless-sky/endless-sky/issues/1624

**Closed by tehhowch** 2020-10-18 19:08 UTC
