### ISSUE TITLE
Fleet is instantly destroyed if missiles and 'Spend ammo' set to 'Always'

### ISSUE THREAD

**Issue by tukoz** [endless-sky/endless-sky#4556] opened 2019-09-27 16:16 UTC
My escort ships gets *instantly* destroyed upon arriving on the system when they are equiped with missiles and 'Spend ammo' is set to 'Always'. More specifically:           

- ~50% of the nearby escort ships that have shield+hull `=<` Navy Cruiser (100% get disabled during that single second)
- ~100% of the nearby escort ships with shield+hull `=<` Leviathan, Arach Hulk, Falcon, Vanguard and so on.

**To Reproduce**

- Capture or buy ships until you can deploy anything above 20 of them
- Equip your hyperdrived/non-jump-drive escort with some missiles launchers (of which *heavy rockets*) note: I do this with the smaller and transport ships rather than with the capital ones.
- set 'Spend ammo' to 'Always' either before or early on upon arriving at destination system

**Expected behavior**

- missiles explosions impact your escort accordingly to

  1. the type and amount of missiles DPS they launch during the initial salvo, and 
  2. obstacles in the system that are within the missile(s) explosion range (e.g. 200 for heavy rocket) compared to any of your ship.

**Screenshots**
At H + 1 sec then H + 3 sec upon arriving in this system:

![20190821071145_bug_fire-ammunitions-instant-destroy-dozens-of-MY-capital-ships](https://user-images.githubusercontent.com/2217680/65784301-06d98f80-e152-11e9-95c1-6340236d3d0f.jpg)
![20190821071845_bug_fire-ammunitions-instant-destroy-dozens-of-MY-capital-ships](https://user-images.githubusercontent.com/2217680/65784315-0e009d80-e152-11e9-9b48-93e344283468.jpg)

**System:**

- Arch linux up-to-date (e.g. kernel 5.2.8-arch x86_64 GNU/Linux with Nvidia 435.21)
- Game Source: Steam 1.0.0.61
- Endless Sky v0.9.9

**Additional context**

Happens without any plugin as well as with (eg. 'BetterVanillaPirates').

**Comment by tehhowch** [comment] 2019-09-27 18:26
What's the issue you are reporting? If you have a lot of escorts and they're firing a lot of strong missiles, then whatever they're shooting at is going to be destroyed very quickly.

You mention this occurs in the base game with no plugin ships or plugin missions active - can you provide a save file and the steps to reproduce the issue you are seeing?

**Comment by MCOfficer** [comment] 2019-09-27 20:42
judging by this

> Equip your hyperdrived/non-jump-drive escort with some missiles launchers (of which heavy rockets)

> missiles explosions impact your escort 

i'd say this is referring to escort suicide. which is an issue, due to the AI being a bit dumb, but not technically a bug.

**Comment by tukoz** [comment] 2019-09-27 20:48
@tehhowch 'Escort ship' mean the player's ships (e.g. in [Player's Manual](https://github.com/endless-sky/endless-sky/wiki/PlayersManual)), but I'll edit post n. 1 to make it clearer.  
Looking at the screenshots above you'll see dozens of **my** capital ships (and most of the smaller ones) get instantly destroyed **if** 'Spend ammo' is set to 'Always' either before or early on upon arriving at destination system. 'Instantly' = before the first second ends. **If** 'Spend ammo' is set to 'frugally' or 'never' then none of my ships are destroyed during that time. But then they don't fire a single missile (or almost).

|ship|shield|hull|total|
|----|-----:|---:|----:|
|Osprey|7 | 2 | 11k|
|Vanguard| 10 | 6 | 16k|
|Hulk | 6 | 14 | 20k|
|Kestrel | 20 | 7 | 27k|

How many missiles are required to hit how many obstacles within the blasting radius in order *instantly* destroy 40 of these ships? Also, happens without many asteroids (screenshots), with very little enemy ships within the blasting radius, and 99% of the casulaties are mine. Isn't that legit.

**Comment by tukoz** [comment] 2019-09-29 20:24
Update: Got the game (with a pilot + fleet) back and stable without any sort of plugins, but it took some time. Now searching for a system with more than a couple pirates, as the galaxy seems almost empty of them pirates coming from "Better Vanilla Pirates".
Question: would a save file be totally useless if plugin '[Better Vanilla Pirates](https://github.com/ZBok/BetterVanillaPirates)') was installed in this location?

**Comment by jafdy** [comment] 2019-09-29 21:27
No, but a list of all used plugins is helpful. Just in case.

**Comment by tukoz** [comment] 2019-09-30 01:42
Thank you jafdy. I asked about the plugin presence after playing a few hours on pure vanilla with no problems (and no pirates or almost none lol).  
So here is a save file where, if setting 'Spend ammo' to 'always', I consistently get 30-40 of *my* ships instant-wrecked ie *destroyed* upon arrival. Not the best exemple [1] but it'd gives you the idea.

- Endless Sky v0.9.10 (Beta)
- Plugins: just one '[Better Vanilla Pirates](https://github.com/ZBok/BetterVanillaPirates)'
- Systems: Algorel (depart) -» Phecda (destination)
- My non-jump fleet is ~2/3 guns and ~1/3 missiles of wich ~15 heavy rockets. My jump-equiped fleet has no issue at all firing missiles.

Question: how can 40 (or even 100) missiles destroy such number of ships in less than one second, i.e. well before any ship even exploded?
[Garg.Antua-test-exploding-your-ships-with-missiles.zip](https://github.com/endless-sky/endless-sky/files/3668476/Garg.Antua-test-exploding-your-ships-with-missiles.zip).

PS: Result IG can be visually appealing even gorgeous but maaan, it's a bit expansive !o)

[1]: because of the crazy number of asteroids Phecda system has. I just can't wait any longer to show you.

**Comment by jafdy** [comment] 2019-09-30 09:24
Heavy rockets are splash, so there is no theoretical limit to the number of ships they can destroy.

**Comment by tukoz** [comment] 2019-10-01 02:19
Another save file much, much clearer.
[Garg.Antua-test-exploding-your-ships-with-missiles-NO-rockets-NO-asteroids.zip](https://github.com/endless-sky/endless-sky/files/3674105/Garg.Antua-test-exploding-your-ships-with-missiles-NO-rockets-NO-asteroids.zip)

Same game as [above](https://github.com/endless-sky/endless-sky/issues/4556#issuecomment-536367553)
- Systems: Phurad (depart) -» Wazn (destination, no asteroid)
- My non-jump fleet is ~2/3 guns and ~1/3 missiles (of which *zero* heavy rockets).

Issue: A few dozens of *my* ships are instantly destroyed (before any ship explodes) by *their* missiles *if* 'Spend ammo' to 'always'. 
Same question as before (without heavy rockets nor asteroids to explain): how can that many ships be destroyed by their own torpedoes/Meteor/Sidewinders and a few Hai trackers in less than one second?

Note: my way to move in such scenarios with pirates armada is the following:
1. All fleet: Hold on; Flag ship: engage cloaking
2. Flag ship: jump to the pirates' system then move opposite to where my fleet will arrive
3. Flag ship disengages cloaking; pirates ships rush to my flagship; release all fleet; check 'Set ammo' is set to 'always'
4. Fleet engage pirates from a distance (fast bombers have time/free space to break away)

**Comment by tukoz** [comment] 2019-10-04 11:44
So what else is *OP* waited for already?

**Comment by tehhowch** [comment] 2019-10-04 11:49
A save with no plugin requirements. Debugging plugin issues is not the responsibility of any maintainer in this repo

**Comment by Amazinite** [comment] 2019-10-04 12:24
This seems like a `wontfix` to me. Your Marauder Ravens have a LOT of heavy rockets, and your Vanguards have some as well, and you're launching into a system with a high asteroid density. I'm not able to replicate the mass dying that you're saying is occurring, but what I am finding is that since the ships hyperdrive in bunched up, the Marauder Ravens and Vanguards are causing a large amount of damage to themselves and to the other escorts near them since their rockets are slamming right into nearby asteroids and causing splash damage to themselves.

**Comment by tukoz** [comment] 2019-10-04 23:10
@tehhowch yes I understand that therefore the question and answer above: https://github.com/endless-sky/endless-sky/issues/4556#issuecomment-536342851 . Since AFAIK this plugin claims it's just *adding* ships, my reasoning was and is that the bare crazy number of ships could have revealed some otherwise invisible IG glitches:

> With this plugin installed, your game will be completely vanilla everywhere early game, except you'll see pirates in more ships that they don't use in vanilla, like Aerie/Mule/Vanguard (no military ships yet).

@Amazinite thank you for testing. Sorry I forgot about the Vanguard with 6 Particules and 1 Heavy Rocket each (those with more than 1 are all parked as are the Raven with rockets in this save). Thanks again for testing! Even though I have a hard time understanding how these few HR destroy way more of player's escort vs pirates ships, unless I take this literally:

> So it seems like this is just a case of friendly fire.

Like in player's escorts missiles hitting player escort ships?

Note all the testing I've done end game with BetterVanillaPlugin On since 0.9.10 went out revealed much less of these cases. Specifically, none yet where dozens of my *capital* ships would be instantly sent to Hell in the first second of the fights, like it did every so often with 0.9.9. From my tests and yours I guess one could put any HR equiped ship in a group and prevent them coming *with* the rest of his or her fleet.

**Comment by Amazinite** [comment] 2019-10-04 23:44
>Like in player's escorts missiles hitting player escort ships?

What specifically seems to be occurring is that your ships hyperdrive together, all bunched up, then an unfortunate asteroid passes by your heavy rocket ships right when they attempt to fire at a target. Since you had so many ships with heavy rockets, as well as so many ships bunched up together, all the heavy rocket ships fire at once, hit the asteroid that passed by, and cause splash damage to your own ships, heavily damaging many and destroying the weaker ships.

**Comment by Pointedstick** [comment] 2019-10-17 21:23
Seems likely. The AI should probably avoid firing unguided splash-damage weapons when an asteroid is in the way.

**Comment by jafdy** [comment] 2019-10-18 08:03
Give weapons an arming range, so they don't do damage just after they have been fired? Then if they hit something only very shortly after being fired they don't hit the thing that fired them. Moving at high speeds might brake this in some way but it should save a few ships (and offers the chance to fight ships like that by getting very very close).

**Comment by tukoz** [comment] 2019-10-18 08:50
I like @jafdy proposition a lot as it would improve the immersion by a magnitude. Pirates included (i.e. these Hawks and Fury destroying themselves on first shot... jee).  
Note that yesterday after my Tek Far 78 shields got fully wrecked by my ships before the battle starts I got rid of all heavy rockets out of frustration.

**Closed** 2021-04-26 22:32 UTC
Labels: unconfirmed
