### ISSUE TITLE
Furnace Class Generator vs Dwarf Core

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1106] opened 2016-05-21 01:16 UTC
`Generator (Furnace Class)`
`Price: 625000`
`Mass: 39`
`Outfit Space: -39`
`Energy Generation: 330/s`
`Heat Generation: 780/s`
vs
`Dwarf Core`
`Price: 900000`
`Mass: 36`
`Outfit Space: -36`
`Energy Generation: 288/s`
`Heat Generation: 840/s`
The Furnace produces more energy and generates less heat, and takes up only 3 more outfit space, although it sells for less.
Confuse.
michaelfixplz

**Comment by endless-sky** [comment] 2016-05-21 03:46
I've tweaked the prices a bit: 10b4b7c.

**Comment by wambat1** [comment] 2016-05-21 07:51
i was just noticing this last night. i was wondering if the difference in price simply reflected the poor resale value of non-reproducible alien technology.

**Comment by endless-sky** [comment] 2016-05-30 20:24
Closing this because it's fixed in 0.9.1, which is released now.

**Closed by endless-sky** 2016-05-30 20:24 UTC
Labels: balance
