### ISSUE TITLE
When destroyed, ships could left debris and wreckage for salvage operation

### ISSUE THREAD

**Issue by montaropdf** [endless-sky/endless-sky#6045] opened 2021-06-06 11:40 UTC
**Is your feature request related to a problem? Please describe.**
No

**Related Issue Links**
#990
#3190
Thanks to @beccabunny for pointing them out. 

**Describe the solution you'd like**
When destroyed, ships should left debris fields and even wreckagee for the bigger one, depending how they have been destroyed.

Those debris and wrecks, could be salvaged using a variation of the boarding game play and some specilised equipment.

Wrecks should have a greater change of containing working equipments, while debris would provide mostly metal and other basic materials.

Debris and derelict ships, should stay in the system for a long period of time especially in system without a trading hub.

They should, also, drift slowly in space, requiring searching for them.

Regarding the specilised equipment, an alternative would be to simply store industrial goods as equipment, it would avoid creating another equipment. Those industrial equipments are disposable, salvaging will lead to such machinery to be destroyed during some operation. The more salvaging equipment you have the better the chance of avoiding problems during operations and retrieving valuable equipments.

Debris and wreck should also act like asteroid combat-wise and provide cover.

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by beccabunny** [comment] 2021-06-06 11:50
> Related Issue Links
None

https://github.com/endless-sky/endless-sky/issues/990
https://github.com/endless-sky/endless-sky/issues/3190

**Comment by montaropdf** [comment] 2021-06-06 12:31
> > Related Issue Links
> > None
> 
> #990
> #3190
> ?

Indeed, they are related, I update my initial post with those references.

**Comment by Pointedstick** [comment] 2021-09-20 04:58
Basically a duplicate of https://github.com/endless-sky/endless-sky/issues/990.

**Closed by Pointedstick** 2021-09-20 04:58 UTC
Labels: enhancement
