### ISSUE TITLE
Fleet ship indicator turning red if map opened mid-jump

### ISSUE THREAD

**Issue by Wrzlprnft** [endless-sky/endless-sky#988] opened 2016-04-23 14:45 UTC
The fleet ships symbols in the bottom right turn red if they can't jump with you, but they also do so while you jump and it's their last jump before they have to refuel.

**Comment by endless-sky** [comment] 2016-04-23 17:52
Fixed in 582d653.

**Comment by Alkallid** [comment] 2016-04-23 20:51
Also, happens when you open the map mid-jump.

**Comment by Amazinite** [comment] 2016-04-29 20:23
It's working as intended for me. The indicators aren't turning red when I open the map, only when attempting to jump and a ship has no fuel.

**Closed** 2016-04-29 20:51 UTC
Labels: bug, unconfirmed
