### ISSUE TITLE
(bug) Skeins are letting Finches free when jumping

### ISSUE THREAD

**Issue by LZHM1230** [endless-sky/endless-sky#1019] opened 2016-05-01 04:37 UTC
My fleet of 40 Skeins and assorted carriers/Bacterians has a shared total of 344 Finches between them, but when I jump between systems, the Finches occasionally seem to "fall out" between systems, leading to about 18-36 Finches left behind whenever my fleet jumps to a new system. (I jump ahead of them as only Bacterians/Korath Raiders are equipped with jump drives.)

So, say from Tarazed I jump to Sheretan. The jump drive equipped ships reach much earlier, but once the rest of the Fleet (Kestrels, Dreadnoughts, Carriers, and Cruisers) arrive, there will inevitably be Finches left behind. Another issue is that sometimes the Skeins themselves get left behind and refuse to  move, so when I jump into the system, I see a skein surrounded by dozens of Finches. Not even a joke.

It's really surreal seeing them all clustered around a single ship, but as I type, there's  Skein in Peacock and Ascella, and about 48 Finches in each system. When I jump in with my fleet to those systems, and recall the fighters, the 48 finches move in one bunch, stacked on each other, the mass hovering to each fighterless Skein, then repeating. Doing this for 8 fighterless Skeins per system takes 5 minutes, and their behaviour is really, really, really, weird. Is this supposed to happen?

**Comment by LZHM1230** [comment] 2016-05-01 05:07
I was jumping back to retrieve those Finches, and now there are about 66-90 Finches in Deneb!

**Comment by LocalGod79** [comment] 2016-05-01 07:25
ships are spontaneously deploying their fighters?

**Comment by LZHM1230** [comment] 2016-05-01 07:54
It seems that they are deploying when I am not in the system and waiting for them to arrive...

**Comment by jafdy** [comment] 2016-05-01 07:57
I noticed this as well. I think it may be when you deploy fighter ships in other systems are doing it as well. Most of the Skeins jump out then one ship is trying to carry a huge number of fighters.

**Comment by LZHM1230** [comment] 2016-05-01 08:02
yep, unfortunately this happens even when I don't deploy fighters. It seems
rather random

**Comment by jafdy** [comment] 2016-05-01 08:26
Ok well i'm stumped.

**Comment by LZHM1230** [comment] 2016-05-01 10:51
On further inspection, it appears that this bug only happens if I press escape and then re-enter the game while my Skeins are in another system.

**Comment by endless-sky** [comment] 2016-05-01 13:59
Are you sure that you toggled "deploy" off before jumping? If your ships are still set to deploy fighters, they will try to recall fighters when jumping but then dump them as soon as they are idle for a second.

**Comment by LZHM1230** [comment] 2016-05-01 14:02
Right, I'll watch out for that happening and notify you if anything is off,
or whether I'm just the shitty player complaining to the author again hahaha

**Comment by LocalGod79** [comment] 2016-05-01 16:31
and so begins the adjustment to fleets with fighters...

**Comment by DingusShingleton** [comment] 2016-05-01 20:58
Two steps forward, one step back; such is the price of progress

**Comment by LocalGod79** [comment] 2016-05-02 01:24
there *is* a bug where if your fleet is gathering, but in another system, and you land - when you take off, those fighters undock, and if they cannot dock before the carrier jumps, they are left behind...

**Comment by endless-sky** [comment] 2016-05-03 01:04
I've made it so that "deploy" only applies to ships in the current system (677dc88). But I'm not sure if that was the root cause of the problem or not.

**Comment by LocalGod79** [comment] 2016-05-03 02:32
having tested the commit, i can tell you that: upon takeoff, when your escort fighters and carriers are in another system, the fighters are no longer docked in their bays.

my temporary gameplay fix is to tell my fleet to hold position while i land, and then wait for all the fighters to dock before telling the fleet to gather again (or wait for my entire fleet to catch up to me).

**Comment by LocalGod79** [comment] 2016-05-03 02:35
having (actually) tested the commit, i can tell you that: if your escort fighters and carriers are in another system when you land, upon takeoff, the fighters are no longer docked in their bays, and the carriers leave them behind in an attempt to gather.

my temporary gameplay fix is to tell my fleet to hold position while i land, and then wait for all the fighters to dock before telling the fleet to gather again (or wait for my entire fleet to catch up to me).

**Comment by endless-sky** [comment] 2016-05-03 03:08
That should be fixed in 09b7387, but I still haven't been able to reproduce the initial issue.

**Comment by endless-sky** [comment] 2016-05-03 03:25
Of course, that introduces another issue: if fighters in other systems are not unloaded when you land, they end up "teleporting" to the current system if you reload the game (because they have no system defined). So, I think 5de8fab is the best compromise.

**Comment by LocalGod79** [comment] 2016-05-03 04:29
perhaps it's something to do with the way the player's fleet list is laid out?  i.e. lots of carriers, then tons of fighters, rather than carrier, fighters, carrier, fighters...

this is a new phenomenon for me, so i'm trying to figure out what's different now, besides slower escort carriers...

**Comment by endless-sky** [comment] 2016-05-30 20:27
Closing this because it's fixed in 0.9.1, which is released now.

**Closed by endless-sky** 2016-05-30 20:27 UTC
Labels: bug
