### ISSUE TITLE
frugal firing/Angle of fire

### ISSUE THREAD

**Issue by CruaverVoidDrake** [endless-sky/endless-sky#3053] opened 2017-09-16 00:23 UTC
This is a main issue I find with the system. I make or buy a weapon that use ammo but rather than calculating how much is needed and holding back frugal settings do nothing, same as never. If I set it to always I basically spam ammo all over the place making extremely high costs. So why is it that frugal fire doesn't do anything? If anything it should launch at targets based on the formula:
 target hull/weapon damage*asteroid percentage this way the system would not fire so many at a time. As it is:
Always: Fire all ammo batteries without regard for target's size, shields, etc
Frugal: Fire no ammo at all
Never: Fire no ammo at all

Seems like a bug to me, and hopefully my suggested formula will help you improve the system.

As for the second bug, when building weapons and ships I notice that turrets don't account for the ship in the way, ie they fire straight through my ship no matter how big, no matter what side of the ship they are on. This should be in the settings, ships are not flying cardboard, they are three dimensional entities.

**Comment by gunqqer** [comment] 2017-09-16 00:25
Yeah I've seen that too, frugal just doesn't let them shoot. Could just be me

**Comment by CruaverVoidDrake** [comment] 2017-09-16 00:36
So far my only solution has been to increase the reload time on the drones to make it so they have more time to think. Less drain on resources but the shields take more of a beating.

**Comment by endless-sky** [comment] 2017-09-16 00:48
Frugal firing means your ships will only fire secondary weapons if you are outgunned, i.e. the enemy ships in-system are stronger than your fleet.

**Comment by CruaverVoidDrake** [comment] 2017-09-16 01:05
Ok I didn't know that, but it makes no difference when the ships I built don't have anything other than the secondary weapons. I'm building ships after the stargate Aurora class warships, which for the most part only fire drones.

**Comment by tehhowch** [comment] 2017-09-16 02:11
Strength is measured in cost, not damage per second.
Frugal ships will also fire when they are sufficiently damaged as well.

With regards to restricted firing arcs, this is not yet a feature. Gun hardpoints fire in the ship's `facing` direction, and turrets have a 360deg arc, with a non-instantaneous turn rate. It is not a bug that turrets on the port side of the ship can fire at targets on the starboard side.

**Comment by CruaverVoidDrake** [comment] 2017-09-16 04:08
We have different definitions of bug then.
1. Strength should not be measured in cost, they aren't on a proper relative curve. I could make my drones 100% piercing and cost a million credits or a billion credits each and they'll still be fired the same.
2. It's rather counter productive to fire explosive weapons when you're damaged, that's a suicide run not frugality. 
3. It is a bug because it should not happen, from a logical perspective. As I stated, ships aren't seen as 2d, they need to be seen as 3d. You need to think in three dimensions (unlike star trek where all the ships are magically on the same y value). Turrets either take up space or are integrated into the system, the best case is direct integration since if they are taking up space on the exterior of a ship they'd only hit a target when it's above or below the ship relative to the placement of the turret.
4. Bugs can be a failing at a concept or a failing of an intended feature, thus I'm counting it as a bug. (Plus it cuts back on issues to one instead of two that I'd have to keep track off.) I would suggest allowing turrets to have the left or right tag of fighter and drone bays, while the default can remain a 360° arc to prevent old systems from breaking apart.

**Comment by tehhowch** [comment] 2017-09-16 05:01
1 - cost is one of the balancing mechanisms for an outfit. 
2. Ships will avoid firing weapons that will damage themselves at any HP, provided the projectile hits its target at the estimated point of impact (current velocity + time flight estimate). Most outfits that are secondaries are not splash damage effects, so this is irrelevant anyway.
3. This is a space trading and combat game, not a space sim or one claiming 100% accuracy of mechanics. Realism and truth of logic are sacrificed for gameplay experience and *fun*. I notice you did not complain that disabled ships come to a stop, 
4. You are confusing a feature and a bug. The game does not state that turrets fire on a single side of the ship. If it did, then there would indeed be a bug in the code. However, endless sky merely lacks a feature that you would like to see implemented.

**Comment by CruaverVoidDrake** [comment] 2017-09-16 05:10
1. Cost is not automatically calculated, meaning any custom outfits can be grossly overpowered.
2. Ok you make a good point there, but that doesn't mean they should wait till they are half dead.
3. There's a point where things can be explained due to sci-fi nonsense and when it can't. Ships coming to a stop when disabled is one that can be explained away as inertial dampeners fail to remain powered to keep it's velocity. Hence my 24k ton ship can be pushed around by the weapons of those super powerful aliens I haven't figured out how to contact yet. If it were a space sim then we'd all lose because flying space ships are super hard and something always goes wrong. Not that I haven't found that out in my early days when I ran out of fuel exploring systems.
4. I'm saying they should, it's not like I'm yelling and screaming with flaming pitchforks, I just think it would be a realistic change that would give more diversity to the weapons and customization of plugins.

**Comment by ghoulavenger** [comment] 2017-09-16 05:47
1. Game cannot be balanced against what is not part of its core, e.g. if you're saying a custom outfit is overpowered, then you need to take it up with the creator of the outfit.
3. There is no inertia or friction in space, ships should always keep moving until another force stops them -- in fact, the typical behavior of the game is this, you can accelerate for a bit and then keep flying until you decelerate intentionally. Disabled ships stopping makes no logical sense, but it works great from a gameplay standpoint.
4. Realism is often a sticking point versus playability. The question is, is the change necessary? I don't think so, because turrets are the significantly easiest way to play combat (speed of combat makes it so that ships are constantly turning, which makes forward mounted guns much harder to control).

**Comment by CruaverVoidDrake** [comment] 2017-09-16 05:59
1. I was pointing out that using a system based on cost was pointless because outfits can be overpowered and underpowered to any lengths thus an automatic adjustment to firing parameters would make sense that way it would help creators balance their creations.
2. Inertia is the newtonian force that makes objects continue doing what they do, it always exists. Inertial dampeners would be the sci-fi answer to things like artificial gravity, high speed changes, and people not flying into walls on movie sets (lol). And you just described inertia so I think you failed in your ideas there.
3. I agree turrets are far easier to work with because they can adjust better, bust most ships with turrets have at least 2 one on each side because your logic sense tells you that's where they go. But think about it this way, in star trek (just as an example) phasers can only fire in the direction they are angled. So very much like turrets, but they cannot fire through the ship. It's not as if I'm saying change everything, I'm just saying that giving the option to lock turrets in a specific angle of fire adds an entirely new range of ability to customization and fighting. With turrets having angle issues you then have to start thinking about keeping your ship moving or enemy ships can move in under you and stab you to death. Dynamic fighting gives players more options and more ways to fight, or you can just turn on automatic aiming and firing and let the computer do all the work.

**Comment by ghoulavenger** [comment] 2017-09-16 06:39
1. Assuming that it is in the core game, then you can assume the outfits will be balanced for the functionality of its features. Therefore their systems in theory should work fine, in practice may require some fine tuning.

2. I don't think you understand. Inertia is indeed the reason why you would not decelerate in space, because the force is always applied to keep your ship in motion. Where is the counter force to the inertia to slow down the ship? In Earth this force is called friction. Space does not have friction. You're throwing out random statements as if they make any sense whatsoever. If inertial dampeners were the theoretical answer, then your ship would *need* to be functioning for them to do *anything*. Or are you suggesting that an attacking vessel tractors you to a halt? While possible, that seems like you might have to chase them first.

3. You want to turn turrets into guns basically -- the game already has guns.

**Comment by CruaverVoidDrake** [comment] 2017-09-16 07:01
1. I am quite aware of that. It would be nice if there was a "balancing" formula that I could use to finish my plugin making, rather difficult to do true to tv sci-fi in the game. But it's still a fun challenge.
2. Well speaking from a sci-fi perspective if one's inertial dampeners were to suddenly cut out the default inertia would return, meaning all your high speed moves would suddenly grind to a halt as if acted upon by a force of friction. (Plus in space there is particles from stars via the stellar wind, negligible but just barely strong enough to be mentioned.)
3. Guns are locked into facing one way, they can't move unless the ship moves. While sure I'd love for them to have some range in the data files on how they're positioned that's not what I'm after. What I'm after is a logical use of turrets. Your ship in space either has the turrets on top and bottom allowing for a full 129,600° rotational multi-directional axis (that's including the x, y, and z) and this is a limited way of turrets. It doesn't allow for ingrained turrets, the sort of turrets that fire out from the sides of ships rather than the top or bottom.

**Comment by ghoulavenger** [comment] 2017-09-16 07:39
I don't think inertial dampeners make any sense then. One needs to overcome inertia to enter motion, and once in motion inertia becomes momentum. Adding more inertia into the mix sounds to me like it would actually make it harder to change velocity (your thrusters aren't stronger, but your resistance to acceleration is). This could be preferable if you wanted to be able to maintain a uniform velocity, but accelerate rapidly (intertial dampeners on to accelerate, off to maintain velocity).

Normally, to stop your ship you would need to apply the force yourself in the form of thrust. Reverse thrust or turning your ship around and applying thrust in the opposite direction are how this is applied in game. The space particles bit might be more interesting, but as you said, negligible and well beyond the scope of this game, since it isn't a space simulator, but a space exploration game.

Well if you want locked turrets for your own development purposes I guess I can't tell you no, but I feel those would be very awkward outfits to use. They basically give up the strength of the turret for the limited nature of the gun, or pretty close to it.

**Comment by CruaverVoidDrake** [comment] 2017-09-16 07:49
Think about it this way, what happens when you drop say an anvil on a moving wagon? It suddenly slows down. You didn't change if the wagon was moving forward or backwards, but it still slowed down because the effective mass increased. So the inertia of mass A cannot provide the same velocity of mass B because of the difference in their mass. 

It would only be the limited nature of the gun if they are locked at one degree. But if instead I am able to specify how far they can turn, then I'd call that progress.

**Comment by ghoulavenger** [comment] 2017-09-16 08:29
If you dropped an anvil on a wagon and the wagon remained intact, it would indeed slow down. Basically the wagon had to make the anvil move as the wagon is moving, first by overcoming downward momentum (if the wagon survived the impact, then the wagon might vibrate, causing energy to leave the wagon), then by making the anvil move forward (since the anvil was NOT in motion in the direction of the wagon the wagon would need to overcome the anvils inertia). It's basically the same principle with people on a train. When a person is on a train they have a zero relative velocity to the train, but a non-zero relative velocity to the outside. This means if the train stops suddenly and you fly out the window, you're going at the velocity the train was going at, despite not being in motion relative to the train. 

The ship however is a little bit different. First, the ship is already moving, so unlike the anvil which did not have the a zero relative velocity with the ship, the ship still has a zero relative velocity with itself. Second you still didn't supply the necessary counter-force to the ships motion -- so even if the ship is more massive, there is still nothing slowing it down.

**Comment by CruaverVoidDrake** [comment] 2017-09-16 08:37
The ship's own movement would slow it down. Now instead of dropping said anvil on the poor wagon instead imagine you were to change the mass of the wagon without changing its other velocities. For the sake of math we'll assume this wagon is sliding over frictionless ice. Once you change the mass, the original inertia which was providing the "force" to move the object has to move a much larger object thus slowing it down. The mass itself acts as a force. Remember these sci-fi inertial dampeners were used to let the ship move as fast as it can at a smaller mass. Suddenly reintroducing that mass should in theory counteract the force event. This is why in most sci-fi ships continue to apply thrust even though in space they should retain their velocity.

Furthermore, this is totally irrelevant to this thread. The whole point was to discuss including options for turrets to have a limited arc of attack and a better frugal ammo usage even maybe a retrieval system since things like unexploded missiles can still be reused.

**Comment by ghoulavenger** [comment] 2017-09-16 08:48
>Once you change the mass, the original inertia which was providing the "force" to move the object has to move a much larger object thus slowing it down. 

Inertia is the force that resists acceleration. This object is *not accelerating*, it is already *in motion*. This does not act upon itself, it acts upon other forces. *Show me the counter-force and you can have your deceleration*.

Is it irrelevant? I thought the whole point of this line of inquiry was about the realism within the game and how you're being picky and choosy instead of accepting game mechanics? But I'll stop harping on it if you do.

**Comment by CruaverVoidDrake** [comment] 2017-09-16 08:53
The counter force is the mass suddenly being added, how have you not realized that the re-adding of the mass would be like hitting a wall? Up till the moment of shut down the ship was operating as if it was super small, thus the missing inertia has to go somewhere.

There's a difference between sci-fantasy, and sci-fiction. One's pure stupidity (Invader Zim) and the other is mumbo jumbo that invents concepts and ideas that may or may not happen/work in the future (Star Trek). You brought up ships stopping when disabled.

**Comment by ghoulavenger** [comment] 2017-09-16 09:05
>You brought up ships stopping when disabled.
No, I didn't. tehhowch did.

>The counter force is the mass suddenly being added, how have you not realized that the re-adding of the mass would be like hitting a wall? Up till the moment of shut down the ship was operating as if it was super small, thus the missing inertia has to go somewhere.

It already did -- the conservation of mass and energy would state that the mass *never* left. It was merely transformed. The exact effects of one of those things breaking might be beyond me, but I don't think you're right. More likely that if it violently broke the ship would be destroyed (the hull would likely already be compromised and unable to sustain the extra mass), but it would still be moving.

**Comment by CruaverVoidDrake** [comment] 2017-09-16 09:15
Ok I admit, I was wrong about that one. I'm not good with people names…

Near as I can figure there are a handful of options:
A. The ship shatters at the sudden experience of moving at high velocity with a mass that cannot be sustained by the materials.
B. The ship suddenly stops or slows down immensely as the inertia of the ship that had been shielded from the effects of the acceleration suddenly shows up and demands the same divided velocity thus the greater the difference in velocity the greater the deceleration.
C. The ship continues on uninterrupted and you never get to raid it for resources or capture it for sale.
D. The inertial dampeners fail partly instead and the ship breaks apart as some parts want to continue at high speed and the others want to regain the inertia they had before. 

Oh and the only way I can think of to affect inertia without converting part of your ship into energy (which would likely cost vast amounts of power, certainly far more than is reasonable for interstellar flight) would be to alter the properties of space itself, namely to warp the space so as to negate the natural warp we call a mass's gravity. It's that warping on the fabric of space that we call inertia.

**Comment by jafdy** [comment] 2017-09-16 09:59
If you increase the mass of an object there is no acceleration because the extra mass is already moving at the same speed.

There is a simple way to prove this.
The Sun would be speeding up relative to the universal stationery point if an increase in mass could slow on object. Since saying "universal stationery point" is complete nonsense a change in mass dose not affect velocity directly.

I will also point out that Si-Fi ship always thrust forward because it looks good.

**Comment by warp-core** [comment] 2017-09-16 11:52
Inertial dampeners were not used to reduce the effective mass of a ship in Star Trek except in the second episode of DS9 were they were modified to do so in order for the weak engines on the station to move it closer to the wormhole in a reasonable amount of time. Outside of that, they were used as an explanation for why the massive changes in momentum of the ships did not affect the contents of said ships.
The point that @tehhowch originally made was that sometimes, in games, a set to which Endless Sky belongs, "Realism and truth of logic are sacrificed for gameplay experience and fun." Using the example of how you did not complain about how disabled ships come to a stop as an example of where a lack of realism is something that has been accepted for gameplay purposes.
This is a lack of realism as the disabled ships have no way of producing a force to slow themselves down and, even if inertial dampeners worked the way you believe, that would only result in a reduction of speed (assuming inertial dampeners exist in ES at all) as kinetic energy would be conserved and since KE = (1/2)mv^2, an increase in mass (m) would result in a decrease in velocity (v) but it would not result in the ships coming to rest as this would require velocity to be 0 and so kinetic energy would have to reach 0 but there is nothing to reduce the amount of kinetic energy the ship has.

On the topic of limiting turret targeting arcs, the game takes place in 2D, so the turrets will act as if all the ships are on the same plane because they are. Changing this would basically make this an entirely different game. All the turrets are mounted on top of the ships and so, in general, have a full 360 degree view, the only way to prevent this would be to add 3D information about ships to allow the game to determine where the turrets are and where some part of the ship _**may**_ block their line of sight. Giving specific turrets limited turn ranges would require rebalancing of all turrets, all ships, all fleets and every single piece of mission/job based combat in the game.
And since there are already fixed guns and to be able to utilize them you have to ensure that your ships is pointing in the correct direction, limited turret range is pointless.

**Comment by KyroFirehammer** [comment] 2017-09-16 14:42
A solution could be to add a way to set ships to judge how much firepower should be used on a ship
 i.e preventing it from shooting of 10 typhoons on a fighter and instead shooting a few meteor missiles

**Comment by warp-core** [comment] 2017-09-16 14:50
A frugal ship won't fire 10 typhoons at a fighter and a ship that always uses ammo _should_ use the ammo anyway. Taking into account how much health the enemy ship has, how much damage the ammo based weapons are going to do, in addition to any non-ammo based weapons that may be used, and how many of the projectiles are likely to strike their target (because some might hit asteroid, some might get taken out by anti-missile turrets (not just on the target ship but on any ships of opposing governments) and some may just be outrun by the target ship) would be extremely difficult for programming (some of the factors that affect if the ship will be hit are based on random number (anti-missile) as well as requiring for the AI of the firing ship to predict how other ships will act and having to account for asteroids (which wouldn't be too difficult for non-homing weapons but is fairly complicated when the missile can home and will change direction to follow the target ship) and will increase the processing required to run the game by a _**lot**_.

**Comment by KyroFirehammer** [comment] 2017-09-16 15:54
More like a "expend  cheaper first " so they will shoot the cheaper ammo before the more expensive unless you are outgunned

**Comment by CruaverVoidDrake** [comment] 2017-09-16 16:38
I take a rest and you all spam at me…oh well I'll catch up.
1. Star Trek never said they were using inertial dampeners to move DS9. But if you want a show that actually said it you can check out Stargate SG-1 where Sam specifically states that the engines take mass out of the equation. So that would mean when it's re-added it would cause the system to slow proportional to what was being canceled out. However there's always the option that ships have an emergency brake that fires when disabled to prevent them flying into the abyss so that they can be rescued, it's actually a pretty smart system.
2. No it would not take full 3d information, it would just require something like this:
Turret x y AngleOfFire ArcOfFire 
And by default the turrets can be considered transverse being dual turrets on the top and bottom allowing for full 129,600° fire. As I stated before, I just want the option for creating purposes.
3. Frugal fire only needs to calculate the basic fire requirements and use them then switch to another target. Think about all the ordinance you waste on target A when target B could be getting hit with it. If you failed to destroy the original target then that's fine you can return to it with the same system. Less waste, smarter firing.

**Comment by Kryes-Omega** [comment] 2017-09-16 17:04
I think that a good way to balance it would be to set how much ammo you fire at the enemy ship based on the damage it will do relative to their health, for example, a shield beetle with 6 nukes and a heavy laser, would only fire 1 at a time at a sparrow, but maybe 2-3 at another shield beetle. that way, you're not firing everything, but you aren't simply ignoring your secondary because the enemy isn't big enough.

**Comment by warp-core** [comment] 2017-09-16 17:09
You're correct, I apologize, DS9 was moved by utilizing the deflector array to reduce it's inertial mass, not inertial dampeners. And, in Stargate, inertial dampeners do indeed reduce (or increase if desired) the effective mass of the ship, an increase in mass as a result of inertial dampening going offline would _only_ reduce the velocity of the ship, it would still be moving. (Assuming inertial dampeners exist in ES and serve the same purpose as the ones in Stargate which wouldn't make sense in itself, why can't we add more inertial dampening through outfits to reduce the ships mass further?)
On the topic of a space brake, if such a thing existed in game, why can't ships that aren't disabled just use it to come to a stop instead of having to turn around and fire their main engines in the opposite direction to their motion?

On the topic of limited turret range, if it's not as a result of parts of the ship (such as fins that extend upwards) blocking the turrets, you're talking about arbitrarily limiting the amount that the turrets can physically turn, see my previous point:
> And since there are already fixed guns and to be able to utilize them you have to ensure that your ships is pointing in the correct direction.
If you only want the ability to specify the limited turn range for your own content, I'm sure it can be done, you'll either have to modify the source code yourself or find someone capable, and willing, to do it for you.

For ammunition usage, making it so that the ship fires off enough to kill the enemy ship if all of the projectiles hit their target and then switching to the new target, doing the same here and then switching back to the first target (because it's probably not dead because asteroids, anti-missile, limited velocity and turning of the projectile and imperfect tracking) would result in the ship taking more damage as target A which would've been killed in, say, 2 seconds, will take 1 second of projectiles, have time to regenerate some of shields and continue doing damage while target B is shot at for a second. This effect would be amplified if there are more than 2 enemy ships. The current targeting AI takes many factors into account, I can't explain them all, but this type of targeting would be worse. It'd also require rebalancing. However, @endless-sky does intend to do an AI overhaul, at least redo the code, if not actually planning to change the way the AI works at the moment, before the next release so if you can make a good enough argument for him, he might consider it.

**Comment by CruaverVoidDrake** [comment] 2017-09-16 17:20
Umm keyword emergency. You don't use your emergency stuff every time it's convenient. Most ships don't have back thrust so the AI by default turns them around hence even though my ship has back thrust it still turns around when on autopilot. Plus inertial dampeners would be needed or ion drives would be hopelessly slow. It's a matter of physics, little ions at high speed vs huge mass…
I'm talking about a way to simulate an obstruction without having to calculate entire 3d models. Why bother with that when you can just have the option to integrate the turrets into your custom ship.
Back to ammo usage. I never said just enough for the system. Recall higher up, I stated that the system should take the asteroid density into account. Plus the anti-missile tag on the secondary weapons can be used to define how much extra ammo is needed for the given target before moving on. Another option of course would be to alter the homing AI to switch to a new target so your fancy ordinance isn't going to waste in the vastness of space and instead trying to hit another viable target at random. Less waste.

**Comment by jafdy** [comment] 2017-09-16 17:35
p=mv mass and speed are equally important. If you fire 1kg of particals at 1x10^6ms^-1 then you will have enough moment change to accelerate a 100 tonne ship to 10ms^-1. If we push that a bit further and fire at 1x10^8ms^-1 (33% lightspeed) then that 100 tonne ship could get to 1kms^-1. 
Simply, Ion Drives work.

Your rules for homing weapons are to complex to be added. Whatever rules are used need to be guessable.

**Comment by warp-core** [comment] 2017-09-16 17:40
The only reason I can think of not to use a piece of technology that is available and is convenient to use outside of an emergency is if the technology can only be used once (obviously, it'd be restored to it's original condition on landing so it can be used again) but this would mean that if a ship is disabled, it comes to a stop with this omni-directional thruster that is comparable to (if not significantly better than) it's main engines in force output (since _your_ inertial dampeners are gone, the ship now has significantly more mass then before and so more force will be required to produce the same amount of acceleration) and then repaired, and then disabled again, it no longer comes to a stop. This results in inconsistent and frankly, unenjoyable, gameplay especially for new players who are going to be confused about why ships sometimes stop when disabled but not always and are going to assume it's a bug. Of course, if this emergency braking thruster doesn't need to be reset everytime it is used by landing on a planet, why can't it just be used whenever it is convenient since it seems pretty convenient to use.

Why do only ion engines necessitate the need for inertial dampeners? They produce less thrust than their less heat/energy efficient counterparts and so result in a proportionally lower amount of acceleration. The ion engines are also not 'small' and certainly not comparable to modern ones.

You want to simulate an obstruction on the ship. What if there are multiple obstructions and the turret has 2 arcs that it can fire in? If you want this to be added to the base game ships, good luck rebalancing everything. If you only want it for your own content, I point you to my previous response:

> If you only want the ability to specify the limited turn range for your own content, I'm sure it can be done, you'll either have to modify the source code yourself or find someone capable, and willing, to do it for you.

As for secondary weapon ammunition usage, I have nothing to add that hasn't already been said by me or someone else.

**Comment by CruaverVoidDrake** [comment] 2017-09-16 17:49
You do realize you need to get those ions from somewhere and that NASA hasn't finished work on ion drive themselves? So no, ion drive is still horribly bad at fast acceleration when you have a massive ship. Efficient, yes. High acceleration, no.

Back to this emergency brake, there's no telling how destructive it could be. For all we know, lore-wise it could put the ship at risk of being torn asunder and risking the lives of everyone on board. Definitely something only useful for emergencies. It could even have it's own emergency power for inertial dampeners. It's not like we're demanding a full workup on how the ships work though. Sci-fiction doesn't have to work out all the bugs, just enough to be theoretically viable.

Back to the arc question, what ship designer would allow a turret to turn in such a way as to hit part of the ship even by accident? It's a bad design. You don't increase the risk to your ship just so you can fire more. One arc of fire should be just fine. Since it could be set as an option for the base game it would give vastly more versatility to customization. And if the base game ship designers want to use it, then by all means.

And I don't think homing weapons would be that horribly complex. You could just keep sending them targeting data from the firing ship. Would they hit asteroids or run out of fuel before hitting the new target? Maybe, depending on how close the ship is.

**Comment by ghoulavenger** [comment] 2017-09-16 17:53
>It's not like we're demanding a full workup on how the ships work though.

When you target a specific feature because it isn't realistic, you have to justify why it isn't realistic. You're trying to do just that because the behavior is preferable to the alternative. So, naturally people are going to poke holes in it. The whole point is that a game mechanic does not have to be realistic to be functional.

**Comment by CruaverVoidDrake** [comment] 2017-09-16 17:55
It's also something we see in sci-fi tv series all the time, so trying to explain something that every sci-fi franchise already does or does not would be a waste of time.

**Comment by ghoulavenger** [comment] 2017-09-16 17:57
What happens in sci-fi is not necessarily realistic either. But as long as we're talking realism, we're talking realism in game, sci-fi isn't the same thing.

**Comment by CruaverVoidDrake** [comment] 2017-09-16 17:58
I gave you a viable explanation, do you want me to also explain the potential way for hyperspace to be done?

**Comment by ghoulavenger** [comment] 2017-09-16 18:01
> I gave you a viable explanation, do you want me to also explain the potential way for hyperspace to be done?

That depends. Are you trying to disqualify hyperdrives because they are not realistic? If not, we already have one large incongruity to work with and there is no need for further counter-examples.

**Comment by CruaverVoidDrake** [comment] 2017-09-16 18:01
Anyways, back to my marathon to catch up on all the youtube I missed while building my plugin. Please provide a bullet point list of all things you want me explain on how they can or could be realistic…

**Comment by warp-core** [comment] 2017-09-16 18:09
If the emergency brake has a chance of ripping the ship apart, why would anyone use it? And it would also require a random attribute be added to each ship and everytime a ship is disabled, it needs to have a chance of being destroyed there and then. This is another piece of inconsistent gameplay, unless new players have it explicitly stated to them that, when a ship is disabled, it has a chance of destroying itself, they're not going to understand why it keeps happening. It could be stated in a message like self destruction but they'll likely have the same question as I: Why would anyone use it? And they'll also probably get annoyed about how it nerfs capturing and plundering as a method of making money.

@endless-sky already has an explanation of how a theoretical hyperdrive could work.

> what ship designer would allow a turret to turn in such a way as to hit part of the ship even by accident?

Good question. The answer is 'none' and that's why all the ships in game have the turrets mounted on top without obstructions. I already said that all the ships are considered to be on the same plane because the game is 2D. If you want a 3D space sim there are other games that do that.

Sending missiles targeting data would be a _big_ change. Currently, a missile only knows it's target and it's government. (I'm not even certain about the second one.) Not the ship it was fired from.

As for ion engines, you're comparing modern technology to fictional technology from a game set 1000 years in the future where there are aliens that can make, manipulate, and destroy wormholes. What makes you think NASA's stuff can even compare?

**Comment by jafdy** [comment] 2017-09-16 18:34
>You do realize you need to get those ions from somewhere

Easy; Take gas, add electrical discharge, get ions.

>subspace

is an excuse to explain FTL travel in some games and films/TV. It was supposed to be believable and you fell for it completely. The only "Subspace" compatible theories out there are the nested universe ones, and they can't explain the fact that only some routes are available.

**Comment by CruaverVoidDrake** [comment] 2017-09-16 21:46
> If the emergency brake has a chance of ripping the ship apart, why would anyone use it? And it would also require a random attribute be added to each ship and every time a ship is disabled, it needs to have a chance of being destroyed there and then. This is another piece of inconsistent gameplay, unless new players have it explicitly stated to them that, when a ship is disabled, it has a chance of destroying itself, they're not going to understand why it keeps happening. It could be stated in a message like self destruction but they'll likely have the same question as I: Why would anyone use it? And they'll also probably get annoyed about how it nerfs capturing and plundering as a method of making money.
That's what emergency things are for, they are options of last resort. Plus this is just a sci-fi explanation of why ships suddenly stop when they are disabled. 

> Good question. The answer is 'none' and that's why all the ships in game have the turrets mounted on top without obstructions. I already said that all the ships are considered to be on the same plane because the game is 2D. If you want a 3D space sim there are other games that do that.

Just because the representations of the ships are 2D doesn't mean they have to be seen as 2D. Adding in some more 3D mechanics would add in a greater dynamic to the system. (And force the AI to not bring ships in so close. If you play around with a fleet of warships you'll notice they overlap when they really shouldn't, I suppose we could consider that another bug. Easily fixed by adding in a size variations of the sprites) I like this game because I don't have to mesh and texture a 3D model that would no doubt look horrible considering how much performance death would happen with high quality models. 

> Sending missiles targeting data would be a big change. Currently, a missile only knows it's target and it's government. (I'm not even certain about the second one.) Not the ship it was fired from.

Actually yes I can semi-confirm the second one because the bird of prey I flew around in was able to cloak after firing a torpedo at a republic surveillance drone. I still agrod them so I'd take that as proof the missiles keep who owns them into account. Maybe only with players though.

> As for ion engines, you're comparing modern technology to fictional technology from a game set 1000 years in the future where there are aliens that can make, manipulate, and destroy wormholes. What makes you think NASA's stuff can even compare?

Yes, yes I am. I am doing so in order to show the issues with it. Any fuel propellant adds to the mass of the ship in question. Thus after enough time you'll run out of fuel and die in the vastness of space. In order to use ion engines all the time you'd need to have a source such as solar wind which would only work if say you had a magnetic deflector that absorbed the particles into a chamber for high speed expelling out the engines while your inertial dampeners lessened your mass to the point the ion engine's expelling is enough to provide suitable thrust.

> [subspace] is an excuse to explain FTL travel in some games and films/TV. It was supposed to be believable and you fell for it completely. The only "Subspace" compatible theories out there are the nested universe ones, and they can't explain the fact that only some routes are available.

Oh don't be silly, I was considering subspace as a mixed layer between the 2nd and 3rd dimensional layers that would, should the universe be like a Russian nesting doll, be significantly less distance than normal space thus allowing FTL travel without that nasty business of relativity getting in the way. The explanation for routes could be that those are ways that are easiest to use and without a jump drive to let you teleport between systems. Don't underestimate how good I am at explaining away nonsensical sci-fi bs, I explained transporter tech without that stupid quantum cloning problem.

**Comment by Bladewood** [comment] 2017-09-16 22:57
Stop.

This is a 2D space game.
It is a *core* feature of the game that gameplay is in two dimensions.

**Comment by CruaverVoidDrake** [comment] 2017-09-16 23:01
> This is a 2D space game.
What you see - the 2D gameplay, the simple sci-fi excuse - are core features of the game.

Well aren't you limited in your thinking. A map used for plotting placement and movement of troops is 2D but it represents a 3D item. Once you start thinking of it as only 2D you fail to get the same thrill of a space battle. That's why we include inaccuracy in the weapons, because unless something is homing in on a target there's no reason for your shot to miss because computer assisted targeting.

**Comment by MessyMix** [comment] 2017-09-16 23:24
This IS a 2D space game. Period.
It's a homage to the Escape Velocity series that defined the top-down space game genre. That's not changing. It's what the game is. In every other case, I would call this thinking closed-minded. But it's literally THE central tenet of the game.
Your emergency stuff just adds too much complexity to the game. The only emergency thing I would go for is an escape pod for hardcore mode, but that's been discussed before; it'll come when it's ready.
And, your explanations of sci-fantasy phenomena is just downright unrealistic. It's FINE for them to exist, because we're not doing science. We can all suspend our belief for a bit to have some fun, or for a feature to work best. Hyperspace is only one example. (No, "subspace" isn't a valid explanation. Alcubierre drives are probably the most plausible, but I have my doubts about even that.) Let's just make things up that SOUND okay, and not try to actually explain it, because it'll break down one way or another. Remember midichlorians? The thing that ruined the Star Wars prequels? That happened because they actually tried to scientifically EXPLAIN the force. Let's not go there. Keep it simple. It'll work out. :)

**Comment by Amazinite** [comment] 2017-09-16 23:40
If you're complaining about the current way that frugal acts in game then this issue is a duplicate of #1871 (which would handle how the frugal personality is handled to avoid missile Argosies being useless).

>I'm saying they [i.e. turret arcs] should [exist]

Which makes this issue a duplicate of #2237. Given that both "bugs" brought up in the original issue are duplicates of other issues, this issue should be closed.

I'd go on, but anything else is repetition from what others have said at this point.

**Closed** 2018-01-18 02:37 UTC
Labels: question
