### ISSUE TITLE
Wanderer shipyards can be viewed from the start

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1603] opened 2016-09-21 00:00 UTC
https://github.com/endless-sky/endless-sky/blob/master/data/wanderer%20missions.txt#L308
"Wanderers Conversation":
> ...and that you will be allowed to "[view, admire, envy]" their ships, but not to purchase them.

I think you should do one of two things:
1. Prevent the player from visiting Wanderer shipyards until you complete "Wanderers Conversation".
2. Change or remove this line.

I'd prefer 1, because that line is brilliant, and because I don't really see the point of letting us visit shipyards but not outfitters.

**Comment by MessyMix** [comment] 2016-09-21 01:52
You can have licenses on ships, but they aren't used on outfits. Therefore, once the outfitter is opened, then you can buy Wanderer outfits, but you can have licenses on ships so that the player can't buy it.

I think it's a brilliant line too, and the fact that you are allowed to enter the shipyard but not purchase the ships actually _reflects_ the literal meaning of the line.

**Comment by KiLEdEnNis** [comment] 2016-09-21 12:06
outfitters should be able to require licenses, it would make it more realistic

**Comment by MessyMix** [comment] 2016-09-21 12:46
That would be another project for another time. As of now, I don't think it's _that_ important.

**Comment by KiLEdEnNis** [comment] 2016-09-21 13:36
it isn't indeed, just a cool feature for 1.0.0

**Comment by endless-sky** [comment] 2016-09-23 20:16
This is basically a duplicate of #666.

**Closed by endless-sky** 2016-09-23 20:16 UTC

**Comment by KiLEdEnNis** [comment] 2016-09-23 21:15
666... ;-;
