### ISSUE TITLE
Please add a "lock ship" or "favourite ship" mechanic to prevent faviourited ships to be sold.

### ISSUE THREAD

**Issue by IrradiatedKiwi** [endless-sky/endless-sky#9833] opened 2024-02-16 01:21 UTC
### Problem Description

Selling ships,especially multiple ships can be dangerous.As some player's faviourite ships,inculding flagship,can be sold accidentally.The in game confirmation warning can not solve this problem sufficiently.

For example,I have multiple ships I carefully outfitted.But after captured hundreds of similiar ships,I want to sell all others ships except my favourite ones.This can be worrisome since there are too many look-alike ships.And i don't want to accidentally sell my favourite ships by mistake.

There was also a time that I accidently sold my unique flagship because I accidently press S in Shipyard.
I don't think additional warning message when selling flagship is the sufficient solution here.
Also I **don't** want the S key to sell ships in shipyard to be removed since the key is actually quite useful.

### Related Issue Links

I searched github issues but didn't find similiar suggestion.

### Desired Solution

Add a mechanic to marks ships as a "locked " or "favourited",which will prevent some ships to be sold in shipyard.

My suggestion is that If I can just lock the ships i want to keep,I can simply select all ships and sell them in peace.In this way the locked ships will be kept while all other ships will be sold.

I don't know about code but for GUI I think this can be done with a little lock or heart icon in "Ship info" menu or besides the ship picture in shipyard to lock desired ships.

### Alternative Approaches

N/A

### Additional Context

I also wish the lock ship protection mechanic is applied universally instead of limiting to one specific shipyard.So player don't have to worry about selling their favourite  ships whenever they are trading at any shipyards in the galaxy.
I believe this mechanic will also make fleet management easier.

**Comment by xX-Dillinger-Xx** [comment] 2024-02-16 20:15
I, as well, have accidentally sold ships I wished to keep and would like to see this feature. 
@IrradiatedKiwi You can always reload your game from a previous planet and everything will be back, safe and sound. It's not always practical but it is an option.

**Comment by IrradiatedKiwi** [comment] 2024-02-17 03:07
> I, as well, have accidentally sold ships I wished to keep and would like to see this feature. @IrradiatedKiwi You can always reload your game from a previous planet and everything will be back, safe and sound. It's not always practical but it is an option.

Thank you for the reply

I know I may retrieve my ship via reloading save files,but this is really not a proper way to solve the problem of accidental selling ships,especially if you have too many look-a-like ships.

Also if sold my ship then exited game and then cleaned my save files,i won't be able to get my ship back.

**Comment by xX-Dillinger-Xx** [comment] 2024-02-17 05:04
Trust me, I understand, but like you, I'm just a player. Hopefully, someone who matters will chime in.

**Comment by Hurleveur** [comment] 2024-02-18 14:52
> Trust me, I understand, but like you, I'm just a player. Hopefully, someone who matters will chime in.

All players matter, and anyone can just open a PR to do changes - ofc you need a dev to merge it at the end of the day, but the community matters.
Anyway this could be useful if its expended to outfits as well so you dont sell your unique outfits by selling the ship its on by accident.

**Comment by Hurleveur** [comment] 2024-02-19 08:35
https://github.com/endless-sky/endless-sky/pull/9085 would this be enough?

**Comment by Hurleveur** [comment] 2024-02-19 14:54
I mean not being able to open a PR just means you have to wait longer before to get the functionality in, and you dont have to be sorry for it haha

I see what you mean, I just never had this issue because I ~~play single ship now~~ know how many ships I captured/have, and the captured ones are all at the bottom of the list. That doesnt mean it isnt a worthwile thing to add, but maybe the easy and somewhat intuitive way to go about it would be to hide those ships from the shipyard list, effectively singling out all others?

**Comment by xX-Dillinger-Xx** [comment] 2024-02-19 16:38
Without looking myself, whats happens if you add "unique" to a ship? If it doesn't work at the ship level what about adding it to one of the weapons installed on those favorite ships. Clearly, you don't have any issues with editing your save file. Just a short term solution, but .....

> `unique:` if present, the outfit is considered to be unique. When disowning a ship with a unique outfit or when launching from a planet that has unique outfits in stock that will be lost when you depart, a warning will be provided telling you that you will lose the unique outfits. Intended for use on outfits that are limited in quantity within a single save file; stuff that once lost, the player will never be able to r

**Comment by Amazinite** [comment] 2024-02-20 22:30
This is effectively a duplicate of #9022, so closing this to move discussion there (or to the newly opened PR).

**Closed** 2024-02-20 22:30 UTC
Labels: duplicate

**Comment by xX-Dillinger-Xx** [comment] 2024-02-21 00:11
@IrradiatedKiwi They created a PR #9844

**Comment by lumbar527** [comment] 2024-02-21 00:57
#9844 is a PR so I think it's less about the discussion of the feature and more about the implementation maybe.

**Comment by quyykk** [comment] 2024-03-14 18:52
> but this is really not a proper way to solve the problem of accidental selling ships

Why not?

> Also if sold my ship then exited game and then cleaned my save files,i won't be able to get my ship back.

Seems like a very contrived scenario...

**Comment by xX-Dillinger-Xx** [comment] 2024-03-14 21:16
What are you asking, because it sounds like your suggesting we don't need PR#9844 .  I'm I too assume you think having to reload a save file is a good enough solution?
Isn't the best solution to provide a way to prevent accidental sale in the first place?

And BTW this was never a duplicate of #9022  there offer two completely different approaches.

**Comment by Amazinite** [comment] 2024-03-14 21:38
> And BTW this was never a duplicate of https://github.com/endless-sky/endless-sky/issues/9022 there offer two completely different approaches.

We don't open an issue for every idea someone has to solve a problem. Issues are for tracking the problem itself. Both #9022 and this issue are about the same problem.

> 9833: [Ships] can be sold accidentally.

> 9022: If you accidentally sell a ship you didn't mean to, you can't recover it without reloading from a previous save.
