### ISSUE TITLE
Functionality for missions to check for, add, and remove ships

### ISSUE THREAD

**Issue by AzureNyoki** [endless-sky/endless-sky#4679] opened 2019-11-21 08:55 UTC
**Is your feature request related to a problem? Please describe.**
This feature would open up new possibilities for missions, like gaining a ship as a reward, or a mission to capture a particular ship and bring it back.

**Describe the solution you'd like**
This feature is already present for outfits. One mission in the free worlds questline needs you to capture electron lasers from the republic, and this is also how you get your hyperdrive substituted for a jump drive at the end. I propose a similar feature, but one that checks for a ship in your fleet instead, adding or removing them.
As a secondary but related suggestion, a unique identifier for ships could also be implemented, something like an unchangeable "license plate", for the event that you have to capture a specific ship, like a hypothetical mission to capture a pirate warlord's personal ship, to be a trophy in an enemy pirate's headquarters.

**Comment by tehhowch** [comment] 2020-01-31 04:28
Is this not a duplicate of https://github.com/endless-sky/endless-sky/issues/4399 too?

**Closed** 2020-01-31 15:35 UTC
Labels: duplicate
