### ISSUE TITLE
Reduce the Size of Ship Icon in the Outfitter Screen

### ISSUE THREAD

**Issue by hellogts** [endless-sky/endless-sky#3486] opened 2018-01-03 04:11 UTC
It's a pain when you have too many ships and have to scroll up and down to find a new ship to outfit.  It would be ideal if the ship icon's size adjusts dynamically depending on the number of ships you own, so that all ships can be displayed on a single page.

**Comment by tehhowch** [comment] 2018-01-03 04:20
Duplicate of #3326

(please close this issue)

**Closed** 2018-01-03 04:23 UTC
