### ISSUE TITLE
PlanetLabel renders behind stellar objects

### ISSUE THREAD

**Issue by DeaeLunae** [endless-sky/endless-sky#6194] opened 2021-08-17 00:43 UTC
**Describe the bug**
[A clear and concise description of what the bug is.]

**To Reproduce**
1. Set date to Sat, 25 Jul 3035
2. Set current system/spöb to 7 Autumn Rising/Sandy Two
3. Zoom in or out just so (see screenshot)

**Expected behavior**
A readable label. It turns out that simply reordering the render order won't do this in a way that makes text readable.

**Screenshots**
<img width="303" alt="bug" src="https://user-images.githubusercontent.com/80430868/129645714-983de001-ee96-4621-a497-2b853e9ad73d.png">

**System (please complete the following information):**
 - OS: [e.g. Windows 10 Pro, build 19042, also confirmed on Xubuntu 20.04.2 LTS
 - Game Source: Nightly, also self-compiled
 - Version: commit hash dda40b6

**Link to save file**
[Luna Deos.txt](https://github.com/endless-sky/endless-sky/files/6996114/Luna.Deos.txt)

**Additional context**
A PR will be submitted shortly following this report with my suggested fix.

**Comment by Amazinite** [comment] 2021-08-17 00:56
Duplicate of #6176.

**Closed** 2021-09-20 02:31 UTC
Labels: duplicate
