### ISSUE TITLE
Buying an outfit to cargo when the outfitter doesnt offer the item results in the wrong error message

### ISSUE THREAD

**Issue by hellminister** [endless-sky/endless-sky#8438] opened 2023-02-21 19:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When you try to buy an outfit to cargo and said item is not offered by the outfitter, you get the message that the item doesn't fit into cargo

### Steps to Reproduce

Have an item in storage or cargo that the outfitter doesn't normally sell (example : a jump drive)
Have more than enough space in cargo for said item
unselect all ships (to pass to cargo mode)
select the item to buy (the one from step 1)
select buy or press b

you get the message (in the case of a jump drive) "You cannot buy this outfit, because it takes up 20 tons of mass, and your fleet has XXX tons of cargo space free."

### Expected Behavior

Get an error message more in line with it not being sold at said outfitter for example :
"This outfit is not sold here" or "This outfit is unavailable for sell in this outfitter"

### Operating System

Windows 10

### Game Source

Steam

### Game Version

v0.10.0

**Comment by warp-core** [comment] 2023-02-21 19:55
I believe this is a duplicate of #7376. It should be fixed by #6952.

**Closed by warp-core** 2023-02-21 19:55 UTC
Labels: bug, unconfirmed
