### ISSUE TITLE
Trading

### ISSUE THREAD

**Issue by UserPlayer** [endless-sky/endless-sky#3876] opened 2018-08-01 10:46 UTC
At times the price of resources isn't displayed right. It shows profit :xxx instead of low or high without having any resources of that kind in cargo.

**Comment by Amazinite** [comment] 2018-08-01 15:06
Is this a bug report? Can you describe how you get this bug to occur so that we can recreate it?

**Comment by Pointedstick** [comment] 2018-08-01 15:27
And better yet, add a screenshot?

**Comment by tehhowch** [comment] 2018-08-01 18:32
Pretty sure this is cargo in parked or out of system ships. A known issue.

**Comment by Pointedstick** [comment] 2018-08-01 19:48
A known-non-issue? 😝

**Comment by RedLucidity** [comment] 2018-08-02 18:08
The out of system ship that has that type of trade cargo is also what I figured out... Perhaps some dialog in game as part of a starter mission might help with understanding this mechanism.

**Comment by tehhowch** [comment] 2018-08-03 17:40
@RedLucidity if you review the issue i linked, you will note that this issue is addressed.

Please verify you observe the behavior you take issue with on the current `master` branch. **If you cannot reproduce it, close this issue.** If you can, then you need to provide more detail about the behavior you are talking about.

**Closed** 2018-08-03 23:52 UTC
Labels: duplicate
