### ISSUE TITLE
Too many Southern Carriers

### ISSUE THREAD

**Issue by Alkallid** [endless-sky/endless-sky#1012] opened 2016-04-30 02:44 UTC
I have been playing the beta, and after dominating all of the Southern Pirates, I realized something- All the pirates were Carriers. If I went to Nunki or Shaula and demanded tribute, all I would get is a bunch of Barbs, Skeins, and Roosts. Most normal fleets when flying around Lesath or something were Roosts and Nests. When I was doing the FW escort missions, still a bunch of Roosts. The fighters they carried confused me, too. When demanding tribute, most of the carriers had Lances, when flying around normally they were nearly all Barbs, and only once or so did I see pirate Finches.

I checked fleets.txt, it didn't even _have_ the carriers in any fleets.

Writing this, I also realized that the Free Worlds and Militia _also_ had them. I think I saw some interceptors with them, but all warships or freighters were replaced by Carriers. They mostly carried Finches and Barbs.

Even the Southern Patrol ships are now two Nests and a Roost, though this could be intentional.

There is not a single other pirate or Free Worlds ships besides unconfirmed green interceptors.

**Comment by Alkallid** [comment] 2016-04-30 03:22
Also, I'm a bit too judgey, but in-game, the carriers look _wrong._ I'd agree with whatever lore there is that the ships were refurbished and that's why they look so new, but these are too brightly colored for me, and the edges are too sharp. LocalGod's _too_ good.

**Comment by Alkallid** [comment] 2016-04-30 03:27
I'd post a screenshot if I knew how...

**Comment by mdsmestad** [comment] 2016-04-30 03:36
I concur with this.I really like the southern carriers, but they are now it seems like that's all there is for the pirates. Fleets need some adjustments to make for more balanced compositions.

**Comment by endless-sky** [comment] 2016-04-30 03:51
You're right, it looks like the carriers event is setting those fleets to be nothing but carriers. I've patched the Steam build so that anyone who hasn't updated yet won't get that problem, but it'll need some sort of fix as well for everyone who's now stuck with nothing but carriers in human space.

**Comment by Alkallid** [comment] 2016-04-30 05:02
Can we change to 'Opt out' and back?

**Comment by jafdy** [comment] 2016-04-30 07:42
You could probably uninstall Endless Sky and reinstall it. You might want to back up your saves first.

**Comment by IFailAtGaming** [comment] 2016-04-30 11:53
on steam you can just delete all the files in the actual game folder then verify the game cache, that should keep your saves intact and fix it, of course the problem is if this sticks to the save through a mission

**Comment by endless-sky** [comment] 2016-04-30 14:00
I'll upload a fix today that adds new events that undo the events that created all the carriers. (Or, you can edit your saved game and delete the new fleet definitions.)

**Comment by LocalGod79** [comment] 2016-04-30 16:43
it was the fighter names, wasn't it?

**Comment by endless-sky** [comment] 2016-04-30 16:46
The issue is the way fleet modifications work: if you want to add new variants to a fleet, you have to also include all the old variants in your redefinition.

I'm testing a fix right now, so I'll probably upload it soon.

**Comment by LocalGod79** [comment] 2016-04-30 16:47
okay...not sure why i thought that events added variants to the fleet, rather than replacing it...

**Comment by Alkallid** [comment] 2016-04-30 17:35
Haulers to me don't look new at all, and the carriers are very bright and sharp against the background, whereas most other ships kind of fade in.

**Comment by endless-sky** [comment] 2016-04-30 18:13
Also, the X1050 ion engines sprite should be changed to have an even height, and to tone down the brightness of the engines so it will fit in with the other ion engines. (Because the height is odd, when it is drawn it is offset by half a pixel and comes out looking fuzzy. In general, I try to have all the outfit image dimensions be multiples of 10, just to keep things simple.)

**Comment by endless-sky** [comment] 2016-04-30 19:51
I've uploaded a fix for the carrier fleets: 20a3461. (I also made the carriers phase in over a whole year, starting with the Free Worlds fleets and gradually expanding northward.)

**Comment by VrykoMonkeylord** [comment] 2016-04-30 20:41
Is the fix live to the steam beta? If so, what should I do to see it? I'm still seeing only carriers.

Thanks!

**Comment by endless-sky** [comment] 2016-04-30 20:55
I just uploaded the fix to Steam. It will slowly phase out the carrier fleets over the course of a year of game time (if you were infected by them) and also make it so that new pilots you create won't get the carrier infection in the first place.

**Comment by VrykoMonkeylord** [comment] 2016-04-30 21:22
Excellent, thanks!

**Comment by toilethinges** [comment] 2016-05-01 01:45
I agree that the carriers do seem a bit... bright.

**Comment by LocalGod79** [comment] 2016-05-01 04:30
okay, so i'm working on the files to touch up my end of Southern Carriers.  i feel terribly about the "infection", and am suffering it, as well.  it certainly illustrates the power of massed fighters if you linger in a pirate system, though...

fixing the sprite for the X1050 Ion Engines was easy - the blending mode on the white blobs needed to be changed from 'overlay' to 'normal', cleaned up a little and opacity adjusted - boom, desaturated...

working over the carriers...are the fighters okay?

@endless-sky would you like these corrections to be tacked onto #995 ?

**Comment by LocalGod79** [comment] 2016-05-01 05:13
so, to discuss the actual carriers...
![hauler iii 2x](https://cloud.githubusercontent.com/assets/16969517/14940195/5f91a1ba-0f39-11e6-8ca7-09df621729c2.png)![skein 2x](https://cloud.githubusercontent.com/assets/16969517/14940196/6a9c596a-0f39-11e6-849a-766e77ecb858.png)
you can see from these images, that the "Hauler" part of the Skein is nearly identical (Southbound workers patriotically cleaned up some scorching when installing the new 'Type F' pods), and that the cargo pods, in both cases, appear to be of differing age than the engine/cockpit.

it is even more evident on the Hauler I than the III:
![hauler i](https://cloud.githubusercontent.com/assets/16969517/14940203/d071bdde-0f39-11e6-9a57-70da77d0c2e8.png)

**Comment by endless-sky** [comment] 2016-05-01 13:57
The trouble with the Hauler model is that so many surfaces are exactly horizontal, and therefore the lighting makes them all into flat patches of the same color - which ends up looking fake and flat. That's why the Hauler has so much more "fake" shadow drawn on top of it compared to some other ships.

Basically, when I'm post-processing ship sprites I use the black spraypaint to break up any line that seems too sharp and any big area that's all the same color. That's the only way to avoid having the ships look artificial.

Also, if by "sharpness preserving reduction" you mean something like doing an unsharp mask before you shrink the image - don't do that. The ship sprites are double the resolution that they are drawn at, which already serves quite well to preserve sharpness. If the original sprite is *too* sharp you get aliasing effects when the sprite rotates.

**Comment by LocalGod79** [comment] 2016-05-01 16:05
i'll take that into consideration - i think i'm going to take some of my newfound blender skills to the model to avoid the spray can, if possible.

actually, while using Photoshop's "Image Size" to reduce the resolution, i just made sure that it was using the "Bicubic Sharper (best for reduction)" option from the drop down in the dialog.  it's been my experience that the reduction remains sharper than if it's left "Bicubic Automatic".

i always felt like my results were comparable to your own, but others seem to be of a different opinion.

touched the 'house, and took the opportunity to illustrate the difference between reduction styles;
![roost auto](https://cloud.githubusercontent.com/assets/16969517/14942777/e2f9978c-0f94-11e6-9179-1d0374cce042.png)![roost sharp](https://cloud.githubusercontent.com/assets/16969517/14942776/e2f981a2-0f94-11e6-89b0-3f2b4c75c208.png)

**Comment by LocalGod79** [comment] 2016-05-01 17:04
a little more time on the blender...
![roost2](https://cloud.githubusercontent.com/assets/16969517/14943061/357bd85a-0f9d-11e6-971e-b447d8b62e2f.png)

**Comment by LocalGod79** [comment] 2016-05-01 20:06
those southern pirates sure love these new carriers, even after the fix...and so they should!

**Comment by endless-sky** [comment] 2016-05-30 20:27
Closing this because it's fixed in 0.9.1, which is released now.

**Closed by endless-sky** 2016-05-30 20:27 UTC
Labels: bug
