### ISSUE TITLE
Derelict Ship Personality Issue

### ISSUE THREAD

**Issue by Alkallid** [endless-sky/endless-sky#2121] opened 2017-02-08 00:56 UTC
If there's a derelict fleet set somewhere and you repair some of them, the repaired ships won't do anything until all of their fleet is fixed. Then they resume normal functions. Instead of sitting there, maybe make them go to repair their allies?

**Comment by tehhowch** [comment] 2017-09-19 05:41
Derelict ships, once repaired, are still quite low on health. This generally means they will stick near to their parent ship and avoid fighting.
Furthermore, derelict ships are forbidden from asking for help - only the player helps them - so the lack of providing assistance to their disabled derelict allies is intended behavior.

I'm not sure there is an issue here.

**Comment by Amazinite** [comment] 2017-09-19 11:32
I believe that when this originally made 
>the repaired ships won't do anything until all of their fleet is fixed.

That is, that stay completely stationary and don't even try and defend themselves before all the ships in the fleet are repaired I'm unsure if this is the case now, but one could test this by doing one of the first Wanderer missions where you defend against an Unfettered Invasion and some Wanderer ships start off derelict in orbit.

**Comment by tehhowch** [comment] 2017-12-07 21:59
Using this as a test mission:
```
mission "derelict test"
	name "derelict spawn test"
	job
	repeat
	npc kill
		government Merchant
		personality derelict escort
		fleet "Large Core Merchants"
```
as of eac558b0cda9535e2b3fa6a583562660dc972d61
And as soon as any one derelict is repaired, it responds to things going on in the system. (Since it is expressly forbidden for anyone but the player to assist a derelict ship, it won't repair its fleetmates)
I would consider this issue closed, with an unknown milestone

**Comment by Pointedstick** [comment] 2018-11-20 22:18
> I would consider this issue closed, with an unknown milestone

Yeah, closing.

**Closed by Pointedstick** 2018-11-20 22:18 UTC
Labels: bug, unconfirmed
