### ISSUE TITLE
Holding jump key without a hyperspace drive

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#3633] opened 2018-02-05 01:36 UTC
A certain muffindrake has told me that the alarm sound plays very, very rapidly when you hold the jump key without a hyperspace drive installed.

**Comment by tehhowch** [comment] 2018-02-05 01:45
Which is correct. The fail noise plays if you cannot make the jump to the selected system. If it is wormhole accessible, that would initiate the landing sequence to route there.
To me, this is working as intended.

**Comment by Amazinite** [comment] 2018-02-05 02:35
>the alarm sound plays very, very rapidly when you hold the jump key **without a hyperspace drive installed.**

https://github.com/endless-sky/endless-sky/commit/65b70c02db61f7c835eb8ed4e3b67383ea0339f8
Note how the repeating alert noise was only removed when out of fuel, but just a few lines up it has been allowed to repeat if no hyperdrive or no jump drive is installed.

**Comment by tehhowch** [comment] 2019-03-29 22:58
Fixed with 53a888545eb60b24030e00f46b38c105c3f190e5

**Closed by tehhowch** 2019-03-29 22:58 UTC
Labels: bug
