### ISSUE TITLE
Hub

### ISSUE THREAD

**Issue by UserPlayer** [endless-sky/endless-sky#3874] opened 2018-08-01 10:44 UTC
Hi all,

It would be nice to have the ability to choose a/one non inhabited world to create your home base/hub where you can store ships, cargo, missions and gathered equipment for future use.

Doesn't have to come for free.. Up keep, pay of maintenance personal related to storage size.

**Comment by Amazinite** [comment] 2018-08-01 15:05
Duplicate of a few other issues. #754 #2199
The whole idea of "maintenance costs" has also been brought up before, and if it isn't going to happen for outfits and ships then I don't see it happening for storing said outfits and ships: #2219

What functionality is exactly missing from the game currently that would allow you to store ships and equipment? Currently you can park your ships wherever you want, and it doesn't cost you anything. Storing specific outfits then is just a matter of installing them on a ship then parking that. And what exactly do you mean by storing missions, and what cargo would you even want to store?

**Comment by RedLucidity** [comment] 2018-08-02 18:02
I think the storage mission would be, 
Mission "Storage..."
' "I hear you have a secure storage facility. Well, I have this <Item> that needs to be stored until <date>. The thing is, I think someone is trying to steal it. Would you be store able to protect my <item> until I can have it retrieved on <date>?" '

**Comment by endless-sky** [comment] 2018-08-03 23:10
Given that the game already lets you purchase a cheap ship and stick anything you want to store in it, purchasable "storage facilities" already exist in the game.

**Closed** 2018-08-03 23:09 UTC
Labels: duplicate
