### ISSUE TITLE
Button for auto aim/steer towards targeted ship/asteroid/planet.

### ISSUE THREAD

**Issue by ChamEV** [endless-sky/endless-sky#4339] opened 2019-06-06 12:45 UTC
Currently there is no button for auto aim.  You can autoaim while firing, or none at all.  This option provides a middle ground and gives the player greater control of the combat experience.  Additionally this can be used to figure out which direction that one ship is, or that planet if one desires.  It even works on targeted asteroids.

The only current issue it has is the matter of preference keys layout.  I selected a default key of z, though A would be more in line with EV.

You can view the code here, https://github.com/ChamEV/endless-sky I'll submit a pull request soon.

**Comment by tehhowch** [comment] 2019-06-06 13:35
Duplicate of #166

Please make sure you reference existing issues (as pointed out in the issue template):

See also #314

**Closed by tehhowch** 2019-06-06 13:35 UTC
