### ISSUE TITLE
Attribute-landable planets can be selected via the map...

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2596] opened 2017-06-02 04:39 UTC
and will be highlighted when you visit the system (hitting the land key will even make the autopilot try and land on the planet and give you its name) if you had the attribute but lost it/removed it.

To replicate: get a Gascraft as your flagship. Click on Nenia on the map and click on one of the planets. Then change your flagship to something without gaslining and fly to Nenia. The planet that you selected will be highlighted and trying to land will cause your ship to fly over to the planet and hover above it.

**Comment by Bladewood** [comment] 2017-06-02 11:08
can I mention something else
https://github.com/endless-sky/endless-sky/issues/2487#issuecomment-299711327
k
kbye

**Comment by tehhowch** [comment] 2017-06-03 12:37
Ooh, if you do this and your ship drifts just outside the planet radius and you try to land, you get a segfault...

**Comment by tehhowch** [comment] 2017-06-05 06:14
Should be fixed in #2601

**Comment by tehhowch** [comment] 2017-06-21 08:39
I believe this can be moved to 0.9.7 (done) as the behavior should be irreproducible now, due to #2639 merging.

**Closed** 2017-06-23 20:07 UTC
Labels: bug
