### ISSUE TITLE
[Bug] AI ships repeatedly landing and taking off

### ISSUE THREAD

**Issue by lheckemann** [endless-sky/endless-sky#1290] opened 2016-07-01 17:44 UTC
I don't know exactly what the factors leading up to this situation were, but a merchant ship was disabled by pirates; I repaired it, and then it started repeatedly landing/taking off on the nearest planet.

**Comment by Bladewood** [comment] 2016-07-01 18:06
This seems to happen quite often to ships with the "derelict" tag, as in the `Wanderers: Defend Vara Ke'sok` mission.

**Comment by Amazinite** [comment] 2016-07-01 18:12
I've had it happen to my escorts as well, but I have no idea why it happens.

**Comment by Bladewood** [comment] 2016-07-01 18:18
Are you jumping to an unlinked system while your escorts have only hyperdrives? Because that tends to be the cause when my escorts do it.

**Comment by Amazinite** [comment] 2016-07-01 18:28
No, I've had it occur when I'm in an unlinked system with a landable planet and I try to jump to another system. Even when my escorts have enough fuel, they will sometimes, but not always, just start landing  and taking off over and over again and not getting ready to jump, so I have to leave the system and wait till they snap back to reality and jump out of the system. But I've also had it randomly occur in linked systems. It may be related to #1238, but I always carry both a jump drive and a hyperdrive on my ships.

**Comment by MarcelineVQ** [comment] 2016-07-02 02:15
I noticed this once recently with a disabled enemy world ship. I left the system it was disabled in and when I came back it happened to be over a planet and, while disabled, it tried landing on it repeatedly before it drifted off the planet and ceased trying to land.

**Comment by LocalGod79** [comment] 2016-07-27 14:03
circumstances i've observed this behaviour;
a) npc entered system via hyperspace, was disabled, then assisted.
b) undocked Fighter with fuel pod and no orders. (tried flamethrower fighters)
c) escorts unable to follow flagship by hyper/jump drive.

**Comment by KiLEdEnNis** [comment] 2016-07-27 21:42
I once had a big war fleet (like 50-60 big ships)
one ship kept doing that, but not on a planet, no: an empty part of space
I parked all other ships, still happened, so I had to sell it

**Comment by Alkallid** [comment] 2016-07-28 02:45
@KiLEdEnNis It landed in an empty part of space?

**Comment by KiLEdEnNis** [comment] 2016-07-28 14:38
@Alkallid  yes, same sector but just a random empty part, if I put it on hold position it'd listen but anything else: land on empty void

**Comment by Alkallid** [comment] 2016-07-28 15:56
How? Was it shrinking and enlarging? Or just sitting there?

**Comment by KiLEdEnNis** [comment] 2016-07-28 19:11
it's exactly like if av ship keeps landing and taking off, but then without an object to land on, so "shrinking and enlarging" yes

**Comment by Tadrix** [comment] 2017-02-09 08:00
I too had similar situation. It was an NPC merchant, Hauler II, over a planet in Albaldah system, which after battle was stuck landing and taking off (shrinking and enlarging ad infinitum). Probably LocalGod79's case A.

**Comment by tehhowch** [comment] 2017-07-27 18:27
case c) is solved by #2839

**Comment by Amazinite** [comment] 2019-05-28 15:43
I haven't experienced this bug in some time. Anyone else?

**Comment by Pointedstick** [comment] 2019-05-28 17:52
Me neither.

**Closed** 2019-06-01 20:53 UTC
Labels: bug
