### ISSUE TITLE
Pathing Issue Thru Ember Wastes; lose control of escorts

### ISSUE THREAD

**Issue by Zavindur** [endless-sky/endless-sky#5770] opened 2021-03-04 23:13 UTC
**Describe the bug**
Escorts get "stuck" and don't enter wormhole (even though they have keystone).
They patrol randomly in the system they are in and don't gather or move as commanded.

**To Reproduce**
1. Go to Remnant/Ember waste before all the wormholes are explored.
2. Have like 40 escorts chase after you as you go around.
3. Some will not enter the wormholes and just go awol

**Expected behavior**
Even if ships get 'stuck' on nothing, direct commands should override their behavior.

**Screenshots**
na; see save file; escorts are still broken even after saving/loading game

**System (please complete the following information):**
 - OS: Windows 10 Pro
 - Game Source: download from github
 - Version: build version/time 2021-02-09 07:37 UTC

**Link to save file**
[Money Bags - Copy.txt](https://github.com/endless-sky/endless-sky/files/6087124/Money.Bags.-.Copy.txt)
see attached saved file, broken escorts still broken after loading (ignore error of missing outfit, trivial thing)

**Additional context**
I've had this happen before in another area of the game, just ended up disowning the disobedient escorts.

**Comment by Zavindur** [comment] 2021-03-04 23:18
note, removing 	

"destination system" Antevorta

from the save file for those escorts returns them to normal behavior

**Comment by tehhowch** [comment] 2021-03-05 13:56
Note that as of https://github.com/endless-sky/endless-sky/commit/0d1a226d0ba2c766e21700952e3f66ed03e9232f (a few days ago), relaunching the game should perform that same fix. (The root cause of the routing issue is not yet addressed.)

Closing this since other issues track the bug.

**Closed** 2021-03-05 13:56 UTC
Labels: duplicate
