### ISSUE TITLE
Extending NEIGHBOR_DISTANCE

### ISSUE THREAD

**Issue by kbaegis** [endless-sky/endless-sky#4557] opened 2019-09-28 20:22 UTC
**Is your feature request related to a problem? Please describe.**
I was investigating mechanisms to extend the jump distance when I realized that the system linking mechanism isn't set up to read any attributes or variables to enable this

**Describe the solution you'd like**
A ship attribute that allows you to scale the jump distance for a given ship.

**Describe alternatives you've considered**
Changing the time it takes to make a jump from one system to another

**Comment by Amazinite** [comment] 2019-09-28 20:46
Duplicate of #788.

**Comment by kbaegis** [comment] 2019-09-29 12:15
Yeah, probably a duplicate. I guess I'll consider this #wontfix along with #788.

**Closed** 2019-10-02 13:17 UTC
Labels: duplicate
