### ISSUE TITLE
bad time format string in saved game tooltip

### ISSUE THREAD

**Issue by velartrill** [endless-sky/endless-sky#9971] opened 2024-04-06 17:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

the format string used to generate the tooltip for saved game files doesn't seem to be getting parsed fully. it's producing strings like `%-I:58 AM on %-d Mar 2024`

### Steps to Reproduce

1. open the game load UI
2. hold your cursor over a saved game entry  for a few seconds
3. observe the resulting tooltip

### Expected Behavior

i would assume these tooltips should produce valid date-time strings

### Screenshots

![image](https://github.com/endless-sky/endless-sky/assets/5723574/a0e706da-e607-43a8-b704-ed51f32aa995)

### Operating System

nixos 24.05 uakari, linux 6.8.2, glibc 2.38

### Game Source

Built from source

### Game Version

commit SHA 810a8d5

### Additional Information

built from nixpkgs derivation `nixpkgs.endless-sky` with `src` updated to the most recent commit

**Comment by xX-Dillinger-Xx** [comment] 2024-04-06 22:49
I am seeing something similar but not as bad.
`1:59 AM on d Mar 2024`
Only the `d` is not parsed. I assume it is the day of the month.  

- Windows 10 
- Continuous (2017674)    
- Continuous (24fdfcd) with PR6416  -----  Same as above
- 0.10.4 is displayed correctly

**Comment by ziproot** [comment] 2024-04-07 19:23
I can reproduce it on continuous and not stable. I think 3f890aa4c343b974d120879d7408d77dbb43540a broke it

**Comment by warp-core** [comment] 2024-04-07 20:08
This is a curious issue.
I'm on Windows 10.
When I build locally with clang, I can't reproduce this.
When I build locally with mingw, I can reproduce it.
Though, not quite the same as what @xX-Dillinger-Xx is seeing:
![image](https://github.com/endless-sky/endless-sky/assets/20605679/4739df11-dfda-4d38-9ee3-696680f1c519)
The continuous release build provided by GitHub is also built with mingw, and I see the issue with that as well.

**Comment by warp-core** [comment] 2024-04-16 00:27
Should be fixed by https://github.com/endless-sky/endless-sky/commit/530f52806b42ce579914e1b9924cfa2b3c48a2a8

**Closed** 2024-04-16 00:27 UTC
Labels: bug
