### ISSUE TITLE
[suggestion] Selecting landable place on the map should select it in space as well.

### ISSUE THREAD

**Issue by gendalv** [endless-sky/endless-sky#7254] opened 2022-09-18 05:32 UTC
Currently you have to click the list on the left, then click the tiny dot on the radar on the right. I'm saying you should only have to click the picture.
![123](https://user-images.githubusercontent.com/10047774/190887217-b4f09d4e-a0e7-4003-be8b-1cc8249d2f21.jpg)
Also would be nice to have a right-click->"land here" option on the left list.

**Comment by Amazinite** [comment] 2022-09-18 09:52
Duplicate of #7065.

**Closed by Amazinite** 2022-09-18 09:52 UTC
Labels: duplicate
