### ISSUE TITLE
Cannot fire weapons after switching captured ship to flagship

### ISSUE THREAD

**Issue by McloughlinGuy** [endless-sky/endless-sky#7506] opened 2022-11-02 23:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Its a bug where if you capture a ship and then land on a planet and switch to that ship, you won't be able to use your weapons.

### Steps to Reproduce

1. Accept a bounty mission
2. Capture a ship
3. Land on a planet
4. Switch the newly captured ship to your flagship
5. You will be unable to fire your weapons

### Expected Behavior

You should be able to fire primary and secondary weapons

### Screenshots

https://user-images.githubusercontent.com/70719891/199621680-19d24d48-fd92-47d2-8a08-a07a21571221.mp4

You can see here that the turrets are not rotating to point at the other ship like they should be

https://user-images.githubusercontent.com/70719891/199622280-8898ecd6-bc2b-4518-87a8-92df1ede6546.mp4

Shows how to replicate bug

### Link to save file

Just accept any bounty mission and you should be able to easily destroy and capture it with my falcon. This only works if you try to take off immediately after landing with the captured ship, if you refresh it'll be fine. 

[Caleb Harolds.txt](https://github.com/endless-sky/endless-sky/files/9924820/Caleb.Harolds.txt)

### Operating System

Windows 10

### Game Source

Steam

### Game Version

0.9.16

### Additional Information

If this isn't fixable, or easily fixable, it should probably just be closed since it isn't that much of an issue, its just a slightly weird thing I found that I think should be fixed if it's not too much trouble.

**Comment by warp-core** [comment] 2022-11-02 23:57
This is a duplicate of #7458 and was fixed by 7e14629.

**Comment by RisingLeaf** [comment] 2022-11-03 00:00
Closed because it is a duplicate

**Closed** 2022-11-02 23:59 UTC
Labels: bug, unconfirmed

**Comment by McloughlinGuy** [comment] 2022-11-03 00:08
> This is a duplicate of #7458 and was fixed by [7e14629](https://github.com/endless-sky/endless-sky/commit/7e14629d76419dfa4accf83f15114e44aed396b7).

I looked, I should've looked harder. Glad its fixed though.
