### ISSUE TITLE
Heavily conditionalize jobs by what type of flagship the player has

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#542] opened 2015-12-29 22:33 UTC
If I fly a massive heavy warship brimming with guns, I still get offered routine cargo jobs. If I have a fearsome combat rating but happen to be flying a light transport ship, I still get offered jobs to hunt pirates in Leviathans. I think it would provide some positive differentiation to the game by conditionalizing a lot of these missions on what type of flagship you have; you would only get offered the really good passenger missions if you were flying a transport ship, really good cargo missions with a freighter, and really good escort and bounty hunting missions with a warship.

This could increase replayability and discourage players from building overpowered jack-of-all-trades ships (like the Mule and Bactrian) that can do everything.

**Comment by endless-sky** [comment] 2015-12-30 02:31
Jobs are currently based on how much bunk and cargo space the player's fleet has. So, if you have a large fleet, you get offered huge bulk cargo missions, even if it's a warship fleet. I don't see much reason to not have those jobs available, even if a warship would not usually bother to take them.

**Comment by bobafetthotmail** [comment] 2015-12-30 09:27
the issue here is that overpowered jack-of-all-trades exist (talking mainly about bactrian, but also mule is a bit op)

If you have jack-of-all-trades that are better than specialist ships in the same class... why not use them.

**Comment by wraitii** [comment] 2015-12-30 11:20
The jack-of-all-trades tend to be more expensive but are probably not expensive enough, all things considered.

**Comment by bobafetthotmail** [comment] 2015-12-30 11:51
if you raise price, people will just buy a fleet of different ships instead.

Only way is changing a bit the stats so it's not plain better than everything else of its class.

Like the saying goes, "jack-of-all-trades, master of none".

**Comment by omagasohe** [comment] 2016-01-01 22:52
price really isn't an issue, just means I grind more. I think people don't really understand that you can have over powered stuff and it's okay. Balance just means that that there is options, not better options, but options none the less. It's a game, games should be fun, too much balance makes things not fun.

**Comment by bobafetthotmail** [comment] 2016-01-02 03:54
Balance doesn't mean all ships are re-skins, but that someone made trade-offs to keep the same eyeballed power level for ships of the same class. Slow ship with more shields, fast ship with less shields, that kind of thing.

Having overpowered stuff (or trashy stuff, same thing) means railroading most players to use "teh bettar ships" and ignore the others.
Which is frustrating, you see that there are ships that you would like to use, but you need stuff to get a job done, and function usually takes precedence.

For example, I'd love to use the Syndacate's 6-turret warship for my 2-3 wingmen, but its shields are made of tin foil, and has not enough space to place more shield generators to compensate, so I can't use it.
The syndacate's warship with only frontal guns is in the same boat as it has the same stats.

While if I take a Bactrian.... It has highest engine cap, highest weapon cap, nearly highest outfit cap, second highest shield pool, it is the only ship I can buy with 6 turrets apart from the syndacate one which is unusable, it also has 4 frontal guns like the average warship, it has a lot of cargo that can be converted to outfits so I can shovel in something like 4 Hai shield generators plus cooling with still 300-ish cargo to spare or even more hai shield gens if I go for pure god-mode build, and it even has 3 figher bays (which are useless currently but let's ignore that).
Ah yes, it also has 245 bunks by default, something like 3 times as much as the average warship, twice of a Star Queen, with nerve gas grenades I can use it to cap a Kroath warship with 100% success (with heavy losses) even if it has 900 or so boarding defense.

Now tell me why I should not choose a bactrian for my flagship, or for my 2-3 wingmen.
What other ships aren't utter trash if compared to it.

Nah, balance is yet another thing that must be addressed, sooner or later.

**Comment by Pointedstick** [comment] 2016-01-02 04:44
More good arguments in favor of nerving the Bactrian, which remains much too good for powergamers. I rather agree that the Protector and Vanguard need a little something, too. When I created the Vanguard, I just copied nearly all the stats from the Protector so it shares the Protector's fragility. You should open separate issues for these observations.

**Comment by Nightmareman** [comment] 2016-01-02 06:26
I don't see a problem with the missions as you have a whole fleet and the ship types in the fleet can variate so making the missions conditional on the flagship would be kind of silly.

Now as for the Bactrian personally I am fine with how it is sure it can be a bit op if you turn all the cargo space into outfit space but you can make several other ships similarly op plus the Bactrian is kind of supposed to be awesome its a cityship that was designed to do everything hence why it is so big and costs so much plus its speed is merely average even with all that engine space only ships in my fleet that fall behind it are the cargo ships. Personally I only keep one in my fleet and I use it for when I want to go ship capturing because of its crew space otherwise my main flag ship is a Kestrel much more fun to fly then the Bactrian, well most the other combat ships are more fun to fly then the Bactrian for normal combat or running around exploring.
Also don't forget we are only looking at somewhere between 20% and 30% of the map and all the new races and ships that will come with all the additional content I am willing to bet that more then just a few will probably end up making the Bactrian look weak. The 20%-30% of the map estimate is just based on the current picture of the galaxy if they add some new feature in the future like another map layer where there are other stars to go to in the same area then we would be looking at an even lower percentage of the map.

**Comment by bobafetthotmail** [comment] 2016-01-02 15:22
>"More good arguments in favor of nerving the Bactrian"

Or of tweaking other ships to be more like it. Balance can be reached by going both ways and it's usually better to move towards the funnier end than dropping nerfhammers from the heavens, bactrian is OP but its customizability is a cool feature I would like to see more around.

>"all the new races and ships that will come with all the additional content I am willing to bet that more then just a few will probably end up making the Bactrian look weak"

what part of "I'd love to use the Syndacate's 6-turret warship for my 2-3 wingmen but I can't" (I said this above) would powercreep ("adding new and much better stuff every new version") solve exactly?

Powercreep is a way to obsolete all game content and push the players to grind grind grind or pay pay pay to always have "the next big thing(s)" or be pwned. It's deliberate game unbalancing for profit reasons.

It makes no sense at all in a singleplayer FOSS game.

**Comment by frameworld** [comment] 2016-01-02 16:14
> if you raise price, people will just buy a fleet of different ships instead, not using that ship anymore.
> … Bactrian … highest engine cap, highest weapon cap, nearly highest outfit cap, second highest shield pool, … only ship … with 6 turrets apart …syndacate unusable, it also has 4 frontal guns
> and it even has 3 figher bays … 245 bunks … cap a Kroath warship with 100% success.

I outfit fighters to gain more cargo space for my fleet -or more bunks- with less ships (which have shields independent of each other).
* The downside is that even the smallest power+thruster+steering with no shields is risky if you unleash them accidentally (best is to disable the hotkey).

I only use Bactrian because of it's high individual shield cap compared to mule. 10 Turrets+guns is also good, when you want more manual control over weapon damage (flagship).

And as a flagship when you can't exchange flag-ships mid-flight - independent of incredibly high costs on it (especially crew).

> ship types in the fleet can variate … missions conditional on the flagship would be kind of silly.

I agree partially.

I think missions should require a certain ship-type in your fleet. Any fleet ship being a trader enables more trade missions. BUT the ship type should depend on it's outfits (cargo-space vs weapons or crew, ?not engines?)

––––
It is also ok if ships basically share the same stats (with minor differences). It gives you a choice for your graphic mid-screen and allows cheaper offers when you advance in the story/game.

It also allows access (via multiple factions/species) to the same ship with different reputation matrices.

But it should be marked as "intended to alias that ship" to avoid confusion and balance discussions (I assume an equal weight class)

**Comment by Nightmareman** [comment] 2016-01-02 17:51
@bobafetthotmail I will admit the syndicate ships do need some love especially the Protector and the new Vanguard the Splinter and the Manta could also use a bit of love. The main problem I find when I try to fly them is I just can't get as good of a fit on them as I can with other ships of the same class even when I include alien tech. They function really well for early and mid game but late game they are just meh. Yea I know the syndicate ships can tear through the standard pirate ships no problem just go watch their fleets duke it out syndicate will always win even when it looks like the odds should be in the pirates favor but that is more of an npc vs npc balance issue or how good a ship is stock issue. But for player usage they just aren't as modifiable as many of the other ships in the game. I love how the Syndicate ships look just hate how they function when you try and use them in a high end fleet.

If we went the path of buff all ships a bit that could probably be used to fix the npc vs npc problem because currently pirates almost always get steamrolled by the other npcs which seems kind of odd you would think the pirates would be more deadly and scary but right now they usually lose at least give them a wider and better selection of ships.

**Comment by endless-sky** [comment] 2016-01-07 03:55
I've added back in the ability for missions to check what categories of ships the player has (in addition to the existing functions for checking cargo size or passenger space).

**Closed by endless-sky** 2016-01-07 03:55 UTC
Labels: enhancement
