### ISSUE TITLE
Faction descriptions repeated twice

### ISSUE THREAD

**Issue by bheimbaugh** [endless-sky/endless-sky#5107] opened 2020-05-26 00:42 UTC
**Describe the bug**
The `Factions` tab of the player logbook for the _Drak_, _Free Worlds_, _Hai_ and _Quarg_ factions repeats the same description paragraph twice for each one. _See screenshot._

**To Reproduce**
1. Press `i` to open _Player Info_ screen
2. Click `Logbook...` button to display logbook screen
3. Click `Factions` tab to view faction descriptions
4. Scroll to view the _Drak_, _Free Worlds_, _Hai_ and _Quarg_ faction descriptions
Obviously these factions will not be listed if they have not been encountered yet in the game. I don't know if I had to do anything else to cause this, I just happened to notice in the middle of a game.

**Expected behavior**
Faction descriptions should not be repeated.

**Screenshots**
![faction descriptions](https://user-images.githubusercontent.com/39772599/82849409-752b4900-9ebd-11ea-88b7-24a197d45636.png)

**System (please complete the following information):**
 - OS: Windows 10 Pro, version 1903 build 18362.836
 - Game Source: Steam
 - Version: 0.9.12

**Link to save file**
[Pyren Frood.txt](https://github.com/endless-sky/endless-sky/files/4679325/Pyren.Frood.txt)

**Additional context**
I've (obviously) edited the ships in my save game, but that's the only part of the file I've touched and no other files. So I don't know how that could have caused this, unless having a jump drive and visiting other factions too early in the story could have caused this? In any case, if no one else sees this in their game, then I must've caused it myself.

**Comment by Amazinite** [comment] 2020-05-26 01:17
Duplicate of #3746.

**Comment by bheimbaugh** [comment] 2020-05-26 02:14
Are you sure it's a duplicate of #3746 ? It's similar, and may be fixed by #5082, but the descriptions don't mention Factions. I don't recall ever quitting in the middle of a conversation.

**Comment by Amazinite** [comment] 2020-05-26 02:58
> but the descriptions don't mention Factions

"Factions" are just a type of log book.

**Closed** 2020-07-16 14:00 UTC
Labels: duplicate
