### ISSUE TITLE
Buy outfits from outfitters on other planets

### ISSUE THREAD

**Issue by jostephd** [endless-sky/endless-sky#3921] opened 2018-09-03 21:37 UTC
[I'd like to be able to buy an outfit from an outfitter that isn't on the planet I happen to have landed on](https://github.com/endless-sky/endless-sky/issues/3864#issuecomment-408665652). There is no fun in hauling a new ship to Wanderer, Remnant, and Coalition space to buy a ramscoop, an anti-missile, and a shield generator... and then to find that you ran out of outfit space, or cooling, or whatever else and need to start over.

> > How does one determine what is available or not?

> Anything that's offered on any outfitter that appears in the player's map, is on a planet the player can land on, and is on a planet whose government is not at war with the government of the planet the player is on. For example, you shouldn't be able to order outfits from pirate worlds to Earth (not above board, anyway).

edit: **Summary**: This idea isn't very popular, but several other ideas are being discussed below, such as [ordering deliveries](https://github.com/endless-sky/endless-sky/issues/3921#issuecomment-418357112) and a [mock outfitter](https://github.com/endless-sky/endless-sky/issues/3921#issuecomment-419079519). (Apologies if I missed others)

**Comment by Bladewood** [comment] 2018-09-03 23:13
Is there a particular difference between this and straight-up removing the outfitter system entirely?

**Comment by Pointedstick** [comment] 2018-09-03 23:58
This is a big part of the fun of the game. If everything (that you've discovered) becomes available anywhere, that would remove a big reason to actually fly around the galaxy.

**Comment by Brick63** [comment] 2018-09-04 12:28
my question is this, how would you order something from the factions that most people, humans and others, don't know about, not to mention the fact that not many people have Jump Drives.

**Comment by kikotheexile** [comment] 2018-09-04 12:37
There are plugins for exactly this form of play, however it makes absolutely zero sense in the context of the story or regular gameplay mechanics to have this be a thing in the vanilla, out of the box game. 

If you are knowledgeable enough to know where to buy all of these outfits, you have likely beaten the main plot, which means you can safely install a plugin without having to worry about being completely overwhelmed by the sheer amound of information which will appear on the outfitter/shipyard screens.

**Comment by TheMarksman-ES** [comment] 2018-09-04 12:58
In game, we have opposing factions that fight each other. One such example is the Wanderers and the Unfretted. Both are on bad terms with each other. So I doubt for lore sake that you'd be allowed to order your goods through eBay.

And anyways, 99% of the galaxy don't own a Jump Drive, so you cant order through eBay anyways in alien space.

**Comment by Zitchas** [comment] 2018-09-04 12:58
I would assume that this would be subject to several limits. The following come to mind:

Only the outfits that meet the following criteria would be available:
a) The outfits normally available on said planet
b) Or all of the following:
   1) Is available in an outfitter the player has found
   2) Is available in an outfitter on a planet the player can land at (not restricted or hostile)
   3) Is available in an outfitter that has an unbroken regular hyperlink path between it and the current planet
   4) There are no hostile government systems along the most direct route between the closest planet and the current one.

In practice, this would basically mean that each government-region would have one outfitter with no difference between good outfitters and backwaters, and for much of the game entire geographic regions would all have the exact same outfitter.

**Comment by TheMarksman-ES** [comment] 2018-09-04 13:03
Another point to note is that on a lore standpoint, the Navy or Syndicate would have pulled a USA and seize any technology being shipped through their space.

**Comment by Zitchas** [comment] 2018-09-04 13:08
Going a different direction, it would be interesting to add new fleet mechanics to things. For instance, instead of just having direct access like this, what if the player had a way to station a ship on a planet with a good outfitter (have a "station" button alongside the "park"). Said ship would have to be paid full crew price despite being on planet, but the benefit is that the player has access to that outfitter so long as they are on a planet that has a direct route between it and the one the stationed ship is on (that it can travel safely).

It'd still cost a lot to do, and I'm not sure it'd be a great addition to the game, but giving the player the ability to use their fleet to setup shipping like that would be interesting, at least.

**Comment by Tadrix** [comment] 2018-09-04 14:40
The idea in it's proposed state isn't very good. And it's doubtful anything would be changed. But, as a thought experiment, let me propose a toned down version:

1. You can order only from outfitters you have discovered (and the planet you are ordering on needs to have an outfitter obviously);
2. You can order only from friendly planets that are in systems with unbroken hyperlinks (wormholes *don't* count) to your destination;
3. The order arrives after *N* days (*N* = `[number of jumps in the shortest path + 1]`);
4. Upon ordering, the player incurs additional costs: *N* * `[total tons of outfits ordered]` * 50.

This would be reasonable enough, but think if it's worth implementing.

**Comment by Amazinite** [comment] 2018-09-04 15:58
>Maybe buying from an off-planet outfitter... the order would take longer to fulfill

>The order arrives after N days (N =[number of jumps in the shortest path]+ 1);

How would these work exactly, though? I'm not on board with this idea to begin with, but I can't even begin to understand how having a delayed arrival time would work.  Will the player need to launch and fly around for the delivery to be fulfilled? If the arrival time is based off of days in game, why not just travel to where you need to go?

**Comment by Brick63** [comment] 2018-09-04 16:04
not to mention that if it only works for places of the same race or government then it changes nothing but just makes you pay more overall.

**Comment by TheMarksman-ES** [comment] 2018-09-04 16:16
"Will the player need to launch and fly around for the delivery to be fulfilled? If the arrival time is based off of days in game, why not just travel to where you need to go?"

Quite agree with this, time pauses when you're on a planet, and with a jump drive and knowledge of where everything is at, it takes less than five minutes to get anywhere. Ten minutes if you use a hyperdrive.

**Comment by TheMarksman-ES** [comment] 2018-09-04 16:18
And anyways, why do you have to outfit at a faction's outfitter? Just buy all the outfits as cargo and go to the shipyard you need to go to!

**Comment by Tadrix** [comment] 2018-09-04 21:26
> I'm not on board with this idea to begin with, but I can't even begin to understand how having a delayed arrival time would work. Will the player need to launch and fly around for the delivery to be fulfilled? If the arrival time is based off of days in game, why not just travel to where you need to go?

I'm not as well, but, as I mentioned, it's a thought experiment. Implementing it doesn't seem to be worth it.

As for the points you raised: The player indeed will need to fly around and then return. This feature has limited utility. But it has some: First, you could attend to business elsewhere and then return to receive ordered stuff. Second, travelling there to buy it and return takes twice the time it would take if somebody just brought it to you. If you have absolutely nothing to do there, you might use this option.

Or, for example, if you can order delivery to some other place, you could be in the Syndicate territory running errands, order some stuff from the Deep to Prime, Betelgeuse, and go there (if you, say, plan on heading further north afterwards), w/o the need to go to the Deep.

One thing @endless-sky mentioned once is, he dislikes the need for excessive flying all over the galaxy to gather necessary stuff himself, maybe it could be alleviated just a bit by this mechanic. I'd liken it to ordering caravans with units in Heroes V.

**Comment by kikotheexile** [comment] 2018-09-05 04:48
delayed arrival which takes longer than the amount of time it would take via the shortest path makes me lol, because then at that point you could just take the shortest path to the outfitter in question and have it sooner. 

Anyway, this is just... a not very well thought out idea. (No offense.)

If you have the most fun by playing with outfits, go back to my initial response and get the plugin.  

https://github.com/endless-sky/all-content-plugin

**Comment by jostephd** [comment] 2018-09-06 12:45
@kikotheexile None taken. I'm glad to see the discussion.

@TheMarksman-ES When I outfit a 700T ship I don't know in advance which set of outfits I'd use, and the choices are interdependent. (Wanderer generators or Korath generators with Hai batteries? Big battery or two smaller ones?) If I had to buy everything in advance I'd have to lug 1400T of gear around just to be sure I had the right permutation in there. That's kinda doable once you have enough cargo ships but it reduces the game to a supply chain management game.

**New idea 1**: Add a way to _predict_ the ship's stats (velocity, acceleration, power, heat) if it had a given set of outfits, _even when there isn't any outfitter on the current planet_. If I've discovered the Sunbeam outfit, there should be a "mock outfitter" that lets me play with configurations that involve Sunbeams, so I know if buying or plundering a Sunbeam is worthwhile. This would go well with the new checkboxes in the Outfitter: [Show outfits in cargo] [Show outfits for sale] [Show outfits for sale elsewhere] [Show enemy outfits]. The last mode would show any outfit type that was plundered at least once, even if the player doesn't have any copies of that outfit installed or in cargo currently.

**New idea 2**: Let the player send an escort to buy the outfit and return. The escort would be paid normal crew salaries and could be equipped with a jump drive if you have a spare one. Basically, instead of ordering a rush delivery from an outfitter or parking a ship+crew at it in advance, you task an escort to go there, do the transaction, and return. This also limits you to the cargo space of the escort; three Sparrows can't buy a Sunbeam, it's too large.

I don't think it should be possible to order stuff from outfitters you haven't discovered yet.

OT: Maybe if you go to a spaceport in Sol before you visited Syndicate space you should have some interaction with Syndicate captains? "Here's a 15% voucher for a Proton Gun [_marks Hephaestus on the map_]", "Would you like to do a cargo run for my boss on Millrace".

**Comment by Zitchas** [comment] 2018-09-06 12:51
As a complete side note, I really like that side idea you mention there about running into a Syndicate captain giving the player a discount coupon for something in Syndicate space. Seems like something they'd do. I'm not sure how well that could be implemented, though.

**Comment by kikotheexile** [comment] 2018-09-08 06:28
On that side note:
```
	on complete
		outfit "<outfit>" 1
		payment -<credits>
```

So it could be doable. Go to location within a set timeframe, when you do, the job gives you the outfit in question and subtracts the credits listed.

**Comment by jafdy** [comment] 2018-09-08 09:05
If you don't have the required credits then you don't get charged.

**Comment by jostephd** [comment] 2018-09-08 15:00
Let's discuss that on https://github.com/endless-sky/endless-sky/issues/3928 and keep this issue for ideas about outfitters. I edited the first post to try and give an idea of some of the additional ideas that have been discussed.

**Comment by Thk54** [comment] 2018-09-11 20:27
what about buying storage space on a planet where you can dump outfits (and normal cargo if you wanted to) to create a stock of them, thus you still go around buying and transporting all the outfits, but you are not limited by how much cargo/outfit space is on your ships once you drop them off.
This could also be nice in that it can reduce the clutter of storage ships in the ship list on the player info menu

**Comment by Bladewood** [comment] 2018-09-11 20:56
@Thk54 I don't see what that has to do with this issue, but in any case, that suggestion is a duplicate of https://github.com/endless-sky/endless-sky/issues/724 and several others. See also https://github.com/endless-sky/endless-sky/issues/3874#issuecomment-410398305.

**Comment by Jorlem** [comment] 2018-10-14 16:29
Lore-wise, this could be a neat way to "post" missions, as a sort of flip side to the game asking you, on planet A, to pick up cargo on planet B and deliver it to planet C.  Just being able to boss NPCs around like that could add a bit of fun to the game, even if it isn't the most optimal way of doing things. Or, if you are persona non grata in certain areas of space due to storyline stuff or whatever, you could use this to hire NPCs to bring you outfits or rare resources from places you can't easily go.

(It could also add another way to affect credit ratings and system/polity trust, if you actually pay the NPC you hired, or you chose to ambush them and try to steal the cargo you ordered.)

**Comment by Amazinite** [comment] 2018-11-20 17:15
Yeah, it seems like whatever system is added would either be too complicated or would water down the outfitting process to the point where outfitters might as well be region based instead of planet based.

**Comment by Pointedstick** [comment] 2018-11-20 17:18
Agreed.

**Closed by Pointedstick** 2018-11-20 17:18 UTC
Labels: enhancement

**Comment by jchamlin** [comment] 2020-08-04 21:32
I think at least creating my own home base (or multiple bases), with a shipyard and outfitter that only stocks what I brought there. I can sell it ships (and the ship and all the outfits go into inventory). Everything you buy or sell at the shipyard or at the outfitter buys and sells for free, and comes from the available stock of whatever you've brought there. The value of everything you've stored there is included in your net worth. That way, you can get ships you want to save, but not clutter up your ship info screen out of the way, and you have a place to store ammo and outfits that you would otherwise need to sell, or haul around with you and take up your cargo space.
