### ISSUE TITLE
Freezing then crashing on maximizing window?

### ISSUE THREAD

**Issue by BuildBruh** [endless-sky/endless-sky#1568] opened 2016-09-14 05:10 UTC
Hey I'm dumb and hit enter before typing the desc. 

I can expand the window manually, but whenever I use the snap feature or maximize it through taskbar it proceeds to crash. Using steam beta version 9.3

Edits: Only crashes when maximizing it through any sort of "shortcut". I can expand it in any way/size and it'll run just fine. Version 9.2 works fine. High-DPI addon is not a problem. AFAIK steam overlay is not effecting it. ingame fullscreen option works fine.

Don't have time to build & test tonight, sorry.

**Comment by Waladil** [comment] 2016-09-14 05:15
My brother (who does not have a GitHub account) reports the same issue.

**Comment by Amazinite** [comment] 2016-09-14 10:54
There's a few reports of this on Steam as well. I'm not sure what OS you guys are on, but the Steamies are reporting being on Windows, all version.

**Comment by Bladewood** [comment] 2016-09-14 12:02
Have been experiencing this with post-0.9.2 builds, never reported because I thought it was just because of my poor compiling skills.

**Comment by endless-sky** [comment] 2016-09-14 12:29
Must be a result of commit 53d0341. I guess maximizing causes the window to have an odd width or height, and trying to force the width or height to be even crashes it?

**Comment by KiLEdEnNis** [comment] 2016-09-14 13:16
I have a 1920x1080 monitor, Windows 10, Steam user

![full window bug](https://cloud.githubusercontent.com/assets/10348657/18513489/01578fa4-7a8e-11e6-9d9a-10a5864c54d0.jpg)

what happens exactly; maximizing the game "freezes" it, it can't even be closed, once you un-maximize it it behaves correctly (if you tried to close it, it does after you un-maximize it)
haven't seen it crash though

**Comment by BuildBruh** [comment] 2016-09-14 22:29
Odd. I cannot un-maximize it. It simply stops responding and window won't resize. after about 20-30 seconds it crashes.

**Comment by KiLEdEnNis** [comment] 2016-09-15 13:06
I have Windows 10, you? may be a cause for that, but it's a bug either way

**Comment by BuildBruh** [comment] 2016-09-15 19:05
Win 7 ultimate

**Comment by endless-sky** [comment] 2016-09-16 01:01
Check if 48ee6ee fixes this for you. I think the issue is that it's getting in an endless loop of trying to resize the window to have even dimensions, but the window not being resized because it is maximized.

**Comment by Amazinite** [comment] 2016-09-16 01:05
Maximizing is working properly now.

**Comment by Bladewood** [comment] 2016-09-16 11:41
Works on Windows 10.

**Comment by endless-sky** [comment] 2016-12-24 01:40
This is partially fixed in 0.9.4, and the full fix will be in 0.9.5.

**Comment by endless-sky** [comment] 2017-01-18 23:41
Closing this because 0.9.5 is released now.

**Closed by endless-sky** 2017-01-18 23:41 UTC
Labels: bug
