### ISSUE TITLE
[0.9.6] Crash on drag selecting

### ISSUE THREAD

**Issue by 0mothership0** [endless-sky/endless-sky#2236] opened 2017-03-08 12:16 UTC
When using this image as a ship sprite (or whatever sprite whose collision mask doesn't cover the center of the image), the game crashes when I try to select it with my mouse. Keyboard selecting works fine though.
I connected the 5 parts of the sprite and problem solved, but this could still be a minor bug :(
![image](https://cloud.githubusercontent.com/assets/5153166/23703402/bfa96384-043a-11e7-8440-93e86d71e75d.png)

**Comment by Amazinite** [comment] 2017-03-08 12:18
[Mechanics]
Ships needs to be one piece or the collision masking doesn't work, leading to a crash.

**Comment by 0mothership0** [comment] 2017-03-08 12:23
@Amazinite Not quite sure, but this sprite with only one piece also lead to a crash, as long as it's not centered.
![image](https://cloud.githubusercontent.com/assets/5153166/23703844/e9a0b974-043c-11e7-93cc-f88930d321ab.png)

**Comment by KiLEdEnNis** [comment] 2017-03-08 15:38
just an idea, but... then center it?

**Comment by 0mothership0** [comment] 2017-03-08 19:11
Thinking about that I actually have an idea now. We really can make the masking system search from the center of the image so that we can decide which part of the ship should be considered as "main hull" by simply center this part. But with the present algorithm it searches from the up left corner and makes it harder to make ships with multiple parts (like the first sprite I posted)

**Comment by Wrzlprnft** [comment] 2017-03-08 19:17
isn't the center of the 512 also empty?

**Comment by KiLEdEnNis** [comment] 2017-03-08 20:03
yes it is, but maybe it's because that 1 surrounds the center so the center becomes a part of the ship (shoot the empty area: you damage the ship as well)
why would you make a ship have different separated parts anyway? if you insist draw a thin black line between the parts, best option ya have

**Comment by LocalGod79** [comment] 2017-03-11 07:01
https://github.com/endless-sky/endless-sky/wiki/CollisionDetection

**Comment by endless-sky** [comment] 2017-03-23 01:23
This is (mostly) fixed by commits 5ba3db4 and 16251ea. Of course, the AI assumes that a ships center of mass is the center of the sprite, so if you use an off-center image like that there will still be a problem that weapons tend to miss it.

**Comment by endless-sky** [comment] 2017-03-23 02:17
Also note that the fact that collision masks have to be a single connected object is by design - it makes the collision detection code a lot simpler. It could be changed, but only if there were a really good reason to do so.

**Closed** 2017-07-21 20:59 UTC
Labels: bug
