### ISSUE TITLE
Remnant Key Stone vs Hai Keystone?

### ISSUE THREAD

**Issue by TammyJess** [endless-sky/endless-sky#4673] opened 2019-11-14 02:03 UTC
Remnant missions are using "Key Stone" while Hai and Deep missions are using "Keystone".

I'm not sure that these are supposed to be different outfits, it seems odd to be able to install both.

Reading the Remnant mission txt leads me to think that maybe they are different, but I'm confused so maybe others might be too.

Perhaps either make the spelling the same so there's only one outfit, or make one a "Hai Quantum Keystone" and the other a "Remnant Quantum Keystone"?

A grep of the the mission text files gives me the impression that changing the Remnant .txt files would be the fastest fix:
remnant missions.txt:319: `mission "Remnant: Key Stones"`
remnant missions.txt:328: `[..] Key Stone that looks different [..]"`
remnant missions.txt:338: `[..] Key Stones are just good luck charms. [..]`
remnant missions.txt:357: `[..] Quantum Keystones" to sell to him. [..] Key Stones sell for here[..]`
remnant missions.txt:567: `has "Remnant: Key Stones: done"`
remnant outfits.txt:335: `outfit "Quantum Key Stone"`
remnant ships.txt:56: `"Quantum Key Stone"`
remnant ships.txt:95: `"Quantum Key Stone"`
remnant ships.txt:210: `"Quantum Key Stone"`
remnant ships.txt:266: `"Quantum Key Stone"`
remnant ships.txt:393: `"Quantum Key Stone"`
remnant ships.txt:460: `"Quantum Key Stone"`
remnant ships.txt:507: `"Quantum Key Stone"`
remnant ships.txt:549: `"Quantum Key Stone"`
remnant.txt:225: `"Quantum Key Stone"`

**Comment by Amazinite** [comment] 2019-11-14 02:07
Duplicate of #2620, #2922. 
There are two different outfits because the Hai and Remnant value them differently. The Hai consider them to be cheap, which the Remnant value them highly enough to put a license on them (although currently said license has been removed to avoid becoming stuck in Remnant space, see: #4491, #4531).

**Comment by TammyJess** [comment] 2019-11-14 02:20
Cool, thank you so much for the clarification.  I did search for the issue, but newbies make newbie mistakes!  :)

I've read your source, and it's now clear.  Should/can I delete or mark this issue I opened "closed"?
I like tehhowch's commentary and naming solution too, "Decorative Keystone" would have stopped me opening my issue!

**Closed** 2019-11-14 18:29 UTC
Labels: duplicate
