### ISSUE TITLE
Impossible Remnant mission: Research Expedition to Deep Space 1Q

### ISSUE THREAD

**Issue by residuum** [endless-sky/endless-sky#8543] opened 2023-03-13 23:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

With version 0.10.0 from the downloads I have gotten the impossible mission to research Deep Space 1Q.

I am using the x86_64.AppImage download from https://github.com/endless-sky/endless-sky/releases/tag/v0.10.0

Excerpt from the save:

    mission "Remnant: Expanded Horizons Astral job"
    	name "Research Expedition to Deep Space 1Q"
    	uuid 1b75cc37-e92f-465d-aa68-7d507731850b
    	description "Travel to Deep Space 1Q with a Research Laboratory to collect data, then return to Viminal in the Arculus system."
    	job
    	repeat 0
    	to offer
    		"Remnant: Expanded Horizons Astral 2: done" != 0
    		random < 50
    	destination Viminal
    	waypoint "Deep Space 1Q"
    	on complete
    		dialog
    			"When you land, a researcher quickly retrieves the data crystals with the information about the surveyed system and hands you the logistics allotment of 500,000 credits."
    		payment 500000
    		"reputation: Remnant" += 1
    	on offer
    		require "Research Laboratory" 1
    	on waypoint
    		dialog
    			"Your scientist unpacks the laboratory and takes the requested observations. A short while later, they have the data compiled on a set of data crystals and inform you that everything is ready for departure."

### Steps to Reproduce

1. Go to 'Viminal'
2. Have a 'Research Laboratory' installed
3. Click on 'Job Board'
4. Scroll down to 'Take the job'
5. See error

### Expected Behavior

Only offer possible jobs

### Operating System

Debian testing

### Game Source

GitHub Releases

### Game Version

v0.10.0

**Comment by warp-core** [comment] 2023-03-14 00:00
This is essentially a duplicate of #7702.

**Closed by warp-core** 2023-03-14 00:00 UTC
Labels: bug, unconfirmed
