### ISSUE TITLE
Cargo full, Bunks full and accepting a space port pop up mission

### ISSUE THREAD

**Issue by Wrzlprnft** [endless-sky/endless-sky#208] opened 2015-11-15 15:19 UTC
![2015-11-15_00001](https://cloud.githubusercontent.com/assets/15857993/11169313/4a6e3694-8bb4-11e5-999a-48506279b3af.jpg)
Accepted a mission, loaded he rest with other stuff to trade, started, out of fuel, landed, accidentally opened the spaceport, got a random mission, curios what would happen, accepted, -2 free cargo

**Comment by endless-sky** [comment] 2015-11-16 00:01
This is by design - I didn't want special missions to be blocked just because you have ordinary cargo taking up all your space. The extra cargo should automatically get sold when you leave the planet - you'll see a message like, "You sold 2 tons of excess cargo..."

**Comment by Wrzlprnft** [comment] 2015-11-16 11:32
Indeed.
Sorry, didn't touch the game or the savefile in case you would need the data.



What if you have several different kinds of cargo, which one will be sold?
And if you only have mission cargo?

Maybe you should add a window where it shows something like "As you return back to the ship, you realise, there is not even enough space to carry all the cargo... Seems you have to sell something"
+Drop Down list of cargo which you could sell/missions you might have to abort and sell part of the mission cargo

**Comment by Wrzlprnft** [comment] 2015-11-17 12:46
ok, that was a pretty demanding comment.
i am going to try to code my suggestion, or at least specify the content

**Comment by Phezzan** [comment] 2015-11-22 07:26
I haven't been bothered by the cargo... but when taking passenger missions it immediately forces me to fire crew...

I can (without leaving the planet) go right back and hire them.
The crew do not get fired when I leave the planet.  I believe this is a 0.8.5 but having to do with how mission bunks are distributed / used in a fleet.  I just merged upstream so if it's already fixed, know that you are awesome.

**Comment by Wrzlprnft** [comment] 2015-11-23 16:04
after a while i realized how unneccessary a extra windwo would be for the game running.
I would just recommend to make a little message appear when you want to depart:
"As you approach your ship, you are confronted with a bunch of angry spaceport-workers, one of them asks you:
"Are you the Captain of this ship? You are lucky that your computer does the maths when you use hyperdrive"
Following you confused look to some cargo crates next to you ship, he yells: "There is not enough space in you little nutshell!"
More polite he wants to know if you plan on selling something yourself, or if he shall do it."
choice:
Go Back
Depart
"

**Closed** 2015-12-14 11:09 UTC
Labels: mechanics
