### ISSUE TITLE
Automations cannot escort players.

### ISSUE THREAD

**Issue by Gkramme** [endless-sky/endless-sky#1004] opened 2016-04-28 01:11 UTC
Ditto^

**Comment by endless-sky** [comment] 2016-04-28 01:26
Are you playing with the latest code (built from source)? They work fine for me.

Or, if you're talking about automata being used as flagships, that's supported only if you add a command center so a human being can control them.

**Comment by endless-sky** [comment] 2016-04-28 03:35
Here's a player fleet with several automata. One has been made human-pilotable by adding a command center and a bunk room:

![automata](https://cloud.githubusercontent.com/assets/11450262/14874667/a38020ec-0cd0-11e6-8b50-039794d97534.png)

**Comment by Gkramme** [comment] 2016-04-28 13:52
As in escort missions. Refer to the quarg boarding mission pr.

**Comment by endless-sky** [comment] 2016-05-12 02:29
Based on the PR, I think what you really mean is that ships with the "Drone" or "Fighter" category can't follow the player from system to system, but that's by design - those categories are reserved for ships that are carried inside larger ships. And, ships with the "automaton" attribute that don't use one of those categories work just fine. So, I'm closing this.

**Closed by endless-sky** 2016-05-12 02:29 UTC
Labels: unconfirmed
