### ISSUE TITLE
[Question] buy a ship without outfits

### ISSUE THREAD

**Issue by daggs1** [endless-sky/endless-sky#6800] opened 2022-05-06 22:03 UTC
### Problem Description

I was wondering if there is a way to buy a ship without any outfits?

### Related Issue Links

this site: https://endless-sky.fandom.com/wiki/Human_Ships shows hull price

### Desired Solution

when in shipyard, I can select between skeleton and fully equipped

### Alternative Approaches

build fully equipped ship and sell all outfits at value cost

**Comment by quyykk** [comment] 2022-05-06 22:10
Duplicate of #6693 I believe.

**Comment by daggs1** [comment] 2022-05-07 08:50
I guess that answers my question, thanks

**Closed** 2022-05-07 09:13 UTC
Labels: duplicate, enhancement
