### ISSUE TITLE
Worse Penalty For Not Paying Mortgage

### ISSUE THREAD

**Issue by McloughlinGuy** [endless-sky/endless-sky#5842] opened 2021-04-17 00:15 UTC
**Is your feature request related to a problem? Please describe.**
I think that we need a harsher penalty for not paying your mortgage. I mean, your credit score going down isn't really the worst thing in the world

**Related Issue Links**
 #4839 is similar

**Describe the solution you'd like**
There are a number of things to do here. The most obvious one is to make the navy or other government hostile toward you. The best way to implement this is to have missing payments damage your reputation. Once your reputation is low enough, a message will appear informing you that you are now considered a criminal and will be destroyed.

**Describe alternatives you've considered**
How about sending a bounty hunter after you? That would be interesting. I also considered having your ship be repossessed as a suggestion, but I don't quite know how that would work.

**Additional context**
I think something like this would be an interesting feature to add in, to add a bit more depth to the game.

**Comment by Terin** [comment] 2021-04-17 01:20
Duplicate of #3469. And I don't think much has changed: You can't choose to not pay a mortgage, and missing a payment causes your principal and daily payments to go up, making it harder and harder to actually hold onto any savings and buy new ships/outfits. Like Derpy said in that issue, not being able to buy anything is punishment enough. The bank will get their payment eventually.

**Closed** 2021-04-17 10:35 UTC
