### ISSUE TITLE
Reverse thruster vs orientation

### ISSUE THREAD

**Issue by wkoot** [endless-sky/endless-sky#353] opened 2015-12-02 19:42 UTC
Reverse thrusters don't actually thrust reversely. If the orientation of your ship changes but you haven't fired forward thrust, reverse thrust is acting on the opposite of the old direction.
The easiest way to reproduce the behaviour is to forward thrust, turn and then hold reverse thrust until you're no longer slowing down but still moving.
It would also be nice to automatically orient the ship in the direction of its velocity (i.e. the opposite of what reverse does without reverse thrusters) when firing reverse thrust, but I guess that's a bit unhandy when also turning.

**Comment by endless-sky** [comment] 2015-12-03 02:14
The thruster actually *is* thrusting in the opposite direction that your ship is pointing. The issue is that drag, which is applied whenever your ship thrusts, is pushing it in the opposite direction it is heading in. For a large ship, drag will be a larger effect than the small amount of thrust that the reverse thruster applies.

I'm not sure there's a way to change that without changing how drag is calculated and applied.

**Comment by wkoot** [comment] 2015-12-03 08:14
Darn. So the fact that the reverse thrusters don't cancel out the movement, even if you turn in the drag-direction, means that according to (that point in) mechanics the ship is actually at rest?

**Comment by endless-sky** [comment] 2015-12-03 14:18
I'm confused about what you're asking. If you reverse thrust in the direction your ship is traveling in, it will indeed "cancel out the movement."

Note that ordinary thrusters work the same way with regard to drag: if you accelerate to full speed upwards, then turn to face the right and begin accelerating, your upward speed will drop as your speed towards the right increases. If it were not done that way, it would be possible to get moving at faster than the maximum speed just by thrusting in two different directions.

**Comment by dplepage** [comment] 2015-12-03 14:56
The reverse thruster behavior is really confusing - it exerts a small backwards force on your ship, but also turns on this mystical "drag" force that otherwise doesn't apply. The net effect is that it slows you down no matter which way your ship is facing. In particular, if you fly up as fast as you can, then turn to face down and turn on your reverse thrusters, you'll slow down dramatically. This makes no sense at all - you're turning on thrusters that should, if anything, make you go *faster*, but instead they're slowing you down.

Maybe rather than using a drag model for this, ships should just have their velocity clamped to their maximum speed? You'd still get the behavior that if you accelerate to the right your upwards speed will drop, but you'd no longer have the problem where activating a tiny engine in the direction you're already moving would slow you down.

**Comment by wkoot** [comment] 2015-12-03 19:42
My initial description was indeed wrong, I just verified that turning while reverse thrusting does make it possible to grind to a total halt (afterwards it'll continue to thrust reversely). It took so long that I didn't notice earlier.

To get a better feeling for movement, I still think it would be nice having the ship turn in the direction of its velocity when reverse thrusting (i.e. the opposite of what reverse does without reverse thrusters). Only quirk is how to deal with turning *and* reverse thrusting, turning should take precedence but movement control would become messy. :(

**Comment by dplepage** [comment] 2015-12-03 21:33
Having drag that only applies while you're accelerating is confusing in general - e.g., the behavior of a missile with drag 1 and acceleration 0 is *extremely* different from the behavior of a missile with drag 1 and acceleration 0.0000001.

The concept of "drag" doesn't make a lot of sense in space - there's not much to drag you. I'd lobby for setting all drag coefficients to 0 and instead just doing something like
```c++
if (velocity.Length() > MaxVelocity()) velocity *= MaxVelocity()/velocity.Length();
```

Or, if you still want to support moving faster than your max when e.g. a ship is accelerated by a giant explosion or a bunch of Koreth ships, you could apply drag only when velocity exceeds the MaxVelocity.

That way, trying to speed yourself up with reverse thrusters wouldn't slow you down.

**Comment by endless-sky** [comment] 2015-12-03 21:56
The trouble is, MaxVelocity() depends on which engine you are using. Your
max velocity when using a tiny reverse thruster will be much lower than
when using your big engines, and that in turn will be slower than big
engines plus afterburner. So, there needs to be a way to smoothly
transition between different maximum velocities depending on which engine
you are using. (It would look completely wrong if a ship immediately
started moving slower the moment it switched its afterburner off.)

The drag method also means that as you accelerate to top speed, your
acceleration gradually reduces rather than suddenly changing to zero. And,
it has the added advantage of making it slightly easier to bring your ship
to a stop than it would be otherwise.

The reason a missile's behavior changes when you change the acceleration
from 0 to 0.0001 has nothing to do with the drag equation - it's just
because an acceleration of 0 signifies to the program that the missile
should fly at constant speed.

**Comment by endless-sky** [comment] 2015-12-04 02:34
Are you able to build the code from source? I've checked in a change (bc6ed15) that checks to see if your ship's acceleration after applying drag would be in the opposite direction that you are accelerating, and if so it applies no acceleration instead of slowing you down.

**Comment by dplepage** [comment] 2015-12-04 14:47
@endless-sky bc6ed15 makes the behavior of reverse thrusters feel more natural, but messes with some other scenarios. For example, now there's no need to keep firing your afterburner once you've reached top afterburner speed - when you stop firing it, you'll keep the speed from it.

I think that limiting drag to only apply when velocity > MaxVelocity makes the most physical sense, in that there isn't actually any drag in space, so this really is just a magic force that we apply to enforce a cosmic "speed limit". Since it's a fake force, we should use it only when it's necessary to do so.

Also, I'm aware that changing the acceleration doesn't affect the drag equation itself, it's just that in general it seems weird to me that anything would only experience drag when it was accelerating itself, and not when other things were accelerating it or when it was just going abnormally fast already.

**Comment by endless-sky** [comment] 2015-12-04 15:26
It's always been true that after you stop firing the afterburner, you keep the speed from it, until you try to accelerate in a different direction, at which point you slowly lose that speed.

Feel free to play around with alternative top speed equations in the code if you want, but I think the current system works pretty well, and that change I just made fixed the one paradoxical behavior that the previous system had.

**Comment by endless-sky** [comment] 2015-12-17 03:18
0.8.9 is now released, so I'm closing this.

**Closed by endless-sky** 2015-12-17 03:18 UTC
Labels: mechanics
