### ISSUE TITLE
better ship coloring.

### ISSUE THREAD

**Issue by abmpicoli2** [endless-sky/endless-sky#6772] opened 2022-04-26 16:47 UTC
### Problem Description

I find it difficult to differentiate my ships from ships from other factions.

I would like a more marked coloring system: it is there, but it is very faint.

My personal solution has been to actually edit the ship images in gimp to make the yellow color more marked. I get to the point of add big bright yellow stripes in the sprites to actually be able to see the faction.

![image](https://user-images.githubusercontent.com/37077317/165351003-98c364a9-38ca-41f1-8443-c44019987555.png)

### Related Issue Links

I don't know about that.

### Desired Solution

Well, what I did in the images, but more artistic: make the "yellow" stripes in the images "brighter", so that it is easier to differentiate ship owners.

### Alternative Approaches

Well, if you want to go there, maybe place an optional "dot" or marker somewhere near the center of the ship? Even a friend-or-foe overlay would be great.

**Comment by tehhowch** [comment] 2022-04-26 21:47
Currently the only supported remedy is to turn on ship overlays (in your game preferences), to rapidly differentiate friendlies from hostiles.

It's possible we could add additional overlays to enhance the game's accessibility, such that you could have one without also having the others.

**Comment by tehhowch** [comment] 2022-04-26 21:49
Closing as a duplicate of https://github.com/endless-sky/endless-sky/issues/3911

**Closed** 2022-04-26 21:50 UTC
Labels: duplicate
