### ISSUE TITLE
A lot of chinese players are looking forward to a Chinese version of the game

### ISSUE THREAD

**Issue by JonathanZhang1** [endless-sky/endless-sky#6158] opened 2021-08-04 12:38 UTC
Many Chinese players have problems in playing this game,so we hope to get a chinese version.

**Comment by MCOfficer** [comment] 2021-08-04 13:14
duplicate of #558 #201 (cmon we should really close one of them).

TL;DR: first we need unicode support (#4123), then we'd need contributors to translate the game and maintain the translated version.

**Closed** 2021-08-04 15:26 UTC
Labels: duplicate

**Comment by Hagb** [comment] 2021-08-05 18:11
@JonathanZhang1 These is [an unofficial Chinese translation project (work in process)](https://github.com/Hagb/endless-sky-zh_CN-l10n) based on https://github.com/oo13/endless-sky/tree/build_test_i18n_v3 .
If interested in translating, please join QQ group 619684526, or contact with @Sun-FreePort or me.
