### ISSUE TITLE
Escorts with jump drives use hidden systems

### ISSUE THREAD

**Issue by CodeKatta** [endless-sky/endless-sky#8841] opened 2023-06-04 00:02 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Well, don't know if it's really a bug, more of an inconsistency. I noticed that ships equipped with a jump drive will sometimes use a system that is conveniently located for them but which doesn't appear on the map since it's still hidden.
I observed this when ordering my ships to go from **Misam** to **Algenib**. In the ship list you can see the system your escorts are at the moment and there I noticed that some are just in **Devil-Run**, which isn't on the map yet but should be somewhere around the top of the 'R' in 'THE CORE', if I'm not mistaken (they jump from **Kor Zena'i** to **Devil-Run**).

### Steps to Reproduce

1. Go to **Misam** (with your escorts, of course)
2. Send your ships (with jump drives) to **Algenib**
3. Look at the 'ship list' in the info screen
4. **Devil-Run** should appear in the 'system' column

### Expected Behavior

Of course, to let me in on the secret, now that they've already discovered that system 😁

### Operating System

Windows 10 Pro version 22H2 build 19045.2965 (but the same in the Android version)

### Game Source

GitHub Releases

### Game Version

v0.10.0

**Comment by TomGoodIdea** [comment] 2023-06-04 09:42
duplicate of #5731

**Comment by Zitchas** [comment] 2023-06-04 15:41
Thank you for taking the time to report on a bug! As TomGoodIdea pointed out, this has been reported already, but nontheless having details about a specific situation it can be repeated in is useful to have. 

Further discussion on this should take place in the older bug report. Thanks again for reporting!|
https://github.com/endless-sky/endless-sky/issues/5731

**Closed by Zitchas** 2023-06-04 15:41 UTC
Labels: bug, duplicate
