### ISSUE TITLE
jump/board/land keys ignored even after movement keys released

### ISSUE THREAD

**Issue by NomadicVolcano** [endless-sky/endless-sky#4755] opened 2020-01-24 00:14 UTC
If you hold down the J/B/L buttons, use the movement keys, and then stop moving, the autopilot does not re-engage.  This is explained better below.

1. Press J, B, or L to begin an autopilot action. (Or whatever you've assigned jump, board, and land.)
2. Hold down the button; do not release
3. Use movement keys.  This cancels autopilot, as expected.
4. Stop using movement keys.
5. Autopilot resumes its action because J, B, or L are still pressed.

Instead, in step 5, the button is ignored.

See #4744 for a related issue.

**Comment by tehhowch** [comment] 2020-01-24 06:27
Closing as a duplicate of #4744

**Closed by tehhowch** 2020-01-24 06:27 UTC

**Comment by NomadicVolcano** [comment] 2020-01-24 13:27
This is not a duplicate of #4744.  That one only mentions jumping.  This issue mentions boarding and landing as well.
