### ISSUE TITLE
Depleted battery + weak generators = stuck in auto-pilot mode

### ISSUE THREAD

**Issue by ghost** [endless-sky/endless-sky#4072] opened 2018-12-15 07:31 UTC
Star barge configuration to reproduce:
* 3 solar panels instead of the default fuel cell
* 1 supercapacitor instead of the default battery
* The rest may be the same

Now everything works fine when the supercapacitor has some charge in it, but once it's depleted and you're in autopilot mode, trying to land/jump, the battery won't charge and you will never be able to jump/land.

For your main ship, this is not a problem, because you can simply turn off the autopilot. However, for your companion ships, they're basically stuck in space forever because they're always in the autopilot mode.

I assume this is because the autopilot is trying to do two things at once: steer and thrust. So when the battery recharges just enough for the steering to work, it's immediately discharged and the ship never has enough energy to thrust.

Possible autopilot fixes:
* The ship should only try doing one thing at a time: steer/thrust/shoot
* Once the battery has less energy that steering+shooting+thrusting requires, the autopilot should wait until the battery is recharged enough so that it has enough energy to do steering, thrusting and shooting all at once

**Comment by tehhowch** [comment] 2018-12-15 08:18
Is this `master` or Steam release? The game will apply fractional thrust in builds as of https://github.com/endless-sky/endless-sky/commit/ba060258ae8991bd7e410014b4e12d5cdf3471f9

Possible duplicate of https://github.com/endless-sky/endless-sky/issues/3915

**Comment by Mark-Weston** [comment] 2018-12-15 12:01
This is v0.9.8p1 packed with OpenBSD

**Comment by Nescio0** [comment] 2018-12-15 12:08
Ramscoop and solar collection only work when they are in the same system as your flagship, not when jumping or in different systems. 
If you have multiple escorts relying on solar energy, you probably want to keep your fleet together. When preparing to jump, hold down J and don't release it until all your ships are properly aligned. That way all of them will arrive simultaneously in the next system, allowing all of them to benefit from ramscoop and solar energy for the same amount of time, preventing ships to get stuck in different systems with empty batteries.

**Comment by Amazinite** [comment] 2021-04-26 22:33
Ghost account.

**Closed by Amazinite** 2021-04-26 22:33 UTC
Labels: unconfirmed
