### ISSUE TITLE
There is little reason to choose a Falcon over a Leviathan if you're in the market for a heavy warship

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#371] opened 2015-12-04 20:26 UTC
The Falcon's advantages compared to a Leviathan:
* 10 more tons of cargo space
* Higher base top speed and acceleration
* 20 more tons of engine space
* 1.8m credits cheaper
* 1 more hyperspace jump range

And its disadvantages:
* 1400 less shields, and 1300 less hull
* Slower shield charging
* Slower turning
* Higher crew complement; higher operating cost
* Runs really hot and overheats easily
* Less energy generation
* 80 tons less outfit space

If I compare these, the Falcon almost never wins, because the things it's better than the Leviathan at are inconsequentially minor or easily remedied. The Falcon seems to need better positive differentiation from the Leviathan. If it's speed and maneuverability, this needs to be much more strongly expressed.

**Comment by endless-sky** [comment] 2015-12-04 20:39
The Falcon was intended to be the option for people who want more speed, but you're right that I should probably rebalance it. How about this (5238bb1)? Just increasing the engine space by 10 is enough to allow it to carry A5 steering and thrusters or an A3 thruster / A8 steering combo.

**Comment by Pointedstick** [comment] 2015-12-04 20:57
More engine capacity is good, but actually making use of it exacerbates the existing disadvantage of an underpowered reactor and high heat output vs the Leviathan. I sort of think it's weird that a ship called the "Leviathan" should have better turning speed out of the box compared to a ship called the "Falcon."

**Comment by Pointedstick** [comment] 2015-12-04 23:07
Yes, and the advantage of a huge cargo bay would be much less noticeable if you couldn't loot reactors or any of the other suggestions to tone down the power of looting.

**Comment by frameworld** [comment] 2015-12-05 06:17
You can compare a ship's potential or the outfit it is bought with by default.
Personally I think there is too little competition for Bactrian and Mule too but I haven't tried all slight balance edges out (such as barely or not fitting items, etc).

I saw that especially with engine space the value raises in steps rather than proportionally with the value given - also dependent on if you prefer ion, plasma or atomic engines.
 * If you equip ships with an Armageddon core you need additional outfit space for cooling. And then it is less energy efficient, which isn't easy to compare either.
 * (which BTW is not purchasable during free-worlds campaign, but you can get one by buying+selling a Bactrian for example)

I figured out that it is better to not fill all turret+gun slots and purchase more ion/plasma drives on 2 ships rather than having 1 expensive with outfit-space-enhancers and atomic engines.

And ion drives have other mass-requirements than atomic, so it is hard to tell how much of a difference this 10 outfit space actually makes.

**Comment by Nikwigi** [comment] 2015-12-05 19:08
I think the bactrian is the best for under 20 million. Tons of cargo to turn into mass. Once you over haul it not much can bring it down. And the huge crew capacity. If anything I think its the best bang for the buck.

**Comment by eggels** [comment] 2015-12-06 04:44
> Just increasing the engine space by 10 is enough to allow it to carry A5 steering and thrusters or an A3 thruster / A8 steering combo.

This is a good balancing move and would allow for a seriously maneuverable fleet ship with an A3/A8 combo, while keeping the Leviathan viable with its better heat dissipation (minor advantage) and outfit space (potentially major advantage.)

**Comment by endless-sky** [comment] 2015-12-17 03:15
0.8.9 is now released, so I'm closing this.

**Closed by endless-sky** 2015-12-17 03:15 UTC
Labels: balance
