### ISSUE TITLE
Issue with Cloaking Devices

### ISSUE THREAD

**Issue by Disiuze** [endless-sky/endless-sky#2557] opened 2017-05-25 20:41 UTC
If you enable cloak at a place in a system where you can not regain fuel fast enough, you will be targetable like normal. However, when you then get closer to the star with a high enough, but not too high, ramscoop value, your ship will cloak and uncloak itself erratically, resulting in enemy ships trying to target the player when they can't, while still firing their weapons, resulting in the situation that happened in the screenshot.
![cloaked 1](https://cloud.githubusercontent.com/assets/8760485/26469660/166fd70a-419b-11e7-9e05-c85a9105f994.JPG)
(source for screenshot is @Elyssaen)

**Comment by KiLEdEnNis** [comment] 2017-05-25 20:53
when you become invisible or visible they can hit you

I'm having trouble trying to find an issue here, if you're outta fuel you become visible

**Comment by Bladewood** [comment] 2017-05-25 20:54
The problem is that it makes the AI ships look like damn fools.

I think this would be resolved by something in a post I saw a long time ago. It basically says that after the ships in the system cloak, their attackers would continue to be wary and panicked.

[They would fly around, mostly in the general direction of the cloaked ship. Ships with splash damage weapons would fire them off.]

**Comment by tehhowch** [comment] 2017-05-25 20:58
I'm not sure it is an issue per say - if you do not deactivate your cloak, every time you get enough fuel for it to function, it will function until it has insufficient fuel. As part of it no longer functioning, you become targetable. Until you're done 'phasing' back into normal space you cannot fire, but while phasing in either direction you can (will) take damage.

I'm curious to see the rest of the screenshot, where the flagship's Shield/Hull integrity is shown (e.g. is damage being received). If damage is being received, then the AI is doing its job 😐

**Comment by tehhowch** [comment] 2017-06-05 18:59
I think the simplest fix is for de-cloaking to occur faster than you can cloak. This way, if your fuel regeneration rate is not sufficient to permanently power your cloak, you will always decloak fully.

**Comment by tehhowch** [comment] 2017-06-06 02:47
This should be adequately addressed by d754ba6e2f7ccd105ab564c04445e69fb32fafc4

**Closed** 2017-07-23 18:36 UTC
Labels: mechanics
