### ISSUE TITLE
Escorts can ask aliens for help

### ISSUE THREAD

**Issue by Alkallid** [endless-sky/endless-sky#1153] opened 2016-05-27 19:05 UTC
If your escorts run out of fuel, and you don't know the Wanderers yet, they'll still request fuel successfully.

**Comment by Bladewood** [comment] 2016-05-27 21:06
This would make sense for escorts, at least. The wanderers are good people.

The only thing is, they don't help the player :(

**Comment by Alkallid** [comment] 2016-08-01 15:20
Not sure if mechanics are closed, but it seems down.

**Comment by jostephd** [comment] 2019-06-09 16:53
Still happens in 0.9.9, reopen please? @beccabunny

**Comment by jostephd** [comment] 2019-07-01 16:22
@MCOfficer In case it's not clear - the bug is that when the `language: Wanderers` condition is unset, escorts who run out of fuel receive fuel from Wanderer ships, even though the flagship can't.

**Comment by MCOfficer** [comment] 2019-07-01 17:40
> 
> 
> @MCOfficer In case it's not clear - the bug is that when the `language: Wanderers` condition is unset, escorts who run out of fuel receive fuel from Wanderer ships, even though the flagship can't.

my confusion stems from you pinging becca, who has nothing to with this issue..

**Comment by jostephd** [comment] 2019-07-01 18:26
I reported this on discord and Becca asked me to ping him when I reported it on github.

**Comment by Tadrix** [comment] 2019-07-03 22:09
I think as an anti-frustration measure it should stay this way. New players go there not knowing what to expect, and they will not immediately gain the translation device. So it's most likely that any escorts that run out of fuel are stranded for good, because backtracking and attempting to refuel them all would be tedious to say the least without a dedicated tanker escort. Let the player worry about his flagship.

**Comment by Bulinus** [comment] 2024-01-21 00:01
I had opened a duplicate of this bug so the report was closed so leaving my two cents here.

The game has gotten more complex since 2016 when the original bug report was opened.  There are now a lot of alien systems where the players cannot communicate with the ships in the newer content especially on the north east past the korath.  I understand the comment from Tadrix that it is an anti-frustration behavior but personally I think the game would be better if the refueling behavior of aliens was consistent between the player and escorts.  It may be my opinion but if you go out into the middle of nowhere without a ram scope in my opinion you deserve to be stranded there.

**Closed** 2024-09-14 22:12 UTC
Labels: mechanics
