### ISSUE TITLE
Crash before loading finishes

### ISSUE THREAD

**Issue by th3Ch4OT1C** [endless-sky/endless-sky#2228] opened 2017-03-07 03:25 UTC
I played Endless Sky with the 0.9.2 Update and it worked fine, would crash sometimes but not very often. Now I just downloaded 0.9.6 and it crashes before the main menu finishes loading see video: https://youtu.be/QVcM-P0-WXQ I have tried running as administrator, and same effect, I have also tried changing the file C:\Users\AppData\Roaming\endless-sky to read and write still no dice.

.

**Comment by MessyMix** [comment] 2017-03-07 03:29
Have you looked at errors.txt?

**Comment by th3Ch4OT1C** [comment] 2017-03-07 03:37
I don't see that file anywhere. Where should it be?

**Comment by MessyMix** [comment] 2017-03-07 03:48
iirc right where you located the rest of your _saved_ game. That's
C:\Users\AppData\Roaming\endless-sky, I think (not a native Windows user).
It should be in the same parent folder as your "saves" folder.

**Comment by th3Ch4OT1C** [comment] 2017-03-07 03:51
Nothing there.

**Comment by MessyMix** [comment] 2017-03-07 03:59
What is in that folder for you, then? I have:
>errors.txt
>keys.txt
>plugins
>preferences.txt
>recent.txt
>saves

**Comment by th3Ch4OT1C** [comment] 2017-03-07 04:09
I only have plugins and saves. No other data is in the endless-sky folder. plugins and saves are also empty.

**Comment by MessyMix** [comment] 2017-03-07 04:12
Are you running old nVidia drivers? Their graphics cards / outdated drivers
have been known to cause issues and crashes with the game (messes with
OpenGL iirc).

**Comment by LocalGod79** [comment] 2017-03-07 04:16
if you played endless sky under 0.9.2, there should be some save files somewhere - what happened to them?

perhaps you could try stepping back one release at a time until you find a version that works, and let us know: might give us an idea of what was introduced that's causing the problem.

release history (with downloads) can be found here;
https://github.com/endless-sky/endless-sky/releases

**Comment by th3Ch4OT1C** [comment] 2017-03-07 04:19
Not sure where to find graphics card info, I'll try stepping back. The reason my saves are gone is because I tried deleting all endless sky files the reinstalling (I moved my save.txt onto my desktop).

**Comment by th3Ch4OT1C** [comment] 2017-03-07 04:37
0.9.2, 0.9.4 and 0.9.5 all work.

**Comment by LocalGod79** [comment] 2017-03-07 04:48
at least you have some new content to chew on until M.Z. gets back from vacation...

definitely review the changes in the [changelog](https://github.com/endless-sky/endless-sky/blob/master/changelog) for 0.9.6 to see known bugs that you can avoid.

**Comment by th3Ch4OT1C** [comment] 2017-03-07 04:57
Well, I just tried actually playing rather than just opening 0.9.5 (probably shoulda tried that earlier) and it crashed right when I clicked load. 0.9.4 loaded fine though.

**Comment by whismerhill** [comment] 2017-03-07 11:07
@th3Ch4OT1C 
did you try creating a new pilot ? if not, could you try it ?

@MessyMix 
I'm not ruling it out completely, but the so called opengl errors in nvidia drivers (that affected minecraft) were in fact related to opengl + java, and were fixed in more recent drivers, which changes nothing for endless sky.

**Comment by Wrzlprnft** [comment] 2017-03-07 12:09
the java related openGl issues where fixed, yeah. but in general, outdated nvidia drivers are not openGl friendly.

**Comment by KiLEdEnNis** [comment] 2017-03-07 12:19
does 0.9.6 crash you too? (I think that 1 is beta,) that 1 has bug fixes

**Comment by KiLEdEnNis** [comment] 2017-03-07 12:20
side question: any plugins installed?
(and no one read my deleted comment, just me not reading & being dumb, shh)

**Comment by th3Ch4OT1C** [comment] 2017-03-07 18:54
I tried creating a new pilot in 0.9.5 and the same thing happened as in the video, so I pulled all of the saves and .txt files from the endless-sky folder then tried again. This time endless sky successfully loaded and I was able to click new pilot then enter my name, but right after that (when I clicked done on the next screen) Endless Sky crashed again. Also no plugins and I have never had a problem running Minecraft.

**Comment by Bladewood** [comment] 2017-03-07 19:03
Sanity check: Are your speakers connected?

**Comment by th3Ch4OT1C** [comment] 2017-03-07 19:24
As a matter of fact my sound IS broken, I'm not sure what's wrong with it but my computer is unable to produce any type of sound anymore, through its speakers or through ear buds. I haven't bothered trying to fix it cause I never use sound for anything but it would be nice...

**Comment by KiLEdEnNis** [comment] 2017-03-07 19:55
still weird that the game crashes when the PC can't make a sound
so this is another Nvidea driver issue?

**Comment by kikotheexile** [comment] 2017-03-07 23:33
I dont think this is a nvidia driver issue, but if you are using nvidia it is never a bad idea to look for updates. they are bad about letting people know that new updates are out.

**Comment by th3Ch4OT1C** [comment] 2017-03-07 23:36
I'm not sure how to check, I looked in Device Manager, Display adapters and it says I have Intel(R) HD Graphics 4000 if that's it.

**Comment by Bladewood** [comment] 2017-03-07 23:56
> Intel

He's not even running an Nvidia card... :|

**Comment by whismerhill** [comment] 2017-03-07 23:57
integrated graphics in the intel CPU then, and not nvidia
their drivers were usually even worse xD, though not sure where they stand nowadays.

that said, I'd first try to fix the sound issue before digging further.

**Comment by th3Ch4OT1C** [comment] 2017-03-08 00:16
I have no idea where to start to fix the sound. I checked in device manager and all sound handlers said they were working properly. Also I just tested some applications and the sound for BlueStacks(android emulator) and Skype both work. Google Chrome, Minecraft, and Endless Sky all appear not to. Spotify refuses to even start a song.

**Comment by th3Ch4OT1C** [comment] 2017-03-08 02:10
Ok, so I disabled then re-enabled my sound drivers and that fixed the problem, now 0.9.5 and 0.9.6 work. I think the sound problem initially arose from using my remote desktop connection (it apparently can cause issues with the sound drivers). I still think you guys should try to fix this problem though. Thanks for all the help :)

**Comment by MessyMix** [comment] 2017-03-08 02:23
and the problem is...?

It seems that this problem only affects you; it's not something that other
players have reported, so there's really not much to fix except remote
desktop connections and sound drivers. I know the developer and many others
use UNIX based systems (Linux, Mac), so it might also be related to
Windows. Regardless it's not a problem that anyone else has reported, and
you haven't really given any information besides your physical
observations, so I don't see how "us guys" can "try to fix this problem"
right now.

**Comment by th3Ch4OT1C** [comment] 2017-03-08 02:26
Sorry, didn't mean to come off (insert correct term). What I was suggesting is making the game not crash when the sound drivers aren't working, I'm pretty sure others have had that problem from what Bladewood said. Although I'm not sure I even know what I'm talking about, so if there's nothing to fix don't mind me :)

**Comment by MessyMix** [comment] 2017-03-08 02:28
Sure. I have no clue what Bladewood is talking about, so we're in the same
boat. :P

**Comment by Amazinite** [comment] 2017-03-08 12:30
Given that @Bladewood opened #2231, either this or that need closed.

**Closed** 2017-03-08 18:24 UTC
