### ISSUE TITLE
Fast-Forward Malfunction on Mac version of 0.9.11

### ISSUE THREAD

**Issue by JustSomeOtherDude** [endless-sky/endless-sky#4989] opened 2020-04-14 17:50 UTC
**Describe the bug**
The fast-forward feature (default CAPSLOCK) is not working on the Mac version of 0.9.11. I currently have the latest High DPI plugin enabled.

**To Reproduce**
1. Launch game, enter ship, hit caps-lock key.

**Expected behavior**
The fast forward (time compression) feature does not activate
**System (please complete the following information):**
 - OS: macOS Catalina - 10.15.4
 - Game Source: direct download from GitHub.com
 - Version: 0.9.11

**Comment by MCOfficer** [comment] 2020-04-14 17:54
Duplicate of #4614

**Closed** 2020-04-15 00:23 UTC
Labels: duplicate
