### ISSUE TITLE
Atomic Engines are too far superior to Plasma and Ion engines

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#271] opened 2015-11-26 19:57 UTC
I get that cost, energy, and heat are the major drawbacks, but at a certain point money is really no object and energy supply and heat dissipation are pretty simple to deal with for most ships. As a result, Atomic Engines seem like no-brainers and I never find myself wanting to use Plasma or Ion engines, ever. It seems like this state of affairs could use some tweaking so there isn't such an obvious "best" choice. Ideally all choices should seem practical in many situations.

**Comment by gchapyzh** [comment] 2015-11-26 19:59
I would disagree. They seem rather balanced, being so expensive and large. I often find myself in a dilemma weather to buy plasma or atomic engines.

**Comment by Pointedstick** [comment] 2015-11-26 20:32
A pair of Atomic Engines are generally the same size or smaller then same "tier" plasma engines, outside of the lowest tier:

A120+A125 = 38 tons vs Chipmunks = 25 tons; Atomic engines heavier by 13 tons
A250+A255 = 59 tons vs Greyhounds = 60 tons; Atomic engines lighter by 1 ton
A370+A375 = 91 tons vs Impalas = 101 tons; Atomic engines lighter by 10 tons
A520+A525 = 142 tons vs Orcas = 172 tons; Atomic engines lighter by 30 tons
A860+A865 = 219 tons vs Tyrants = 292 tons; Atomic engines lighter by 73 tons

In practice the weight savings can be even greater if you consider that Atomic engines are so powerful that you can often downsize to a lower tier and have enough thrust.

**Comment by Tufton** [comment] 2015-11-26 22:08
I feel like the point of the atomic engines was to be generally better in
terms of outfit and output but have higher heat and energy requirements.
That plus they are costlier.  However, I agree they are superior in the
end-game, even over the various alien models.

**Comment by thenerdfreak** [comment] 2015-11-27 00:50
typically I'll use atomic, but early game they're way too expensive. A lot of times I'm limited to only one atomic piece (Thrust or turn) because of low engine capacity. It's fairly balanced as is, it's one of the elements of the game I haven't tampered with

**Comment by Oeleo** [comment] 2015-11-27 01:38
I think that it's the point, that's a better and more expensive technology, so yes it's completely useless when you have enough money. But the problem is their size, 292 tons... for the moment nothing is big enough.

**Comment by endless-sky** [comment] 2015-11-27 02:48
I've considered making ion engines even more energy and heat efficient to make them more desirable. But, the point of atomic engines was to be a premium product, at 5x the cost of other equivalent engines.

The way I think of the balance is: outfitting a ship to use atomic engines (and to be able to power them) basically doubles the cost of the ship. That's enough of a price difference that unless you're too rich to care, you have to think about whether or not it would be better to just buy the stock version of a bigger ship, instead. For example, a souped-up Argosy with atomic engines costs about the same as a stock Corvette, and probably performs about equally well in battle, too.

**Comment by Oeleo** [comment] 2015-11-27 04:20
I agree all that can make th game harder, but as I said the size of the A860 and A865 are far too big to can be put in the biggest boat, so if ion and engines need to be used at the begining (for the first big boats) maybe that reduce their thurst power and their size could be a good idea ?

**Comment by Pointedstick** [comment] 2015-11-27 05:08
In general, I think it's problem in a game like this to have any outfit/item/whatever whose main drawback is high price. The nature of these kinds of games is that if you're even moderately good at them, eventually you wind up with more money than you know what to do with because making money is easy but you've more or less run out of things to spend it on. In this game, it's especially noticeable once you gain access to the missions that pay you 200k+ credits for very little effort (e.g. family transport passenger missions, pirate hunting missions, large rush deliveries), when you have a ship with a cargo bay that can fit looted reactors, and plenty of other fairly simple cases. Once this happens, all the options whose primary drawback is price lose their primary drawback and become no-brainers.

**Comment by Oeleo** [comment] 2015-11-27 05:20
Yes that's why globally all the best stuf would be far more expensive. And it will be far more realistic because, why am I able to build a huge fleet of bactrians in 2 years when there are just a few of them in the Republic's fleet ?

**Comment by airtroop392** [comment] 2015-11-27 05:30
I've never even used the high tier ion or plasma thrusters- there is literally no point in me doing so, because whenever I get that into the late game I can almost always afford a pair of Atomic engines and thrusters, which are incomparably superior to the cheap ion thrusters and the blazing hot plasma thrusters.

**Comment by gchapyzh** [comment] 2015-11-27 05:37
I think I see the issue here: different engines create no drawbacks or bonuses. Maybe Atomic thrusts should be REALLY expensive, plasma thrusts should be SUPER energy efficient but heat generating, and Ion thrusts should be VERY power consuming but little heat production.

**Comment by thenerdfreak** [comment] 2015-11-27 11:33
So in conclusion: at least you should have to FIGHT the crew a little to take some ship parts? (Engine, Reactors, etc.)

**Comment by jafdy** [comment] 2015-11-27 21:42
How about a new kind of engine on the same level as atomic but with differences like the plasma and ion engines are different. 
Or make it so only so many can be bought and the stock slowly replenishes. This could also be used to limit the number of high end ships you can get. It would fit the law easily as put when dreadnoughts become available.

**Comment by kyzentun** [comment] 2015-12-06 04:52
For any experienced EV player, money was never any object, except as a self-imposed challenge.  Increasing price in general doesn't make something require more skill to get, it just increases the idle grinding requirement.

The real downside of atomic engines is being forced to fly all the way to Epsilon Leonis to buy them when I get a new ship.  Then over to Alheka for a fusion reactor, Tarazed for cooling, .... (though lately I've been buying cooling from the Korath through the ship-to-ship exchange program. (looting))

The problem I see with "balancing" atomic engines down to the same level as other engines is that then you have the same problem for the opposite reason: It's not worth thinking about ship design because all choices are equally bad.

I like atomic engines the way they are. (haven't updated in a couple weeks to see changes)

Also, I don't want to have to fight crew for outfits, because the Korath and Quarg crews are invincible.

**Comment by frameworld** [comment] 2015-12-06 10:26
(1) I dislike the dreadnought look. Others may like it.
* It would be cool if we all were able to get an alternative ship with similar stats.
* Then dreadnought and this ship would be exclusive of each other.

Right now the stats dictate which ship icon you have to keep in the middle of your screen (with no modding - not everybody does that).

(2a) Make Capitals unique.
Capitals are Bactrian, Korath-WorldShip, Dreadnoughts - the best ships available from each fraction.

It is a big difference whether a ship is controlled by the player or an escort.

If Capitals were unique, escorts would not be op but you can still offer the player a better ship.
Which gives the balance more freedom.

And you don't need to spawn 7-8 WorldShips in one sector (makes them less awesome).

**Comment by brendanjones** [comment] 2015-12-07 11:24
> typically I'll use atomic, but early game they're way too expensive. A lot of times I'm limited to only one atomic piece (Thrust or turn) because of low engine capacity. It's fairly balanced as is, it's one of the elements of the game I haven't tampered with
> - thenerdfreak 

What are you classing as early game? Considering some Hawks (I think?) and Clippers have atomic engines, they're easy as hell to loot. Within 2 hours of play you can have a Mule decked out with atomic engines. As Kyzentun said, "For any experienced EV player, money was never any object", but I think money is made way faster in ES than in any EV game, and so getting a great ship is way too fast. Ideally, there should be a progression through the ships, as you make just enough money to buy the next higher grade. Instead, making money is so fast that you can have an end-game ship in a couple of hours of play. Too fast.

So, if you're trying to buy atomics, sure, they're quite expensive. But there's no need to buy them, and so there's never any need to buy Ion or Plasma engines.

**Comment by kyzentun** [comment] 2015-12-07 12:25
> I think money is made way faster in ES than in any EV game, and so getting a great ship is way too fast. Ideally, there should be a progression through the ships, as you make just enough money to buy the next higher grade. Instead, making money is so fast that you can have an end-game ship in a couple of hours of play. Too fast.

I'd have to boot up an emulator to confirm (it's been several years), but I think that once I learned how to do it in EVO, getting a decked out crescent warship (~12Mcr?) only took 1-2 hours doing the Telnan <-> New Rigel run.  That warship was then good enough for doing almost every mission in the game with trivial effort.  Unless you're building a shield beetle or bactrian, or other top end warship, you're not in a ship that is going to last the whole storyline in ES.

I think the primary thing that makes earning money seem faster in ES is that there is zero capital depreciation.  In the EV series, when you want to buy a new ship, you sell your current one for half price.  Zero capital depreciation in ES means that if there's only 100k price difference between two ships, you can buy the cheap one now, work up 100k, then buy the next one fairly quickly.  I love this, it makes it much easier to go through ships and try them out.

Balance (to me) only really matters during the storyline, because after the storyline the player has a top-end ship (or they're not surviving two nukes to the face, which hit me before I could dodge on that mission (it took 3-4 tries just to not get hit 3 times and killed)).  
One thought for balancing the storyline would be some way of not allowing the player the *time* to build an end-game ship before playing.  My first pilot went off to Hai space and ferried passengers around for 5 years, then came back and saw the civil war from start to finish.  Apparently there was a 5 year standoff after the nuke attacks?  So maybe the storyline should have some indication that the player needs to go join up soon, or they get a lesser role or something.

I'm happy with the balance of atomic engines because it means I can typically avoid enemies I don't want to fight, and it's not a game ending advantage for killing powerful enemies.  I like that the better engines in ES aren't just a generic "spend 10 tons of space, get more engine" like EVO had.  Making different types of engine, and different sizes of each type is really cool for flavor.

The balance in general in this game is much better than the EV series.  I can't take a shuttlecraft and go take out medium pirate warships (helians or turncoats, depending on missile luck), or an arada and take out entire human/voinian heavy warship fleets the way I could in EVO (so many hours, I even managed to *capture* a voinian frigate with my arada once).  If I want to defeat a ship in ES, it needs to be below or at my level, or I have to be clever.  Not EVO style clever, where the AI didn't fire at max range, so you could fire back as it chases and whittle it down.  Not EVN style clever where you just equip railguns and fire from halfway across the system, dodging their rail fire as needed.  Actual clever, like sticking two flamethrowers on an osprey and making repeated passes on two republic carriers until one overheats. (it helped that I had 2-3 S970s on there)
There isn't the an end-game ship like EVN's raven, which was overpowered to the point that 7 could camp any non-polaris planet and destroy the defense fleet with no losses. (except for the quarg ships, but you can't get one of those without modding or a massive fleet)
Balancing this game for people that are not EV veterans has to be a serious challenge.  I knew already to go for outrunning enemies and heavy shielding, so in the cases where I had to cross republic space I didn't have much trouble because I could outrun even the fighters.  People that don't know those key points are going to suffer some rough lessons, often getting stuck in a pilot that just can't live because they're not in a tough enough ship.

Anyway, I'm going back to showing people the scenic route around the galaxy, with my fleet of 20 blackbirds.  "This is your fleet captain speaking, we will departing Luna now for Thrall to make a rush delivery.  Those of you destined for Earth will have to wait for the next time we visit this system."  "But, it's *right* *there*, I can see it out the window!"  "Don't worry, we'll be back in a few weeks or months."
(btw, the mission list on the right needs to be scrollable, can't remember whether I reported that one)

**Comment by thenerdfreak** [comment] 2015-12-07 12:55
I took my first Quarg ship with 4 shield beetles carrying korath shields and heat shunts, and electron weaponry. Took less than 4 hours. Camped out Sheratan in a cargo Bactrian and waited for a Raider to come, Paid a meager 300k for the pirates to stop attacking me, so pirates aided me in disabling it. Took its jumpdrive and went to terrorize the Pug, got a few more jumpdrives and outfitted them onto the shield beetles. Went to Korath space (before I started doing the  FW Missions) and destroyed Korath ships, jumping back to Polaris to sell/outfit the parts onto my ships, until I had a sizable 4-ship fleet of Shield Beetles and my Cargo Bactrian. Easily ran the missions up to the point where the navy gets electron weapons, and camped out a desolate sector until I had enough to outfit my Beetles, and went straight from there to the Tarazed area. (spoiler) Once I unlock Dreadnoughts in the Missions, I'll outfit those instead, since they can carry a lot more quarg Firepower

**Comment by endless-sky** [comment] 2015-12-07 13:59
In Nova, the bulk freighters had so much cargo space that you could very easily rent of few of them and be earning a million credits per cargo run in the first hour of the game. (Especially if you took the hidden wormhole to Polaris space and rented a Cambrian.)

I think game balance is really a matter of "how long does it take the typical player to amass money?" not "how long does it take for a player who knows all the secrets?"

But yes, the Quarg will need to be rebalanced once the rest of the alien species have been added.

**Comment by brendanjones** [comment] 2015-12-07 18:40
kyzentun you're making me all nostalgic! 

> When the game is complete, Atomic engines will be outdated (alien tech) Quarg outfits will be near worthless (Once again, alien tech) And even Quarg SHIPS won't be the best (hopefully).
> - thenerdfreak

o.O Fighting human ships will be like swatting at flies...

> So in conclusion: at least you should have to FIGHT the crew a little to take some ship parts? (Engine, Reactors, etc.)
> - thenerdfreak

Apparently I missed this comment. Yes, the cargo grind is a lot slower in this game due to having no Cambrian/Pegasus/Leviathan like in EVN, but it's compensated by the fact that looting is overpowered. So make looting less powerful/easy!

This would remove the problem of atomic engines being overpowered, because their high purchasing cost would be in line with purchasing power since your purchasing power would be lower. And looting a free pair of atomics would be much rarer.

**Comment by thenerdfreak** [comment] 2015-12-07 21:43
I've yet to find a way to make trading very profitable in late-game, I made more money in 10 minutes using a Fury than i did in an hour using a bulk freighter

**Comment by kyzentun** [comment] 2015-12-07 22:05
@thenerdfreak Pretty simple, do what is described in #173 and use lots of bulk freighters.  With 64 bulk freighters, each with A520 steering (faster turning means they take less time to jump) and A120 thrust engines, and a fast ship for myself, I made 1Bcr in ~20 minutes.  (getting up to that many freighters too a lot longer, but it's exponential growth).  The trade run is from Sirius (clothing) to Sol (luxury).  Not very interesting, but it does make money.

**Comment by frameworld** [comment] 2015-12-08 01:29
To remove power from looting, make turrets, guns and engines not costing outfit space because they are externally mounted.
But make them produce more heat so you need more (internal) cooling which then could be bigger.

The result would be that looted outfits costing a lot more cargo space "because the outfit space is effectively bigger" without hurting the "logic behind it" from a human perspective.
Then, balance cost/mass for outfits and make ships with a high outfit-cost harder to disable.
* NPC : "Funny how a self-destruction-explosive can save you from exploding due to scavenging players. Even if it is so expensive that it lowers my combat-rating per credit-unit."

When I use atomic engines, I would only use them on my capital.
* Unfortunately using lower tier engines to safe outfit space for weapons make them also less effective, even on a capital ship.

So perhaps it is not bad to also increase the gap between outfit sizes or make the efficiency difference lower (just a thought).

**Comment by endless-sky** [comment] 2015-12-17 03:50
For now, I don't see any compelling reasons to make the atomic engines less powerful, although that may change once more alien engines are available. So, for now I'm closing this.

**Closed by endless-sky** 2015-12-17 03:50 UTC
Labels: balance
