### ISSUE TITLE
"Buying" from cargo in outfitter does not work

### ISSUE THREAD

**Issue by NanzeRT** [endless-sky/endless-sky#8983] opened 2023-07-03 00:05 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

When trying to install outfit, not present in shop, on ship from cargo by pressing [B]uy button nothing happens.

### Steps to Reproduce

1. Have in cargo outfit, not sold in shop (in my case it's Heavy laser in Shaula system)
2. Select ship able to fit this outfit
3. Press key B

### Expected Behavior

Same as with [I]nstall button

### Operating System

Arch Linux

### Game Source

Other (please describe)

### Game Version

0.9.16.1

### Additional Information

Got game from [packages](https://archlinux.org/packages/extra/x86_64/endless-sky/)

**Comment by TomGoodIdea** [comment] 2023-07-03 03:20
There's a newer version available in the repository (0.10.2). Can you update your game and say if the problem persists?

**Comment by xX-Dillinger-Xx** [comment] 2024-03-19 18:28
@NanzeRT 
This isn't a bug. If the item is _in cargo_ you use `i` to install it. You don't need to `b` buy it, you already own it and you can't buy something that isn't available at that outfitter.

If the OP isn't going to respond I recommend closing it. It's not a bug.

**Comment by NanzeRT** [comment] 2024-03-19 18:44
@xX-Dillinger-Xx then it's not consistent behavior, since by pressing `b` when it available both in cargo and shop, it does install it from cargo. Also purposed behavior may serve as enhancement.

(haven't tested on newer versions)

**Comment by xX-Dillinger-Xx** [comment] 2024-03-19 22:12
I'm not sure about the version you're using but on 'continuous' the button at the bottom, does switch from `Buy` to `Install` when you select an outfit that is in cargo as well as for sale. After you install the outfit, it switches back to `Buy`. 

Having `b` work, in the situation where an item is in cargo and for sale, is just a bonus. You should be using `i`. 
- `b` is for buying
- `i` is for installing
- `u` is for uninstalling

**Comment by TomGoodIdea** [comment] 2024-11-04 17:31
The OP isn't responding; I'm closing this.

**Closed** 2024-11-04 17:31 UTC
Labels: bug, unconfirmed, waiting on OP
