### ISSUE TITLE
Feature Request: Multiple ammo lines for Weapons.

### ISSUE THREAD

**Issue by VonZorch** [endless-sky/endless-sky#4285] opened 2019-05-20 04:10 UTC
For instance the Sidewinder launcher.
ammo "Sidewinder Missile"
ammo "Sidewinder Missile II"
The "Sidewinder Missile II" would be introduced after the war was going on for a while and would be an improved version at a higher cost.

The old Mk 29 missile launcher could fire 9 different missile types.  The current Vertical Launch System will fire any surface launched missile in the US Navy's inventory.

This would also require that weapons characteristics be defined in Ammunition category outfits as they are in submunitions.
like so
outfit "Sidewinder Missile ii"
	category "Ammunition"
	cost 1200
	thumbnail "outfit/sidewinder"
	"mass" .2
	"sidewinder capacity" -1
	weapon
		"lifetime" 500
		"shield damage" 190
		"hull damage" 140
		"hit force" 190

**Comment by MCOfficer** [comment] 2019-05-20 09:23
i like the idea of moving all relevant attributes to the ammunition, after all a launcher is just a launcher. that might require some bigger code changes, though.

```
on a sidenote, are you aware of the existance of codeblocks?
```

**Comment by Zitchas** [comment] 2019-05-20 11:30
I fully agree. It makes a lot more sense to have the damage and all the rest of the stats attached to the actual projectile than the launcher. A missile launcher doesn't hit anybody, after all. It just holds the missile in the right position for it to be activated and fly away.

The only complication I can see is how to specify which missile is loaded. That would probably be solved by having the weapon select rotate through the projectiles instead of rotating through the secondary launchers. In the name of realism we might want to impose some kind of time penalty when switching between two missile variants that use the same launcher, although in the interests of gameplay, I'd be willing to accept the built-in delay of having to use the secondary weapon switch to be sufficient delay as it is.

**Comment by Pointedstick** [comment] 2019-05-21 23:32
Duplicate of https://github.com/endless-sky/endless-sky/issues/341

**Closed by Pointedstick** 2019-05-21 23:32 UTC
Labels: duplicate
