### ISSUE TITLE
translation!!!

### ISSUE THREAD

**Issue by Crystal-RainSlide** [endless-sky/endless-sky#708] opened 2016-01-24 07:45 UTC
translation support!!!
Languages folder should be found in such a great game.
If translation or localization is available,send an e-mail to rainslide[a]outlookDOTcom.

**Comment by Wrzlprnft** [comment] 2016-01-24 10:23
#201

**Comment by endless-sky** [comment] 2016-09-12 22:33
Duplicate of #201.

**Closed by endless-sky** 2016-09-12 22:33 UTC
Labels: enhancement
