### ISSUE TITLE
Wanderers: Alpha Surveillance H Doesn't Automatically Clear

### ISSUE THREAD

**Issue by Alkallid** [endless-sky/endless-sky#3460] opened 2017-12-23 06:47 UTC
I don't know if it's because of the interrogation scene's new dialog, since I haven't yet learned all about mission syntax, but even after finishing the dialog an departing, the mission will remain in your mission list and the waypoint will remain on Alnitak until you land anywhere.

**Comment by Amazinite** [comment] 2017-12-23 21:00
Duplicate of https://github.com/endless-sky/endless-sky/issues/1938

**Closed** 2017-12-24 00:42 UTC
