### ISSUE TITLE
[Feature Request] Defense Emplacements/Turrets

### ISSUE THREAD

**Issue by DamienThryn** [endless-sky/endless-sky#2612] opened 2017-06-10 22:08 UTC
I don't know how to estimate how much work or how feasible this is, but I wanted to see what people think about basically putting all anti-missile turrets, radar jammers, small shield/repair modules and other 'defensive' type equipment into its own category and installed into a dedicated class of hardpoints, like (but not in place of) turrets?

My thinking here is that the tradeoff between firepower and missile defense capabilities you get by having offensive and defensive turrets fill the same limited 'turret' space really limits the utility of anti-missile turrets. I believe that creating a new class of dedicated hardpoint would add a layer of customization without adding burden to the user. Rather than decide whether to install defenses, the question would be purely one of space and hardpoint availability. Hardpoints available would scale with ship size just like turrets and guns, and could vary by manufacturer style. Plus, there could be some other natural outfits in the vein of chaff/flares or decoys that could be loaded into these hardpoints that interfere with optical and infrared tracking.

Real-world analog: most naval vessels over the past century have had separate spaces dedicated to defensive gear, that would operate autonomously to engage anything in range, and modern naval vessels integrate the defensive missiles/guns with the jamming/spoofing systems. But the offensive weaponry is tied up in a separate system. And even armored vehicles are headed in that direction. The F-35 was supposed to, supposedly, but the things barely keep the pilot alive at present so yeah...

That would make me, at least, more willing to spend outfit space on defensive outfits rather than just my usual algorithm [ max speed, then max firepower, then max recharge ]. The firepower tonnage I give up to install a single turret that can be too easily overwhelmed makes anti-missile defenses kind of pointless to install, in my opinion. 

Other thoughts? Am I missing a past discussion?

**Comment by 123abchelpineedausername** [comment] 2017-06-10 22:33
The problem is that we are already so far into the game to create a major change such as this. This would allow for much better ships instead of the more strategically designed ships you have now. Eventually the theory is that your shields would be good enough to fend off missiles, but as I have seen mentioned before the Quarq use them, meaning they went up against a powerful enough missile heavy foe, most likely the Coalition. Going back to the idea of built in defensive placements I believe ships are crowded enough as it is plus the fact you would have to change the base model ships and add new locations for something to fire would be too large of a headache. However I do like the idea of defensive weapons having their own area within the outfitter. To kind of offer some support I could see this being implemented on some sort of super-ship that has a special kind of anti missile, but that already exists called the Drax (if I remember right been a while since I've played) and if they, despite being living beings and throughly rough cut, don't need special slots nor would anyone else.

**Comment by Amazinite** [comment] 2017-06-10 22:38
Drak*

**Comment by Amazinite** [comment] 2017-06-10 22:59
I don't really see why one would want to do this. In what way does this expand customization because all I can see is this limiting it.

 Right now, engines are limited by your engine space and weapons (anti-missile inculded) are limited by your weapon space, but everything else (shields, hull, jammers) is limited by your total outfit space, which is much larger than weapon or engine space. This means that most defensive outfits are already in a highly customizable position as they only take up outfit space. The Skein, for example, has 4 large shield generators by default, which takes up a rather massive 180 tons. If we then add the space of the other "defensive" outfits (two heavy anti-missile and a large jammer), then the amount of space taken up by defensive outfits on a Skein is 254. That's more than half its total outfit space. The space used up by these defensive outfits can then currently be expanded by converting cargo. 

If we gave defensive outfits their own space to take up, then we can't use as many of them. Right now if I wanted, I could buy a ship, convert all the cargo into outfit space, install no offensive weapons, and be able to install a massive amount of defensive outfits. To create some sort of "defensive space" attribute would mean that either the attribute needs to be very high compared to the weapon and engine space to keep the current customizability and therefore be pointless to have added in the first place or it would end up cutting down on customizability by reducing the number of shield generators and such that we can install from what we current can do.

Just reading the second to last paragraph, you seem like someone who tries to have each and every ship work independently from all other ships instead of specializing. Personally, I'll usually have a few ships fitted for max firepower, one or two ships fitted with long range anti-missile to protect the firepower ships, then a pursuit ship that is fitted for max speed to track down missile boats. (My flagship is usually either the one pursuit ship or an anti-missile ship that I keep my main firepower around.) And that's only my set-up when I'm expecting major combat.

**Comment by tehhowch** [comment] 2017-06-11 00:07
I'm all for chaff and flare anti-missile turrets, whichcould  cause (multiple) incoming projectiles to change targets, but those would need some changes to the current projectile code, because right now missile weapons have a single target that they either can track or temporarily cannot track, and all jamming can do is increase the chance that it flies straight ahead instead of track their target.

As for adding a third subcategory of outfit space, i think no.
As for designating special hardpoints that can only hold certain types outfits, i don't think that will be a viable option.

**Comment by Elyssaen** [comment] 2017-06-11 00:49
Some games have success with a 'utility mount' approach like you describe – I wouldn't be surprised if you're an Elite: Dangerous player, as you're descrining exactly how it's done there. But I don't see anything wrong with Endless Sky's approach. It'd be a significant about-face in the design of the game, pushes the complexity up a bit too high for this style of game, and I can't see it really being of that much of a benefit.

Question for everyone else – is nobody using anti-missile, like @DamienThryn? I pretty much always use it. I never run a Heavy Warship flagship without a pair of Korath Warders.

**Comment by MessyMix** [comment] 2017-06-11 01:56
I certainly use antimissile. I omit it on some ships; on others I carry pairs of warders—or, where space is scarce, wanderer ams—to protect my fleet.

**Comment by Amazinite** [comment] 2017-06-11 01:56
>Personally, I'll usually have a few ships fitted for max firepower, one or two ships fitted with long range anti-missile to protect the firepower ships, then a pursuit ship that is fitted for max speed to track down missile boats.

**Comment by endless-sky** [comment] 2017-06-11 02:04
I think that forcing the player to choose between using turrets for offensive vs. defensive capability is actually a lot more interesting than forcing each ship to have a certain amount of offensive vs. defensive space. That's also a much more interesting choice than just trying to figure out which anti-missile system is most effective.

**Comment by DamienThryn** [comment] 2017-06-12 16:53
Thanks for the comments!

I never use anti-missile stuff because speed takes care of missiles well enough. And allows me to totally control a fight as a bonus (except v. Kor Sestor, where the 'slowdown' effect as far as I'm concerned just leads to random 'oops, you jumped into a system and had no chance to even move before 20 ships focused fire on you and slowed you to a halt, so save-scum or cloak time'). And because current defensive systems are so easy to overwhelm, I just don't see the point in sacrificing the weapons space. _Maybe_ if anti-missile systems had an area effect?

I don't actually think there would need to be dedicated *space* for these outfits, just a secondary hardpoint (attached to/adjacent to the main turrets?) where you install defensive outfits that combine anti-missile + jamming + decoys (can a ship spawn an object that draw/absorbs fire?), and/or hull repair and shield quantity modules.

I would like to make non-combat play styles truly viable, without forcing a player to game the AI by kiting all the time until missile stocks are depleted. That, I think, depends on the player's ability to build a support ship that can defend itself and _maybe_ also create a role for a ship that may be slow, but can protect others by neutralizing missile barrages.

Guess I just want to actually be able to keep allied fleets alive during missions rather than watch everyone die and then slowly grind through the rest of the battle on my own.

**Comment by tehhowch** [comment] 2017-06-12 17:09
> outfits that combine anti-missile + jamming + decoys (can a ship spawn an object that draw/absorbs fire?)

see my post above:
>[I'm all for chaff and flare anti-missile turrets, which could cause (multiple) incoming projectiles to change targets, but those would need some changes to the current projectile code, because right now missile weapons have a single target that they either can track or temporarily cannot track, and all jamming can do is increase the chance that it flies straight ahead instead of track their target.](https://github.com/endless-sky/endless-sky/issues/2612#issuecomment-307597468)

In other words, even if a ship could spawn a shielding object, any existing missiles will not care about it unless it flies directly into them (normal collision code - it might as well be an asteroid). New missiles won't target it unless their parent ship decides to change targets and fire at it.

Regarding "secondary hardpoints": again, these -if defined- would only affect **newly-bought** ships. And, I normally find myself hurting for outfit space, not hardpoints, so adding additional hardpoints isn't going to make people more likely to use anti-missile or defensive gear. You've even stated so yourself:
>I never use anti-missile stuff because speed takes care of missiles well enough. And allows me to totally control a fight as a bonus
> I just don't see the point in sacrificing the weapons space.

Many folks agree with you, that the best anti-missile defense is overwhelming offense, to shut them down before they become an issue.

Regarding non-combat play: load a ship with A/M turrets and shield generators. You won't be prioritized as a target, but can still fly in front of your allies/escorts to take down incoming projectiles and provide missile defense.

**Comment by jafdy** [comment] 2017-06-12 17:58
I can only see this adding complexity. And that is really not the point, there are games that do "complex" much much better. With out a total rebalance this is never likely to be feasible.

**Comment by DamienThryn** [comment] 2017-06-13 15:32
What's the etiquette on threads like these - would you prefer they be closed once there's been a conversation or left open until a mod (or equivalent) tags/closes?

**Comment by Elyssaen** [comment] 2017-06-13 16:04
@DamienThryn, Michael (@endless-sky) is the owner/mod, and he does a sweep through periodically tagging. If an issue is looking pretty unlikely, he'll probably close it. I'm not aware of an etiquette beyond that, though. Think you should feel free to close it if you like, as it does seem the discussion has fairly decisively gone in one direction. Hope that's not discouraging.

**Comment by DamienThryn** [comment] 2017-06-13 16:29
Thanks @Elyssaen - and I'm perfectly happy to have ideas get shot down. Ideas (mine anyway) come cheap, the trick is figuring out which ones can actually be useful/implemented.

**Comment by Elyssaen** [comment] 2017-06-19 18:02
Great post, Forlarren – although whe you say 'crew hardpoint', I think you're moving behind what [hardpoint](https://en.wikipedia.org/wiki/Hardpoint) means.

What I'm coming to terms with, as a content-oriented kinda' person myself, is that the first priority is getting Endless Sky itself 'finished'. I think stronger support for total conversions is on the table, but right now:

- Michael's priority is 0.9.7, 0.9.8, etc.
- The main priority areas for other contributors are the Republic and Syndicate storylines, the [Project tab](https://github.com/endless-sky/endless-sky/projects) (just Mining and Flotsam) and the [Help Wanted](https://github.com/endless-sky/endless-sky/wiki/HelpWanted) page.

I'm guessing that making more flexible under-the-hood functionality for total conversions is probably a way down the priority list. When we get there, I'm absolutely on board with you that we should be talking about a) more general use of hardpoints (and types of ship space) and b) more flexible crew systems.

**Comment by DamienThryn** [comment] 2017-06-20 20:20
Yep I was also thinking that I ought to just build stuff, then put it out there for people to see what they like/don't like. 

So in the time I can spend on development, I'm trying to do mission content to get used to the feel and requirements. Stuff I can just make and post. Though if there are specific todo items in terms of basic missions/content I'm happy to work on that. Just need 'deliverables' since I'm inconsistently available right now.

**Comment by tehhowch** [comment] 2017-06-20 21:23
@DamienThryn go through the 0.9.x and 1.0.0 milestones... those are generally things that are going to get done and merged. If your implementation isn't chosen, you will have at least furthered the discussion on it and helped get a solution to the item into play.
Some initial easy-to-do missions would be like what I mentioned in #505 just a bit ago. You'll need to develop the fleets to go with those, and could even alter the events in the FW storyline to update those fleets based on what happened (e.g. plasma turret available means you can add some variants that have plasma turrets to the merchant's hunter fleet in FW and Neutral space).

**Comment by VonZorch** [comment] 2017-06-21 18:35
@DamienThryn Your real world analogy doesn't hold up.  An actual warship has it's defensive systems set at design.  In the real world a ships weapons do not change with a few exceptions, in particular the AN/SEQ-3 Laser Weapons System was designed to be able to bolt onto any unused patch of deck in about 30 minutes.  Any other changes are minor modifications or require several months in a shipyard.

I put at least one AM system on all my combatants but usually not on haulers.

**Comment by DamienThryn** [comment] 2017-06-26 20:30
I'm working through some ideas for rebalancing missile/anti-missile stuff that I'll test at some point when I have time - but in general I think that anti-missile systems should have longer range and greater power to justify their weight. 30 tons of anti-missile turret basically buys me partial protection from a ship launching 2 torpedoes at a time. But 30 tons of engines lets me outrun them almost every time.

I think that there is potential for re-balancing by doubling the firepower and range of anti-missile systems, but also more or less doubling the power of each individual missile. And I think that is possibly by tweaking outfits stats, so I'll explore further. 

But before that, I'll see what milestones I can contribute to in the nearer-term.

**Comment by Musaran2** [comment] 2017-08-09 22:03
Hardpoints could each have a maximum attachable mass.

Big ones would of course be meant for big guns, but small ones would be more suited for utility.

This would be a big change and make fitting more challenging, but would allow some nuances :
- Ships accommodating more attachments, but only smallish ones.
- Make "low-end" attachments still have use even when bigger, better ones are introduced.

**Closed** 2018-01-17 04:35 UTC
Labels: mechanics
