### ISSUE TITLE
Issues with warp capeble fighter

### ISSUE THREAD

**Issue by Illlin** [endless-sky/endless-sky#3348] opened 2017-12-03 19:17 UTC
When you sell all of the items in a simple fighter and install a warp drive there are some issues that can occure. After the first jump in the next system the fighter will get in a loop landing and takeing off on the planet. If you hold [J] to stop the jump the ship will never get ready to jump but if you recall your fighter it will get out of the loop but when it gets to the mother ship the game will crash.

**Comment by Pointedstick** [comment] 2017-12-03 19:21
Why not just buy an interceptor instead? Fighters aren't designed for warp travel. These sound like bugs, but they are perhaps not unexpected, lore-wise. :slightly_smiling_face:

**Comment by KiLEdEnNis** [comment] 2017-12-03 19:48
I still liked the idea of being able to have a fighter or drone as a mini flagship that can use hyperspace, I think it was possible way back and it kinda should be possible again

**Comment by tehhowch** [comment] 2017-12-03 20:48
Please share your game details, eg steam, GitHub master, etc

**Comment by Illlin** [comment] 2017-12-04 17:15
This issue was encounterd on the Steam version of the game [0.9.8] and tested on 3 different computers.
[Illin Tori.txt](https://github.com/endless-sky/endless-sky/files/1528076/Illin.Tori.txt)
Here is the save file used, not sure if it will help. From that point I depart, deploy the fighter, hold J to let it refule, it then gets stuck landing so I recalled it and when it gets back the the mother ship there was an instant crash.
Not sure where a crash report might be so here is errors.txt
[errors.txt](https://github.com/endless-sky/endless-sky/files/1528088/errors.txt)

**Comment by Illlin** [comment] 2017-12-04 17:20
I know this issue is unlikely to come up in normal game play as a warp capable fighter is useless, but I thaught it might be worth reporting.

**Comment by tehhowch** [comment] 2017-12-04 17:28
As a reference, when your escorts are out-of-system they will pick up their non-disabled escorts (carried ships) before jumping to meet up with you, and that behavior is very unlikely to be changed. (We could add a check to see if that carried ship is jump capable before waiting for it to board, but then we're working against the design of the game for edge cases.)

The "landing dance" can probably be resolved, and I'll see if I can reproduce the crash. Someone on Steam has a similar issue, but has failed to provide sufficient detail for me to be able to reproduce their issue.

**Comment by tehhowch** [comment] 2017-12-04 23:43
Alright, loaded your save using the current master https://github.com/endless-sky/endless-sky/commit/224e62f563a55fc57e20b2e851a945836378bd0f
1. Departed 
2. Deployed the Barb
3. Held J to align the fleet for a jump
4. Released J when everyone was ready, jumping into Sirius without issue
5. Tapped an arrow key to disable autopilot
6. Watched the Barb successfully land on Relic and refuel
7. Recalled the Barb to the flagship
8. (Fleet) Jumped to Procyon without issue

The reason your Barb was doing the "landing dance" is because your next jump was to an uninhabited system in which it would be stranded:
https://github.com/endless-sky/endless-sky/blob/224e62f563a55fc57e20b2e851a945836378bd0f/source/AI.cpp#L1333-L1342

I'll see if I can reproduce the crash on v0.9.8

**Comment by tehhowch** [comment] 2017-12-05 00:06
With v0.9.8 I can indeed reproduce the crash:
1. Departed
2. Deployed
3. Fleet Jumped
4. Barb refuels
5. Recall Barb
6. Barb docks successfully
7. Press J

This results in a segfault during the constructor for the Barb's EscortDisplay Icon:
`notReadyToJump(fleetIsJumping && !ship.IsHyperspacing() && !ship.IsReadyToJump())`
IsReadyToJump calls JumpFuel, and JumpFuel performs a `nullptr` dereference in line 1934, because this Barb has a Hyperdrive.
https://github.com/endless-sky/endless-sky/blob/97c1fae2e1a9ecec2d14cf44b34101f37e763b05/source/Ship.cpp#L1927-L1938

The responsible bits of code haven't been updated since v0.9.8 so my earlier replication attempt wasn't good enough, and by trying a bit more, I was able to reproduce the crash on https://github.com/endless-sky/endless-sky/commit/224e62f563a55fc57e20b2e851a945836378bd0f

**Comment by tehhowch** [comment] 2017-12-05 00:31
The crash is fixed in #3368 , and the "landing dance" is fixed in #3123

**Closed** 2018-11-20 20:10 UTC
Labels: mechanics
