### ISSUE TITLE
Enhancement request: Close error dialog boxes using <esc>

### ISSUE THREAD

**Issue by lifeyouristhis** [endless-sky/endless-sky#2869] opened 2017-08-01 07:21 UTC
As in title: make [esc] key close error dialog box instead sending to game menu.

**Comment by tehhowch** [comment] 2017-08-01 12:37
What errors are you getting?

**Comment by lifeyouristhis** [comment] 2017-08-01 12:53
> "You can press Escape or Control + W to close most dialogs and panels." in PlayerManual
FailBuy() / FailSell() Outfitter / Shipyard dialog messages.

**Comment by tehhowch** [comment] 2017-08-01 14:01
Hm, those are basic Dialog()s... which currently do not handle the Esc key.

**Comment by marphod** [comment] 2017-08-01 14:45
There are also cases where it would be nice if Escape were treated as 'cancel' (pretty much any cancel/ok dialog).

**Comment by tehhowch** [comment] 2017-08-01 15:14
Right now, setting up Esc as a cancel key doesn't really work well because Esc is mapped by default to the Show Main Menu action. To enable Dialogs to handle the Esc key, they would need to be made uninterruptible. Judging by the wiki comment, this is intended behavior for Esc (to serve as a cancel key).
Dialogs also don't handle the Ctrl + W "close window" request, but this can be added even without the uninterruptible setting.

**Comment by Bladewood** [comment] 2017-08-01 15:24
We can save on a world where a dialogue or conversation appears with esc.
I don't want to lose that ability.

**Comment by tehhowch** [comment] 2017-08-01 16:20
@Bladewood @lifeyouristhis both of you should be happy with the implementation in #2872 
Esc will close dialogs so long as it is not the "show menu" key, and dialogs can (still) be interrupted by the "show menu" key (which is Esc by default).

**Comment by endless-sky** [comment] 2017-10-13 23:45
Addressed by merging #2872.

**Closed** 2019-05-28 00:05 UTC
Labels: mechanics
