### ISSUE TITLE
Uninhabited Planet Visiting Colour

### ISSUE THREAD

**Issue by TheDeathStar3** [endless-sky/endless-sky#5712] opened 2021-02-08 01:50 UTC
**Describe the bug**
If you have visited all or none of the planets in Uninhabited systems than it still does not colour to show if it has been visited or not

**To Reproduce**
1. Go onto map and click/look at a Uninhabited system
2. Click on (has been visited) or (has not been visited
3. the system is not coloured even if you visit it or not.

**Expected behavior**
I expected that the system is coloured saying if I have visited the planets in it or not.

**Screenshots**
![Screen Shot 2021-02-08 at 12 41 15 pm](https://user-images.githubusercontent.com/54761256/107167012-d4a99480-6a0b-11eb-8069-4732519d5007.png)

**System (please complete the following information):**
 - OS: Mac
 - Game Source: Steam
 - Version: 0.9.12

**Link to save file**
I do not think this part is necessary

**Additional context**
You might realize that I have a plugin. I have checked the problem without the plugin and in a new pilot, And it still happens

**Comment by Amazinite** [comment] 2021-02-08 02:23
Duplicate of #5399. Fixed by #5402.

**Closed** 2021-03-07 21:42 UTC
Labels: duplicate
