### ISSUE TITLE
Spaceport vs. ship size

### ISSUE THREAD

**Issue by RedLucidity** [endless-sky/endless-sky#3864] opened 2018-07-28 23:07 UTC
Thought it might be interesting, for space ports that could only handle a max number of ships, and of sizes.. 

This would limit the numbers of ships landing all at once. Also Larger ships may need to deliver goods via shuttles or smaller ships, drones, requiring them to remain in space, as only the larger stations could accommodate them, where small stations would be more prevalent. The numbers of ships that can dock and leave would be small. affecting the time frames are each station. and or the numbers of parked ships. 

Shipyards could then be more accessible to large fleets but offer lower prices on goods. or cause massive fleets to delay to be able to off load all their goods. Also gives more reason for a ramscoop within settled space. 

This could also give rise to player built shipyards and trading stations and gathering of materials from around the galaxy. Perhaps espionoge and alien culture, missions to develop new types of stations..

**Comment by Amazinite** [comment] 2018-07-29 00:31
Duplicate of #3857

**Comment by ghoulavenger** [comment] 2018-07-29 00:33
Considering that players can land on planets regardless of whether or not they have ports at all I find this suggestion dubious at best. If you don't want to play a large fleet, don't play a large fleet.

On Ramscoops -- they're actually very useful in regular space, often affording at least one extra jump on long jump sequences. This saves effectively one game day where you would have had to land one jump sooner. Is this important? Depends on whether or not you're trying to compact the game days or not. But ramscoops are largely intended for the exploration of space, not really civilized areas (so depending on what you're doing you might want to swap that ramscoop for an extra fuel pod instead). As a secondary use ramscoops can help with things that use fuel as power source (like flamethrowers, afterburners and cloaking).

On player based stations and such: I'm actually for having a hideout of sorts, where you can store outfits and such. Currently the only way to do such is parking random ships with the outfits you want to store, which is clunky at best.

**Comment by jostephd** [comment] 2018-07-29 10:05
> On player based stations and such: I'm actually for having a hideout of sorts, where you can store outfits and such. Currently the only way to do such is parking random ships with the outfits you want to store, which is clunky at best.

Seconded, and an extension: I'd like to be able to buy an outfit from an outfitter that isn't on the planet I happen to have landed on, even if that means an S&H surcharge. (I'm sure there are details to work out.) Has that been suggested before?

**Comment by Zitchas** [comment] 2018-07-29 13:47
Having some kind of hideout / base of operations / starport locker that one could stash stuff in would be neat. I'd love to have that. 

In regards to ordering stuff that isn't available on-world: Yeah, that's realistic on the surface, but in practice  it would introduce a range of problems:

- How does one determine what is available or not? Does the game use just planets that the player has discovered? Just ones they can land on? Anything that they have the permissions to buy? All of these add a bunch of extra checks, and more importantly, a lot of complexity and room for confusing the player.

- Time. Realistically, any part we ordered should take at least a day to arrive (if it was the planet next door), probably a week or more if it was more than a few systems away. Players might get more annoyed waiting around for a part to arrive than they would going out to get it.

**Comment by jostephd** [comment] 2018-07-29 17:19
> How does one determine what is available or not?

Anything that's offered on any outfitter that appears in the player's map, is on a planet the player can land on, and is on a planet whose government is not at war with the government of the planet the player is on. For example, you shouldn't be able to order outfits from pirate worlds to Earth (not above board, anyway).

> Realistically, any part we ordered should take at least a day to arrive (if it was the planet next door), probably a week or more if it was more than a few systems away.

Adding a delay would make it difficult to mail-order outfits while a deadline mission is active. Is there any _gameplay_ reason to do this? Being (un)realistic isn't a primary concern.

**Comment by Pointedstick** [comment] 2018-08-01 02:01
Nah. This wouldn't add anything fun to the game. Crew salaries and the irritation of managing a zillion ships are their own natural limitations on fleet size.

**Comment by RedLucidity** [comment] 2018-08-02 17:08
I wasn't thinking player made shipping orders, but order missions. Planets asking for an amount of Mined materials needed to start building a station. Said station being owned by a government/faction. Where player owned stations, could just work the same as outfitters & shipyards currently. But the player gets a salary similar to a tribute, a stock option if you will. If we made it so that players could build a station with an outfitter, shipyard or trading post in a system it would add the building aspect to the game. I think it would be fun to build a Quarg ring style station in a uninhabited system someplace or unlock the mysteries of hyperlinks and wormholes to new unexplored galaxies.

A "storage locker" does seem appealing, but as mentioned that can be done with parked ships, which can move if needed to a different system.  

I think I read somewhere someone mentioning system defenses. These could also be setup to include the station or other orbital platforms, working like player owned ships that get disabled that stay in system though of course without the disabled part. Just the ability to assign then staying attribute or assign a system. Perhaps the player would need a carrier to place them in a system they want to put them in, if the defense system was small. If larger then would need to be built, ordered, or is a ship that transforms to a station after an amount of time. The UrsaPolaris plugin currently does this somewhat. 

The ship size characteristic could also be used via the game system to understand larger, smaller ships. Allowing for mods that use cargo space as hangers for 'smaller then' some ship size to be able to dock. Similar to fighters and drones on carriers. But allows for capital size ships to allow for small freighters or warships to dock, could also share resources for refueling or ammunitions. This would have the added bonus of large fleets of ships not having to be fully rendered on screen all the time when moving between systems, it would also reduce the need for every ship to have a jump drive or hyperdrive. Though that extra outfit space would need to be balanced. Not having to farm jump  drives for all the smaller ships would be a huge real-time saver. As the modules would take up a ships cargo space it would limit the amount of commodities that ship would be able to transport may also lessen Hull strength as the docking ports overall weaken the ship structure... large ships not being able to dock at some stations would also help to balance their over use as carriers. With player built stations, they would be able to build a station to accomadate the large ships, but that would also be more play and or mission driven.

**Comment by Pointedstick** [comment] 2018-08-02 17:57
Those are interesting ideas, but this is a bug tracker, not a place for stream-of-consciousness thoughts. Please take it to a forum or the Discord server (and also please close this issue).

**Closed** 2018-08-07 02:16 UTC
