### ISSUE TITLE
Container Transports sometimes block each other

### ISSUE THREAD

**Issue by CodeKatta** [endless-sky/endless-sky#8839] opened 2023-06-03 22:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If two container transport freighters overlap and they have to move somewhere it sometimes occurs that they form an 'X' and then don't budge an inch even though they obviously fire their engines.
Since I have several of those container transports (16, to be precise) I encounter this phenomenon quite frequently. You order your ships to go to a certain system and on the way there you almost always have two container transports that end up in this deadlock. 
If you position yourself strategically (a system with a wormhole or a planet/station where they have to refuel) you can even see it happen: the whole group of CT-freighters emerges from hyperspace and moves towards the wormhole/planet like [the caterpillars of the pine processionary](https://en.wikipedia.org/wiki/Pine_processionary). Usually there is no problem and the whole group makes it to its destination without any problems but every now and then a pair of CTs ends up in that 'X'-formation unable to break free without any outside intervention.
Now all 16 freighters have the same configuration (and I also changed certain things over time) so it's practically never the same pair that ends up in this deadlock and also replacing engines, shields, weapons, etc. hasn't had any effect AFAICT.
I also have other big and bulky ships (Hai and Wanderer freighters) but so far I haven't observed this behavior.

### Steps to Reproduce

1. Get a lot of container transport freighters and put them all in one spot (as close as possible, usually hitting 'hold position' as one departs a planet should suffice)
2. Order them to move across the galaxy (so that they have to refuel and/or pass a wormhole)
3. Rinse/repeat…
4. Profit (well, at least when they finally reach their destination)

### Expected Behavior

Uhm, to not get stuck and move normally like all other ships, I guess.

### Screenshots

Here they just want to enter the wormhole:
![Endless Sky_ContainerTransport_blocked_01](https://github.com/endless-sky/endless-sky/assets/26285588/a8f9fcf6-cbc1-489a-8f42-4d059dcd798f)

Here they emerged from the Quarg ringworld. I think they had to move a certain distance before entering hyperspace (all other ships left already):
![Endless Sky_ContainerTransport_blocked_02](https://github.com/endless-sky/endless-sky/assets/26285588/450f6cd1-8fab-4cd0-b6d0-9f598a790518)

A close-up of the whole situation:
![Endless Sky_ContainerTransport_blocked_03](https://github.com/endless-sky/endless-sky/assets/26285588/ab1cfdf8-7a9a-4942-80c3-77acbb8029bc)

An other one (it's always the same 'X'-formation):
![Endless Sky_ContainerTransport_blocked_04](https://github.com/endless-sky/endless-sky/assets/26285588/97d9516d-b130-4f81-8b68-1baefd5a63e9)

Here they get scanned by a Remnant ship. Not that it would help very much:
![Endless Sky_ContainerTransport_blocked_05](https://github.com/endless-sky/endless-sky/assets/26285588/26856f02-03ee-486d-95b3-ceff4b29e86c)

### Operating System

Windows 10 Pro version 22H2 build 19045.2965 (as mentioned in #8781 I observed this in the most recent Android and Win64 versions, so it doesn't seem to be constrained to a certain OS)

### Game Source

GitHub Releases

### Game Version

v0.10.0

**Comment by lumbar527** [comment] 2023-06-03 22:53
Are they drifting, or do they just stop (not that this question makes a difference)?

**Comment by CodeKatta** [comment] 2023-06-03 22:58
> Are they drifting, or do they just stop (not that this question makes a difference)?

Nope, completely stationary, even though their engines are firing.

**Comment by UnorderedSigh** [comment] 2023-06-04 16:53
Can you post a save file? Those are obviously not stock ships since they have remnant engines (which include reverse thrusters).

I suspect some odd interaction with AI::DoScatter, or the ship is somehow using its forward and reverse engines at the same time. I would need a save to debug this.

**Comment by CodeKatta** [comment] 2023-06-06 00:08
Hm, interesting. This could well trigger this behavior but it never happens when they are alone (i.e. the other CT is far enough so that they don't overlap) or overlap with an other type of ship. When this deadlock occurs, there are always at least two container transports involved, which means they must somehow interact in some fashion.
I noticed this when I hit 'hold position' as soon as I departed from a planet. This way they don't scatter but stay together in a big ball o'ships (the 16 container transports are also somewhere in there):
![Endless Sky_Ball_of_Ships_2](https://github.com/endless-sky/endless-sky/assets/26285588/4f0ea9a3-7155-4228-821e-88fc922e2113)
Now if you order them to go to an other system they usually keep this formation and if the have to move within a system (towards a planet/wormhole) this 'blocking-each-other' sometimes occurs.

I tried to recreate this behavior of the CTs so I took them to the western Ember Waste (Cardea, Insitor, … [since there is almost no interference from other ships, hostile or otherwise]) and tried to place them as close together as possible. For this I used the system map as you can take the dots representing the planets/suns as point of reference.
![Endless Sky_ContainerTransport_blocked_Insitor](https://github.com/endless-sky/endless-sky/assets/26285588/5aaa8e9b-9b02-4e1c-beb0-2bb2b198618f)

The result looked something like this:
![Endless Sky_ContainerTransport_blocked_06](https://github.com/endless-sky/endless-sky/assets/26285588/5f3d1c0b-b150-4503-80d5-e5469c8ae690)
Yep, those are 16 container transports, one on top of the other. Well, more or less.
As you set them in motion (e.g. send them to Cardea so they have to use the wormhole) one can already see that there are even two groups that form the aforementioned 'X' (in the upper 'X' are even three ships):
![Endless Sky_ContainerTransport_blocked_07](https://github.com/endless-sky/endless-sky/assets/26285588/c809a611-58cd-4e6e-a70d-98e0ccb538a8)
After a while the whole setup looks like this:
![Endless Sky_ContainerTransport_blocked_08](https://github.com/endless-sky/endless-sky/assets/26285588/ee311a56-e2ed-47e4-89ba-b88e9dd7d3ff)
Sometimes it only takes a few seconds for them to 'disentangle' and in other instances it can take minutes (especially if there's no interference). On the screenshots it looks as if only one of them has its engines running but actually they fire them alternately and if one looks closely one can see a flicker (in the game).

So far I couldn't recreate this phenomenon with any other type of slow ship and if I remember correctly this deadlock occurred even before I made any changes to the container transports.
And here is their current configuration (all 16 are the same):

> ship "Container Transport"
	name "Moneymaker-01...16"
	sprite "ship/container transport"
	thumbnail "thumbnail/container transport"
	uuid adb7e638-bce7-4bbb-84d8-64dd0a4be5c5
	attributes
		category "Heavy Freighter"
		cost 9200000
		mass 880
		bunks 18
		"cargo space" 550
		drag 17.6
		"engine capacity" 85
		"fuel capacity" 600
		"gun ports" 2
		"heat dissipation" 0.6
		hull 8000
		"outfit space" 410
		"required crew" 6
		shields 3500
		"turret mounts" 5
		"weapon capacity" 180
	outfits
		"A375 Atomic Steering"
		"Banisher Grav-Turret"
		"Crystal Capacitor" 2
		"Forge-Class Thruster"
		"Jump Drive"
		"Ka'het Annihilator Turret" 2
		"Ka'het MHD Generator" 3
		"Laser Rifle"
		"Point Defense Turret"
		"Quantum Keystone"
		"Reverser (Asteroid Class)"
		"Small Heat Shunt"
		Supercapacitor
		"Systems Core (Tiny)"
		"Wanderer Ramscoop" 2
		"Warder Anti-Missile"
	crew 7
	fuel 600
	shields 3500
	hull 8000
	position -756.47936 -809.94587
	engine -20 195.5
		zoom 1
		angle 0
		under
	engine 20 195.5
		zoom 1
		angle 0
		under
	gun -23.5 -182
		under
	gun 23.5 -182
		under
	turret 0 -90.5 "Ka'het Annihilator Turret"
		over
	turret 0 -40.5 "Point Defense Turret"
		over
	turret 0 9.5 "Banisher Grav-Turret"
		over
	turret 0 59.5 "Warder Anti-Missile"
		over
	turret 0 109 "Ka'het Annihilator Turret"
		over
	leak leak 40 50
	leak flame 30 80
	leak "big leak" 50 30
	explode "huge explosion" 20
	explode "large explosion" 35
	explode "medium explosion" 25
	explode "small explosion" 15
	"final explode" "final explosion large" 1
	system Zubeneschamali
	planet Zug

**Comment by UnorderedSigh** [comment] 2023-06-06 02:56
The source of the problem is more clear when you add reverse and steering engine flares to the Moneymaker ships . The ships are thrashing between trying to turn away from each other and trying to turn towards their destination. In this case, they want to fly right, but they can't face that way.

https://github.com/endless-sky/endless-sky/assets/116329264/28005b73-927e-4ca9-a403-97ecbf54a13f

There are two behaviors that are fighting against each other.

1. If a ship has reverse thrusters, it will come to a full stop and then point in the direction it wants to go.
2. If two ships are close together, they'll turn away from one another.

The bigger bug is in the second step. The ships will keep turning farther and farther away because they don't check if they're already facing away from one another. If I fix that, then the problem goes away. (The logic for the first step is also wrong, but not dead-wrong.)

I will open a PR shortly.

**Comment by UnorderedSigh** [comment] 2023-06-06 02:59
This file has my modified "Moneymaker" ships.

[Friction Diction~3024-04-06 change containers.txt](https://github.com/endless-sky/endless-sky/files/11659496/Friction.Diction.3024-04-06.change.containers.txt)

**Comment by UnorderedSigh** [comment] 2023-06-06 03:46
There we go. Your fix is in #8858.

**Comment by CodeKatta** [comment] 2023-06-06 08:32
> twitching-containers.mp4

Yes, that's exactly the aforementioned problem. With all thrusters visible and in slow motion it's even more apparent.
I just found it strange that it only happened with container transport freighters and not other types of ships since I also have other slow and bulky vessels with reverse thrusters. But they never ended up in such a deadlock. Any deliberate attempts to recreate this behavior with other ships were also unsuccessful so far.
And as far as I remember this problem appeared as soon as I got the container transports, i.e. with their original config (but I have to check that one again).

And thanks for your quick response.

**Comment by CodeKatta** [comment] 2023-06-07 17:28
> And as far as I remember this problem appeared as soon as I got the container transports, i.e. with their original config (but I have to check that one again).

OK, I checked it again and they indeed show the same behavior, although not as often as with the other configuration:
![Endless Sky_ContainerTransport_orig-outfit_blocked](https://github.com/endless-sky/endless-sky/assets/26285588/25ecd880-f69d-4b76-bda8-b5702bb01fec)

Bought twenty new container transports on _Hephæstus_, equipped them with a jump drive on _Buccaneer Bay_, and then took them to _Cardea/Insitor_ where I had them fly back and forth as closely packed as possible (and on some occasions, this deadlock occurred as well).
With the new changes this is probably irrelevant anyway, but I just had to get this off my back 😁

**Comment by UnorderedSigh** [comment] 2023-06-07 17:30
> OK, I checked it again and they indeed show the same behavior, although not as often as with the other configuration:

Your post has a critical ambiguity. Are you saying that my new changes don't fix the problem? Or are you saying that the default Container Transport ship has the problem in a released version of Endless Sky?

**Comment by CodeKatta** [comment] 2023-06-07 17:57
> Your post has a critical ambiguity. Are you saying that my new changes don't fix the problem? Or are you saying that the default Container Transport ship has the problem in a released version of Endless Sky?

Sorry, that wasn't my intention. I meant of course the latter.
I said in one of the posts above that I was pretty sure that the default CTs also showed this behavior but that was somewhat longer ago. So any tests in that regard had to be done with the non-fixed version.
I just wanted to make sure that I didn't misremember and was talking nonsense.

With your current changes this behavior shouldn't manifest itself anymore, no matter which configuration you use for your propulsion system.

So thanks again for your great work.

**Comment by UnorderedSigh** [comment] 2023-06-07 18:04
>  I said in one of the posts above that I was pretty sure that the default CTs also showed this behavior but that was somewhat longer ago. So any tests in that regard had to be done with the non-fixed version.
> With your current changes this behavior shouldn't manifest itself anymore, no matter which configuration you use for your propulsion system.

Ah, good. It is nice to have that clarification for people who are only skimming the comment chain.

**Comment by UnorderedSigh** [comment] 2023-06-07 18:45
I think the cause is the novel combination of: phenomenal turning rate, good reverse acceleration, and poor forward acceleration. Keep in mind, though, that is the perfect combination for invincible battleships that have long-range guns. So, this may be a broader issue that is under-reported.

**Comment by CodeKatta** [comment] 2023-06-07 20:43
> I think the cause is the novel combination of: phenomenal turning rate, good reverse acceleration, and poor forward acceleration.

Yepp, I guess this somewhat unorthodox configuration exacerbated the effects of this bug (although the current config has still better fwd. accel. than the original one) . With the default version you had to be really determined to cause this behavior (as you already knew that it can occur) and painstakingly stack one ship on top of the other to get some results (eventually).
No one does that (and neither did I) but with the current configuration preventing the scattering of your ships ('hold') as soon as you left a planet/station and proceeding from there was enough to provoke this behavior on a regular basis. With the vanilla version (and some other configs) it's probably rare enough to fly under your radar. That's why I only noticed retrospectively that the original version might have had some issue as well.

> Keep in mind, though, that is the perfect combination for invincible battleships that have long-range guns. So, this may be a broader issue that is under-reported.

Indeed, or no forward acceleration at all, like the **[Deadly Battle Station of Death™](https://user-images.githubusercontent.com/26285588/243503578-4f0ea9a3-7155-4228-821e-88fc922e2113.png)** with dozens of "turrets". In the depths of that unholy mess even a container transport can function as one such "turret".
Although with no secondary weapons and practically only continuous fire primary weapons (lasers _et al._) it's more of a  **[Disabling Battle Station of Disablingness™](https://www.youtube.com/watch?v=BjG1o6UOaKo)** 😁

**Comment by UnorderedSigh** [comment] 2023-06-09 23:46
In case someone still thinks this bug is unconfirmed, here is your confirmation:

https://github.com/endless-sky/endless-sky/assets/116329264/28005b73-927e-4ca9-a403-97ecbf54a13f

It is almost hypnotic.

**Comment by CodeKatta** [comment] 2023-06-10 16:53
And it seems they still do (two consecutive screenshots):
![Endless Sky_ContainerTransport_blocked_v0 10 2_01](https://github.com/endless-sky/endless-sky/assets/26285588/0fb7d87b-3800-4394-8812-b8c81c6d7251)
![Endless Sky_ContainerTransport_blocked_v0 10 2_02](https://github.com/endless-sky/endless-sky/assets/26285588/c7ba5b28-8c1d-4bf0-aee6-75b03fc99477)
You can see the alternate firing of their engines and the twitching if you switch back and forth between the two images.
I did this test under the same conditions as before¹ just with the newest [continuous build](https://github.com/endless-sky/endless-sky/releases/tag/continuous) (226df69) so the problem still seems to persist.

----------------------------------
¹go to _Cardea_, stack them as closely together as possible, send them to _Insitor_ and back again as often as necessary

**Comment by UnorderedSigh** [comment] 2023-06-10 16:54
My fix hasn't been merged yet, so I would expect the problem to keep happening.

**Comment by CodeKatta** [comment] 2023-06-10 17:41
> My fix hasn't been merged yet, so I would expect the problem to keep happening.

Oh OK, my bad. Should have paid more attention.

Btw, here are two more screenshots with a pair of Palavrets doing the X-twitch (so it's not just container transports):
![Endless Sky_Palavret-wormhole_blocked_v0 10 2_01](https://github.com/endless-sky/endless-sky/assets/26285588/2bf69ec1-26ac-4391-bb87-c49f0ceaa385)
![Endless Sky_Palavret-wormhole_blocked_v0 10 2_02](https://github.com/endless-sky/endless-sky/assets/26285588/7ed52c02-ec8d-40fc-be59-36b98f4557e3)

They were among the first to emerge from the wormhole but then immediately got stuck in that position. That container transport in the lower left corner is the last ship to pass through the wormhole, so not even several ships crossing over them (which sometimes helps) could shake them out of their deadlock.

On a related note, is there a possibility to send a ship to a position that is already occupied by an other escort? If you hold the mouse toggle button and then right click on said position the selected ship doesn't move there but tells you instead that it is following the ship you just clicked on. So in other words, ignore that other ship at that spot and simply move to the position you marked with your right click. Currently you have to use the [system map](https://user-images.githubusercontent.com/26285588/243502689-5aaa8e9b-9b02-4e1c-beb0-2bb2b198618f.png) as a workaround.

**Comment by UnorderedSigh** [comment] 2023-06-10 20:01
> On a related note, is there a possibility to send a ship to a position that is already occupied by an other escort?

Not that I know of. Actually, the DoScatter() function is supposed to prevent two ships being closer than 20 pixels (unless they're rotated differently or moving differently).

**Closed** 2023-06-13 12:41 UTC
Labels: bug, unconfirmed

**Comment by UnorderedSigh** [comment] 2023-06-13 21:12
My fix was merged, so this should no longer occur in the master branch. I am somewhat saddened by that, because I found the twitching ships absolutely mesmerizing. It's nice to have one less bug, though.
