### ISSUE TITLE
Hyperspace Jump Audio Map Bug

### ISSUE THREAD

**Issue by McloughlinGuy** [endless-sky/endless-sky#5817] opened 2021-03-28 23:39 UTC
**Describe the bug**
When you open the map during a hyperspace jump, the sound of the hyperspace jump will continue playing while the map is open. When you close the map the sound will finish itself if it was still playing when you closed the map, or if it wasn't still playing when you closed the map their will be no sound at all for the rest of the jump
**To Reproduce**
1. Do a Hyperspace Jump
2. Open the map as soon as the sound starts to play
3. Wait a few seconds for the sound to finish
4. See Error

**Expected behavior**
If you kept the map open long enough, the sound will not play at all for the rest of the jump. If you didn't, it will be slightly offset.

**Screenshots**
Its an audio glitch. You can't take a picture of sound.

**System (please complete the following information):**
I run the game on Windows using Steam. My version is the version you would get if you went to steam and downloaded the game right now, except it has the emerald sword even though I got rid of the continuous build.

**Link to save file**
My save file does not need to be included in order to get this glitch.

**Additional context**
Has the Emerald Sword been added outside of beta yet? Because that would answer a few questions I have. After I uninstalled and reinstalled the game to get rid of the continuous build, the Emerald Sword was still there, maybe because I had a save file where I still had the emerald sword.

**Comment by Amazinite** [comment] 2021-03-29 02:14
Duplicate of #351.

**Closed by Amazinite** 2021-03-29 02:14 UTC
Labels: duplicate
