### ISSUE TITLE
It would be nice if we could override outfit license requirements using mods

### ISSUE THREAD

**Issue by wzimrin** [endless-sky/endless-sky#5884] opened 2021-04-24 00:38 UTC
I was trying to make bombardment cannons purchasable via a personal tweak mod.  I could add them to outfitters easily enough, but I couldn't get rid of the heliarch license requirement.  The docs suggest that adding a license in a new file ought to override the existing licenses, but that definitely didn't work (they just required both heliarch and coalition licenses), and treating them like outfitters and using "clear" was even worse (they then needed coalition, heliarch, and "clear" licenses).

Make them work like outfitters and respect the clear directive.  It handles my use case cleanly, and the only way it would break existing code/plugins is if someone is currently using "clear" as a license name.  Code-wise, it should be pretty easy -- if the "license to add" is "clear", clear the licenses array instead of pushing the new license to the back.  I'd do it myself, but I couldn't get stuff to build on mac.

**Comment by tehhowch** [comment] 2021-04-24 01:17
Please use the issue template.

Closing as a duplicate of https://github.com/endless-sky/endless-sky/issues/3907

**Closed** 2021-04-24 01:17 UTC
Labels: duplicate
