### ISSUE TITLE
Wormholes added by Postverta reveal event are doubled up

### ISSUE THREAD

**Issue by shawnc722** [endless-sky/endless-sky#6681] opened 2022-04-04 03:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The two wormholes added by the `Postverta reveal` event seem to be added twice; pressing `l` in any of the four systems they show up in says there's more than one planet to land on, and lets you toggle between two identical wormholes. They seem to be in the exact same spot and both work fine, so maybe they've just been added twice? I didn't spot any issues in the remnant data files, but I'm not familiar enough with the game's engine for that to mean much lol. 

### Steps to Reproduce

1. Go to Prosa
2. Press `l` twice

### Expected Behavior

Other wormholes (tested on the one in Edusa) have only one entry; the "more than one planet available to land on" message doesn't appear if they're the only landable object in the system and pressing `l` more than once doesn't switch landing targets. These wormholes should behave the same way.

### Operating System

Windows 10 Home 21H2 build 19044.1586

### Game Source

GitHub Releases

### Game Version

Commit 469b32f

**Comment by shawnc722** [comment] 2022-04-04 04:35
Something that may be related or may deserve its own issue: the spaceport description of the station on Esquiline is also doubled up: 
![image](https://user-images.githubusercontent.com/45184146/161474521-404bc25d-19a3-4cd6-acb7-6fd8570c5995.png)

**Comment by tehhowch** [comment] 2022-04-04 04:41
Closing as a duplicate of the pinned issue: https://github.com/endless-sky/endless-sky/issues/3746

**Closed** 2022-04-04 04:41 UTC
Labels: duplicate

**Comment by shawnc722** [comment] 2022-04-04 04:54
Oh my bad, I didn't think this was the same bug since I haven't closed the game at all since before the mission that activates the Postverta reveal - unless alt-tabbing counts.
