### ISSUE TITLE
Esquiline Spaceport

### ISSUE THREAD

**Issue by TheGiraffe3** [endless-sky/endless-sky#10309] opened 2024-07-10 13:27 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

In the spaceport on Esquiline, instead of being what it is 
<details>
<summary>supposed to be,</summary>
Although the facilities here are basic, the Remnant cafeteria boasts a food dispenser that is available at any time, along with a mesmerizing view of the clouds outside. Occasionally a void sprite will pass in front of the window, much to the delight of everyone.
</details>
the spaceport just shows "spaceport" as the description.

### Steps to Reproduce

With the provided save file, use the flagship to go land on Esquiline. Go to the spaceport and see the bug.

### Expected Behavior

The description is what it is supposed to be.

### Screenshots

![Screenshot](https://github.com/endless-sky/endless-sky/assets/145969603/fdfae629-1d93-4414-a6d2-4fa88759d629)

### Link to save file

[Asiah Racer.txt](https://github.com/user-attachments/files/16162810/Asiah.Racer.txt)

### Operating System

MacOS Ventura 13.6.7

### Game Source

GitHub Releases

### Game Version

commit b2e805b

### Additional Information

I have a way to fix this.
EDIT: #10311.

**Comment by warp-core** [comment] 2024-07-10 14:32
I think this was caused by: 70130c7
I'm guessing it's because the line `add spaceport "text"` is passed to `Paragraphs::Load` which expects the text to be at index 1, but it's actually at index 2 (because of the `add` token), and this method does not check for that.
https://github.com/endless-sky/endless-sky/blob/b2e805bdec73ab987d5d40e2ed87864ec3e2005f/source/Paragraphs.cpp#L26-L35

In this case, it is not strictly necessary to `add` the spaceport description, as there doesn't seem to be any text in the spaceport description prior to this, and I don't think anything else in the vanilla game uses `add spaceport`, the same code is involved in handling planet descriptions, and `add description` is used many times.

For example, on Rand:
[warp core add descriptioin tes.txt](https://github.com/user-attachments/files/16163619/warp.core.add.descriptioin.tes.txt)

**Comment by TheGiraffe3** [comment] 2024-07-10 14:35
I'm not sure what you're saying, but okay. So does that need a code change, or just #10311?

**Comment by warp-core** [comment] 2024-07-10 15:23
The specific problem with the spaceport on Esquiline seems like it can be resolved by simply removing `add` from the change in the event, with no adverse effects.
However, the change that resulted in that event no longer working as expected also causes problems elsewhere. And, those problems cannot be corrected the same way as this one.

**Comment by TheGiraffe3** [comment] 2024-07-10 15:26
> The specific problem with the spaceport on Esquiline seems like it can be resolved by simply removing add from the change in the event, with no adverse effects.

So the PR would fix that.

> However, the change that resulted in that event no longer working as expected also causes problems elsewhere. And, those problems cannot be corrected the same way as this one.

Where else?

**Comment by warp-core** [comment] 2024-07-10 22:51
> > However, the change that resulted in that event no longer working as expected also causes problems elsewhere. And, those problems cannot be corrected the same way as this one.
> 
> Where else?

Anywhere that uses `add description <text>` no longer works correctly, it will currently only add a line with the word "description" to the end of the existing planet description, instead of adding `<text>` to it. See: the description of Rand in the save file I linked.

**Closed** 2024-07-11 22:41 UTC
Labels: bug
