### ISSUE TITLE
Worldship farming is needlessly cruel

### ISSUE THREAD

**Issue by Wyrdean** [endless-sky/endless-sky#8390] opened 2023-02-17 03:04 UTC
### Problem Description

After capturing a Dreger, a player's next step in the capture tier list would be to capture a worldship, however, based on the math, a player would have to wait 2.5 *hours* per *chance* to capture a 577 world ship with a jump drive, the only jump capable worldship within the capture range of a capture optimized dredger.

2.5 hours is quite a long time, as there remains the very likely chance the WS simply jumps out immediately, only staying within the system for a second at most. 

Especially when it requires constant focus to make sure it isn't mistaken for another WS, that has either way too much crew or lacks a JD, and thus ignores it by mistake.

Especially as it requires the player to get lucky enough for one to spawn,  see it, get to it before it leaves, disable it - and don't kill it by mistake. The ships are not very durable and often have several escorts to protect them, leading to crossfire.

And finally, even if the player did everything right, there's another step that requires luck: not rolling high on crew, as, if it did, there is nothing the player could do to capture it, even with a maxed dredger.

There is quite a lot that can go wrong, and if it did, that's another 2.5 hours between sightings based on the math:
One large raid, every 20000 frames / 60 frames in a second, = once every five minutes, * 28 due to it being a 1 in 28 chance of rolling the ship out of the fleet, = about 2.59 hours between sightings.

### Related Issue Links

https://discordapp.com/channels/251118043411775489/308902312741568512/1075760091829116958
I farmed a worldship, and it took 5 hours from the start, including preparation. I had three sightings in that timeframe, which is luckier than average, and got fairly lucky several times over that I didn't kill the final worldship that I ended up capturing. 

### Desired Solution

Make the fleet more common, and the ship itself more common within the fleet. 

The fleet only appears in two systems, once every five minutes at the most common, and once every 8 at the least. 
Once every minute and a half, to every three minutes, would be much more reasonable

Lower the weight of the other ships in the fleet, in order to make the weight of the worldship 1/16 from 1/28. 
The ship will still be uncommon, it will still be very rare, it will only appear on average every *24 minutes*
I think this is still too long of a wait, considering how likely it is to die, but it is still a massive change from 2.5 hours *per*, so I will leave it still awfully rare.

### Alternative Approaches

I could leave it as it is currently, where it is as a solid contender for the most unlikely to spawn ship in the whole game.

I could make it more common, to the point it is only a bit less common than the omnipresent dredger, this would be my preferred solution, which I think might prove too controversial to actually put in the desired solution section.

Or a balance between the current diamond in the pig trough and the proposed diamond 250 meters underground. You know where it is, you'd just have to spend a few weeks digging.

### Additional Context

While capturing may be overpowered, there are other PRs that seek to solve this.

**Comment by Saugia** [comment] 2023-02-17 03:42
We are not here to promote a "capture ladder" for the game. Worldships *should* be very hard to capture. In the future, it will be possible to obtain one in an Exile campaign. Otherwise, the current rate of them is entirely intended, and we have had many debates on it.

**Comment by Hurleveur** [comment] 2023-02-17 06:39
Honestly, worldships could just not be cappable and it wouldnt be an issue.
Not everything needs to be obtainable indeed -but- if you want an easy world ship what you do is just take one of the 3 from the wanderer story, not just get it for free without consequences.
It then becomes a meaningfull gameplay decision.

**Comment by Hurleveur** [comment] 2023-02-17 06:42
Also the next step in capping after the "dredger" is not the 577, it's an Echo-Galleon. But that should also be a meaningfull decision: do you want to war Quarg over it?

**Comment by ziproot** [comment] 2023-02-17 15:19
If you want to get jump enabled 577 world-ships, it's in the korath home fleet. It should appear once every 612 seconds, which is a little over 10 minutes, at the Kor En'lakfar system.

**Comment by Luuiscool4567** [comment] 2023-02-19 17:11
Least genocidal captain. Somebody CRY for the children. PLEASE.

**Comment by movingpictures** [comment] 2023-02-19 22:55
I fail to see how this is a problem. Is a world-ship an objective in some mission? No? Then it's a non-problem.

**Comment by binaryspica** [comment] 2023-02-20 15:34
Not all ships are allowed to be captured. Although it is cheap that there is a ship that could be captured but unable to obtain.

> Least genocidal captain. Somebody CRY for the children. PLEASE.

Children, yes, but not pirate. The Korath Exile faction is no more than a group of mere pirate, after all. Destroying them only makes the galaxy better, as destroying human and hai pirate does. You will remember that there is the korath civilian faction, as well.

**Comment by Hurleveur** [comment] 2023-02-20 15:58
They're providing food for the civilians.
The only one where I'm sure it'd be best to not have them is FL

**Comment by binaryspica** [comment] 2023-02-20 17:08
Perhaps, and I don't forget the fact that they have low on resource either. But it does not also means the human are allowed to suffered by the exiles.

Anyway, before there is the civilian faction among Korath, I am eager to destroy every single korath exile ships to death, not just disable. This include worldship as well, and I was concentrate on their destruction if I could. I am half belive that I am the most infamous korath killer on the history except for someone with WMD.

Back to the topic, isn't it just enough to increase the numbers of minimum crew if it is really not meant to captured? Something barely able to do but hard to find one that is able to move back to the human territory seems weird.

**Comment by roadrunner56** [comment] 2023-02-21 23:28
As stated above this is a non-issue and is entirely intended behavior. I'm closing this as it's not going to get 'fixed' anytime soon.

**Closed by roadrunner56** 2023-02-21 23:28 UTC
Labels: balance, unlikely
