### ISSUE TITLE
Feature Request: Fighter Bays as Outfits

### ISSUE THREAD

**Issue by rktaylor** [endless-sky/endless-sky#692] opened 2016-01-19 04:37 UTC
In the EV series, you could buy fighter bays for non-carrier ships, or remove them from carriers to free up outfit mass. I've seen some folks request stronger fighters, or increased fighter capacity for ships like the Bactrian (it does seem odd that an Aarie can hold 2/3rds the fighter capacity of a city-ship), so this might be a reasonable solution. 

Suppose each bay could hold and supply 2 fighters, then the Aarie would begin with one fighter bay outfit, the Bactrian 2, etc. and captains could choose to buy carriers and strip out their bays for range, cargo, extra reactors, etc.

**Comment by natangold** [comment] 2016-01-19 06:15
Mule has space to carry one fighter. One bay = one fighter?

**Comment by jafdy** [comment] 2016-01-19 08:22
One bay = One fighter seems like a good idea and all round I would like more fighter bays but the problem is working out where they will launch from. To the best of my knowledge fighter bay positions are currently hard coded in.

**Comment by thenerdfreak** [comment] 2016-01-19 12:55
Could just add some little files of coding that make all fighters launch from center of the ship. who pays attention to where fighters launch from anyway?

**Comment by endless-sky** [comment] 2016-01-19 14:18
The biggest issue I see with this idea is that most people already consider
fighters pretty useless, and if the game is changed so that fighters also
cost a significant amount of outfit space, that makes them even weaker.
(For example, if you could sell the fighter bays in a Bactrian to make
space for another reactor or several shield regenerators, I don't think
anyone would keep the fighter bays.)

**Comment by rktaylor** [comment] 2016-01-19 16:35
Maybe not a huge priority--something that could be played around with after you've made more progress with story and universe-building--but I think it would be pretty cool to pair fighter bay outfits with re-balanced fighters.

Fighters don't need to be tough, but if a fighter bay costs 50 outfit space I could basically turn a Bactrian into a hive with dozens of them, and then suddenly they're useful. Regardless, I think there has to be some way for fighters to be as useful in ES as they were in EV.

**Comment by DingusShingleton** [comment] 2016-01-19 20:03
You could have fighter bay as an outfit--- but let some ships have fighter bays built in. Makes enough sense, on some ships the bay is literally built into the hull of the ship, and therefore isn't removable.

**Comment by rktaylor** [comment] 2016-01-19 20:10
I mean, if we're looking at physical intuition, you could always seal off a fighter bay and put a bunch of batteries in it.

**Comment by DingusShingleton** [comment] 2016-01-19 20:24
...dang it. You're right, I can't fluff my way out of that one.

One issue I just thought of though, is that the mass of the two fighters currently in game are over 100 tons. Not sure how that translates into shipboard mass, but intuitively it doesn't make sense to put a 100 ton fighter into a 50 ton fighter bay, and if the fighter bay was 100 tons I'm not sure that would be worth it. Seems like it would be hard to balance. I do favor fighterbay outfits as an idea though.

**Comment by Pointedstick** [comment] 2016-01-19 20:30
The problem with fighter bays as outfits is that it opens the door to ridiculous scenarios like fighters with no weapons that can fit a fighter bay. You could do that kind of thing in the EV games. I like having fighter bays being built into ships. It helps differentiate them. The only thing that's really needed is to make fighters useful…

**Comment by rktaylor** [comment] 2016-01-19 20:54
So the real discussion here is balance:

How do we make fighters that aren't garbage, have reasonable specs, and fit into a customizable outfit system?

Perhaps we could reduce the mass of fighter components. If a fighter hull is 20 tonnes (reasonable, that's the mass of an F-15), it could sport a single blaster (5 tonnes?) or missile launcher (10 tonnes). Then we'd need thrust, steering, and battery to come in at ~20tonnes. 

The Dagger is a good case study. It's propulsion system costs 29 tonnes. The fuel cell, however, weighs far too much (30 tonnes). Why should a fuel cell weigh more than the damn hull? If we follow the Korath precedent, it doesn't need a shield generator either--shields should be resupplied on the mothership (as should weapons, like in EV/EVO/EVN).

If we took those very low-power systems and trim their requirements, we could build a fighter that makes sense:

--Hull 20 tonnes
--Steering 5 tonnes
--Thrust 10 tonnes
--Two blasters or 1 missile launcher 10 tonnes
--One battery or low-power fuel cell 15 tonnes

Then we have a fighter that's 60 tonnes.

If we make a fighter bay have a capacity of 150 tonnes, then it makes sense that the Aerie (whose hull is 1900 tonnes) could have one of these, and the Bactrian could have two. In this way, you'd have to make a trade off like "Do I want a good battery and a fission reactor, or do I want a fighter bay?" that would fit into different outfit styles.

For example: when I'm fighting the Korath, my weapons loadout is entirely energy weapons and heavy shields. So I'm looking at 3 Wanderer shield generators and 3 Wanderer Dark Sun reactors on a Bactrian. That makes sense, since the Korath use energy weapons and have terrible shield recharging, so you can just fly away, recharge shields, and come back to chip away again.

But if I'm fighting a Republic Carrier, I might want a Bactrian loadout with three fighter bays to keep those pesky drones off my ship, meanwhile I can put torpedos on the Bactrian to handle the Carrier. In that way, fighters/drones become DPS multipliers, while the mothership becomes a tank of sorts.

**Comment by rktaylor** [comment] 2016-01-19 20:58
In this scenario, we'd have "Fighter Bays" as an outfit that increases a new parameter, "Fighter Capacity" (analogous to "Weapons Capacity.") The captain can then customize a fighter loadout to maximize on that fighter capacity. Maybe I want a swarm of fast-moving missile drones? Or maybe I want a beefy, shield-generator-equipped bomber that takes twice as much space?

The customizability then is solved.

The only real problem then is micromanagement. If there's some way to save ships pre-sets in the Outfitter, it would make restocking on fighters a lot easier. (Also would make equipping a "customized loadout" on mass-bought escorts much easier, i.e. "I want my Ospreys to have more than 4 jumps of fuel ffs.")

**Comment by natangold** [comment] 2016-01-19 21:02
What about "bay ports", similar to gun ports? Have Mule, Aerie, Bactrian, Carrier, and Cruiser begin with x bay ports, then sell three separate outfits: "fighter bay", "drone bay", and "bay port". The first two achieving the same result as the currently hard-coded bays, and the third transforming, say, two turrets into a single bay port (into which one could then install a drone or fighter bay outfit).

The bays' locations are already encoded in those five ships, as are turret locations on all turret-wielding ships, so the "where do they dis/appear at" problem is solved. I doubt we'll ever see a fighter with two turret points, so the problem of a fighter carrying additional fighters is averted. Depending on how it got tweaked, you could have the bays themselves eat up some combination of weapon space, outfit space, and mass. Personally, I think they ought to take up far more mass than they do outfit/weapon space, making carriers significantly slower without crippling their ability to defend themselves. Something like 15/25/40 tons outfit and/or weapon capacity (for drones/fighters/bombers if we ever get the last) but 75/125/200 tons of mass added on.

An idea that could tie this together with the "everybody hates fighters because they suck" issue - give the bay itself a new ability: bays grant their fighters/drones the same shield regeneration power generation of their carrier, but only if they are within some specified distance of said carrier (say, twice the distance of an outfit scanner). If they no longer need their own power sources and shields, more oomph can be packed into their weapons.

**Comment by rktaylor** [comment] 2016-01-19 21:06
I like the idea of bay ports--that's kind of what I was getting at with "fighter capacity." It'd be a hard-point with a hard-coded appear/disappear location. So you could only have a maximum of x fighter bays, but you could buy huuuuuggeee fighter bays if you want to turn that Bactrian into a hornets nest.

I like that shield idea. I don't see any problems as far as physical intuition goes, and it fits into a paradigm of treating the mothership as a tank and the fighters as DPS. 

If we expand drones to civilian use, we could add something more useful than spy drones by adding repair drones. Stuck in a system with no ships to help you repair? Dispatch a repair drone.

**Comment by DearVarun** [comment] 2016-03-16 13:55
I think there should be two separate systems, hangar exits and hangar space.

Hangar exits would be the preexisting hangar bays and would be able to deploy a fighter every x seconds (should be long to make ships with more than one bay usefull). 

Hangar space would be similar to cargo space with a initial value a stat of the ship and the ablilty to convert to and from outfit space.

**Comment by daerogami** [comment] 2016-03-17 06:16
Bays should have ship type restrictions and a minimum empty hull mass to keep things sane. That way another field doesn't have to be added to track the number of bays a ship has along with more text crowding the outfit screen. I agree with @thenerdfreak on just having fighters emerge from the middle.

**Comment by LocalGod79** [comment] 2016-04-23 06:22
so, for anyone still subscribed to this issue, southern carriers #939 introduces a series of three carriers (added to the FW story, are in the south), and three fighters (distributed anywhere fighters weren't previously available) in an attempt to show the community how effective fighters really can be.

these carriers use a new "external carry" token, which basically rules out closing off a hangar for outfit space.

it looks like fighter/drone bays are going to remain a character feature specific to hulls...

**Comment by LocalGod79** [comment] 2016-04-25 14:43
#995

**Closed** 2016-08-28 01:55 UTC
Labels: mechanics
