### ISSUE TITLE
Request: Buy all and sell all buttons on the port map

### ISSUE THREAD

**Issue by HamsterBoo** [endless-sky/endless-sky#781] opened 2016-02-13 01:00 UTC
It's so much nicer to do missions than trading because you can look at the missions on a map at the same time you pick them. Imagine having to go to another menu, look up the mission by name, and then accept it. That's basically what we do with generic cargo, but there's already a nice price comparison map, so couldn't we just add buy all and sell all buttons to that?

**Comment by endless-sky** [comment] 2016-02-13 23:33
This is a duplicate of #408. The main problem would be that on small screens, the map would be less usable if the sidebar has to be expanded to include your current cargo, etc.

**Closed by endless-sky** 2016-02-13 23:33 UTC
