### ISSUE TITLE
After destroying a target, weapons remain target that point in space.

### ISSUE THREAD

**Issue by mdsmestad** [endless-sky/endless-sky#682] opened 2016-01-17 04:22 UTC
I tried this a couple of times, and noticed that after the target is destroyed, if you continue to fire your weapons they will focus on the exact spot of the targets destruction..not a big issue but odd.

**Comment by Pointedstick** [comment] 2016-01-17 04:25
Only until you select another target. I agree, it is a bit odd.

**Comment by endless-sky** [comment] 2016-01-18 03:13
What version are you running? This used to be an issue, but I can't reproduce it in 0.8.10, and I think it was fixed a while ago.

**Comment by Pointedstick** [comment] 2016-01-18 23:30
I just reproduced this with the latest sources. The issue is that sometimes when you kill a ship, it remains in your target selection after it's dead, and in this state, your turreted weapons will continue to target the last location of the destroyed ship.

It's only sometimes that a destroyed ship isn't cleared as your target. I haven't been able to figure out what causes this.

**Comment by endless-sky** [comment] 2016-01-20 02:56
Found the bug. It was happening only if your selected target was a mission NPC, because NPCs (unlike normal ships) are not actually deleted when they die. Fixed in 3cb6f0f.

**Comment by Pointedstick** [comment] 2016-01-20 03:12
Nice!

**Comment by endless-sky** [comment] 2016-02-03 02:05
Closing this, because it's fixed in 0.8.11.

**Closed by endless-sky** 2016-02-03 02:05 UTC
Labels: bug
