### ISSUE TITLE
Ember Graveyard wormhole in Polerius can be landed on.

### ISSUE THREAD

**Issue by Vedvod** [endless-sky/endless-sky#6911] opened 2022-06-05 13:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

version 0.9.15-alpha, 7f4de75 (continuous build)
The Ember Graveyard wormhole (between Polerius and Ossipago) does not act as a wormhole and in fact can be landed on like a planet, albeit an empty one.

### Steps to Reproduce

1. Go to Polerius
2. Land on Ember Graveyard (uninhabited).
3. This is possible???

### Expected Behavior

I'm unsure of if the wormhole was meant to be removed entirely, or if it is merely bugged, as the wormhole is not present at all in Ossipago. If it is meant to be there, I'd expect the wormhole to take me to Ossipago, otherwise I'd expect the wormhole to not be there at all. 

### Screenshots

![image](https://user-images.githubusercontent.com/68318644/172053719-f8823d02-7739-42a1-9cc3-b7e6b72612ad.png)

### Link to save file

[Sir Ten Doome.txt](https://github.com/endless-sky/endless-sky/files/8840071/Sir.Ten.Doome.txt)

### Operating System

Windows 10

### Game Source

ESLauncher2

### Game Version

version 0.9.15-alpha, 7f4de75

**Comment by Vedvod** [comment] 2022-06-05 14:08
Oh yeah also currently this means that the Graveyard unreachable without jump drive.

**Comment by Terin** [comment] 2022-07-08 05:49
Do you have any plugins? Playing off that commit has the wormhole work just fine for me, and I even had to edit the save so I _could_ take off.

**Comment by tukoz** [comment] 2022-07-11 12:15
As a possibly informative comment, I've been passing through the Polarius -> Ossipao wormhole today and quite a bit before in this play.

Operating System: Arch Linux  
Game Source: ESLauncher2  
Game Version: Continuous  
Plugins:

- Aben
- Better Vanilla Pirates
- ES-Restock
- Korath-Automation-Upgrade
- Midnight Expansion
- The Adamas Project
- endless-sky-flamethrower-turret
- Beccas Endless Expansion
- BetterVanillaHai
- Exporianes
- Lost in Midnight
- Midnight Scrapyard
- Ruination
- The Enclave

**Comment by leklachu** [comment] 2022-09-05 15:40
I can confirm all looks fine to me
- current game data files look okay
- fresh start for me (cheat for a jump drive and quantum keystone) lets me use the wormhole properly
- @Vedvod's save seems to work... if I edit to not be currently in the wormhole (or I can't take off!)
- the savefile also doesn't seem to have any missions changing the state of those systems.

Perhaps there was a bug somewhere in some commit, now fixed? Or a plugin? @Vedvod: I recommend updating to latest from github, and trying with plugins disabled. If you need an edited version of your save to get you out of the wormhole I can help: or you can just fly out and land on a normal planet, before you update!

**Comment by warp-core** [comment] 2022-11-20 21:50
Closing because this is almost certainly caused by a plugin and no one has been able to reproduce.
If anyone encounters this without plugins, or can include the plugins they are encountering it with, please comment and we can reopen.

**Closed by warp-core** 2022-11-20 21:50 UTC
Labels: bug, unconfirmed
