### ISSUE TITLE
Turrets auto-target hostile ships if no target selected

### ISSUE THREAD

**Issue by amtgeography** [endless-sky/endless-sky#4193] opened 2019-02-21 00:28 UTC
Context: I asteroid mine. A lot. Often while mining, a hostile ship flies nearby, that I'm happy to ignore. But my turrets say _nein schweinhund_ and fire at the nearest hostile within some invisible range fence.

I have double and triple-checked that turret opportunistic firing is off (set to focused firing) and I leave auto-aim and auto-firing off. 

Reproduce by shooting at an asteroid with nothing targeted (beam weapon is easiest) and a hostile nearby - on screen but just out of weapons range.

Linux 0.9.8 and happy to add more info, but don't want to post more in case I'm just insane and missed a setting somehow.

**Comment by tehhowch** [comment] 2019-02-21 02:03
Can you reproduce with the latest build? We've had 700+ commits since 0.9.8, including changes to turrets and their targeting.

**Comment by amtgeography** [comment] 2019-02-21 17:00
I'll work on it, thanks for the heads-up.

**Comment by tehhowch** [comment] 2019-02-21 17:20
Just reviewed, and it is intended behavior that your ship--with no ship target selected--will aim its turrets at the nearest hostile ship (within a reasonable range) if there is one. Since turrets take time to turn, this ensures that you can fend off the hostile as soon as possible.

In source builds you can use the asteroid scanner to enable aiming your turrets at it instead of a more distant physical threat. Note that if a hostile ship is well-positioned relative to the targeted asteroid, your turrets may track the ship instead of the asteroid. 

 - The auto-aim preference refers to aiming your *ship*, not your turrets, to maximize your chance of forward-facing weaponry hitting your target
 - The `opportunistic` preference refers only to the passive turret state - once combat begins, all turrets will do their darnedest to stay useful, by tracking the body they can most reliably damage

**Comment by amtgeography** [comment] 2019-02-21 20:33
Ah, yeah I just go around without targeting asteroids, playing it arcade style. And I'm mainly a turret user, so it would be _nice_ if they didn't try to think for me on their own, those pesky crew members.

I figured that's what the auto-aim and opportunistic buttons were about, but wanted to make it clear I had actually tried to fix the issue on my own.

**Comment by amtgeography** [comment] 2019-02-22 23:46
So should I close this, given that this is a feature and not a bug? Or re-tag 'content' as I know I'd like the option to disable the behavior. But not worth putting much time into.

**Comment by VonZorch** [comment] 2019-05-20 02:37
I'm having the opposite problem.  I lock a hostile ship and the turrets shoot at the nearest asteroid.
These are probably related.
That was from the commits as of Apr 4.

**Comment by Pointedstick** [comment] 2019-05-21 23:35
@VonZorch please file a new bug.

@amtgeography since this is fixed in git master, closing it now.

**Closed by Pointedstick** 2019-05-21 23:35 UTC
Labels: mechanics
