### ISSUE TITLE
Freindly AI killing hostile AI

### ISSUE THREAD

**Issue by McloughlinGuy** [endless-sky/endless-sky#5530] opened 2020-12-04 15:28 UTC
**Is your feature request related to a problem? Please describe.**
The Navy/Syndicate are always killing Pirates/Raiders before I can loot them. Shouldn't the pirates be arrest or something and not murdered?

**Related Issue Links**
Has anyone else had this issue or idea? Share some links to those [Issues](https://github.com/endless-sky/endless-sky/issues), [Google Group threads](https://groups.google.com/forum/#!categories/endless-sky), or [Steam forum posts](https://steamcommunity.com/app/404410/discussions/)

**Describe the solution you'd like**
I would like to remove the behavior which I have named "Military Genocide" Where the ships are destroyed instead of disabled. Maybe you could bored a ship and find it deserted if a navy/syndicate ship had boarded it previously. As for pirates destroying merchant ships, that can be left how it is, I doubt they have the same sense of decency that Navy/Syndicate ships have.

**Describe alternatives you've considered**
An alternative would be to make it so that the Navy/Syndicate would board the ships and then bring them back to the planet as if they had confiscated the ship from its original owners.

**Additional context**
I think that the Navy are men of honor and would not kill a defenseless ship. Therefor I am suggesting this change.

**Comment by MCOfficer** [comment] 2020-12-04 16:03
> **Related Issue Links**
> Has anyone else had this issue or idea? Share some links to those [Issues](https://github.com/endless-sky/endless-sky/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc), [Google Group threads](https://groups.google.com/forum/#!categories/endless-sky), or [Steam forum posts](https://steamcommunity.com/app/404410/discussions/)

This part is supposed to prevent duplicates. Please check if your issue has already been discussed.

#5528 
#5245
#3388
#5446
#591

**Comment by tehhowch** [comment] 2020-12-04 16:12
This is your directive to complete, and not ignore.
> **Related Issue Links**
> Has anyone else had this issue or idea? Share some links to those [Issues](https://github.com/endless-sky/endless-sky/issues), [Google Group threads](https://groups.google.com/forum/#!categories/endless-sky), or [Steam forum posts](https://steamcommunity.com/app/404410/discussions/)
> 

Closing as a duplicate of #580 / #1959

**Closed by tehhowch** 2020-12-04 16:12 UTC
