### ISSUE TITLE
tactical screen / command mode

### ISSUE THREAD

**Issue by johndh** [endless-sky/endless-sky#7912] opened 2022-12-20 18:26 UTC
### Problem Description

ES has some basic tactical commands, but I've identified two areas where some changes could help it fulfill more of its tactical potential. You've got a whole fleet, so you might as well be able to use it as such.

1. Fights are generally too fast for maneuvering and commanding a fleet
2. It's hard to keep track of ships that aren't immediately near the flagship

Mindustry is a good analogy because (much like ES) your flagship is essentially your cursor in realtime play, but you can pause to get a view of other parts of the map, select objects and issue commands, etc, then return to the flagship view when you resume.

### Related Issue Links

#4818 making game speed more adjustable would partially address point 1
https://github.com/thewierdnut/endless-mobile/issues/22#issuecomment-1338350003 (mentions these concerns specifically regarding mobile devices)
#6523 (combat instancing, rejected for being overly derivative, would be a completely different game)
#2792 (reversing the function of fast-forward)
#2865 (an older discussion of tactical enhancement, which resulted in more hotkeys)

### Desired Solution

Ideally:
1. The ability to pause the action (or slow it down drastically) and be able to issue commands while paused. The factor could be adjusted as needed for the best experience.
2. 
* a. The ability to pan and zoom while paused, independent of the flagship location. Players of Mindustry will be familiar. Potentially could be faked by having an invisible, very fast flagship that can't be targeted
* b. The ability to more easily select and command ships, and select and target enemy and neutral ships. E.g. selecting multiple ships in fleet info, and fleet info selection should also select ships outside of fleet info
* c. A tab on the fleet info screen that lists enemy ships, neutral objects, scanned asteroids, etc. This would make all kinds of scanners more useful.
* d. Making it easier to click on things on the radar view (currently I have to be very precise and try several times to actually select a particular dot... but this may be specific to mobile devices)
* e. Ability to switch view to selected ship or object

### Alternative Approaches

* instead of panning the main view, tactical mode could expand the radar and give more details to the dots 
* Warcraft, C&C, Age of whatever, and the myriad games like them
* Switching between ships on the fly through the fleet info screen or with selection keys (i.e. select an escort, and some new button lets you take remote control of it, while Captain's body remains in the flagship)
* slowing down the pace of combat, which is a dead horse discussion

**Comment by Zitchas** [comment] 2022-12-20 19:36
For another game along the same lines, Ares (by the same company, AmbrosiaSW, that made the Escape Velocity series. Ares was basically EV, except with a focus on fleets instead of ship customization.

One neat feature I really liked about Ares was that it had a zoom (very similar to our zoom), but it zoomed out farther. At a certain zoom level it switched the "main view" from being literal ships to basically being one giant "mini-map". As in, it didn't even pretend to display ship sprites, and instead just showed all fighters as triangles, frigates as another, cruisers as another, missiles were basically dots. One could zoom out even farther, which just shrank the scale. It was a great way to manage large battles, which in that game usually involved having constant influxes of ships from planets & stations that the player controlled, with quick grouping and ordering fleets in various directions to respond to the enemy. Was quite a bit of fun.

I've often thought that ES could benefit from that. At our furthest zoom level have everything shift over to iconography and then let us  scale out a few levels farther for system-wide tactical view.

**Comment by vitalchip** [comment] 2022-12-21 13:05
Haze is a problem when you zoom right out, might just cull it and see how the starfield looks on it's own. Tiled asteroids would probably be an issue as well but I no longer have them so can't give a first haand account.

There's a value if you have very spread out systems as things do tend to get quite far away. The 'fence' is set at 250,000 here, rather than the usual 10,000 and Neptune is 224,000 away so there is activity all the way out.

On screen the furthest zoom gives approx 38,000px of visibility from side to side, so if I didn't have icons there's no way I'd be able to see the ships at all.

I'm thinking some better form of escort display is required but of course the problem is there's no limit on fleet sizes so space has to be given to show quite a number of ships and this makes the display for any individual ship or group very small.

I'm not really in favour of limiting fleet sizes but the unlimited nature of it certainly doesn't help the Ui design.


https://user-images.githubusercontent.com/65342577/208911967-17f32b65-aeec-43e5-8e58-1f9685689f56.mov


https://user-images.githubusercontent.com/65342577/208912011-d113de85-d7d4-40d4-96d2-028dbcbe4d26.mov

**Comment by johndh** [comment] 2022-12-21 23:56
Wow! Having seen it, I have some thoughts.

First of all, that looks really cool! Were you already working on something like this?

I actually like that the view remains centered on the flagship, which reinforces the feeling that the player is not an anonymous eye in the sky (like many RTS) but rather a specific person commanding from the flagship, and the literal center of the action. That is, of course, if the entire "fenced" area is visible.

Since ES already has handy categories for ships (transports, heavy warships, etc), I wonder how much work it would be to use different icons based on that. Free Orion has some good ones for this type of thing.

**Comment by Amazinite** [comment] 2024-02-04 19:30
Closing for the same reasons as #2865. We're not looking to turn Endless Sky into an RTS.

**Closed by Amazinite** 2024-02-04 19:30 UTC
Labels: enhancement, mechanics

**Comment by johndh** [comment] 2024-04-21 13:30
If we're able to command a fleet (which AFAIK is basically required for success, or at least incentivized heavily) it would be more engaging to be able to do it well or not at all. I would argue that ES is in an awkward halfway between an RTS and something else, and that it could be even better if it leaned into one or the other.
