### ISSUE TITLE
Fast forward: auto return to normal speed when hostiles enter the system

### ISSUE THREAD

**Issue by jostephd** [endless-sky/endless-sky#4826] opened 2020-02-17 12:24 UTC
**Is your feature request related to a problem? Please describe.**
When I fly to an uninhabited system and wait for pirates I want to use fast forward while waiting and return to normal speed when they show up.

**Related Issue Links**
I searched and didn't find related issues on this, open or closed.

**Describe the solution you'd like**
Make fast-forward automatically return to normal speed when hostiles enter the system and the warning siren (alarm.wav) is sounded.

**Describe alternatives you've considered**
Not sure if this should be the default or configurable.

**Additional context**
The siren is played [here](https://github.com/endless-sky/endless-sky/blob/f0251dabfde09d62f9c19b4388b729f7437275b5/source/Engine.cpp#L2004-L2015), so this should be fairly easy to implement.

**Comment by tehhowch** [comment] 2020-02-17 13:30
Duplicate of #2809

**Closed by tehhowch** 2020-02-17 13:30 UTC
