### ISSUE TITLE
Fleet not following me in Sestor space

### ISSUE THREAD

**Issue by grantmolnar** [endless-sky/endless-sky#2105] opened 2017-02-04 15:27 UTC
Several times, while I was flying in Kor Sestor space, my ships stayed in the system they were in instead of following me. There were no fuel problems, and I waited for several minutes for them to move.

When I closed and reopened my game, they remembered they were supposed to follow me and immediately flew to where I was. I have attached my game file.

[Hazak Benmalak.txt](https://github.com/endless-sky/endless-sky/files/752356/Hazak.Benmalak.txt)

**Comment by Amazinite** [comment] 2017-02-04 15:35
Did you accidentally tell them to hold positions and never tell them to stop holding positions again?

**Comment by ldsgsm** [comment] 2017-02-04 15:38
I'm not sure. It is possible. I'll look out for that when I fly in Sestor space again.

**Comment by whismerhill** [comment] 2017-02-04 15:41
wrong fleet orders seem the most probable in my humble opinion, also if you had your fleet selected & clicked anywhere it's basically a hold order

**Comment by ldsgsm** [comment] 2017-02-04 15:42
It's very likely that happened. I'll close this thread and re-open it if I find that was not the issue.

**Comment by whismerhill** [comment] 2017-02-04 15:44
made a small addendum, sorry if you know about this already.

**Comment by ldsgsm** [comment] 2017-02-04 16:56
This is not the problem. My fleet is at Kor En'lakfar, and I am in at Alcyone. I am in space, and I have pressed "g" (and had the game tell me my fleet was gathering around me), and clicked, and told the fleet to gather at a particular spot where I am in space, and they are not Jumping at all.

**Comment by KiLEdEnNis** [comment] 2017-02-04 22:13
did have them selected or not? (green or white in left bottom)
seems like an AI bug though, new pathfinding caused some of these things

**Comment by Amazinite** [comment] 2017-02-04 22:20
If you select your fleet, clicking is "hold position at this location," and I assume that if they're out of the system then they just hold position. Just press your gather key, not gather then click.

**Comment by ldsgsm** [comment] 2017-02-04 22:40
They were white. I pressed "g" and waited, but they didn't jump.

**Comment by ldsgsm** [comment] 2017-02-04 22:41
Well, technically, they were blue.

**Comment by endless-sky** [comment] 2017-02-05 02:39
Escorts won't jump if the jump will take them into a system where they would be out of fuel and unable to refuel. Could that be what is going on?

**Comment by ldsgsm** [comment] 2017-02-05 03:53
My ships had full fuel and wanderer ramscoops, so that shouldn't be the
problem.

**Comment by ldsgsm** [comment] 2017-02-05 03:57
Also, when I exited and re-entered the game, my ships immediately took off
to rejoin me.

**Comment by whismerhill** [comment] 2017-02-07 14:20
"and clicked, and told the fleet to gather at a particular spot where I am in space"
if I understand your actions correctly : 
you clicked in a position, which makes you fleet move to where you click & hold
therefore cancelling the "guard" order

**Comment by themightygrunt** [comment] 2017-02-09 17:45
I've had this happen more times than I'd like, it appears that the ships believe that they can land and refuel, when in actuality, they can't.

It appears that the hostile uninhabited Planets in Sestor space seem to be good to the AI but actually isn't

**Comment by themightygrunt** [comment] 2017-02-09 17:46
And no, I've never told them to hold in Sestor space (why would I leave my fleet to be eaten alive?)

**Comment by KiLEdEnNis** [comment] 2017-02-09 17:52
if you let them hold in a different system they can't die
that'll probably never be fixed :/

**Comment by ldsgsm** [comment] 2017-02-09 18:08
I pressed "g" and waited for several seconds for them to react. They
didn't. I clicked nearby and waited for them to react. They didn't. I
landed, and took off again. They didn't move. I didn't ask them to stay
there, but they did.

As soon as I closed my game and opened it up again, they took off to get
closer to me.

**Comment by VonZorch** [comment] 2017-05-20 16:50
I've had the same thing happen in the Rim.  I was headed for Rust for missions and to sell captured ships
I had some ships with jump drives and jumped an advance force, about 4 ships, from Acrux to Mimosa.  I did this by holding the entire fleet then unholding individual ships.
After taking out any pirates I did a hold/unhold cycle to bring the rest of the fleet.  The ships with jump drives arrived promptly and so did most of the others, but some stayed in Mizar.  I did check for fuel status, all the ships had more than enough, the lowest fuel tankage was 300.  I did a hold/unhold cycle several times.  When I passed back through Mizar headed for Spica the stuck ships fell in and followed.
The same sort of thing happened in Republic space but I don't remember the details.

**Comment by KiLEdEnNis** [comment] 2017-05-21 10:08
I noticed a time ago that if you go to your save file and delete the destination line from the ship that got stuck it gets unstuck, so the problem is caused by a ship storing a certain destination along your route

**Comment by tehhowch** [comment] 2017-10-09 17:48
I think this situation should be a lot harder to encounter (daresay fixed) with the recent PRs to address refueling, held planet / system targets, and other updates to the Move__ functions.

**Comment by tehhowch** [comment] 2019-05-29 12:39
@ldsgsm @themightygrunt please attempt to reproduce this in the latest official release

**Comment by Amazinite** [comment] 2021-04-26 22:40
Hello?

OP didn't mention how they get to Korath space, but since their linked save as the Eye open, this might be another instance of weird AI behavior after passing through wormholes.

**Closed** 2021-04-26 22:42 UTC
Labels: bug, unconfirmed
