### ISSUE TITLE
Use of plugins causes x64 ES to fail to load on Win10 v1703

### ISSUE THREAD

**Issue by TheIvanic** [endless-sky/endless-sky#2605] opened 2017-06-06 22:29 UTC
Running on Windows 10, Steam version 9.6.

Game starts fine on its own, but whenever a plugin is added to the game, it refuses to start.

Updating to beta version seemed to fix it, but only for one launch, afterwards the game refused to start on subsequent tries.

Plugins tried:
High DPI pack
Stronger Hulls by Connor Waterbanks

**Comment by Disiuze** [comment] 2017-06-06 22:53
What OS are you using? I'm experiencing the same problem on Windows 10 Home 1703. You can check your Windows 10 version (if you use it) by going into the start menu and searching "About your PC". This isn't something caused by the game, but rather Windows itself.

**Comment by TheIvanic** [comment] 2017-06-06 23:54
I'm using win 10 Education 1703, so pretty much the same.

**Comment by MCOfficer** [comment] 2017-06-07 10:15
have you tried the 32bit version, too?

might be a duplicate of https://github.com/endless-sky/endless-sky/issues/2520

you can download any ES version as here: https://github.com/endless-sky/endless-sky/releases

**Comment by TheIvanic** [comment] 2017-06-07 12:58
Seems you were right, switching to the 32bit version fixed the problem.  Thanks for the help,

**Comment by tehhowch** [comment] 2017-06-07 17:56
I would keep this issue open, as the game should function properly on x64 systems regardless of the version you are using and if plugins are present. To clarify, when you **do not** have plugins installed, are you able to run the x64 build of Endless Sky?  If you are able to, please re-open and change the title of the issue to "Use of plugins causes x64 ES to fail to load on Win10 v1703." If x64 **in general** will not work for your system, then it can stay closed as 2520 marks that issue.

**Comment by TheIvanic** [comment] 2017-06-07 18:00
Indeed, only when I had plugins installed would the game fail to load.  I'll reopen and change the title, thanks for the advice.

**Comment by Disiuze** [comment] 2017-06-07 22:36
A temporary solution, if you don't want to use the 32-bit version, is to enable Compatibility mode for the executable. This allowed me to start the game with plugins and without any issues.

**Comment by MCOfficer** [comment] 2017-06-08 15:14
while reading into the update notes of 1703, two things striked me the most:

- with the new update, every "non-executable" (probably incorrect name, i mean dlls and vsts) gets it's own svchost.exe, instead of getting grouped up. this does only work with more than 3.5 GB RAM (=**only on 64bit**)
- also, microsoft added a new scaling method for low dpi applications. if you want to test this, you can play around with the "advanced scaling" somewhere in the compatibility settings for endlesssky.exe

i'm pretty confident that one of these may be the cause to your error.

**Closed** 2018-01-17 04:35 UTC
Labels: bug
