### ISSUE TITLE
New Tibet braver than Earth

### ISSUE THREAD

**Issue by ldsgsm** [endless-sky/endless-sky#3114] opened 2017-10-12 02:04 UTC
My combat rating is level 10. I've been systematically conquered all of Republican space, except for New Tibet, which tells me "Please don't joke about that sort of thing" when I demand tribute. I don't mind this, but it seems to me very bizarre that Earth, the capital of human space, is willing to take my forces seriously but New Tibet, a sparsely populated planet on the edge of Republican space, is not.

**Comment by tehhowch** [comment] 2017-10-12 02:07
it is not an error.

**Comment by ldsgsm** [comment] 2017-10-12 02:27
Is there a reason it is set up that way? What makes New Tibet special?

**Comment by tehhowch** [comment] 2017-10-12 02:30
You ever hear of Tibetan monks?
You should also search for duplicate issues prior to opening new ones - there are more than a handful about the lack of tribute fleets on New Tibet and Harmony.

**Comment by ghoulavenger** [comment] 2017-10-12 02:45
Normally when a planet does this, it means it lacks a defense fleet. It shouldn't be too hard to make a plugin to give it one, if you truly want to dominate it. 

On the lore side, I disagree very heavily with why aliens and certain human worlds resist domination. If theres someone threatening to kill you, you take them seriously unless you want to die -- in this case, we could institute razing worlds (which destroys the spaceport, shipyards and outfitters -- trading and hiring of crew may not be available either, but if you didn't kill everybody there might still be someone there for that). On the game mechanics side though, dominating worlds doesn't really do much other than make you a pirate, which means it doesn't matter overly much.

**Comment by Wrzlprnft** [comment] 2017-10-12 09:03
given that a fleet which could raze a planet is kind of immersion breaking anyway, i wouldn't even bother, but that's just my opinion

**Comment by ghoulavenger** [comment] 2017-10-12 10:30
> given that a fleet which could raze a planet is kind of immersion breaking anyway, i wouldn't even bother, but that's just my opinion

You think so? Nuclear weapons are available, and they can completely decimate a world many times over, what makes you think that even a small fleet isn't capable of the same? Actually destroying the world or the sun is quite another matter -- although the technology for it supposedly exists in the lore (check out the Korath systems, talk to the Quarg).

**Comment by Amazinite** [comment] 2017-10-12 10:30
Duplicate of #1406

**Comment by Quantumshark** [comment] 2017-10-12 14:54
From the planet description of New Tibet
"In the lowlands, large farms support sprawling cities full of factories"
So it's not that the only inhabitants of the planet are the monks, there just are some monasteries there as well.

**Comment by MCOfficer** [comment] 2017-10-12 15:35
to me it seems like the monks rule the planet, but of course allow outsiders to settle there.
also not the "religious" attribute.

**Comment by jafdy** [comment] 2017-10-12 16:44
Tribute is just a feature for end-game player with nothing better to do. End of story.

**Comment by KiLEdEnNis** [comment] 2017-10-12 20:47
he just gets annoyed by that 1 red dot between all the green ones on his map

**Comment by ldsgsm** [comment] 2017-10-12 22:28
In fact, I am more bothered by the strangeness of being able to conquer the
capital of the human galaxy, but not an underdeveloped mining/monastic one.
If earth were the unconquerable planet, I wouldn't mind as much.

**Comment by KiLEdEnNis** [comment] 2017-10-13 08:17
a good example: would a planet with maybe 100 people on it have a defense fleet? probably not, they're just a mini colony
the main concept is the same for New Tibet; there are either not enough people on that planet or it's just too undeveloped to be worth defending
basically: I can think of a handful of reasons why a planet would have no defense fleet

**Comment by Hadron1776** [comment] 2017-10-13 14:53
> basically: I can think of a handful of reasons why a planet would have no defense fleet

Sure. However, I _can't_ think of a reason why such planets would think you're kidding when you demand tribute. Maybe they should hide in a bunker or somewhere your weapons can't reach them? It doesn't make much sense for a planet lacking any sort of defense fleet to answer a powerful fleet with "Please don't joke about that sort of thing"...

**Comment by Amazinite** [comment] 2017-10-13 14:59
Which becomes a matter of #2758.
But again, this issue is a duplicate of #1406; please close this issue.

**Closed** 2017-10-13 16:46 UTC
