### ISSUE TITLE
[bug] XCode Iconutil warning

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#1015] opened 2016-04-30 06:48 UTC
![screen shot 2016-04-30 at 2 46 02 am](https://cloud.githubusercontent.com/assets/16969517/14934433/c2cb9608-0e7d-11e6-9fe4-f86660b4c94c.png)

**Comment by endless-sky** [comment] 2016-04-30 14:15
Yes, my icon source graphic is only 256x256 and I haven't gotten around to creating a new one.

Also, I think it's ridiculous to require an icon at such high resolution that it becomes 2% of the entire download size.

**Comment by LocalGod79** [comment] 2016-04-30 16:38
i know very little about iconset...would better image compression help with that burden?

**Comment by endless-sky** [comment] 2016-10-27 02:07
This is a duplicate of #378.

**Closed by endless-sky** 2016-10-27 02:07 UTC
Labels: enhancement
