### ISSUE TITLE
Missing cargo

### ISSUE THREAD

**Issue by pogopossum3** [endless-sky/endless-sky#9276] opened 2023-09-07 23:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Cargo disappears between jumps; sometimes it is extra ammunition, jump drives, captured weapons. 

### Steps to Reproduce

2. Click on '...'
[errors.txt](https://github.com/endless-sky/endless-sky/files/12554259/errors.txt)

3. Scroll down to '...'
I don't know and would prefer not to.

### Expected Behavior

My cargo to be there when I need it.

### Operating System

Mac OS 13.5.2

### Game Source

Steam

### Game Version

v0.10.2

**Comment by quyykk** [comment] 2023-09-08 00:09
Did you mean to close this issue?

**Comment by pogopossum3** [comment] 2023-09-08 02:50
no

**Comment by pogopossum3** [comment] 2023-09-08 03:01
Cargo disappears when you come into port. I have had the cargo I was carrying appear as stock in the port I landed in, so If I wanted to use it on any of my ships that I had brought It for, I had to repurchase it.

**Comment by Hurleveur** [comment] 2023-09-08 08:53
I had the same issue with Jump drives but it was because it couldnt fully fit into one ship, in the last stable
However, given this is for ammo this could be a separate issue

**Comment by pogopossum3** [comment] 2023-09-08 14:11
All Ships were present and accounted for.

**Comment by pogopossum3** [comment] 2023-09-08 14:14
All the cargo fit on one ship.

**Comment by Hurleveur** [comment] 2023-09-08 17:16
Just to be sure, you're positive you didnt accidentaly hit sell outfits?

**Comment by pogopossum3** [comment] 2023-09-08 17:38
This has happened so many times that I am sure I did not hit sell outfits. Also, when cargo winds up in stock and I have to re-purchase it to use it is a royal pain and can be quite expensive.

**Comment by mOctave** [comment] 2023-09-09 04:01
> All the cargo fit on one ship.

Just because all the cargo _fits_ on one ship doesn't mean all the cargo gets _loaded_ on one ship. That may not be the problem here, but it's something to keep in mind.

Please do post your save (just attach the .txt file).

**Comment by pogopossum3** [comment] 2023-09-09 16:14
All the ships arrived and wee accounted for.

**Comment by xX-Dillinger-Xx** [comment] 2024-03-03 23:34
A bit late but might help to close this.
The OP keeps using the words "in stock", not in storage. I wonder if they were uninstalling items that aren't for sale at that outfitter. Once they leave those 'in stock" items disappear. 

@pogopossum3 is this still happening, and does any of what I said make sense?

**Comment by pogopossum3** [comment] 2024-03-04 15:46
Could be. I noticed that when I purchase a load of goods to sell and I get a warning that I have too much on board when I go to leave that port, it seems to be a warning that something is going to "disappear."
________________________________

**Comment by xX-Dillinger-Xx** [comment] 2024-03-04 19:34
Don't take this the wrong way, but I'm starting to feel this less of a bug as it is just a misunderstanding of whats happening in game. You and I , and others if needed, will try to figure this out.   

>Could be. I noticed that when I purchase a load of goods to sell and I get a warning that I have too much on board when I go to leave that port, it seems to be a warning that something is going to "disappear."

Well, I'm not sure how you are purchasing more then you can carry. The game will not allow that. Are you parking ships between the time you buy your cargo and the time you `Depart`? And, what exactly is the warning saying?

You keep using the word cargo then sometimes you refer to outfits.  Are you losing cargo you purchased at a trader or are you losing outfits?

Are you aware you can uninstall outfits rather sell them, using the `u` key? The reason I ask is because 'uninstall' is not on the outfitter screen in the form of a clickable button. It's only a hotkey. 
If you sell something to an outfitter they do not sell, you will lose it when you `Depart`  However, if you uninstall an outfit it will go into storage at that outfitter and will remain there until you install it again or sell it.  Something, else to know, incase you don't already, you can press `F1` at anytime and you will get onscreen help related to where you are in the game.

**Comment by pogopossum3** [comment] 2024-03-04 20:55
If it's an outfit I want, such a jump drive, I store it yo avoid losing it.
________________________________

**Comment by xX-Dillinger-Xx** [comment] 2024-03-04 21:23
I'm not clear what you are trying to say. Sorry, if that sounds rude but we can't help you if you don't give us clear answers. In order to get the help you need, you are going to have to give us more details, explained clearly.  I really want to help you, but I need you to help me understand.

**Comment by pogopossum3** [comment] 2024-03-04 22:00
I've had this problem for years and have written in about it long ago. I am not sure what causes it to happen and the only solution I found is, when I notice something has disappeared, I back track to when I last had it (if I can) and store it and pick it up later. One problem I have run into with this is no matter what "previous" I pick, they all take me back to the same "previous."
________________________________

**Comment by xX-Dillinger-Xx** [comment] 2024-03-05 06:51
You seem to be having a lot of strange issues.  Are you using a lot of plugins? If you are, I'm wondering if your having some strange conflicts with them.
I still don't know exactly what issue you are calling a bug. We may have to start all over again from the beginning of your issue.

**Comment by pogopossum3** [comment] 2024-03-05 15:38
Only one plug in, enhancement.
________________________________

**Comment by xX-Dillinger-Xx** [comment] 2024-03-05 21:27
I going to say this first.
  
**I am just a player of this game, the same as you, I do not represent Endless Sky in any way.** 

That being said, I don't think I will be able to help you with this. You are not really helping yourself, by not giving clear answers and descriptions related to your problem. 
If, when you have more time, you can come back to github and give a clear and detailed explanation of exactly what is happening and when, someone might be able help. 
One, last thing I would recommend is to reset your _first-time help_ and carefully read it so you have a good understanding of how everything works.

Instructions for resetting first time help:
- Launch your game
- go to **Preferences**
- go to **Settings** tab
- go to second page    **Next**
- on the right side panel, under **other**, select `Reactivate first-time help`

**Comment by TomGoodIdea** [comment] 2024-08-02 10:53
We can't do much without a savefile. I'd suggest closing this issue and opening a new one when you'll have the bug documented and reproducible.

**Comment by Hecter94** [comment] 2024-10-09 00:13
Closing this since we can't seem to reproduce. Feel free to reopen if anyone can reproduce a bug or has any new information to share.

**Closed by Hecter94** 2024-10-09 00:13 UTC
Labels: bug, unconfirmed
