### ISSUE TITLE
can sell and outfit ships in other systems

### ISSUE THREAD

**Issue by atklobas** [endless-sky/endless-sky#4913] opened 2020-03-12 05:39 UTC
**Describe the bug**
When selecting multiple ships in outfitter/shipyard it will select all ships between the endpoints allowing the player to sell/outfit ships in other systems

**To Reproduce**
1. Go to player info.
2. Place a ship in the current system on either side of ship(s) in any other system.
3. Go to Outfitter.
4. Click on of the placed ships.
5. Shift click on other placed ship.
6. You can now buy/sell/install outfits on ships in other system 
note: If you do this in the shipyard window you can sell stranded ships (or accidentally sell your whole fleet)

**Expected behavior**
I expected to only see outfits for the ships I can see in the selection window. and not be able to install outfits on ships on the other side of the map.

**Screenshots**
![Arrange ships](https://user-images.githubusercontent.com/1409034/76489892-e8590f00-63e6-11ea-8a90-b5941c59c042.png)
![select remote ships](https://user-images.githubusercontent.com/1409034/76489896-ec852c80-63e6-11ea-9bcb-ae44f6ffe913.png)

**System (please complete the following information):**
 - OS: e.g. Windows 10 Home, version 1809 build 17763.1039
 - Game Source:  Steam beta
 - Version: 0.9.11

**Link to save file**
https://gist.github.com/atklobas/fef3ec66a9572b0a0e56c26aa5b79954

**Additional context**
This allows one to acquire ships/outfits that would otherwise be impossible. Such as getting "Enforcer Confrontation Gear" by remotely installing Jump Drives/Ramscoops on captured ships.

**Comment by downRightCoder256** [comment] 2020-03-12 05:58
duplicate of #4887
and fixed in 6dea115

**Closed** 2020-05-14 15:29 UTC
Labels: duplicate
