### ISSUE TITLE
Have fuel, energy, and heat show for other ships (outside of your fleet)

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1227] opened 2016-06-11 18:11 UTC
Do that so that I can see if someone has enough fuel to give me, if my ion cannons are actually being useful, if my flamethrowers are also being useful...
It doesn't make sense for it to just show for your fleet, if you are capable of scanning everything else. Maybe you can add this as part of a separate scanner?

**Comment by endless-sky** [comment] 2016-06-11 19:13
Duplicate of #1115.

**Closed by endless-sky** 2016-06-11 19:13 UTC
