### ISSUE TITLE
Reloading save during conversation escapes infiltrating and launching endpoints

### ISSUE THREAD

**Issue by Daeridanii1** [endless-sky/endless-sky#10506] opened 2024-09-26 20:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If the player reloads their save during a `landing` mission's conversation:
1. If that mission had the `infiltrating` tag, the player will be able to access the planet's normal services upon reloading
2. If the conversation had a `flee` endpoint, it will not force the player to launch once the endpoint is reached

This provides a way to get around `infiltrating` and forced launches for landing missions.

### Steps to Reproduce

1. Fulfill the conditions of a `landing` mission with `infiltrating` or a `flee` endpoint. Presumably works for `depart` and `decline` as well, but I haven't yet tested these endpoints.
2. Land, such that an `on offer` conversation pops up.
3. Reload your save through the main menu.
4. Observe: you have access to shipyards, outfitters, etc. if these are normally available, and you are not forced to launch upon reaching the end of the conversation

### Expected Behavior

`infiltrating` should remain in effect (shipyards, outfitters, spaceport, bank, etc.) should not be available)
`flee` and other launching endpoints should launch the player once reached

### Screenshots

Before reloading:
![1727381192](https://github.com/user-attachments/assets/95e65520-a861-4127-a8e6-adde49226bdd)
After (note that the planet's services are now available):
![1727381202](https://github.com/user-attachments/assets/bbeb95cd-2f72-4956-965b-7aea5d3600cb)

### Link to save file

[Unwanted Guest.txt](https://github.com/user-attachments/files/17157297/Unwanted.Guest.txt)

Test using the Successors: Unified Defense mission. Attacking and destroying any of the High Houses ships flying around will fulfill the mission offer conditions, then land and perform the steps to reproduce.

### Operating System

Arch Linux, kernel 6.10.8

### Game Source

Built from source

### Game Version

8982fae

**Comment by TomGoodIdea** [comment] 2024-09-26 22:38
Could you post a previous save? The one linked seems to be after landing and has the bug triggered already.

**Comment by Daeridanii1** [comment] 2024-09-27 00:08
Okay, added a fresh one.

**Comment by TomGoodIdea** [comment] 2024-09-27 08:34
For the `flee` not working, I think it may be a problem with branches in the conversation:
https://github.com/endless-sky/endless-sky/blob/8982fae697876f301b9f41bbc9849d3facebc560/data/successors/successor%20side%20missions.txt#L437-L441

The bug with `infiltrating` is a duplicate of #3168.

**Comment by TheGiraffe3** [comment] 2024-09-29 14:01
The `flee` aspect is fixed. Is the rest of this still regarded as a duplicate?

**Comment by TomGoodIdea** [comment] 2024-09-29 17:27
> The `flee` aspect is fixed. Is the rest of this still regarded as a duplicate?

yes

**Closed** 2024-09-29 17:28 UTC
Labels: bug, duplicate
