### ISSUE TITLE
Suggestion: Additional fleet commands?

### ISSUE THREAD

**Issue by Fleurghber** [endless-sky/endless-sky#4380] opened 2019-06-18 11:44 UTC
In addition to existing fleet commands, would it make sense to add something along the lines of "protect me" and/or "protect target ship"?

Normally ships only (effectively) protect other ships indirectly, by defending themselves and being within a certain radius of the ship in question.  But when the success of a mission depends on the survival of one ship in particular, this would be a useful way of improving its chances.

**Comment by tehhowch** [comment] 2019-06-18 12:19
You can already assign ships to follow others (select the escort(s) and right click the escortee).

The current implementation of ship targets means this relationship will work best with turreted escorts.

**Comment by Fleurghber** [comment] 2019-06-18 14:13
That might work: can i do it for myself too?

**Comment by Fleurghber** [comment] 2019-06-18 14:14
That might work: can I use it that way on myself too?

**Comment by ChamEV** [comment] 2019-06-18 23:18
Press g by default to gather escorts around you.  Currently you can't right click on yourself though.

**Comment by Fleurghber** [comment] 2019-06-19 08:53
Seems this is part of a bigger issue…

#302 
#700
#849
#866

… and possibly others.

**Comment by Pointedstick** [comment] 2019-06-30 21:07
Basically a duplicate of https://github.com/endless-sky/endless-sky/issues/802

...or any of the aforementioned others.

**Closed by Pointedstick** 2019-06-30 21:07 UTC
Labels: duplicate
