### ISSUE TITLE
Suppress 'your ship is moving erratically' message from escorts?

### ISSUE THREAD

**Issue by brendanjones** [endless-sky/endless-sky#773] opened 2016-02-09 09:58 UTC
Annoyingly, I can't recreate this. At least I have a screenshot. :) 

For a while when I first bought my Bactrian, I was getting 'your ship is moving erratically because...' warnings, even though I had +200 crew. My movement was not affected.

Screenshot for proof:

![screen shot 2016-02-06 at 5 49 43 pm](https://cloud.githubusercontent.com/assets/16049594/12912921/f5c38486-cf1b-11e5-9730-29e68f86fdf8.png)

You can see the faint 'your ship is moving erratically' text at the bottom of the pic

**Comment by natangold** [comment] 2016-02-09 13:30
Weird. You can get the message if your escorts are understaffed (and those escorts will fly wonky), but your Bactrian is full up, so you must've landed, which should have staffed all of your escorts. Unless your escorts were either out of system or warping in at the moment you landed, in which case, they'd continue as they were.

**Comment by endless-sky** [comment] 2016-02-10 04:20
Could one of those escorts in a different system be one that you captured with not enough crew to pilot it?

**Comment by brendanjones** [comment] 2016-02-10 11:53
No idea. How does an escort not have enough crew to pilot it? Is it when you capture a ship and your own crew numbers are so low that the crew has to be split across the two ships - both with not enough crew? I don't think I would have done that (because it annoys the crap out of me when you can't control your ship. It's faster in real time to land with just enough crew, refill your crew, then take off and start killing again), but I can't rule it out.

**Comment by jmhorjus** [comment] 2016-02-10 17:11
I've had this as well - I believe it turned out to be a disabled escort in another system that didn't have enough crew and was spamming the message all the time.  

Perhaps this should only be displayed when your flagship is short on crew? Escorts usually manage their own crew just fine whenever you get them onto a planet.  An abandoned escort in another system shouldn't cause this message.

**Comment by jmhorjus** [comment] 2016-02-10 17:26
Confirmed:  I can reproduce this with the above mentioned procedure: 
1.) Capture a ship causing both to be short on crew.
2.) Let that ship be disabled. 
3.) Land.   

The messages will continue until the disabled escort is rescued or parked (which you can still do, even though it's disabled).  
Interestingly, after you've landed the disabled escort actually appears to gain enough crew to run, but does not stop spamming the "not enough crew" message.  

Clear solution is to restrict this message to only trigger on the players flagship.

**Comment by endless-sky** [comment] 2016-04-29 20:47
In 0.9.0 I've switched this so that if it's not your ship, the message says the name of the ship instead. But I think it's still worth having the message visible if one of your escorts is short on crew.

**Comment by endless-sky** [comment] 2016-05-12 02:33
Closing because this was addressed in 0.9.0.

**Closed by endless-sky** 2016-05-12 02:33 UTC
Labels: mechanics
