### ISSUE TITLE
Mission ships don't all jump as group

### ISSUE THREAD

**Issue by SirStigII** [endless-sky/endless-sky#3243] opened 2017-11-21 03:28 UTC
I am on the liberate Poisonwood mission, and the falcons and cruiser won't all jump at the same time, even when I hold down the J key. the cruiser and one of the falcons will prep for the jump, but one of the falcons always is drifting , causing both falcons to wait to jump while the cruiser jumps in immediately. This makes it super hard (for the cruiser) to successfully survive the waiting pirates when using a weak player ship. I have noticed this drifting behaviour at other times too, but usually it is a small inconvenience, but on missions like this it's a real pain.

**Comment by tehhowch** [comment] 2017-11-21 03:32
Are you on 0.9.8 (i.e. Steam), or a self-compile? Behavior is different between them.

**Comment by SirStigII** [comment] 2017-11-21 03:33
self compile. Just retested and it happens with jump and hyperdrive.

**Comment by SirStigII** [comment] 2017-11-21 03:39
it seems that the ships are using a different escort personality, as the cruiser looks for a fight, and the falcons like to stay a little closer to me in combat. Although that doesn't explain why one will prep for jump but not the other one...

**Comment by tehhowch** [comment] 2017-11-21 03:40
Post your save so we can easily reproduce

**Comment by SirStigII** [comment] 2017-11-21 03:42
[Flee Destiny~3018-07-09.txt](https://github.com/endless-sky/endless-sky/files/1489945/Flee.Destiny.3018-07-09.txt)
[Flee Destiny~3018-07-02.txt](https://github.com/endless-sky/endless-sky/files/1489946/Flee.Destiny.3018-07-02.txt)
With both drives.

**Comment by SirStigII** [comment] 2017-11-21 03:45
happens on the escort behemoth mission too, one behemoth with prep, other will go off and fight or drift near me.

**Comment by tehhowch** [comment] 2017-11-21 03:51
Yeah, this a a change you can thank me for ;)
The NPC flagships obey you (the cruiser and falcon that wait), while the NPCs' escorts obey their flagship (the falcon that is obeying you).
The fix is to propagate the JUMP && WAIT command pair through - though I thought I had done this already.

**Comment by tehhowch** [comment] 2017-11-21 14:30
It happens because the "middle" ship in the order - the NPC flagship - doesn't give itself the jump command until its parent (you) actually begin jumping. This means when its escort is deciding how to move, if everyone is in your system, its parent doesn't have the jump command set, and it instead chooses KeepStation behavior.

It works fine when you aren't in the system, because the NPC flagship executes a different command block, one in which it gives itself both the jump command (instructing escorts to prepare) and the wait command (until its escorts are ready).

**Comment by tehhowch** [comment] 2017-11-21 21:24
Should be addressed in #3246.

**Comment by endless-sky** [comment] 2017-11-24 16:06
This should be fixed by 69edbbe.

**Comment by tehhowch** [comment] 2017-11-24 16:49
I can confirm  69edbbe fixes this

**Comment by mootootwo** [comment] 2017-12-05 15:11
Can this also be used to make escorted ships only follow the player if they are all jumping in sync?

Because escorted ships auto-path to their leader, the abusive tactic for successful escort missions is just to race directly to the destination and then land as soon as the escorted ships arrive.  If escorted ships -- or at least 'ESCORT TIMID' ships -- only jumped with their leader, it would prevent this abuse.

**Comment by tehhowch** [comment] 2017-12-05 16:45
>Because escorted ships auto-path to their leader, the abusive tactic for successful escort missions is just to race directly to the destination and then land as soon as the escorted ships arrive. If escorted ships -- or at least 'ESCORT TIMID' ships -- only jumped with their leader, it would prevent this abuse.

Personality `escort` means only that the ship should be displayed as an escort. It does not mean that the ship follows the player. As an example, you can create a mission where the player has to catch up to a hostile fleeing ship before it lands. This task can be made a bit easier by letting the player know where that ship is (e.g. they have a spy on it, or bugged it, etc.).

**Closed** 2019-05-27 23:51 UTC
Labels: bug
