### ISSUE TITLE
Fleet formation

### ISSUE THREAD

**Issue by CheatMaker** [endless-sky/endless-sky#8580] opened 2023-03-25 01:53 UTC
### Problem Description

I want a way to make custom formations with my fleet. 

### Related Issue Links

None

### Desired Solution

There should be a gui where you can create a new formation and move the ships in your fleet around.
To select the fleet, there should be a hotkey that opens up a circle gun where you can select the formation you want your fleet to perform. Think like the fortnite emote selection.

### Alternative Approaches

None

### Additional Context

None

**Comment by bene-dictator** [comment] 2023-03-25 02:24
See #302.

**Comment by Zitchas** [comment] 2023-03-25 04:12
The PR you're hoping for would likely be this one: https://github.com/endless-sky/endless-sky/pull/4471
It supported picking various formations, moving them tighter or farther out, etc. In combination with the hotkeys for groups we already have, it worked quite well.

Unfortunately it was closed, and I don't know when/if something like it will be implemented.

**Comment by petervdmeer** [comment] 2023-04-28 13:37
Closing this ticket as duplicate of #302 .

**Closed by petervdmeer** 2023-04-28 13:37 UTC
Labels: duplicate, enhancement
