### ISSUE TITLE
Issues With Remnant Missions

### ISSUE THREAD

**Issue by mathwhiz1212** [endless-sky/endless-sky#7642] opened 2022-11-18 11:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The mission is marked as complete until you leave Nernia, then it's marked as incomplete and there's nothing you can do.

### Steps to Reproduce

1. Start Remnant: Cognizance 1: Follow-up Observations
2. Get in the Puffin.
3. Go to Nernia
4. Land on both planets.
5. Get the success message.
6. Leave Nernia
7. The mission is no longer marked as complete.

### Expected Behavior

The mission would stay complete.

### Link to save file

[No Way 2~3039-11-19 Mission Undone.txt](https://github.com/endless-sky/endless-sky/files/10040778/No.Way.2.3039-11-19.Mission.Undone.txt)

### Operating System

Linux Mint 20 (Based on Ubuntu 20.04) using the 5.4.0-131-generic kernel.

### Game Source

GitHub Releases

### Game Version

v0.9.16

### Additional Information

https://github.com/endless-sky/endless-sky/issues/7008 is similiar, but I used the Puffin to go to both planets, got a success message, and it says "complete, go here to finish" on the mission panel. Until I leave Nernia. Then it's marked as incomplete.

**Comment by mathwhiz1212** [comment] 2022-11-18 11:17
It just decided to work on the third attempt. Not sure why.

**Comment by mathwhiz1212** [comment] 2022-11-18 11:18
Though it shouldn't take three attempts to get it to work, so I'll leave the issue open until someone takes a look.

**Comment by mathwhiz1212** [comment] 2022-11-18 11:22
The follow-up mission was also weird. It said "Meet me in the spaceport in one hour" but it wouldn't give me anything until I left the planet and came back. 
[No Way 2~3039-11-21 Came Back.txt](https://github.com/endless-sky/endless-sky/files/10040833/No.Way.2.3039-11-21.Came.Back.txt)

**Comment by mathwhiz1212** [comment] 2022-11-18 13:59
There's another mission where you have to have 280 tons of cargo available on a single ship (but not necessarily your flagship) instead of 280 tons of cargo available within your fleet.

Failed with ~400 cargo capacity:

[No Way 2~3038-06-18 Cool Hurricane.txt](https://github.com/endless-sky/endless-sky/files/10041835/No.Way.2.3038-06-18.Cool.Hurricane.txt)

Succeeded with a heavy freighter: 

[No Way 2~3040-09-15 Lost two beetles gained jump drives.txt](https://github.com/endless-sky/endless-sky/files/10041862/No.Way.2.3040-09-15.Lost.two.beetles.gained.jump.drives.txt)

The only way to succeed in this mission is to jump, cloak, and land before they destroy the heavy freighter. At least with the fleet I've got.

**Comment by warp-core** [comment] 2022-11-18 16:12
As soon as I load the save in your OP, the mission completes and I get the `on complete` conversation.
I don't get the expected spaceport mission immediately, I have to take off and land, but I suspect this is because determining what missions to offer in the spaceport is actually done on landing, so the spaceport mission is not "available" in your save file (since, for whatever reason, the current mission is not yet marked as complete). I have no idea why the mission would not complete. If you have an earlier savefile, that might be useful, and if you can reproduce it again, checking hte errors file and uploading that may also help. Are you using any plugins? Otherwise, I'm not sure what's going on here and can't really do anything about it.


> Edit: This was one was resolved. There were some damaged fighters I probably disabled but hadn't destroyed. That wasn't clear.
> 
> Later on when patrolling a new constellation for the remnant, it also gave me a success message "You have patrolled all six systems" but won't mark the mission as complete. [No Way 2~3040-08-19 Success but not complete.txt](https://github.com/endless-sky/endless-sky/files/10041536/No.Way.2.3040-08-19.Success.but.not.complete.txt)

There's currently a PR open that should help with this.



> [No Way 2~3040-08-31 Sucess but no message.txt](https://github.com/endless-sky/endless-sky/files/10041644/No.Way.2.3040-08-31.Sucess.but.no.message.txt)
> 
> Later on I have a similar problem to the one I started with. I load up the Aeon Cell, it disappears from my inventory, the job is marked incomplete like I didn't pick it up in the first place.
> 
> Do I need 160 free cargo space on my flagship? Edit: Buying a Freighter did work. It wasn't clear that was necessary though. Maybe say "160 tons on a single ship".

Yes, an outfit cannot be spread across the cargo holds of multiple ships. I think we already have an issue about this and I think I'll add a warning if you try taking off with an outfit you cannot take with you.

**Comment by mathwhiz1212** [comment] 2022-11-18 16:45
```
Are you using any plugins? Otherwise, I'm not sure what's going on here and can't really do anything about it.
```
No plugins. If further investigation won't help someone else, I'll let it go. Maybe put in a FAQ somewhere that if you don't get an expected mission message, leave the planet and come back.

```
There's currently a PR open that should help with this.
```
Great!

```
Yes, an outfit cannot be spread across the cargo holds of multiple ships. I think we already have an issue about this and I think I'll add a warning if you try taking off with an outfit you cannot take with you.
```
The situation I want to prevent is someone taking off with an outfit they can't hold, losing it as soon as they leave the planet, and wondering why. A warning like you're proposing would fix that. 

It makes perfect sense in retrospect, but I've only started playing a week or so ago so everything is new. When I get into something I become an "advanced newbie": I know some advanced things, but am missing some basics.

**Comment by warp-core** [comment] 2024-01-18 23:38
On reconsideration, I'm almost certain the original issue with Cognizance 1 not completing when you first landed was because mission cargo from that mission was in one of the escorts that hadn't caught up to you yet. After taking off and landing a few times, the ship carrying the cargo caught up. The reason the mission completed immediately upon reloading the save was that this was prior to #7505 so the save file did not record that the cargo was in one of the out of system escorts, so it was "teleported" to your flagship, which allowed the mission to complete.

The mission should probably be given an "on visit" message indicating that the mission cargo may not have arrived yet.

I believe all the PRs I mentioned related to other issues brought up here have since been merged, so those shouldn't be problems anymore.

**Comment by mathwhiz1212** [comment] 2024-01-19 04:14
@warp-core Thanks!

**Comment by mathwhiz1212** [comment] 2024-07-17 22:43
> @mathwhiz1212 was this fixed?

I haven't tried the Aeon Cell mission with ships who have "enough" cargo space, but not on any one ship. 

If we can verify the player gets a warning in that situation, we should be able to close this issue. I think I've been through the Remnant missions enough times since to confirm that the other issues have been fixed.

The player gets a warning if they don't destroy all the fighters in a mission, the missions all appear to complete when expected, and give warnings when they do not, I just haven't tested that particular issue.

Did some variant of https://github.com/endless-sky/endless-sky/pull/7645 get merged?

**Comment by mathwhiz1212** [comment] 2024-07-18 23:16
> > Did some variant of #7645 get merged?
> 
> Yes. #9138.

Then we should be good to close this issue.

**Closed** 2024-10-06 20:23 UTC
Labels: bug
