### ISSUE TITLE
Other missions fail when taking off from Nenia during egg return mission

### ISSUE THREAD

**Issue by dome2048** [endless-sky/endless-sky#5039] opened 2020-05-04 04:40 UTC
When trying to leave Nenia after returning the eggs, you will be unable to take off if you have any missions requiring more cargo and/or bunks available in your gas craft vessel, even if you have a suitable escort in system with you.

The error doesn't happen until taking off from Nenia.

Current workaround is to complete other missions before undertaking this one.

Further described here: https://www.reddit.com/r/endlesssky/comments/gd0524/void_sprites_spoilers/

**Comment by tehhowch** [comment] 2020-05-04 11:34
Likely the same reason as #1624 and it's duplicates.

Did you save and reload the game while landed? Or just land and then take off, without closing or reloading the game?

**Comment by kikotheexile** [comment] 2020-05-05 04:45
I've had a resolution for this for some time but it has been incredibly low priority for anyone to work on. The answer I came up with is preserve ship inventories rather than fleet inventories, remove automatic fleet re-sorting upon load (only allow that when purchasing items, outfits, or taking new jobs,) and implement a way to do so manually. This would fix these bugs, and allow cargo to be preserved on parked ships without issue, thus answering a number of feature requests. 

I currently have asked @Ferociousfeind looking into this on the ESS side, but our programming prowess over there is limited, so progress is slow.  If we come up with a proper solution for it, we will PR the fix over here as well, but frankly someone like @tehhowch is going to be able to do so faster and better than our side can.

`It's worth noting the engine already preserves ship cargo per ship, its just the automatic fleet inventory sort that causes the main problem we see. Disabling that will fix the bug, but will lead to additional problems - hence the need for a change to the UI to allow for manual sorting, and preserving ship cargo rather than fleet cargo. `

**Comment by NomadicVolcano** [comment] 2020-05-19 03:05
Try PR #5070 and see if it fixes the problem. It saves mission cargo and mission passengers.

**Comment by NomadicVolcano** [comment] 2020-05-19 03:48
I looked at the reddit URL and this is definitely bug #1624, which should be fixed by PR #5070.

**Comment by NomadicVolcano** [comment] 2020-05-19 03:56
From reddit:

> Just restarted this game after an 18 month hiatus. I went to check out the Graveyard and new remnant missions and found the new void sprites mission to put eggs back in nenia. The mission to nenia was easy enough, but when I try to leave, it is telling me that I am failing all my missions (due to lack of bunk space), and also I can't cloak or hyper jump. Is this a bug? Any suggestions? Or is another board better for this question? Thanks!!

The player does not provide details about when they saved or loaded, but the behavior otherwise fits #1624 .

"I cannot cloak" is a weird complaint to have about the gascraft.

**Comment by dome2048** [comment] 2020-05-20 07:16
> Please use the issue templates.
> 
> Likely the same reason as #1624 and it's duplicates.
> 
> Did you save and reload the game while landed? Or just land and then take off, without closing or reloading the game?

Sorry for the delay, and for not using the template.

I did not save on the planet. I wouldn't be surprised if this is the same bug as described in #1624 though I have no easy way of confirming that. It's possible I (and the other player) only encountered it on Nenia since it's a planet that only the gascraft can land on (and not the player's other ships).

> 
> "I cannot cloak" is a weird complaint to have about the gascraft.

Maybe they transferred the cloaking device to the gascraft to avoid the Archon? That was the other player, not me, so this is just speculation.

Thank you all for your hard work on this outstanding game!

**Comment by NomadicVolcano** [comment] 2020-05-20 13:58
Another possibility: the fleet was in the system, but did not land because the cargo ships (or whatever) did not have gaslining. However, the gascraft did land, since it had gaslining. The internal mission logic transferred the cargo from the cargo ships to the planet, since the player had landed. When the player took off, it was impossible to fit the cargo because there were no ships to put it on.

**Comment by NomadicVolcano** [comment] 2020-05-20 16:58
Confirmed. Here's the relevant code in PlayerInfo.cpp. It does not check if a ship can land on the planet before removing the cargo.

```
        for(const shared_ptr<Ship> &ship : ships)
                if(!ship->IsParked() && !ship->IsDisabled())
                {
                        if(ship->GetSystem() == system)
                        {
                         	ship->Recharge(hasSpaceport);
                                ship->Cargo().TransferAll(cargo);
                                if(!ship->GetPlanet())
                                        ship->SetPlanet(planet);
```

**Comment by dome2048** [comment] 2020-05-22 05:18
I don't recall if I encountered this error right before the stable beta release (0.9.12) or the unstable one just prior.

**Comment by gggainzzz** [comment] 2020-06-09 01:41
I reloaded and had to bring my whole fleet to the system to avoid failing missions at landing with gascraft and it was 9.12 IIRC

**Comment by Amazinite** [comment] 2021-04-26 22:29
Closing since this is probably just a duplicate of #1624.

**Closed by Amazinite** 2021-04-26 22:29 UTC
Labels: unconfirmed
