### ISSUE TITLE
Sound while jumping does not stop in menus

### ISSUE THREAD

**Issue by lehgogh** [endless-sky/endless-sky#887] opened 2016-03-30 17:29 UTC
Here's another hyperspace aesthetic issue to go along with #885.

The jump drive sound does not stop while inside menus, so if I want to check my map as my ship is making the jump, the visible flash occurs several seconds after the corresponding sound. Perhaps we could pause the sound while in menus?

**Comment by endless-sky** [comment] 2016-04-01 00:06
Duplicate of #351.

It's on my to-do list, but not high priority - I want to get ambient sound / music working first, and that probably won't be in this release.

**Closed by endless-sky** 2016-04-01 00:06 UTC
