### ISSUE TITLE
Captured ships cannot fire until save is reloaded

### ISSUE THREAD

**Issue by Anarchist2** [endless-sky/endless-sky#7458] opened 2022-10-24 07:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After capturing a ship, its guns cannot be fired until the save is reloaded. No other method allows the ship to fire again except for reloading.

### Steps to Reproduce

1. Capture a ship
2. Try to fire its guns, either by switching to the ship or ordering it to attack as an escort

### Expected Behavior

The ship should shoot.

### Operating System

Win10

### Game Source

Built from source

### Game Version

0ecb87933

**Comment by warp-core** [comment] 2022-10-25 16:26
This was caused by bc586bd20fe9ae770dab048c131697fb957d50f6.

**Comment by warp-core** [comment] 2022-10-25 18:23
Should be fixed by 7e14629

**Closed** 2022-10-25 18:23 UTC
Labels: bug

**Comment by Version135b** [comment] 2023-01-17 23:45
Just had this reproduced on the latest version (9.16.1) and just as is reported here a reload fixed it.  if it's relevant this occurred on a marauder falcon.

**Comment by Amazinite** [comment] 2023-01-17 23:48
The update that fixes this will be releasing mid next month.

**Comment by warp-core** [comment] 2023-01-17 23:49
This was fixed after 0.9.16.1. The fix is in the continuous build and will be in the next release (hopefully, not more than a month.)

**Comment by Version135b** [comment] 2023-01-17 23:49
Oh  ok - I should have realized there was a while for this to go from commit to steam build.  Thanks and sorry!
