### ISSUE TITLE
Mouse input Issues with 0.9.4 release on OSX

### ISSUE THREAD

**Issue by archa347** [endless-sky/endless-sky#1733] opened 2016-10-22 03:15 UTC
I downloaded the 0.9.4 release onto my late 2013 13" MBP Retina with OSX 10.11.6.  When I start it up, its super high resolution, really hard to see the text.  It also doesn't appear to accept any mouse input.  Keyboard input seems to work.  I downloaded 0.9.2 and that seems work fine.  Everything is readable and the mouse input work.

**Comment by Pointedstick** [comment] 2016-10-24 03:28
FWIW, that release (as well as the latest compiled code) is fine on my late 2013 Retina MBP with 10.12.1.

**Comment by NHDaly** [comment] 2016-10-25 20:26
I'm seeing the same behavior as @archa347, also starting after the latest release:

Same exact specs -- 2013 13" MBP Retina with OSX 10.11.6 -- and same error.

Interestingly, when I start up the game (if I have fullscreen disabled) it starts as a smaller window (which is the same behavior as before `0.9.4`). However, this window is too small and cuts off some of the in-game UI, so I usually maximize the window. In this case, it is only when I resize the window that it jumps to the very high resolution and the mouse input stops working.

By reading the `preferences.txt` file, it looks like the resolution starts out at `"window size" 1180 700`, and mouse input works correctly. Then, upon resizing the window at all (but trying to keep the window size the same), it changes to `"window size" 2360 1400`. Which is double. And then the mouse input stops working correctly.

In this double-resolution state, I've realized the mouse input *does* work if you point your mouse way in the bottom right corner, which correlates with the doubled-resolution hypothesis.


Finally, if I change to `fullscreen 1` in the `preferences.txt`, the above problem exists immediately.


-----------------------------

This could be related to the way retina MacBookPros handle the retina resolution by essentially doubling/scaling the size of a pixel.

**Comment by Amazinite** [comment] 2016-10-25 20:44
Duplicate of #1689

**Closed** 2016-10-27 02:32 UTC
