### ISSUE TITLE
Outfits and Ships Should not have the same worth everywhere + Purchase outfits into Cargo and alternatives

### ISSUE THREAD

**Issue by KendrickAllenway** [endless-sky/endless-sky#5521] opened 2020-11-27 10:15 UTC
_**Feature Request**_
So, presently in game the outfitter and shipyard market is static, everything is worth the same everywhere (excluding depreciation) if you can buy it.
+ We should be able to buy outfits to install and place into cargo.
+ Further Developments will probably add a more detailed Feature Request

I think outfits should be valued differently in different systems and planets in the system.
This has a few benefits.
1. Trading outfits (supplying outfitters)
2. Adds importance to certain planets, like Tarazed which can have say, lower prices for things as they are manufactured there.
3. Make some planets have exceptionally low costs for certain ships to make them easier to access.
4. Being able to move installed outfits or purchased outfits into Cargo is extremely useful especially for certain missions that wants you to bring an outfit. You don't have to make Outfit Space just Cargo Space.

**I'm not saying this should be implemented exactly as I say it should be, or implemented anytime soon as these would probably break all forms of economic balance in the game**
However, these do make sense from a real world perspective.

**Trading Outfits**
Trading commodities was good, and quite profitable but I'm suggesting that outfits should be worth more and less in different places. For example, I can buy a "White Sun Reactor" from the Wanderers for 13.9 Million, put in my Cargo, ship it to human space and sell it for a mark up, say 20 Mil. In this example we're trading interspecies technology and I think that should be worth a decent markup as Humans have never seen such advanced technology. Also applies to ships.
On a smaller scale, I can take say a Tarazed produced, Liquid Helium Cooler for 150K and sell it in another part of human space for a small markup say 200K as they do not produce it there. Not a large enough markup to be unpurchaseable/unreasonable in human space but enough to make a tidy profit.

**Alternative**
Say, we don't sell directly to the outfitter as that would inevitably break the economy of the game. At least add some form of Mission like the Unfettred who would buy Jump Drives for a straight 1 Mil regardless of depreciation. These missions can be limited to a set amount or frequency but pay really well. Also applies to ships.

**Further Developments**
Potentially by selling interspecies technology, their technologies improve over time and they develop newer tech.
e.g. Introducing Wanderer Sun Beams to the Free Worlds, improves their human Plasma Cannons or introduces say, Plasma Beam

**Planet Importance**
Making Outfits worth more or less in different systems and planets will indefinitely make some planets and systems more important because of their sell prices and I think this can be incorporated into the Free Worlds Storyline, where you take and defend strategic planets.
Could also be incorporated into future storylines where you capture certain planets to cripple their production of ships, or ammunition or supplies to weaken them.

**Lowered Costs**
The lowered cost can allow for new players to work their way up the ship tree easier as they can pay for ships at a lower cost, provided that they find the planet that sells at those lower costs.

**Moving Outfits into Cargo**
This is extremely helpful in general, for example if you accidentally sell the Broken Jump Drive from your Cargo into the outfitter in Remnant space, you can just repurchase it and place it into cargo if you don't have the outfit space.

**Related Issue Links**
Found none else

**Comment by Amazinite** [comment] 2020-11-27 11:59
Outfit trading is a duplicate of #928. 
Buying into cargo is already possible by deselecting all ships (ctrl+click any highlighted ships) in the outfitter before purchasing or checking “Show outfits in cargo” at the bottom left of the outfitter.

**Comment by Zitchas** [comment] 2020-11-27 13:08
While generalized "this port is more expensive" or "the man HQ of this company sells their stuff for cheaper than available elsewhere" is a neat idea, it might be more realistic from a gameplay perspective to create the functionality to allow outfits to be sold at different prices individually at specific places. 

I could see this taking one of two forms:
A) Be able to specify in the planet attributes something to the effect of  `Outfit 'Jump Drive' Price 50000000` where, the specified price is the new base price for that outfit. So if it is for sale, then that is the list price, and when selling that outfit, that is the base price that is used in the depreciation calculation to find out what the outfitter will pay for it.
B) In the outfit attributes be able to specify something like `'Viminal' 50000000`, which is literally just stating that on the specified planet/port its price is whatever amount specified instead of the normal price.

Generally speaking, due to the problems listed in #928 the variation in prices should be kept small, and should never be applied to H2H or other particularly high value-to-space outfits. Might be most effective when used to highlight specifically dangerous trade routes. For example, having stuff from a good supplier available at a pirate port, at a mark up to reflect that it is stolen goods and thus in short supply.

**Comment by KendrickAllenway** [comment] 2020-11-27 19:13
> Buying into cargo is already possible by deselecting all ships (ctrl+click any highlighted ships) in the outfitter before purchasing or checking “Show outfits in cargo” at the bottom left of the outfitter.

That's incredibly useful to know.

**Comment by Zitchas** [comment] 2020-11-27 23:31
You can also uninstall into cargo using `U`

**Comment by InfiniteDonuts** [comment] 2020-12-03 19:00
Interesting idea. I do think it would be nice to change outfitters' prices for certain items. For example, say I have a bunch of plundered Wanderer tech in my cargo hold. Human outfitters have pretty much no way to get any of that, so they should be willing to pay a lot of money for it.

**Comment by InfiniteDonuts** [comment] 2020-12-18 13:02
Hey, Vitalchip told me to take a crack at writing some code. I think this would be a good weekend project :D

**Closed** 2021-03-07 21:43 UTC
Labels: duplicate
