### ISSUE TITLE
[Suggestion] Collateral for Missions

### ISSUE THREAD

**Issue by 19wolf** [endless-sky/endless-sky#2943] opened 2017-08-19 15:07 UTC
All missions should have a collateral. If they don't get completed, you should have to pay a fine or similar. Especially on Rush missions.

**Comment by Bladewood** [comment] 2017-08-19 17:10
... What?

**Comment by Amazinite** [comment] 2017-08-19 17:17
Duplicate of #2205

**Closed** 2017-08-20 20:41 UTC
