### ISSUE TITLE
System-wide commands

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#2265] opened 2017-03-15 10:15 UTC
It would be nice to have a way to issue commands to all escorts currently in the same system without changing selection, by double-tapping or holding [G] or [H].

**Comment by MessyMix** [comment] 2017-03-15 14:10
Too complicated imho.

What's so urgent that you cannot change your selection?

**Comment by Tadrix** [comment] 2017-03-15 14:34
Gather command while the flagship is nearing death, for example.

**Comment by KiLEdEnNis** [comment] 2017-03-15 14:43
if you are nearing death your escorts may not be in time anyway
all I want is an option to instantly unselect all escorts (or toggle; in 1 you have no escorts selected and you can toggle back to the escorts you selected before you toggled)

**Comment by Wrzlprnft** [comment] 2017-03-15 19:40
you could assign a number to your selection -> deselect -> gather -> use the number to reselect

or am i missing the point?

**Comment by KiLEdEnNis** [comment] 2017-03-15 20:54
not sure, you miss my point a little bit; where you have a toggle button so you can have 2 different selections under 1 button
so some could have 2 configurations saved, others could have specific selections or no selections under that button (which is close to what you said, just less buttons)

**Comment by Wrzlprnft** [comment] 2017-03-15 21:27
i was not responding to you anyway

**Comment by KiLEdEnNis** [comment] 2017-03-15 22:04
oh, awkward, I'll leave this issue now

**Comment by Tadrix** [comment] 2017-03-16 00:08
Unselecting and reselecting sound like a great idea. A while ago I wrote about that too in #2102 which was part of bigger issue and likely got overlooked as a result:

> Key bindings: It would be nice to be able to UNselect a ship without need to scroll through all of them, and to be able to select an asteroid (even if just with a mouse). Or probably I'm just a dummie — but it's no fun accidentally killing an escort or allied ship, or pressing frantically "next ship" while an asteroid flies by.

This was before 0.9.6. 

If number of ships following are variable (for example, player regularly parks ships without jump drive before going to alien space, then unparks upon return) and some are jumping into system later then others then a way to instantly issue a command to all of them is handy. People are used to that possibility too.

**Comment by endless-sky** [comment] 2017-03-23 01:45
Note that you can unselect all ships and clear your current target just by pressing any numeric hotkey that you have not assigned to a group of escorts. (For example, you could leave 0 unassigned, so you can just press 0 any time you either want to clear your target, or issue a command to your whole fleet.)

**Comment by Bladewood** [comment] 2017-03-23 02:34
I forgot that numbers could be assigned to escorts.

**Comment by KiLEdEnNis** [comment] 2017-03-23 10:09
@endless-sky any chance my "toggle key" is considered to add (scroll a bit up)? seems like a cool extra touch & wouldn't seem that hard as far as I know

**Comment by endless-sky** [comment] 2017-03-24 02:51
The problem is that right now, the Gather and Hold keys already toggle (between gathering and not gathering, or holding and not holding) and that's useful behavior because there's no other way to set your escorts back to the default behavior (keeping station).

**Comment by Tadrix** [comment] 2018-01-05 05:46
> the Gather and Hold keys already toggle

Maybe we could add a third key, "keep station"? Much more intuitive than cancelling previous order to do it.

Also, I propose using tilde (~) key to clear selections — unselect both target and escorts.

**Comment by jafdy** [comment] 2018-01-05 09:34
~ is kept in different places on different keyboards, for me it is on the # key on the far right of my keyboard, for people in the US it is on the ` key on the top-left of the keyboard.

**Comment by KiLEdEnNis** [comment] 2018-01-05 13:59
> for people in the US it is on the ` key on the top-left of the keyboard.

(or people w/ a US qwerty keyboard, like me while I'm Europese)
the problem here would be that one would have to hold Shift & then press ` to use the ~ key, I really don't know what the idea is

**Comment by Tadrix** [comment] 2018-01-05 18:22
Sorry, got you both confused. Where I'm from, we call the ` key "tilde key". I meant using it without shift.
And I'm also from that greater part of the world where it's at the top left of the QWERTY layout (I'm also in Europe).

The point was, we are using number keys for control groups, so we could place unselect key next to them. It could be either ` or Backspace (because - and = are taken).

**Comment by KiLEdEnNis** [comment] 2018-01-05 22:06
so the ` would unselect all escorts? seems fine to me, but idk if it'll work for other keyboard lay-outs (like the AZERTY one, which isn't that uncommon either if I'm not mistaken)

**Comment by Tadrix** [comment] 2018-01-05 23:59
Unselect all escorts and unselect your current target (useful if, for example, you plan on attacking asteroids, but have selected that nearby Navy gunboat, or that merchant ship you just repaired).

Judging by [this](https://en.wikipedia.org/wiki/AZERTY), AZERTY is used mainly in France. Wikipedia says that ` is located either where we have \ (this or Alt Gr + \), or Alt Gr + 7. Anyway, users of these already have their keys laid out differently, so it wouldn't be a surprise if they remapped it anyway. Just make sure it is doable via preferences.

**Comment by jafdy** [comment] 2018-01-06 09:07
Can't you just click open space to deselect? That would be the same as most RTS games.

**Comment by Tadrix** [comment] 2018-01-06 17:12
Apparently you can. I didn't know that.

Then you'll have deselected escorts, but not target focus. I propose a way to instantly clear all selections, target included (because currently you have to tap N repeatedly). One more nice thing would be to be able to cycle backwards (N, N, N, overshot a ship, push a key to cycle back, not N twenty times more).

**Comment by KiLEdEnNis** [comment] 2018-01-06 18:12
> Can't you just click open space to deselect? That would be the same as most RTS games.

yes you can, but to me it's annoying to have to use my mouse to deselect an escort when I'm just using my keyboard

**Comment by Tadrix** [comment] 2018-01-09 23:06
Anyway, I'd like to clarify:
A key to deselect everything should do everything pressing an unassigned number key does presently, the only difference should be that a group of ships can never be assigned to the deselect key.

**Comment by endless-sky** [comment] 2018-01-17 04:02
Technically speaking, giving the player the flexibility to preserve one number as a "deselect all" key, without forcing them to do so, gives those who want this behavior the option without having to change something that others may be relying on.

**Closed** 2018-01-17 04:18 UTC
Labels: enhancement
