### ISSUE TITLE
After selling the ship and paying back all loans, cannot take a new loan.

### ISSUE THREAD

**Issue by the2nake** [endless-sky/endless-sky#5875] opened 2021-04-22 00:44 UTC
**Describe the bug**
When starting the game, I can sell my ship after buying it, then pay back all my loan. Yet this does not increase my credit score enough to take out a loan of the same size.

**To Reproduce**
1. Start the game
2. Buy, then sell a starship
3. Pay back the entire loan on the bank screen
4. Cannot take out another loan.

**Expected behavior**
I expected to see the option to take out another loan of the same size

**System (please complete the following information):**
 - OS: Linux Mint Ulyssa 20.1 Cinnamon
 - Game Source: nightly
 - Version: commit hash e19c8e2

**Comment by tehhowch** [comment] 2021-04-22 01:12
Closing as a duplicate of #5801.

While you differentiate slightly by purchasing and then selling back the ship, the core issue is the same: you have no net worth history, and thus cannot qualify for a loan.

**Closed by tehhowch** 2021-04-22 01:12 UTC
Labels: duplicate
