### ISSUE TITLE
Land and reload, and a disabled ship is perfectly fine

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1048] opened 2016-05-07 22:23 UTC
I found a ship. I captured it. It was somehow disabled. I landed by mistake.
Then, I left, and there it was floating in space, disabled.
And for some reason, I felt the urge to reload the game, and so I did. (Maybe I did that after another landing? I don't know, I forgot.)
And when I left the planet again, the ship was perfectly fine, not disabled, it was active.

**Comment by endless-sky** [comment] 2016-05-08 00:11
What version are you running? I'm pretty sure I fixed this recently, and I can't reproduce the bug with the latest code.

**Comment by Bladewood** [comment] 2016-05-08 00:16
"Unstable release 0.9.0 [beta]"? I always run the latest version. That is released on Steam.

**Comment by endless-sky** [comment] 2016-05-08 00:23
This was fixed in commit 9deba41, which was after 0.9.0 was published. So, it will be fixed in 0.9.1.

**Comment by Bladewood** [comment] 2016-05-08 01:50
Oh, I see, my apologies.

**Closed** 2016-05-08 17:44 UTC
Labels: bug
