### ISSUE TITLE
Turret sprites on ships

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#843] opened 2016-03-08 15:56 UTC
perhaps related to #603 , some static top-down rendering of turret outfits to sit on top of the ship sprites (perhaps only on npcs ship when hostile to another - to reduce cpu overhead), with a firing effect for the turrets that turns them to the appropriate angle?

i recognize that this would bulk the images resources somewhat, but would certainly add some of the visual depth i believe is sought.

from the coding perspective, it would involve adding a 5x5 sprite according to the turret address (which would also contain the outfit who's sprite should be rendered), with a check for hostile/in combat for npcs (if it's possible).  at this level, a check that makes the sprite disappear when firing would also be timely.

as a followup question - can OpenGL create a shadow for the turret (as a part of the firing effect)?

in the image resources, a new folder /turrets would contain the currently 10 required 5x5 turret hostile/firing effect sprites (at that size, blaster and mod blaster will appear the same) to be rendered onto the hull.

this modification would also facilitate 'q-ships' referenced in #831 

thoughts?

**Comment by jafdy** [comment] 2016-03-08 16:54
I would very much like to see something like this but the turret hard points are very small so it seems (to me) that it would only make it harder to render very large fights for little to no visual advantage. I'm no programmer so there may be a way perhaps only have the turrets displayed if they are on screen. (is this the way asteroids are done currently?)

Having read this and #603 it appears to be more or less the same thing although this has been better thought out.

**Comment by endless-sky** [comment] 2016-04-02 19:09
I think this is basically a duplicate of #603, which I'll merge with this one by copying the one thing not mentioned here:

> Another thing I would like to see implemented is a a way to make turrets change location for animated ships..imagine pieces of a ship that rotate, with turrets mounted to them. The turrets should move with the rotating elements of the ship, so naturally they would need to change position on the ships sprite.

As a first step, the turret sprites could just always point toward a ship's target (or forward, if no target is selected). But eventually, it would open up some new strategic possibilities if turrets took time to rotate rather than being able to instantly jump to point at any angle.

It would also maybe look cool if the turrets sort of swept the sky at random when no target is selected, scanning for possible enemies. That would help make ships look less lifeless.

**Comment by Bladewood** [comment] 2017-08-04 00:45
I think this can be closed now.

**Closed** 2017-08-04 01:12 UTC
Labels: enhancement
