### ISSUE TITLE
[H]  Hold Fire !!!

### ISSUE THREAD

**Issue by ChuckStarchaser** [endless-sky/endless-sky#7543] opened 2022-11-07 04:23 UTC
### Problem Description

When a mission requires you to disable, but NOT destroy, a ship, your escorts become a liability, killing the ship on sight in less time than you see the color of it.

Solutions proposed to me were to,

1. Tell my ships to hold fire
2. Tell my ships to stay put
3. Leave my ships parked
4. Reduce my ships' weaponry to lasers

However, telling my ships to hold fire is presently not possible (and is the whole reason for this feature request).
Telling my ships to stay put (with **[H]** key) works only if the target ship I want to disable doesn't come in at MACH 5 and plunges into my 23 escorts ...  which is actually the way it went.
Leaving my ships parked was not an option because I had other missions that involved cargo, and my leader ship has only 22 tons of cargo space, due to my addiction to outfit expansions.  Trying to leave the planet without my escorts told me that the mission cargos did not fit in my ship and were going to be sold at auction;  a subject for a big fat bug report ...
Reduce my ships' weapons to lasers, that is about 15 minutes of work to do, and then I have to put everything back how it was, which is another 45 minutes of work, for 23 ships armed to the teeth.

### Related Issue Links

None.

### Desired Solution

The simplest solution is to move the "hold ground" command from [H] to [P] (call it "Stay Put"), and repurpose the [H] for actually issuing the command "Hold Fire !".

### Alternative Approaches

Leave [H] for "Hold Ground", and use some other key, like [X] for "Hold Fire !".  I don't like this, myself.

### Additional Context

Ah, yes, I have additional content:  The "Hold Ground" command does not last.  If you tell a bunch of ships tightly packed to "Hold Ground" ([H]) and you see them holding ground;  but if you then cross to Coalition territory, do some missions, and come back, you find your ground holding ships all spread out.  They kind of drift ...

**Comment by Hecter94** [comment] 2022-11-07 15:41
Duplicate of #645

Also see:
https://github.com/endless-sky/endless-sky/issues/1951
https://github.com/endless-sky/endless-sky/issues/2919
https://github.com/endless-sky/endless-sky/issues/5245
https://github.com/endless-sky/endless-sky/issues/5257
https://github.com/endless-sky/endless-sky/issues/6007

**Comment by Koranir** [comment] 2022-11-07 23:20
>If you tell a bunch of ships tightly packed to "Hold Ground" ([H]) and you see them holding ground; but if you then cross to Coalition territory, do some missions, and come back, you find your ground holding ships all spread out. They kind of drift ...

I think that's an engine limitation, and really is not that big of a problem. It's unlikely to be changed in the future.

**Comment by ChuckStarchaser** [comment] 2022-11-08 06:32
Nice!  Thanks!  Yeah, the drift is not a problem.

**Comment by warp-core** [comment] 2022-11-17 16:49
Closing because duplicate.

**Closed by warp-core** 2022-11-17 16:49 UTC
Labels: duplicate
