### ISSUE TITLE
Revert ability for fighters to charge their carrier

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#9131] opened 2023-08-06 02:39 UTC
### Problem Description

As of v0.10.2, a carrier will repair the shields and hull as well as recharge the batteries and fuel of carried ships if the carrier has excess repairs, energy, or fuel to provide. #8385 made it so that fighters can also grab a chunk of energy from the carrier just as they deploy so that fighters always deploy with as much energy as they can get, useful for battery-powered fighters.

But, that PR also made it so that the carried fighters can feed energy back to the carrier. This has made it so that a carrier can be fitted with absolutely zero energy generation of its own and instead fit its fighters for maximum energy production, not only allowing the carrier to use the space it otherwise would have used for energy production for something else (most likely shield generation or hull repair), but also frees up space that would have otherwise been used for the cooling of said energy production, as there is no heat transfer between carriers and their fighters while the fighters are docked (although there is some heat transfer at the moment of deployment and retrieval of fighters).

That is, fighters have now become zero-heat energy generation for their carriers. Just using human tech and a Carrier, I'm able to construct a zero-energy generation Carrier with 10 electron beam weapons and 285 shield generation per second. Docked with Lances and Combat Drones, each Lance is worth 564 energy generation while each Combat Drone is worth 114, resulting in 2,940 free energy generation. This is stronger than a Triple Plasma Core for zero heat production toward the Carrier.
![image](https://github.com/endless-sky/endless-sky/assets/17688683/37e6948b-8c1f-4942-8b95-a69eb09a3239)
![image](https://github.com/endless-sky/endless-sky/assets/17688683/23c4c05e-c7e2-4890-bf66-db2d36383a6f)
![image](https://github.com/endless-sky/endless-sky/assets/17688683/399ddeb9-262c-4930-87e2-1fdd20b37e07)

### Related Issue Links

#3174, particularly https://github.com/endless-sky/endless-sky/issues/3174#issuecomment-340630101 where I highlight that this mechanic effectively gives carriers hundreds of "free" outfit space to carriers.

### Desired Solution

Keep it so that fighters can grab a chunk of energy from their carrier, but not that fighters can send energy back to the carrier.

### Alternative Approaches

Make it so that fighters can only send their energy back to the carrier if the fighter has no energy generation of its own. Although this then just turns fighters into spare batteries, so we should probably just never have fighters transferring anything to the carrier.

### Additional Context

When people say "buff fighters," I don't think this is what they mean. The meta shouldn't be to _not_ deploy your fighters.

**Comment by Hecter94** [comment] 2023-08-06 04:09
![image](https://github.com/endless-sky/endless-sky/assets/15916854/7f3ae4ef-2cda-4370-aaf1-4f455bc2f312)

I probably shouldn't be able to do this to an Emerald Sword and have it still be a functional build.

**Comment by Zireael07** [comment] 2023-08-06 08:46
I wouldn't revert the PR.

I would instead block the 'send energy to carrier' if carrier's energy generation is below X

**Comment by Zitchas** [comment] 2023-08-06 13:44
The description of the problem states that the problem is that fighters have become a zero-heat source of energy. So why not just fix that specifically, and ensure that fighters transfer all their heat back to the carrier too? 

If a stronger nerf is required, then I would suggest eliminating heat dissipation from fighters while docked (they're inside a bay, right? So heat would be dissipated into the carrier.), requiring the carrier to provide *all* the cooling necessary for whatever heat is being produced by the fighters.

Of course, this also brings up the fact that there's currently no mechanical difference between internal and external bays. It would be interesting if there was. For instance, external fighters can use their own heat dissipation and can contribute to regenerating the carrier's shields. However, if the shields go down, then the fighter takes a proportionate amount of hull damage alongside the carrier.

**Comment by Pshy0** [comment] 2023-08-06 20:17
Alternative solutions:
 1. Make the energy transfer from the fighters to the carrier have a limited rate, and only happening when the carrier's energy is low, and lower than the fighter's energy.
 2. Make energy transfer from the fighters to the carrier not 100% efficient and produce heat proportionally to the energy transferred.
 3. Limit the total energy transfer rate from the fighters to the carrier to be proportional to how many energy capacity the carrier has. So to make use of this battery-fighters mechanic, a carrier would need to consume a lot of outfit space installing batteries.
 4. Reserve a chunk of the carrier's energy, proportional to the highest amount of energy the carrier's systems could consume, that cannot be reloaded by fighters. This way, carriers relying on their fighter's power would need extra batteries installed on the carrier it-self, consuming outfit space.
 5. Power off docked fighters so they don't even produce energy (I though that was already the case).

This way, players can still take advantage of the good idea they might come with, to use fighters as outfits expansions by converting fighter bays. This is something I do, especially since fighters are just cannon feeders when launched, and I feel right about it.

About fighters being designed to be launched, and not just ship extensions, the Boxwing is a counter example. It is meant to never be deployed, but instead be used to carry more cargo. For this I would however use the remnant Smew that has similar cargo but has much better stats, twice the outfit space, and a few bunks for passengers.

**Comment by Amazinite** [comment] 2023-08-06 21:34
> About fighters being designed to be launched, and not just ship extensions, the Boxwing is a counter example. It is meant to never be deployed, but instead be used to carry more cargo.

The difference with the Boxwing and fighters like it is that they don't buff the carrier, they buff the fleet via increase cargo and passenger capacity, which is true of any ship that you buy that has cargo or spare bunk space..

**Comment by Zitchas** [comment] 2023-08-06 21:58
Or perhaps more to the point, cargo and passengers aren't combat attributes. Increasing your flagship's cargo capacity just means increased mass, and thus less mobility. So it does actually have a built-in balance. Which, apparently, the "transfer energy without transferring heat" missed out on.

**Closed** 2023-08-18 21:44 UTC
Labels: balance
