### ISSUE TITLE
[Feature Request] Automatically replenish extra crew members on landing.

### ISSUE THREAD

**Issue by starscollide5** [endless-sky/endless-sky#3086] opened 2017-09-28 00:12 UTC
Having to do it manually every time one lands after capture becomes infuriating experience after a few games, even with the help of keyboard shortcuts it's somewhat annoying. 

I propose to add an optional setting that will trigger effortless automatic extra crew member replenishing, the same way required crew members are replenished in the current release.

**Comment by tehhowch** [comment] 2017-09-28 00:28
Easy enough to do: requires setting up a private variable and a setter method on the PlayerInfo class (`desiredCrew`, `SetDesiredCrew`), whenever the flagship changes it gets zero'd, and in the relevant Land method `if(desiredCrew)` then `flagship->AddCrew( desiredCrew - flagship->Crew() )` 
Lastly, alter the HiringPanel's methods to call the setter method with the new total crew amount.

I'm sure an accessibility argument can be made for it as well.

**Comment by jafdy** [comment] 2017-09-28 07:17
This is going to come under "too much automation", I can feel it.
It would be nice though.

**Comment by Amazinite** [comment] 2017-09-28 10:49
Duplicate of #1504
Please close this issue.

**Comment by jafdy** [comment] 2017-09-28 16:06
This is a little more focused than 1504, that was asking for special crew to do this and other things as well where this could just be a button that says "refill to this many crew". MZ also responded in a general way about not wanting to detract from the experience and it is easy to argue this will enhance the experience.

**Comment by tehhowch** [comment] 2017-09-28 16:16
The solution I propose above would not be a button or really visible at all to the player. At most, I would use the Messages function to report `"You hired < added > crew to replace those lost during boarding operations."`, and only for excess crew additions (e.g. not the normal, automatic minimum crew restoration).

**Comment by endlesssteve** [comment] 2017-09-28 18:23
To reduce to a lower or normal number of crew would you them manually fire the ones you didn't want anymore?
Is this like cruise control?

**Comment by tehhowch** [comment] 2017-09-28 19:00
If done as mentioned above, yes. Boarding other ships is an incline that "slows you down". Changing your flagship is like braking (disables the functionality). Hiring and firing is using the Accel / Coast to fine tune the setpoint.

**Comment by tehhowch** [comment] 2017-09-28 23:49
Implemented my earlier comment in #3089. 
Doesn't quite "brake" when changing flagships per se, because the PlayerInfo's `flagship` pointer (which tells the game which ship in the list of ships the player owns is the flagship) is invalidated upon landing (since it can change a fair bit while landed, unlike while in-flight).

If this gets tagged as `unlikely` or `wontfix` I'll be closing it though.

**Comment by starscollide5** [comment] 2017-09-29 00:02
@tehhowch thank you very much! Hopefully it will get implemented. 

I would argue that message is excessive, though.

**Comment by endlesssteve** [comment] 2017-09-29 06:55
Although not a priority for me this change seems reasonable and in line with the existing automatic processes for, hull repair, hyper drive fuel, standard crew and secondary weapon ammunition.
Personally I would like to have the message.

**Comment by BenjaminH333** [comment] 2017-09-30 19:36
A checkbox in the preferences screen or in the hire crew menu on the planet that says something along the lines of "Automatically replenish crew members lost on boarding missions" seems like a nice addition as well.

I'm in support of this feature.

**Comment by KiLEdEnNis** [comment] 2017-09-30 22:35
I think MZ said something like this once: "I don't want to automatize everything in this game, to the point where a player presses 1 button and sits back for a minute"
so probably not going to happen

**Comment by endlesssteve** [comment] 2017-10-01 10:25
Ok we'll put it another way then.

Request for a manual feature to let the player choose the number of crew members added by the existing automatic feature that rebuild the players crew after landing.
QED  Less automation.

This is crews control not autopilot ( had to put that in as nobody spotted my pun the first time).

**Comment by BenjaminH333** [comment] 2017-10-01 18:39
By "automatically replenish" I think I should clarify that I meant it replenishes when you land on a planet. I personally want the ability to turn this off, hence why I suggested a checkbox somewhere.

**Comment by tehhowch** [comment] 2017-10-02 02:56
It's now a hidden preference, default off

**Comment by endless-sky** [comment] 2017-10-06 15:22
I find that I more often have the opposite problem - after a plundering run to earn some extra cash, I forget that I have extra crew on my ship and end up paying them for weeks or months before I finally get around to firing them. (I only hire extra crew when I'm intending to go find some pirates to capture.) So, changing this could cause just as much annoyance and confusion as leaving it as-is.

**Comment by endless-sky** [comment] 2017-10-08 20:37
Fixed by merging #3089.

**Closed by endless-sky** 2017-10-08 20:37 UTC
