### ISSUE TITLE
Be able to sort Job Board missions by payout

### ISSUE THREAD

**Issue by KeronCyst** [endless-sky/endless-sky#1507] opened 2016-08-29 01:31 UTC
, distance, deadline, distance+deadline (?!), and other filters.

**Comment by VladFurman** [comment] 2016-08-29 03:06
Also - have a "days left" counter - most of the time, that's more important than the specific date.

**Comment by endless-sky** [comment] 2016-09-10 17:30
Duplicate of #236.

**Closed by endless-sky** 2016-09-10 17:30 UTC
