### ISSUE TITLE
Illegal outfits on parked ships cause fines when landing on the planet they are parked on

### ISSUE THREAD

**Issue by Quantumshark** [endless-sky/endless-sky#7391] opened 2022-10-16 12:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If a ship with illegal outfits is parked on a planet with security, landing on the planet it is parked on triggers fines for the illegal outfits.

### Steps to Reproduce

Purchase an illegal outfit, place it on a ship, then park the ship on a planet with high security, then take off and land again on that planet. Multiple landings may be required depending on the planet's security.

### Expected Behavior

It does make some sense to have fines issued in this circumstance, but doesn't entirely make sense for the local government to check your parked ships when you land on the planet but not at any other time.
Maybe a more realistic system would be having intermittent checks on parked ships on high-security planets, perhaps with a frequency specified in the planet definition?

### Operating System

Windows 10

### Game Source

Steam

### Game Version

0.9.15 beta

**Comment by Amazinite** [comment] 2022-10-16 14:40
Duplicate of #5090.

**Closed** 2022-10-16 21:27 UTC
Labels: duplicate
