### ISSUE TITLE
Remove In-Game Icon

### ISSUE THREAD

**Issue by Alkallid** [endless-sky/endless-sky#2095] opened 2017-02-03 02:21 UTC
Doesn't the angled view of a flying ship look better than a shipyard view?

**Comment by MessyMix** [comment] 2017-02-03 06:00
Yes. I would PR except I'm worried about cross-platform compatibility. I currently am using the angled Bezerker. I can confirm that a hard replacement works on Mac.

**Comment by Alkallid** [comment] 2017-02-03 06:19
I just deleted the file.

**Comment by endless-sky** [comment] 2017-02-03 18:58
Are you talking about the window icon? What OS are you on, and what circumstances is it showing up in? My impression was that it would only be used for the little icon in the corner of the window, but maybe that's not the case.

**Comment by MessyMix** [comment] 2017-02-03 21:49
@endless-sky:
It's currently using the icon.png in the endless-sky folder.

Which is the largest top-down bezerker image in the endless-sky.icns file, which I find in steam/steamapps/common/Endless Sky/EndlessSky (show package contents)/content/resources/endless-sky.icns.

**Comment by KiLEdEnNis** [comment] 2017-02-03 22:21
you mean the icon you see on the toolbar when the game is launched? for me (Windows 10) I see icon.png as well

**Comment by Alkallid** [comment] 2017-02-04 00:28
I'm on Mac OSX; it's in the dashboard whenever the game is open.

**Comment by CH-de** [comment] 2017-02-09 17:09
Correct me if I'm wrong, but `icon.png` is only used under Windows as window icon (top left corner) as @endless-sky wrote.
The application uses a icon set (graphics of different sizes). For Mac the graphics are in `endless-sky.iconset`, for widows I used the needed graphics out of the same folder to create `WinApp.ico`. The bigger graphics are the 'angled view' and the smaller ones are the 'Shipyard/top-down' ones.
It's the OS that then decides which graphic from the provided icon set is used for the different purposes (for Winows e.g.: Taskbar, Explorer, Desktop, …). This means, that in places where a smaller graphic is needed, you should get the 'top-down' one and else the 'angled view' one. You can check this under Windows in the Explorer by changing the view settings ('Extra large icons', 'Large icons', …).

So the problem seems to bee, that there's not 'the one' icon for Endless Sky. But …

> ---Microsoft design guideline for icons---
**In the smaller sizes, the same icon may change from perspective to straight-on.** At the size of 16x16 pixels and smaller, render icons straight-on (front-facing). For larger icons, use perspective.

Are there any guidelines for Linux/Mac OS?
Who's the designer for the actual graphics? What's his opinion?
Maybe we should use the 'top-down' version only for 16x16?

**Comment by MessyMix** [comment] 2017-02-09 18:47
Top-down goes up to about 64x iirc, where the angled version is then used. the problem is right now that the current icon in the taskbar is the 16x16 one, and not the higher resolution ones. It's pixelated af. Both the app icon (in, say, Finder) and in the taskbar are the same; it works for the app icon because it's tiny, but when it's in the taskbar, it's pixelated and unaesthetic.

**Comment by endless-sky** [comment] 2017-02-18 00:22
On Windows 7, the window icon and the icon in the application switcher are using the "icon.png" file. The task bar icon is apparently using the WinApp.ico icon, which includes the angled view.

I haven't tested on OS X yet, but if it's replacing the dock icon with the "icon.png" file, that's not the intended behavior and I can fix it by just not calling the code to set the window icon on OS X.

**Comment by MessyMix** [comment] 2017-02-18 00:42
Yes. The current dock image is icon.png; I just replaced that manually with the .icns file you find after "open package contents" --> resources.

**Comment by endless-sky** [comment] 2017-02-18 01:56
I found [two](https://sourceforge.net/p/exult/mailman/message/31341368/) [sources](https://forums.libsdl.org/viewtopic.php?p=44300&sid=e9aa881daead901c0d7bd50011ed121f) saying that you shouldn't call SDL_SetWindowIcon() on OS X because it will override the application icon. So even though I haven't tested it yet, I feel pretty confident that just disabling that function on OS X (9445252) is the right solution.

**Comment by Amazinite** [comment] 2017-02-18 02:06
Yup, it's fixed now. Plugin sounds that use to not play are now playing.

**Closed** 2017-02-23 04:01 UTC
Labels: bug
