### ISSUE TITLE
Should Pug Gridfire Turrets damage other Pug ships?

### ISSUE THREAD

**Issue by Admiral-Danforth** [endless-sky/endless-sky#1797] opened 2016-10-30 19:43 UTC
When you have a fleet of Pug Arfectas the #1 cause of death is other Pug Arfectas. Wouldn't it make sense if the Pug designed them, so they would be unable to damage fleets in their ships?

**Comment by toilethinges** [comment] 2016-10-30 19:45
AoE will always hurt everything.

**Comment by Admiral-Danforth** [comment] 2016-10-30 19:46
It seems like the Pug would have made it, so they cannot hurt each other.

**Comment by Pointedstick** [comment] 2016-10-30 20:20
Who knows why the Pug do anything?

**Comment by Amazinite** [comment] 2016-10-30 20:45
This is a duplicate of a previous issue asking that blast radius not damage friendlies. Not sure which one though.

**Comment by Amazinite** [comment] 2016-10-30 20:49
#1341

**Comment by toilethinges** [comment] 2016-10-30 20:54
#821

**Comment by Amazinite** [comment] 2016-10-30 21:04
Was going to post both, but 1341 has MZ's explanation.

**Comment by Admiral-Danforth** [comment] 2016-10-30 22:26
I'm not sure if you understand. There is two questions being asked:
A. Should Pug ships be able to damage each other with AoE?
B. Should AoE affect friendlies?

Question B. has been answered, A. has not.

**Comment by Bladewood** [comment] 2016-10-30 22:28
A. It's fine if Pug ships damage each other, they have cloaking devices and can regenerate themselves and such.

**Comment by Amazinite** [comment] 2016-10-30 22:30
Question A and B are the same thing, though...
"Should Pug be able to damage other Pug"
"Should friendlies be able to damage other friendlies."
Pug are friendly to eachother.

(Please close this issue.)

**Comment by Bladewood** [comment] 2016-10-30 22:31
Not Pug vs Pug, Pug *ships* vs Pug *ships*.

**Comment by Amazinite** [comment] 2016-10-30 22:34
So making Pug ships invincible to certain weapons?
Absolutely not.

**Comment by Admiral-Danforth** [comment] 2016-10-30 22:37
Maybe just the AI?

**Comment by Amazinite** [comment] 2016-10-30 22:38
How would that even make sense lore wise and even logically?

**Comment by Admiral-Danforth** [comment] 2016-10-30 22:41
I've tried this, but in theory you could use this to your advantage and use it against the Pug Arfecta.

**Comment by Amazinite** [comment] 2016-10-30 22:43
>How would that make sense lore wise and even logically?

**Comment by KiLEdEnNis** [comment] 2016-10-30 22:49
> Pug are friendly to eachother.

remember MZ may have leaked 1 "Pug faction", and that there are apparently gonna be more? :3

**Comment by Pointedstick** [comment] 2016-10-30 22:56
@Admiral-Danforth You're tempting me to create my own Please-Close-This-Issue sockpuppet account… 😝

**Comment by Amazinite** [comment] 2016-10-30 23:23
The answer is yes.

**Comment by toilethinges** [comment] 2016-10-31 02:11
@Amazinite 

> > How would that make sense lore wise and even logically?

Wyrmholes! (See what I did there?)

**Closed** 2016-11-06 02:58 UTC
