### ISSUE TITLE
Planet/moon labels may be obscured by other planets/moons

### ISSUE THREAD

**Issue by lheckemann** [endless-sky/endless-sky#2340] opened 2017-03-30 12:04 UTC
On systems with a landable moon orbiting a landable planet, zooming out may cause the label for either to be obscured by the other. I think the label should be "above" the bodies themselves.

**Comment by Amazinite** [comment] 2017-03-30 14:35
I'm pretty sure they're intended to not overlap at normal zoom, but higher zoom levels isn't guaranteed. Same as the map. Zoom out to just before the labels get removed and a bunch of stuff overlaps.

**Comment by lheckemann** [comment] 2017-03-30 14:39
Well, in the Altair system, Shiver's moon is close enough to overlap its label at any zoom level. My point is that the overlap should give priority to the label, not the planet, it looks awkward in the current way.
![2017-03-30-153851_1678x1029_scrot](https://cloud.githubusercontent.com/assets/341954/24509722/03da2efa-155f-11e7-8130-cd900ad93cfe.png)

**Comment by KiLEdEnNis** [comment] 2017-03-30 15:58
there is a sector around the Deep/Dirt Belt; a giant-ass gas giant w/ a moon, and you can land on the moon
you already need to move away to autoland, but I think this issue will be the worst w/ that sector

**Comment by Amazinite** [comment] 2017-03-30 16:25
If that's what you're talking about then this is essentially a duplicate of #1154

**Comment by lheckemann** [comment] 2017-03-30 16:28
But given that this is a HUD element, surely it shouldn't be obscured by the environment?

**Comment by DingusShingleton** [comment] 2017-03-30 17:16
Should the border also be drawn over ships then? Personally I think it looks better this way. Yes it's a hud element, but actual objects should take precedence IMO

**Comment by MessyMix** [comment] 2017-03-30 18:29
HUD elements should be drawn on top of the environment, imo, such that it seems to be added onto the backdrop.

**Comment by lheckemann** [comment] 2017-03-30 19:25
The planets are effectively just decoration. The ones that can be interacted with have the HUD to mark them, and I think that it should be drawn over the planets themselves, but under ships — because ships may need more immediate attention, and because it doesn't look awkward.

**Comment by Wrzlprnft** [comment] 2017-03-30 19:31
i like the subtle jarvis style hud, with the hud really just being a background thing.

**Comment by endless-sky** [comment] 2017-03-31 02:34
The labels are not terribly important in most cases - they serve more of a decorative purpose, and also provide a hint that you can land somewhere. So I'd prefer not to bring them too far up the visual stack.

In the game engine, what's going on is that a separate thread assembles a list of all the sprites that need to be drawn in a given frame, and what order they should be drawn in. Then, the GPU thread just goes through that list as fast as possible and draws them. There's no dividing line in the list in between the planets and the ships, so unless I switched to maintaining several different lists there would be no way to draw the labels in between the two.

**Closed** 2017-05-29 17:20 UTC
Labels: mechanics
