### ISSUE TITLE
Escort gets stuck on an infinite loop landing and departing the same planet

### ISSUE THREAD

**Issue by docauntry** [endless-sky/endless-sky#710] opened 2016-01-24 16:47 UTC
I'm not certain how this happened, but my freighter escort now only lands and leaves the same planet continuously. If i ask it to fight something, it will do so, then it will resume it's infinite landing/departing sequence. Hold position also works.  It won't follow me on hyperjumps and thus can't trade with it, which means my save file is now going to the crapper since I'm 1.1M in debt and I needed the extra space to make it up.

**Comment by mrec** [comment] 2016-01-24 18:06
It'd probably help the devs if you attach a savefile.

Might also be worth double-checking that you didn't do something embarrassing like sell its hyperdrive...

**Comment by masterpierround** [comment] 2016-01-24 19:20
One question: did you repair it just before landing? I've noticed this behavior in AI ships after they get repaired.

**Comment by Gkramme** [comment] 2016-01-24 21:12
If you are jumping to a unreachable place, such as Korath space, and your escort cannot jump there (due to lack of jump drive) it will assume this motion.

**Comment by docauntry** [comment] 2016-01-24 23:59
Yep, didn't realize i sold the hyperdrive. Problem solved. Thanks!

**Comment by mrec** [comment] 2016-01-25 03:19
You can close this issue (button at bottom right, next to "Comment") if you're satisfied that it's not a bug in the game.

**Closed** 2016-01-25 08:18 UTC
