### ISSUE TITLE
When escorts are recalled to the Roost they go to the middle of the ship.

### ISSUE THREAD

**Issue by ixPost** [endless-sky/endless-sky#8977] opened 2023-07-01 14:51 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Escorts will go to the middle of the Roost and suddenly pop on the side arms of Roost. It appears very unnatural.

### Steps to Reproduce

1. Buy a Roost,( Nest, or Skein).
2. Buy Flinches( or any other fighter).
3. Depart and deploy the fighters.
4. Recall the fighters.
5. Observe how they go under the Roost, and then suddenly teleport and pop into place.

### Expected Behavior

They should go under a slot and lock onto it.

### Operating System

Ubuntu 22.10

### Game Source

Other (please describe)

### Game Version

0.9.8                    Got it from Ubuntu Software source: ubuntu-jammy-universe (deb)

**Comment by lumbar527** [comment] 2023-07-01 14:53
Yep, fighters don't fly to the bays but to the middle of the ship.

**Comment by mOctave** [comment] 2023-07-02 01:49
This is how all bay-based ships work, for all carriers. It would be nice for the Roost if fighters went to bays instead, and for some other ships having fighters all follow a certain approach path to their hanger and not going in the back wall, but currently that's just not how it happens, and it would be a lot of work (both in terms of code and for content editors) to make fighter/drone paths logical.

That said, it shouldn't be impossible to create an attribute for ships (or bays) that makes fighters target them instead of the ship's centre. That would solve the major issues with this kind of thing, and the primary concern here.

**Comment by Hecter94** [comment] 2023-07-02 05:01
ref: https://github.com/endless-sky/endless-sky/pull/6130

**Comment by Saturnalia9** [comment] 2023-07-25 22:14
I thought I saw a previous related PR. Thanks, Hecter. xD Wasn't sure if I was going insane or not.

**Comment by Amazinite** [comment] 2024-03-07 07:39
Duplicate of #957.

**Closed by Amazinite** 2024-03-07 07:39 UTC
Labels: mechanics
