### ISSUE TITLE
TDR crashes (possible solution, need user input)

### ISSUE THREAD

**Issue by whismerhill** [endless-sky/endless-sky#3516] opened 2018-01-08 14:33 UTC
hello, continuing from this issue : https://github.com/endless-sky/endless-sky/issues/2067
who was wrongly named (because it happened over much more driver revisions than what's written in the title as seen in the comments) & wrongly closed (because it never got fixed whereever the issue comes from, be it an nvidia issue, an endless sky issue, both, or neither)

so here I am to reopen this issue and get people possible **feedback** from people who already experienced the issue.
Please do state : 
 -if you still have TDR crashes ? ( _a TDR crash happened when you see the message : "Display driver stopped responding and has recovered," and in event viewer you should see something like "A TDR has been detected. The application must close.  Error code: 7  (pid=5152 tid=5940 endlesssky.exe 64bit)"_ )
-which nvidia driver revision you're running  ?
-which endless sky version you last played with (github, 0.9.8 , 0.9.7 ......) ?

Because **I just built endless sky with Visual Studio Community, left it running overnight without any problem**
steam thread  : http://steamcommunity.com/app/404410/discussions/1/143388511231569856/?ctp=4
current github build : https://github.com/whismerhill/endless-sky/tree/VS2017

Thank you very much.

Thanks & Testers : 
 - M\*C\*O from discord left it running overnight in space without issues however he doesn't have TDR.
GTX  1060 6GB, DirectX12, OpenGL4.6, Drivers v.388.71, Windows 10 64bit

**Comment by endless-sky** [comment] 2018-01-17 02:00
Closing this because this appears to just be an announcement of the fact that you have no issues and have been unable to reproduce the named issue.

**Closed by endless-sky** 2018-01-17 02:00 UTC

**Comment by whismerhill** [comment] 2018-01-17 02:41
what the fuck ?
@endless-sky

**Comment by KiLEdEnNis** [comment] 2018-01-17 02:45
> what the fuck

don't, please

**Comment by whismerhill** [comment] 2018-01-17 02:51
I don't care. I've spent HOURS diagnosing this, and he just closes this like right out of the blue without even trying to contact me first

**Comment by whismerhill** [comment] 2018-01-17 02:52
I have a lone tester beside MCO who is currently testing out the executable I compiled with VS
and no the problem is not gone and a bunch of people were affected from the steam forums and whatnot. I just can't believe this.
Alright I'm done seriously

**Comment by whismerhill** [comment] 2018-01-17 03:05
the only reason this isn't a PR instead of an issue is : 1 : I wanted more testers & feedback
2 : because you previously stated you didn't want to compile in yet another compiler which needs to be maintained afterward  : "VS", however the fix to this issue seems to be exactly that

it's also pretty hard to give updates since I'm dependent on people's willingness to play & test stuff out
Also you can't say I have no problem when the possible fix is to compile in VS through my fork of the thing

**Comment by Tadrix** [comment] 2018-01-17 03:30
Mby make a PR and mark it as a work in progress?

**Comment by KiLEdEnNis** [comment] 2018-01-17 03:42
@Tadrix I appreciate your input, but from what I understand it's not that simple
