### ISSUE TITLE
Bug: Profit Column

### ISSUE THREAD

**Issue by wambat1** [endless-sky/endless-sky#2339] opened 2017-03-30 06:08 UTC
There seems to be an issue with the display on the profit column. I don't know if this is exclusive to Coalition space; that is the only place I have observed it.

![profit column](https://cloud.githubusercontent.com/assets/16410142/24489854/8bcf09ba-14d4-11e7-973c-d405259bc9aa.jpg)

**Comment by jafdy** [comment] 2017-03-30 06:49
You have some of that commodity in in your fleet so it is showing the profit you would get if you could sell it there.

**Comment by wambat1** [comment] 2017-03-30 07:08
Negative; that is displaying profit from a previous run. You can see there is nothing in my cargo. I had sold electronics at this port, but the food was sold at a previous port, and the more different commodities I sell at different ports the more of the profit column gets filled up with antiquated profit margins.

**Comment by KiLEdEnNis** [comment] 2017-03-30 10:47
a big part from your fleet is not in-system
I've only had this when my escorts had commodities & weren't in-system, once they are & I sell the commodities it disappears
and I think buying & selling again works too
should have made the issue 3 days ago when I saw it :P

**Comment by Bladewood** [comment] 2017-03-30 11:12
Yes, the problem is that any fleet ships that may have been carrying those goods are out of the system.
I've experienced this many times before.

**Comment by endless-sky** [comment] 2017-04-02 18:24
If this were fixed by not showing "profit" if all your stock of that commodity is in other systems, it would introduce a new problem that commodities show up as being able to be sold for a profit or loss as soon as you buy them. So, I don't see any way to completely avoid confusion in these cases.

**Closed** 2017-05-29 17:19 UTC
Labels: mechanics
