### ISSUE TITLE
Reputation settings in npc conversations have no effect

### ISSUE THREAD

**Issue by jjhankins** [endless-sky/endless-sky#3196] opened 2017-11-03 17:06 UTC
If you assist a merchant and trigger this mission, your reputation doesn't get changed.

```
mission "oops"
	assisting
	destination "Earth"
	on offer
		conversation
			apply
				"reputation: Merchant" <?= -10000
			`I hate you now!`
				accept
```

**Comment by jafdy** [comment] 2017-11-03 18:05
It strikes me that you could just put that in the `on offer` without the need for the `apply`.

**Comment by tehhowch** [comment] 2017-11-03 18:16
@jafdy I think that the posted mission is a simple illustration of a syntax that apparently does not work, yet should.
Based on the conversation in the real mission, I imagine the reputation value is different (or perhaps not even changed)

**Comment by jjhankins** [comment] 2017-11-03 18:35
The mission where I first ran across the problem involved an npc assist where I want the npc to become hostile after the assist.

**Comment by KiLEdEnNis** [comment] 2017-11-04 04:16
sounds like an ungrateful bastard to me

**Comment by tehhowch** [comment] 2017-11-06 20:29
Its worth noting that the OP gives an example of an `on offer` conversation (albeit one that is created when assisting a random, non-special NPC) and not a conversation that is caused by completing an NPC block - the latter would be:
```
mission "..."
    ...
    npc assist
        ...
        conversation
            ...
```

Are rep changes having no affect in both cases (conversations in an `on ....` node within a mission definition, and within a mission's NPC block), or just the latter?

**Comment by jjhankins** [comment] 2017-11-06 21:43
The original trouble involved an NPC block, and I ran the test above to confirm it, so both cases.

**Comment by tehhowch** [comment] 2019-11-12 05:16
@jjhankins please verify in the latest release if this is still an issue

**Comment by Amazinite** [comment] 2021-05-03 16:44
Hello?

**Comment by quyykk** [comment] 2022-11-21 20:32
This is working now, so we can close this.

**Closed by quyykk** 2022-11-21 20:32 UTC
Labels: mechanics
