### ISSUE TITLE
All ship gear lost when loading savegame

### ISSUE THREAD

**Issue by mikezila** [endless-sky/endless-sky#85] opened 2015-08-30 05:51 UTC
I'm not sure what event caused it, but I just loaded a savegame and got some flavor about how I don't have thrusters installed, and upon checking my outfitting I have no outfitting gear at all.  No thrusters, steering, or the cargo extension I had bought.  Worst of all no hyperdrive, and I'm in a system with none for sale.  I had been keeping snapshots, so I can roll back to the previous and continue, but it's is pretty serious.

**Comment by endless-sky** [comment] 2015-08-30 13:41
That's a long-standing, very rare bug (#33) that I have not been able to track down yet. I've never been able to reproduce it on my own computer, despite doing a lot of testing.

**Comment by mikezila** [comment] 2015-08-30 21:35
I have snapshots from right before it happened, would it be helpful for me to upload my save someplace for you to examine?

**Comment by endless-sky** [comment] 2015-08-30 22:09
Sure, if you don't have a convenient place to upload, you can also just post it in a new thread here:

https://groups.google.com/forum/#!forum/endless-sky

Also, what OS are you running?

**Comment by mikezila** [comment] 2015-09-01 02:23
I've zipped the games save folder in my Roaming and put it on Onedrive.

http://1drv.ms/1ht6dRM

I'm using Windows 10 Pro x64.

**Comment by captainexplode** [comment] 2015-11-05 01:50
I had the same issue twice now. 

It always happens after I am killed by a pirate and reload. 

Not sure if you have posted a fix to this somewhere else, let me know if I can send any useful info. Win 7 64 bit

**Comment by endless-sky** [comment] 2015-11-17 01:00
This is probably a duplicate of #33, which in turn was probably due to the effects of plundering being delayed until the game was reloaded.

**Closed by endless-sky** 2015-11-17 01:00 UTC
