### ISSUE TITLE
Outfit Comparison Table and Ratios

### ISSUE THREAD

**Issue by mrunderhill89** [endless-sky/endless-sky#4830] opened 2020-02-18 17:52 UTC
Hello.

Over the past couple of months I've been filling out pages on the Fandom wiki comparing different outfits, and I was wondering if the outfit screen could be updated to make it easier to compare outfits without needing to run a calculator, an Excel sheet, or a browser alongside the game.

Here's a mock-up of what I have in mind:
![endless_sky_outfitter_mockup](https://user-images.githubusercontent.com/3249430/74762578-fb871d80-5232-11ea-8ee3-51eb11ada4de.png)

The basic idea is that when you select an outfit, you have the option of comparing it with any other outfit that shares attributes with it (besides cost). When comparing outfits, their attributes are shown next to each other in a table along with the difference between them, color-coded to show which is better (i.e. lower cost, space, and heat, but higher energy). Additionally, I've added energy/space and energy/heat ratios to better judge efficiency.

How hard would this be to implement? And do you have suggestions for improvements?

**Comment by MCOfficer** [comment] 2020-02-18 17:58
Related: #376, and #500 could be useful.

**Comment by Zitchas** [comment] 2020-02-18 18:33
I'm not sure about the "better" or "worse" part - that's a judgment call - but plenty of games have color codes or up and down arrows next to the various values to highlight where the differences are and in what direction. Having these could be useful. 

Likewise, as a default behaviour, it would be useful if - when the player highlights an outfit that has the same attribute as something they already have on their ship, it has the arrows next to it as appropriate. This, however, would require the game to support multiple arrows, as if the player had, say, three different batteries onboard and was highlighting a new one, there would be three different comparisons going on.

**Comment by Amazinite** [comment] 2020-02-18 19:16
This seems like a duplicate of #376 and #4106.

To note, you can already do comparisons on the map by selecting one outfit (or ship) and shift+clicking another. This doesn't tell you the difference, though, only allowing you to easily see the stats side-by-side. No such functionality exists for being in the outfitter (or shipyard) though. 
![image](https://user-images.githubusercontent.com/17688683/74769251-0ef8af80-5258-11ea-9266-deec8b3433de.png)

At most I'd expect it to be the case that this map comparison be added to the outfitter and shipyard in some way for side-by-side comparisons of items, but going further to the point of providing ratios between stats and highlighting the difference or whichever is better/worse steps into the realm of doing to much automation for the player and gets away from the intended mostly-monochrome UI. (See #1118, #1539, #2671, #3436, #3963 for a related situation with commodities.)

**Closed** 2020-02-23 04:51 UTC
Labels: duplicate
