### ISSUE TITLE
Enhancement: Tow Ship for "stuck" fleet

### ISSUE THREAD

**Issue by gerbosphere** [endless-sky/endless-sky#823] opened 2016-02-28 17:39 UTC
I have had plenty of occasions where my ships get stuck in a landing cycle, stuck without a hyperdrive in an uninhabited system, stuck in a habitable system, and not responding to commands...there's about 10 of mine like this currently.

With that in mind, instead of destroying a ship or leaving it parked for all eternity, and to avoid plenty of questions about "bugs" like this in the future, why not have a cosmic tugboat-type ship that can tow other ships?  It can be clunky, very slow-moving, no cargo space, enough passenger space for a crew, and minimally weaponized, but can hold any ship long enough to tow it to a planet.  Even if it's only sold in one system, a new ship like this would be highly convenient for someone like me who can't seem to stop this issue.

**Comment by jmhorjus** [comment] 2016-02-29 17:46
Unfortunately making new a new game mechanic, AI support, new ship stats, sprites, descriptions, etc is quite a job and might not happen for long time.  
However, what about this: we add a new button similar to "park/unpark" that the player can use from the player-info screen while landed: You pay 5% of the value of one of your owned ships to have that ship "retrieved" for you. It is repaired (if it was disabled) and instantly appears in the current system. 

Maybe have the cost be pretty low to retrieve from friendly systems, higher to retrieve from uninhabited systems, and highest to retrieve from hostile systems.

**Comment by GalacticRuler** [comment] 2016-03-01 05:25
But what about jump-only systems?

**Comment by lehgogh** [comment] 2016-03-01 14:48
If this can't be done already, perhaps allow us to move outfits between ships and equip them without landing? This would let us jump to a populated system, buy a ramscoop, and put it on our ship until we can land.

**Comment by jmhorjus** [comment] 2016-03-01 16:55
@GalacticRuler Probably would need a "retrieval not available" flag that could be set on systems. The motivation behind this is convenience, not realism though. People always complaining about their ships being stuck. =P
@lehgogh Yeah, "reconfigure ships while flying" has been requested before and may be on the road-map, I'm not sure.  My favorite suggestion for that was that you need a huge "repair bay" outfit, which would go on your flagship and enable boarding escorts to access their outfitters screens to install/uninstall outfits from your cargo. The first step in that direction is just allowing outfits to be purchased "as cargo" - another long-requested feature which is planned to be added eventually.

**Comment by KiLEdEnNis** [comment] 2016-08-15 17:38
just got an idea (may be a bad one), although it'd be very hard, it basically allows any ship to be a tow ship
a special (quite large) turret that you can somehow "link" on an escort ship (by targetting it and pressing a special hotkey), which consumes energy etc. (may need balancing to avoid abuse)
after that you can jump WITH the towed ship, although (if the escort has no drive) your drive would have to be used for 2 ships, a.k.a. double the fuel (from the ship that tows, because you can't teleport fuel between ships)
if the towed ship doesn't even have engines, it would still come after, and if you land while linked so does the linked ship

it's very complex, weird, semi-unrealistic and possibly bad, but it does it's job; fixing stuck ships
up to others to Judge if it's a decent idea

**Comment by KevinKorzekwa** [comment] 2016-08-16 01:32
@jmhorjus I really like that, although I think the cost is tiny.  Instead, what about hiring a small fleet of Skylances to be your towtrucks, for 2000% of the credit value of the ship?   And make the feature only available after the human storyline is over?

@KiLEdEnNis That's a decent idea, if you can figure it out and code it, that would be cool.  Or at minimum, a beam weapon that gives hyperspace fuel with some sort of efficiency loss might be a good first step.

**Comment by jafdy** [comment] 2016-08-16 13:13
Out of interest do you have the foggiest idea what a Skylance is?

>~Skylances~Deadlest-weapons-in-the-game to be your towtrucks

**Comment by KevinKorzekwa** [comment] 2016-08-16 13:21
Lol oops, meant Skylarks. It's too funny to fix in an edit though, so it stays.

**Comment by KiLEdEnNis** [comment] 2016-08-16 14:04
@KevinKorzekwa unfortunately I do not have any coding knowledge (I turned 17 9 days ago), but when school starts (last exam year) I have to learn the basics of C++
but for now if my idea would be added (if it's even possible, since it's very hard to make a special hotkey-linking beam ray "weapon") someone else who can code should make it

> Or at minimum, a beam weapon that gives hyperspace fuel with some sort of efficiency loss might be a good first step.

ships have a tiny amount of ramscoop, and you can get a ramscoop to give them fuel, I don't think the issue is fuel, more like an actual AI bug or missing outfits(?)

**Comment by KevinKorzekwa** [comment] 2016-08-16 15:52
@KiLEdEnNis Glad to hear you're getting an introduction to programming! You might be interested in reading up on how to do what's known as psuedocoding, especially in the context of following along as you read through MZ's commits and as a prep for your C++ course.

And you're right, just giving fuel to ships would not fix the bug in this issue of ships being stuck in a loop, or just deciding not to jump even though enough fuel is there.  That sounds like it needs some code.  What I envisioned for the beam weapon idea thingy was a way to efficiently give your entire fleet enough fuel to jump together, instead of having to run around and top up each one individually.

**Comment by KiLEdEnNis** [comment] 2016-08-16 17:23
@KevinKorzekwa thanks, gonna be a programmer if it goes well (I ain't stupid at all)

on a less relevant topic; the RNS should get a few new unique ships; at least a Battleship (created near he end of the FW story), but maybe cool unique ships like a "refueling" ship, and maybe a design the Deep makes mid-story which is a ship that increases shield regeneration of nearby allied ships, so a "support" ship, because the Navy is a bit boring; missile ship, basic scanner ship, standard ship, big standard ship, even bigger "standard" ship (Carrier)
the FW & Syndicate use basic Merchant ships (the FW more than Syndicate), but all 3 main factions should get a few more ships, even if they're just a better version of the original; like the Frigate gets an upgraded version (between Frigate & Cruiser; the Destroyer)

**Closed** 2016-10-27 01:20 UTC
Labels: enhancement
