### ISSUE TITLE
lack of support for in-space cargo and crew

### ISSUE THREAD

**Issue by downRightCoder256** [endless-sky/endless-sky#4969] opened 2020-04-02 06:56 UTC
**Describe the bug**
Right now, the game lacks the ability of proper distribution and saving cargo and mission location in savefile, assuming that the flagship has all the cargo. This commonly leads to some uncomfortable situations (eg. players having to either reload games or fail certain missions) and hacky behaviors (eg. players can just reload their game at the last savefile, and any missions not completed because cargo was not in system will be completed).

**To Reproduce**
(assuming player has a fleet of one or more ships)
1. Accept some mission requiring cargo or crew carrying. 
2. Select a ship with necessarily lower cargo and crew carrying capabilities than the mission requires as a flagship.
3. Depart. Order escorts to hold position.
4. Jump and land on planet NOT required to complete mission.
5a. (control) Depart. Nothing will happen.
5. Exit and load the game at the latest save. Depart. Game will warn the player that he will fail some missions.

alternatively:

4. Land on planet REQUIRED to complete mission
5. The game will give the warning to depart and wait for escorts carrying mission cargo to enter system.
6. Exit and load the game at the latest save. The missions will be completed.

**Expected behavior**
The game warned that the missions will fail and the mission was complete at reload because at the reload the game has associated any cargo with the flagship, when that wasn't the case.

**System (please complete the following information):**
 - OS: MacOS 10.15.3 "Catalina"
 - Game Source: Github
 - Version: 0.9.11
**Additional context**
i would consider OS and version to be trivial, since this was in the game for quite a while

**Comment by tehhowch** [comment] 2020-04-02 12:07
Duplicate of https://github.com/endless-sky/endless-sky/issues/1624

**Closed** 2020-04-02 12:07 UTC
Labels: bug, duplicate
