### ISSUE TITLE
links on map flicker and display random artifacts

### ISSUE THREAD

**Issue by ChamEV** [endless-sky/endless-sky#4386] opened 2019-06-21 09:15 UTC
Artifacts appear on screen when the star map is open, links between stars flicker.  This happens even when there is no user input and the game state is not changing.

Video demonstration:  https://streamable.com/hmv51 (ignore new trade stuff on left, it's unrelated)

Screenshots of one of the artifacts: 
![vlcsnap-2019-06-15-23h52m00s510](https://user-images.githubusercontent.com/51398924/59910425-b6220000-93c6-11e9-9ab0-e1d566210ce5.png)
![vlcsnap-2019-06-15-23h49m06s526](https://user-images.githubusercontent.com/51398924/59910424-b6220000-93c6-11e9-850d-11fbb331dfb8.png)
second one was while dragging between main galaxy and SW pug galaxy.

It looks like the links are being drawn from bad data on some random frames.  I compiled a version of the game with MapPanel::DrawLinks() disabled and observed no artifacts.

DrawLinks() is called each frame, and goes through each link and calls LineShader::Draw(...) which has a lot of openGL code that I'm unfamiliar with.

I have also seen this with travel plan links, which use the lineshader as well but with a thicker line.

My theory is some variables in the GL code are not being properly reinitialized and are being reused incorrectly.

OS: Windows 7, nvidia 1060, older drivers 388.31.  I generally don't update unless there are problems with the games I play.  This issue seems likely to be independent of graphics drivers anyway.  I have no application specific settings for endless sky in the NVidia control panel, it is set to let the 3D applications decide.  Also no overlays on.

Zarvox also indicated he has this issue, he has a 1070  and his graphics drivers are up to date.  No word on his OS.

This user also has the same issue, 3 days ago, user self closed: https://github.com/endless-sky/endless-sky/issues/4381
Potentiall similar issue with a different part of the game: https://github.com/endless-sky/endless-sky/issues/3414

**Comment by ChamEV** [comment] 2019-06-27 05:50
I reduced the problem to just LineShader and compared it to RingShader.

To easily reproduce this if you're affected at all, commenting everything out from MapPanel::Draw and replace it with this.  The flickering happens about 10 seconds after opening the map screen.

`glClear(GL_COLOR_BUFFER_BIT);`

`for(int i = 539; i >= 0; --i)`
`{`
`	LineShader::Draw(Point((i/90)*300 - 800,(i%90) * 10 - 500), Point((i/90)*300 - 700,(i%90) * 10 - 500), LINK_WIDTH, red);`
`	// RingShader::Draw(Point((i/90)*300 - 810,(i%90) * 10 - 500), 7.f, 5.f, Color(.3,.3,.8,1));`
`}`

Here is what it looks like https://streamable.com/o63eb

Notably the earlier lines are the ones most likely to randomly flicker, their position must be corrupted or overwritten somehow.  Sometimes you see an artifact on screen, this is from the corrupted position, artifacts are always the same color as the links, the color is never corrupted despite being specified after.

The data being fed to the shader is good, so the corruption must be happening in the shader or  potentially graphics card drivers.

If you comment out the line shader, and put in the ring shader, there is no flickering.  They are very similar classes/shaders which to me suggests this is a problem that can be fixed and is isolated in the line shader.  Strangely if you draw both the line and ring shaders one right after the other, there is still no flickering.  https://streamable.com/lstzf

Something about calling the line shader repeatedly must be production the gl_position corruption, and the ring shader somehow prevents it.

**Comment by jafdy** [comment] 2019-06-27 08:47
I don't see it, those lines look rock solid to me.

**Comment by Zireael07** [comment] 2019-06-27 09:02
@jafdy: Second column from the right flickers in the picture that is labeled as flickering.

**Comment by MCOfficer** [comment] 2019-06-27 11:04
it strikes me as interesting that this problem has not been reported for years, but now we have 3 occurrences in a very short timespan. [Assuming that this is indeed caused by a recent change:] Since it does also occur with older drivers, and the LineShader code hasn't been changed for years, that only leaves the changes to the map itself as possible trigger. are you sure the data fed to the shader isn't the cause?

**Comment by oo13** [comment] 2019-06-27 15:04
If I remember correctly, I noticed this problem more than a year ago at least.

OS: Debian GNU/Linux
Graphic Driver: nVidia

Some rings and texts is flickered, too.

**Comment by ChamEV** [comment] 2019-06-27 22:50
MCOfficer I noticed this problem several years ago when I played through then.  At the time there was also random occasional flickering in the main game panel as well, presumably the stars, but that no longer occurs.

The data going into line shader was specified completely by the for loop shown in the third post here.  It does not change at all between frames or otherwise.

oo13 do you have that issue currently for text and and rings?  What gfx card?

So far I've only heard of this being an issue on nVidia cards.

**Comment by oo13** [comment] 2019-06-28 15:25
@ChamEV Please ignore it, because I cannot reproduce it now. Probably I modified something at that time.

However, some rings are flickered now when I kill LineShader::Draw() by inserting return at the first line in the function, or comment out calling MapPanel::DrawLinks().

I use GTX 1050 Ti.

**Comment by ChamEV** [comment] 2019-06-28 23:12
The issue turns out to be power management mode.  Originally when looking through nVidia control panel settings I tested AA, shaders, texture settings and more, but I apparently missed the power management one.

This issue seems to affect nVidia 10 series cards and later (1050, 1060, 1070, 1080, etc...), including current drivers as per Zarvox.

By default, PMM (Power management mode) is `Optimal power` which means throttling the clock down whenever it thinks it can.  `Adaptive` is the middle setting but was not enough.  The highest setting, `Prefer Maximum Performance` works and results in no flickering of links or anything else for me.

Bug characteristics:
* Begins ~8 seconds after opening the map.  PMM thinks it can rev down because ES isn't doing much.
* Only happens in full screen.  In windowed mode the graphics card is taking care of drawing the rest of the screen and which keeps PMM revved up.
* Only happens to the first 240 or so lines, somewhat randomly.  Makes sense that after this many, PMM is ramped back up.
* Only the lineshader's vertex shading was messed up, which suggests while not revved up, input data was not getting to the vertex shader in time and it was running with whatever garbage data was set.

3 Solutions.
* Figure out how to tell graphics cards that it needs to be revved up for the draw phase, and when done that it's safe to rev down.  Or figure out how to make the shader wait until it's ready.
* Advise people with this issue to adjust the Power Management Mode to set `Prefer Maximum Performance` as an program specific setting.
* Draw system circles before any links/worholes are drawn.  These things almost never overlap even on a full map, only wormholes intersect systems, and they're a simple very thin line when not on the travel path.

The later works for me, but it may result in rings flickering for some people as oo13 suggested.  For whatever reason, the RingShader does not exhibit the same problem as the LineShader on my 1060, perhaps due to slightly increased complexity.  Additional testing would be needed.  Can also give the graphics card some off screen busy work with some sprites to rev it up.  These are band aid solutions, the best one would be advising the graphics card to rev up itself.

**Comment by Pointedstick** [comment] 2019-06-30 20:54
Sounds like this is an upstream issue in the NVIDIA driver. Can you report this to NVIDIA please?

Is there anything to be done here for this? Seems like no...

**Comment by jafdy** [comment] 2019-07-01 07:54
Has anyone actually seen this while running on intel or AMD graphics? Circumstantial evidence that it only appears on nVidia systems isn't reliable due to the prevalence of such systems.

**Comment by Amazinite** [comment] 2019-07-01 07:56
Running on Intel graphics and never had this issue or anything similar. Nvidia seems to cause a lot of problems in general for some reason.

**Comment by ChamEV** [comment] 2019-07-01 08:01
There's a reason I don't update my graphics card drivers unless something is noticeably broken.  Nvidia's drivers like to randomly break things.  This case was an exception as if I updated and it fixed it and other people had the issue, it would become hard to isolate and test.

**Comment by ZBok** [comment] 2019-07-02 05:23
I've been seeing these artifacts since forever, including earlier today. I just now switched my Nvidia setting to "prefer max performance" and it seems to be fixed.

**Comment by quyykk** [comment] 2022-11-21 19:40
Seems like a graphics driver issue (or even GPU), so I'll close it (and we haven't seen reports for this for a long while).

**Closed by quyykk** 2022-11-21 19:40 UTC
Labels: bug
