### ISSUE TITLE
Cargo space should be available for use at outfitters

### ISSUE THREAD

**Issue by lnxworx** [endless-sky/endless-sky#2182] opened 2017-02-24 13:26 UTC
Cargo space should be available at outfitters to purchase extra items.  Currently cargo space can be used to scavenge disabled ships where items end up in your cargo hold to be either sold or installed at outfitters.  There should be an option to add extra outfits to your cargo hold as well.

Example1  Send a freighter to Capella to pick up a load of Particle Cannon's to be used to outfit your fleet that is parked in Sargas.

Example 2 Send a freighter into Hai space to pick up a load of Tracker missles.  These can be stored in cargo until needed.  If the ship has a Tracker Pod these could be used to reload the weapon.  The reload wouldn't be instantaneous but could take X second/minutes based on the assumption that you have to send crew to get the ammo from the cargo bay, and move it to the launcher and reload the weapon.  A minimum amount of crew would be required to pull off the reload.  Perhaps this can be mapped to another keyboard shortcut so you have to actively choose to reload.

Example 3 Another twist on this could be the option to be a gun runner from system to system.  With the result of being scanned and caught either ending in a fight or your ship being boarded and all cargo confiscated thereby causing a net loss.  This can be balanced using the combat rating.  Lower combat rating you would be scanned, boarded and cargo confiscated.  Higher combat rating you can be scanned, boarded, cargo confiscated and end up in a fight.  A radomizer could be used to determine if you get disabled or destroyed in a fight.  If disabled cargo confiscated (net loss) if destroyed try again.

Example 3 makes an assumption regarding the cost of outfits changing from system to system like commodities.  I will open an another issue detailing that idea rather than muck this one up even further.

**Comment by Rakete1111** [comment] 2017-02-24 13:47
I think this is already possible: Ctrl + click on your selected ship in the outfitter, then you can buy the outfits directly into your cargo hold.

**Comment by lnxworx** [comment] 2017-02-24 13:52
Thanks Rakete1111 that seemed to work, but I have to go to a couple different systems to see if I can buy any item.  The system I am in right now will only allow me to buy back something that I just sold from cargo or missles.

**Comment by MessyMix** [comment] 2017-02-24 14:06
I'm pretty sure you can buy at any system...

**Comment by SonEasterZombie** [comment] 2017-02-24 18:37
Please close this issue. this can already be done by deselecting all your ships and then buying so it's a non issue

**Comment by KiLEdEnNis** [comment] 2017-02-24 18:43
it should be more clear though, I found out a couple of months ago & I play since... late 2015?

**Comment by Amazinite** [comment] 2017-02-24 18:45
The feature is only a couple of months old...

**Comment by DingusShingleton** [comment] 2017-02-24 19:24
But it's extremely non intuitive and not documented anywhere in the game... This is another one of those well intentioned "don't overwhelm the player" ideas that takes it too far IMO.

**Comment by SirStigII** [comment] 2017-04-06 16:48
Woah, that is possible to do? Man, that makes outfitting runs so much faster. It would be nice if each planet menu had a "Help" button that would list the different options/key modifiers in that particular section.

**Comment by tehhowch** [comment] 2017-04-06 17:58
Two possibilities:
- Defaulting to no-ship-selected when entering the Outfitter:
Forcing a player to click on a ship, rather than auto-select the first in the list, helps one understand that it's possible to buy without a selected ship. 
- Make the ship selector auto-toggle:
If you click on a currently-selected ship, this ship is removed from the selection, while clicking on a different ship changes selection. If the different behavior associated with single-click is perceived as confusing, use double-click to deselect and keep the current single-click behavior regardless of the click target.

**Comment by endless-sky** [comment] 2017-05-04 00:51
After thinking about various ways to implement this, I've settled on the one that makes the most sense to me (commits 1f35704 and 3f67e43).

There are now two checkboxes in the bottom left corner in the outfitter. One toggles whether outfits you do not own are displayed. The other toggles between showing cargo and showing your ships. So, for example, turning off "show outfits for sale" and then selecting a ship shows only the outfits installed in that ship. If you then click "show outfits in cargo," it will instead show just the outfits you have in your cargo:

![outfitter](https://cloud.githubusercontent.com/assets/11450262/25687166/186f42c6-3042-11e7-852b-89dea7987cb7.jpg)

**Comment by Jorlem** [comment] 2017-05-06 00:43
If I may suggest, could the first option be changed to instead say "Show Outfitter's stock"? I think that the current wording is somewhat imprecise, and could be made clearer/more intuitive.


With regards to the second option, from the function of the toggle you describe, I believe there is an "only" that is going unstated.  As this checkbox is being added to make it clear to a player that they can purchase directly to the cargo space, turning on this checkbox would need to de-select any ship that is currently selected, which is what you described it as doing.  However, this would not be the expected behavior, as the current wording tells the player that this toggle will control if the items in the player's cargo hold will be stacked with what is installed on the ship, and potentially with the outfits available for purchase. (For example, if the player wanted to buy a new outfit instead of installing one from the cargo.)  However, it instead does something else, deselecting all ships to show only the cargo hold, in spite of the position of the toggle at the far corner of the screen from the ship selection controls informing the player that these controls are not linked, what the first option taught the player about how these checkboxes interact with the ship selection controls, and what the text actually says it does.


As an aside, I'm curious about the reasoning behind putting some of the controls for what is displayed in the Outfitter window in the upper right corner of the screen, and putting the rest of the controls for what is displayed in the lower left corner.  

This got a bit away from me, sorry.

**Closed** 2017-07-21 21:00 UTC
Labels: mechanics
