### ISSUE TITLE
Inconsistency collecting flotsam

### ISSUE THREAD

**Issue by LepRyot** [endless-sky/endless-sky#7291] opened 2022-10-01 19:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This only seems to happen when using the Emerald Sword; the flotsam sprite connects with my ship's collision mask but occasionally it simply passes by without being collected, even though I have enough room in my cargo. Sometimes it passes through one side of the collision mask and then gets collected on the other side while it's already "in" my ship. Interestingly, I've noticed more consistent collection when approaching the flotsam from the front or rear and less so from the sides. No idea what it might be caused by, but it remains annoying and detrimental to playthtough satisfaction

### Steps to Reproduce

Like I said, only happens to me with the Emerald Sword. Supplied is an edited save with the ship in your fleet and a yummy Bactrain in the system to shoot at and test with
1. Launch
2. Shoot the Bactrain until it booms to smithereens
3. Try to collect the flotsam

### Expected Behavior

The flotsam being collected whenever it crosses the collision mask

### Screenshots

Video showing many of flotsam passing by with no effect, some getting collected while already under my ship and others being collected normally
[https://www.youtube.com/watch?v=ZLQ4mD6vgtM](url)

### Link to save file

[Flotsam Test.txt](https://github.com/endless-sky/endless-sky/files/9691389/Flotsam.Test.txt)
The mission text I used to to spawn the Bactrain
[flotsam mission.txt](https://github.com/endless-sky/endless-sky/files/9691392/flotsam.mission.txt)

### Operating System

Windows 10

### Game Source

Steam

### Game Version

v0.9.14

**Comment by mOctave** [comment] 2022-10-01 23:22
I can confirm this (MacOS Monterey 12.6, v0.9.14, GitHub releases).

I seem to recall hearing something about there needing to be space around the edges of a ship image for it to work properly, but the Emerald Sword has space so that isn't what's causing the issue.

A note for about the save: @LepRyot, you said there was a Bactrian in system, but I couldn't find one. Instead I loaded up on commodities and shot up my shuttle escort.

**Comment by vitalchip** [comment] 2022-10-02 10:29
I find this happens most often when the ship is turning, I have a theory but I don't know if it holds.

In order to be collected the flotsam has to be within 5px of the ship outline, if the flotsam is moving towards the ship and the ship is turning towards the flotsam ( and combined they have enough velocity ) it might be possible for the flotsam to be say 6px outside the mask on one frame and 6px inside the mask on the next. It will be collected on neither frame.

What would happen then is it would drift through the ship until it meets the outline on the other side where it may or may no be collected again for the same reasons.

I'd say that almost all flotsam is collected by my ship with a small percentage drifting through to the other side and a tiny percentage not collecetd at all.

Flotsam doesn't check if it's contained within the mask (fairly sure..) so it's only the edges of the ship that can collect.

**Comment by quyykk** [comment] 2022-10-02 13:56
> Flotsam doesn't check if it's contained within the mask (fairly sure..) so it's only the edges of the ship that can collect.

They do check whether they're inside the mask, unless I'm massively misunderstanding the code.

> Instead I loaded up on commodities and shot up my shuttle escort.

You cannot pick up your own flotsam. So in your case this is working as intended.

**Comment by vitalchip** [comment] 2022-10-02 14:30
I was working from memory (this issue has come up before) but I've gone and checked..

DoCollection calls CollisionSet::Circle which in turn uses Mask::WithinRange and not Mask::Contains, so it is checking distance from the flotsam to the outline.

As a belt and braces test I've shifted flotsam above the flagship and sure enough a few pass through the outline, float across the ship and only get collected as they are crossing the outline on the way out.

Changing the radius from 5 to 1 makes a great many more do this (naturally, the chance of being within a single pixel of the outline on any given frame is much smaller than being within 5)  Changing the radius to 7 seems to cut it down to "very few" without making the collection happen so far from the ship it looks odd.

It's not a huge problem (in my opinion) if the odd flotsam doesn't get picked up by the first interaction with the outline because there will be a second chance and in small ships that chance will come very quickly. Large ships only seem to suffer from it more because the second crossing of the outline is further away but they still get two shots.

**Comment by quyykk** [comment] 2022-10-02 16:04
Oh thanks, I didn't know that! This should probably still be fixed though. I've seen ships as small as the shuttle struggle to pick up flotsam.

**Comment by mOctave** [comment] 2022-10-02 21:41
> You cannot pick up your own flotsam. So in your case this is working as intended.

In 0.9.14, I can pick up my own flotsam. I can't in the continuous build I have installed.

**Comment by quyykk** [comment] 2022-10-02 21:46
Oh you're right, it was a newer change. Huh didn't know that.

**Closed** 2024-01-01 17:25 UTC
Labels: bug
