### ISSUE TITLE
Bug:  game freezes when I go to outfitters

### ISSUE THREAD

**Issue by zer0Entropy** [endless-sky/endless-sky#2272] opened 2017-03-16 23:22 UTC
Been playing a lot the last few days, and everything's been working fine up until today.
I thought it might be because I'd amassed a pretty sizable fleet (> 25 ships), but I tried selling a bunch and whittling it down to about a dozen, and I'm still seeing the same behavior.

What happens is:  the moment I click on the "Outfitters" button while on any planet with an outfitter, it promptly shows the outfitters' screen with a pop up that says "Do you want to reload ammunition for all your ships?  It will cost 8,000 credits." (OK/Cancel)  At this point the game is frozen and will not respond to input.

Has anyone else seen this?  This game is popular enough that it seems unlikely that I'm the first to stumble into it, and yet I searched both Google and this Github issues tracker with terms like "Outfitters" and "Reload ammunition" and didn't turn anything up.

I'm running version 0.9.6 of the game on Ubuntu Linux 16.10, by the way.  Attached is my most recent save file.
[Zaphod Beeblebrox.txt](https://github.com/endless-sky/endless-sky/files/849241/Zaphod.Beeblebrox.txt)

**Comment by Bladewood** [comment] 2017-03-16 23:26
Closest thing there is to your issue is a Steam bug report. http://steamcommunity.com/app/404410/discussions/1/135511455873251125/

**Comment by zer0Entropy** [comment] 2017-03-16 23:40
That's...interesting, and definitely similar, but I wish to note two things:
1)  The poster there attributes his bug to having "Pointedstick's vanguard" in his fleet - not sure what that is, but I'm pretty sure I don't have it.
2)  He claims "If I hit yes, my game crashes."  In my game, Endless Sky is frozen as soon as I enter the outfitters - clicking either "OK" or "Cancel" does nothing.

**Comment by comnom** [comment] 2017-03-17 02:10
@zer0Entropy It's getting stuck in a refill loop in OutfitterPanel::Refill(). 

Any idea where you got the bastion "Khan's Ravager" and how it ended up with 1 Heavy Rocket Launcher (20 capacity) and 34 Heavy Rockets? I don't see one in variants and it shouldn't let you buy more ammo than you can hold.

In addition, I was under the impression that if you sold ammo storing weapons it'd sell off the excess ammo.

**Comment by Amazinite** [comment] 2017-03-17 02:16
Sounds like #1277

**Comment by comnom** [comment] 2017-03-17 02:20
@Amazinite Pretty close yeah. If I set the ammo at 20 it works fine, so the cause is definately the excess. Still curious how we got there though. 

@zer0Entropy You can edit your save to fix the hang, just edit the 34 ammo to 20. Make sure you check out the "editing the data files" paragraph at https://github.com/endless-sky/endless-sky/wiki/CreatingPlugins if you've never done any save editing before.

**Comment by zer0Entropy** [comment] 2017-03-17 02:30
Thank you, @Amazinite & @comnom!  That was fast detective work!

@comnom I captured "Khan's Ravager" during a pirate battle, but I'm afraid I have no clue how its ammo value would up in an illegal state.  I haven't fooled around with any mods, and this is the first saved-game-hackery I've done since I started playing.

**Comment by LocalGod79** [comment] 2017-03-17 04:23
is it possible that you pillaged one of the launchers before you captured the ship?

**Comment by zer0Entropy** [comment] 2017-03-17 13:38
The latter case sounds entirely plausible to me (talk about an edge case!)
As to the former, I don't _think_ I would have plundered it before capturing, but I wouldn't swear to it.

**Comment by endless-sky** [comment] 2017-03-24 16:02
Fixed in 536384a. Turns out the bug only occurs when one of your ships has too much ammo, *and* one of your ships also has too little ammo (i.e. needs a refill).

**Closed** 2017-07-21 20:59 UTC
Labels: bug
