### ISSUE TITLE
snapshot save files when landed on plugin planets load on New Boston [bug]

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#2035] opened 2017-01-19 18:20 UTC
from Steam (my plugin's guide page):

> I have this plugin, and for the most part it works pretty well, but whenever I load a save that was from when I was on Ursa Polaris Station, it thinks I'm on New Boston.
> Current save, which should be from when I was on Hope: https://www.dropbox.com/s/fhunwrzp16419jz/Andrea%20Fenn.txt?dl=0

further, i've experienced this with the World Forge plugin as well...

**Comment by jafdy** [comment] 2017-01-19 18:30
The return to new boston was to prevent the game breaking if it tried to load up on a mod planet. 
Where the planets created by events?

**Comment by endless-sky** [comment] 2017-01-28 23:38
I think the issue is that Ursa Polaris Station is created by an event, so it doesn't actually exist until after the events in the saved game are applied.

**Comment by endless-sky** [comment] 2017-01-28 23:45
Commit 8ac7df7 should fix this.

**Comment by endless-sky** [comment] 2017-03-22 22:43
Closing because 0.9.6 is released.

**Closed by endless-sky** 2017-03-22 22:43 UTC
Labels: bug
