### ISSUE TITLE
Unable to finish mission "Remnant: Cognizance 26"

### ISSUE THREAD

**Issue by masonwheeler** [endless-sky/endless-sky#8448] opened 2023-02-23 22:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After picking up the Aeon Cell and returning to the station, the mission fails to complete.

### Steps to Reproduce

1. Fly an Albatross
2. Start the mission
3. Land on Viminal
4. Albatrosses do not have enough cargo space to hold a 160-ton piece of equipment.  You get warned about this.  So far, so good.
5. Buy a second Albatross and equip it with a spare Jump Drive so it can reach the destination.  You now have over 160 tons of cargo space available.  Neither ship individually can hold the thing, but there is no warning that anything's wrong.
6. Take off and fly to the station.
7. Mission does not complete upon landing on the station.

### Expected Behavior

Either the mission should complete, or it should warn me on step 5 that I can't hold it.

### Operating System

Windows 10

### Game Source

Steam

### Game Version

v0.9.16.1

**Comment by warp-core** [comment] 2023-02-23 22:31
#7645 will address this by providing a warning even when your total space is sufficient if no single ship can hold the outfit.

Also, this might be a duplicate of something, but I can't think of specific issue right now.

**Comment by masonwheeler** [comment] 2023-02-23 22:33
> Also, this might be a duplicate of something, but I can't think of specific issue right now.

Well, I did search for any other issue mentioning "Aeon Cell" and found nothing.  It's possible it's a duplicate of something somewhere, but if so it's not a particularly exact duplicate.

Good to hear there's a fix in the works already. 😄

**Comment by ziproot** [comment] 2023-02-23 23:12
Duplicate of #6505.

**Comment by movingpictures** [comment] 2023-02-28 01:27
> #7645 will address this by providing a warning even when your total space is sufficient if no single ship can hold the outfit.
> 
> Also, this might be a duplicate of something, but I can't think of specific issue right now.

Yeah, i stumbled on this a while back.

**Comment by ziproot** [comment] 2023-11-13 06:21
Is this still a bug?

**Comment by warp-core** [comment] 2024-01-18 22:57
> Is this still a bug?

Since #9138 (which took over #7645) was merged, the player will receive a warning when attempting to take off with an outfit in cargo that their ship(s) can't actually carry, so I think this is resolved.

**Closed by warp-core** 2024-01-18 22:57 UTC
Labels: bug
