### ISSUE TITLE
Flight checks from spaceport blanks out description

### ISSUE THREAD

**Issue by Terin** [endless-sky/endless-sky#5263] opened 2020-08-27 19:45 UTC
**Describe the bug**
When you trigger a flight check dialog (for overheating/no engines/no power) while in the spaceport, the spaceport description will blank out, instead of remaining there, or even returning to the main planet description.

**To Reproduce**
1. Land on a planet with an outfitter
2. Remove engines/power, or overheat your ship
3. Click on Spaceport
4. Click on Depart
5. See blank description behind conversation dialog

**Expected behavior**
Either the spaceport description remains, or it defaults to the planet description.

**Screenshots**
![desc1](https://user-images.githubusercontent.com/4471575/91487381-45506080-e873-11ea-804d-cb0f3da8a339.png)
![desc2](https://user-images.githubusercontent.com/4471575/91487385-45506080-e873-11ea-84c0-7dd412bf8b2e.png)
![desc3](https://user-images.githubusercontent.com/4471575/91487387-45e8f700-e873-11ea-9108-81879c6e30f2.png)
![desc4](https://user-images.githubusercontent.com/4471575/91487393-46818d80-e873-11ea-923f-89afa6c751c5.png)

**System:**
 - OS: Windows 10 Pro version 1903
 - Game Source: Continuous
 - Version: commit hash 9b94dfd

**Comment by Amazinite** [comment] 2020-08-27 21:25
Duplicate of #4543.

**Closed** 2020-08-27 22:38 UTC
Labels: duplicate
