### ISSUE TITLE
Endless sky plug-ins

### ISSUE THREAD

**Issue by deiniolte2376** [endless-sky/endless-sky#6294] opened 2021-10-15 20:09 UTC
### Problem Description

Is there a way to plug this into the browser edition of Endless Sky? There is a section of the site that says "Show plugins for download" but does nothing when clicked on, so I can't figure out how to do it on the browser.

### Related Issue Links

https://play-endless-sky.com/

### Desired Solution

-

### Alternative Approaches

-

**Comment by MCOfficer** [comment] 2021-10-15 20:13
I think you meant to open this issue at endless-sky-plugins, but somehow ended up here...? regardless, to clear up any confusion: it's a duplicate of https://github.com/EndlessSkyCommunity/endless-sky-plugins/issues/64

**Closed as completed** 2021-10-15 23:00 UTC
