### ISSUE TITLE
New uses for old Korath tech?

### ISSUE THREAD

**Issue by Fleurghber** [endless-sky/endless-sky#4925] opened 2020-03-17 19:02 UTC
Once it's been possible for humanity to study Korath ships, might it be possible for their control units, or modified versions, to be available from outfitters?  This would then allow for something like the following:

Reasoning Node:  This unit allows an unmanned ship to act on its own initiative, when not required to escort another ship.

Control Transceiver: This unit allows an unmanned ship to receive orders from another ship, when required to escort it.

**Comment by DmitrySukhv** [comment] 2020-03-18 11:30
It is not clear what do you want to achieve with that.

**Comment by downRightCoder256** [comment] 2020-03-18 13:55
i was just looking for that one! id say its a duplicate of #4791, but yeah, i see what he means

**Comment by beccabunny** [comment] 2020-03-18 14:03
Doesn't really seem something for vanilla imo

**Comment by downRightCoder256** [comment] 2020-03-18 15:54
well... i do see that the game used to have human androids at some point in time. delving into why they were removed would probably get us to the exact answer to this issue. pretty sure there used to be a PR addressing it

**Comment by MCOfficer** [comment] 2020-03-18 16:00
> well... i do see that the game used to have human androids at some point in time. delving into why they were removed would probably get us to the exact answer to this issue. pretty sure there used to be a PR addressing it


#1013 

> EDIT: On an unrelated note, androids have broken (read- overpowered) Endless Sky. With maximum tribute, I can now have a lot of ships without going over the payment. A LOT.

4abc9b8d0841d72f69fddf37c2bc316f9b29bbc5

> they're just way too unbalanced.

**Closed** 2020-07-16 14:01 UTC
Labels: unlikely
