### ISSUE TITLE
Select which FTL outfit to use if you have multiple FTL outfits installed.

### ISSUE THREAD

**Issue by CaptainHaywood** [endless-sky/endless-sky#4073] opened 2018-12-16 00:58 UTC
I'm bothered by the fact that you can install multiple FTL modules, but can't choose which one to use. For example, I have a hauling vessel that regularly trucks through both dangerous and safe areas of space. I installed a scram drive in addition to the standard hyperdrive, assuming I could swap the active one when I was travelling through dangerous space. Unfortunately, the game defaults to the scram drive no matter what, expending extra fuel even when I don't need it.

I've only messed around a little with the jump drive, and I haven't done any exploration beyond where hyperlanes and wormholes can take me. But it seems like this would be even more useful while exploring the star networks totally disconnected from humanity - you'd only have to use the fuel-gulping jump drive to move between networks, and switch to standard hyperdrive within each network to save fuel.

What I'd suggest would be an button under the ship tab of the info (i) screen, allowing you to choose between available FTL outfits at will. Additionally, it might make sense to have the game temporarily switch over to, say, the jump drive if there isn't a hyperlane available.

**Comment by tehhowch** [comment] 2018-12-16 03:07
The game will not use a jump drive if you have a hyperdrive and are making a jump that is possible with it.
As far as using only the hyperdrive when both hyper and scram drives are installed, you are correct. This has been raised before: duplicate of #2477

**Comment by CaptainHaywood** [comment] 2018-12-16 03:14
OK, thank you. Should I close this issue, seeing as it was dismissed in 2477?

**Closed** 2018-12-19 00:31 UTC
