### ISSUE TITLE
Continuous - Freeze in new system

### ISSUE THREAD

**Issue by Alexthehuman2** [endless-sky/endless-sky#9735] opened 2024-01-28 01:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Main game state freezes after making a wrong decision.

### Steps to Reproduce

1. Discover the'Patir' System
2. Complete the quest chain to the point where you investigate Builder Settlement (with Dusk I think?)
3. Select the options where you stay still until you reach airlock, and wait for airlock to close.
4. You die, but you're still on planet, and the game freezes - You can still access main menu to reload previous save, but the gameplay completely freezes with no movement or sound whatsoever.

### Expected Behavior

After dying, there should be something mentioned as per #9717, or continue the game loop - although this is likely because the player is stuck in a planet, therefore when they die, the game state isn't updated.

A temporary fix for that would probably be booting player's ship back into orbit, then killing the ship immediately for a traditional death to signify the player died in that part of the story.

### Screenshots

![image](https://github.com/endless-sky/endless-sky/assets/50268488/e9ff1658-eb91-4774-a3f6-08ad1f43a28c)

### Link to save file

AppData\Roaming\endless-sky\saves

### Operating System

Windows 10 Home Edition

### Game Source

Steam

### Game Version

v0.9.15 Continuous

**Comment by bene-dictator** [comment] 2024-01-28 04:42
Well, it's because your character's dead, and the game doing nothing when you're dead isn't a bug, more of an oversight that nobody has made a pull request to fix. It also wouldn't make sense if you died... then your ship appeared in space and explodes. That's not what happened; you died on the planet.

I recommend you post this example in #9717, since this issue is really a duplicate of that one with less scope and it's easier to just have one place to discuss it. Nonetheless I appreciate that you've taken the time to write this.

**Closed** 2024-01-28 11:23 UTC
Labels: bug, unconfirmed
