### ISSUE TITLE
Outfits Overheat Error with Parked Ships

### ISSUE THREAD

**Issue by rktaylor** [endless-sky/endless-sky#688] opened 2016-01-18 06:12 UTC
I've been using a parked freighter to store plundered Korath outfits, and noticed that after installing a Korath reactor it wouldn't let me leave the outfitter due to an overheat error. But the ship was parked, so this is a bug, right?

(Alternatively, could add private storage lockers to accompany private hangers.)

**Comment by thenerdfreak** [comment] 2016-01-18 07:20
Not a bug, it assumes it wouldn't be parked, so you have to make the heat slightly below what your ship can handle (Max Heat)

**Comment by johndh** [comment] 2016-01-18 07:24
Likewise, it won't let you leave if you don't have thrusters, steering, and a power plant installed.

**Comment by endless-sky** [comment] 2016-01-18 15:20
Right now all ships are required to have a "flyable" configuration when you leave the outfitter. Otherwise, someone could outfit that ship, then unpark it, then take off from the planet and be stuck in space with an overheated ship (or a ship with no steering, etc.). In my opinion keeping a beginning player form accidentally getting stranded with an unflyable ship is more important that allowing more advanced players to create unflyable parked ships.

**Comment by mdsmestad** [comment] 2016-01-18 16:05
seconded

**Comment by rktaylor** [comment] 2016-01-18 19:42
I definitely agree with the idea of not accidentally marooning novice players, but would it be possible to have those warnings only trigger for unparked ships? I guess this is no longer a "bug" and now a "feature" discussion.

**Comment by thenerdfreak** [comment] 2016-01-18 20:17
Eh to fix all of this would be to implement a much wanted "storage warehouse" on some/all planets that would cost the player a daily/weekly/monthly fee  i guess

**Comment by endless-sky** [comment] 2016-04-02 17:54
This would basically be fixed if storage were implemented, which is already requested elsewhere, so I'm closing this.

**Closed by endless-sky** 2016-04-02 17:54 UTC
Labels: mechanics
