### ISSUE TITLE
[bug] Crash when ammunition exceeds capacity...

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1277] opened 2016-06-28 02:59 UTC
If for some reason (usually when messing around with some mods) you have more ammunition for a certain weapon than you are suppose to be able to carry and you enter the outfitter, you will get the following message. 
![screenshot_2](https://cloud.githubusercontent.com/assets/17688683/16402259/1960e5f4-3cb9-11e6-8278-c5be29ce8493.png)
Upon clicking "OK," the game will crash.

~~Another thing is that if you launch with excess ammunition "installed," you will be able to keep that ammunition even when you have no capacity space for it.~~ Moved to #1402 
And if you have >2 more ammunition than you are able to hold, then you can sell one and from there buy as many as you want beyond the capacity.

**Comment by MarcelineVQ** [comment] 2016-06-28 06:36
The last two problems are being caused by CargoHold::Transfer dealing in integral numbers only but the mass of ammo tends to be fractional. Changing that touches on a lot of things so it's probably best left to the author.

**Comment by Amazinite** [comment] 2016-06-28 17:04
This bug has been around for a while, I only just now encountered it again, so the mass of ammunition is likely not the cause at all.

**Comment by MarcelineVQ** [comment] 2016-06-28 23:12
Good comment, one was due to mass and one wasn't. Fixes for all 3 issues are included in the pr now

**Comment by Amazinite** [comment] 2016-08-05 21:47
This should be tagged with 0.9.3 (done).

**Comment by Amazinite** [comment] 2016-08-05 21:51
This should be tagged with 0.9.3 (done).
The first and third bugs that I listed have been fixed for the latest code, but the second issue of being able to launch with excess ammunition installed is still happening. I'll bring up a new issue for it individually.

**Comment by endless-sky** [comment] 2016-12-24 02:10
Closing this, because it sounds like the crash is fixed.

**Closed by endless-sky** 2016-12-24 02:10 UTC
Labels: bug
