### ISSUE TITLE
Addition of shield effect when hit and overheating with Changes in cloaking effect

### ISSUE THREAD

**Issue by ProNooberEX** [endless-sky/endless-sky#7069] opened 2022-07-30 14:18 UTC
### Problem Description

Cloaked ships in endless sky will shift from their normal shade of color to red. However, red is most often associate to temperature increase or high temperatures of overheating and therefore won't be suited for cloaking effects. On the other hand, it will be a bit cooler (personally) to show the shield being attacked by projectiles and lasers, providing a more sense of hitting an object and to have an overheating effect on all ships. 

### Related Issue Links

*

### Desired Solution

Change the shift in color from normal to red when the heat level of ship reaches is being overheated, potentially starting to shift when the heat had reached 50 percent of being overheated and ending with turning the ship completely red at the overheating point. Also, one may alter the cloaking effect and replacing it with the transparent effect. In addition, a portion shield can light up at different positions on the ship where it is hit, using images and effects from other games or artworks.

### Alternative Approaches

*

### Additional Context

*

**Comment by warp-core** [comment] 2022-07-30 14:41
The shield thing has been brought up in #2568, maybe elsewhere too, I'm not sure.

**Comment by ProNooberEX** [comment] 2022-07-30 14:45
> The shield thing has been brought up in #2568, maybe elsewhere too, I'm not sure.

Had anything been done about it?

**Comment by ProNooberEX** [comment] 2022-07-31 05:47
> I think the colour change we get with the cloak is a little extreme for overheating, but some effects to indicate it might be nice.
Personally I don't think this will be a major issue(endless sky is set in the technological setting where even the poorest Korath cooling systems could cool down the temperature "of a nuclear explosion" in hyperdrives with other system's heat combined enough to a normal level, therefore extreme temperatures will be needed to overheat spacehsips in endless sky)

**Comment by Hurleveur** [comment] 2022-08-03 05:50
The cloak doesn't make your ships transparent so you can still see them, and potentially give them orders.
We'd need another effect (maybe partly transparent, even, like a transparent effect passing on the ship in diagonal), or another color, simply (blue?)

**Comment by Amazinite** [comment] 2024-02-03 06:16
Considering this a duplicate of #2568.

**Closed by Amazinite** 2024-02-03 06:16 UTC
Labels: duplicate
