### ISSUE TITLE
Could the hit force against heavy ships be reduced to less ridiculous levels?

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#3783] opened 2018-06-16 18:04 UTC
If it uses ship's mass as a criterion, then consider using mass^(2/3) instead. It'd be a rough approximation of a surface area the explosion gets to affect.

**Comment by jafdy** [comment] 2018-06-16 18:07
Using mass^(2/3) would increase the force to heavier ships.

**Comment by Tadrix** [comment] 2018-06-16 18:11
Isn't it doing it currently? (I'm not sure exactly how it works.)

The situation where super-heavy ships (presumably with large inertia) are flung all the way across the system is wrong, which is the case for the current GitHub build.

However, the more surface the explosion gets to affect, the more damage. This could be used to keep missiles useful against the larger ships.

I was operating on a presumption that mass is an approximation of ship's volume, so mass^(2/3) would be an approximation of the part of the surface affected by the explosion.

**Comment by KiLEdEnNis** [comment] 2018-06-16 18:19
I've had ships with mass around 1500-2000 with a max speed of like, 350, be pushed away hard by: ~4 Finisher Pods, ~6 Thunderhead Launchers, even 2 Rainmakers push me away across systems
the case w/ like 4 Finisher Pods smashing me across a system was so bad the enemy ships literally lost track of me & landed before I could make it bad

right now this ridiculous hit force completely ruins gameplay for me, any ship with 4 launchers can push you around as if you're a Sparrow

for all I care it's reverted to how it was (0.9.8), because that way combat was still fun instead of extremely annoying

**Comment by endless-sky** [comment] 2018-07-04 14:19
The boost to the missile hit force was a specific request that people seemed to be behind: #3288, #3294, etc. It's possible that they now push you a bit *too* much, so maybe some balancing needs to be done. But in my experience, the increased hit force is actually helpful in some situations, because if a big cloud of missiles is coming towards you the first hit pushes you away from the cloud before the others can hit you.

**Comment by Amazinite** [comment] 2018-07-04 17:44
>But in my experience, the increased hit force is actually helpful in some situations, because if a big cloud of missiles is coming towards you the first hit pushes you away from the cloud before the others can hit you

But then the rest of the cloud hits you, and it just keeps pushing, and pushing, and pushing...
If you don't have very high end engines on a low mass ship, a heavy warship vs Rainmaker battle can be the player just waiting for the Rainmaker to run out of ammo because the constant barrage of missiles keeps the warship from getting close enough to the Rainmaker to be within firing range. Given just two or three ships with missiles, it can feel like you're in a small ship trying to attack a Korath Raider while being tossed around by their Banisher. At the very least, it *looks* strange that a large ship can be hit by one missile and get pushed a considerable distance while a ship many time smaller can get hit by the same missile and seemingly not budge.

**Comment by KiLEdEnNis** [comment] 2018-07-04 23:29
I've played the game a little to test things and I've had a Hurricane w/ near-400 speed getting slammed out of the system by just a Rainmaker as well
increased hit force ok, imo take the original values and maybe, quadruple or something, but this severe hit force stuff straight-up makes me not wanting to play the game at all, and I haven't even tested big storyline battles

even if it IS helpful at times (which actually nerfs missiles), one can only wait until the enemy is out of ammo and only then fight back

**Comment by endless-sky** [comment] 2018-07-06 20:22
As a compromise, in commit 3a7bcb0 I've halved all the hit forces that were recently increased (in e61c25f5). It'll take a bit more play-testing to decide if that feels like the proper balance.

**Comment by Pointedstick** [comment] 2018-07-08 19:19
For me, the problems are:
- Hit forces are too high relative to damage; personal preference for increasing damage to match hit force rather than the opposite
- Hit force doesn't scale down as fast as it should if you have a really big ship

**Comment by endless-sky** [comment] 2018-07-10 22:23
If I went back to the original mechanics where hit force is inversely proportional to mass, there would be a *huge* effect on small ships compared to large ones with these new, higher hit forces. Ship masses range from about 100 for a light fighter (or even less for a drone) up to 1800 for a Carrier or 2500 for a world-ship.

The new mechanic is that half of the hit force acceleration is inversely proportional to the mass, and the other half is constant. That means that instead of there being an 18x difference in acceleration between a fighter and a Carrier, there's only a 4x difference. It's possible that a weighting somewhere in between would be best. For example, a 70% / 30% split would mean that the same blast accelerates a fighter 7x more than a Carrier.

**Comment by tehhowch** [comment] 2018-07-10 23:06
I think the issue is that for small ships, their own acceleration (from thrusting) can easily counter the hit force from missiles. For large ships, however, their thrust has to fight their whole mass while hit force has a shortcut. This can lead to the perception that small ships are relatively unaffected, while larger ships are disproportionately affected.

I haven't inspected it, but there may be some interplay with how the game implements drag in this as well.

**Comment by Amazinite** [comment] 2018-07-11 14:28
Being hit by missiles feels far more bearable when in a heavy ship, now, and it definitely doesn't look as strange as it did with a World Ship being tossed around like a ragdoll by a Rainmaker or two; right now, hit force feels impactful for ships both big and small, but doesn't look strange in bigger, heavier ships.

And I believe that @tehhowch has hit the nail on the head with what the perceived issue is; while smaller ships are impacted more by high hit force weapons, they are also far better at recovering from being hit when compared to a heavier ship, leaving a player in a heavy ship feeling unable to react.

**Comment by KiLEdEnNis** [comment] 2018-07-11 14:45
just to be clear, I still think especially heavier ships should be less affected, and the general hit forces may still go down a bit, their impact is still a bit too much imo

**Comment by KiLEdEnNis** [comment] 2018-07-11 20:20
after testing from source after e64b590 my heavy warship can actually stand several Thunderheads
I'm not sure if all missiles are fine, but it's mostly ok now

**Comment by Pointedstick** [comment] 2018-11-20 16:54
I think this is good now. Folks seem fairly happy with missile hit forces at the moment. Yell and scream if you disagree!

**Closed by Pointedstick** 2018-11-20 16:54 UTC
Labels: balance
