### ISSUE TITLE
Funny: it appears that for some people "top secret" is a price tag

### ISSUE THREAD

**Issue by abenkovskii** [endless-sky/endless-sky#3031] opened 2017-09-10 18:21 UTC
Apparently if instead of starting the main campaign you fly around doing side plots long enough [certain crafty individuals](https://github.com/endless-sky/endless-sky/blob/cc872e3354aba6d15b063c4ee97b74f52a55f9ba/data/transport%20missions.txt#L1099) manage to get their hands on the early prototypes of [top-secret navy weapons](https://github.com/endless-sky/endless-sky/blob/cc872e3354aba6d15b063c4ee97b74f52a55f9ba/data/marauders.txt#L377).

**Comment by tehhowch** [comment] 2017-09-10 18:27
This (funny/reaction/TIL posts) is more suited to the steam forums and google groups forum than the issues page.

Or, are you suggesting that the appearance of these weapons in game is keyed to having the game event that introduces them? If so, please edit your post accordingly.
(also note that MZ's person uses Electron Turrets)

**Comment by Amazinite** [comment] 2017-09-10 18:46
The ES Github is for feature requests and bug reports. If you're wanting to make posts like this, you should do so over on either the [Steam forums](http://steamcommunity.com/app/404410/discussions/0/) or [Google Group](https://groups.google.com/forum/#!forum/endless-sky).

If you're saying that this shouldn't be the case, then this is a duplicate of #1929.

**Closed** 2017-09-10 19:07 UTC
