### ISSUE TITLE
Autopilot landing may be broken.

### ISSUE THREAD

**Issue by Lineth** [endless-sky/endless-sky#2503] opened 2017-05-08 22:14 UTC
So when you open the map and click on a 'landable' (what a perfectly cromulent word) planet, it does not seem to take, and hitting autopilot will take you to the system, as normal, but it wont land on the planet. Minor issue, but eh. Am I just doing something wrong from forgetting several of the controls?

**Comment by tehhowch** [comment] 2017-05-09 05:18
I didn't know this was a feature, but indeed it appears to be one. And one that doesn't quite work, as well.

Selecting the system in the main map, then the landable object in the "solar objects" sub-map, and then closing the main map and initiating travel results in the expected travel to the system, and when arriving in the system, the summary message "Landing on:  ____" instead of "navigation: no destination", which shows up when one just selects the system via the main map and then initiates travel.

**Comment by EndrosG** [comment] 2017-05-09 09:40
One of the questions which arises to me is, if that intended behaviour, to land right after arriving at the target system, is even somewhat desirable.
Assuming, you perform only 1 jump and press the j key until all ships are ready to jump, this is fine, because all escorts will arrive with you.
Otherwise, it may happen that not all escorts have arrived in the TargetSystem() before/when the flagship is able to land. Most typical cases is having some bulk freighters etc. in your fleet.

I.e. while this feature (which really does not work anymore) might be desirable for small fleets or for fast fleets, it will cause "trouble" with slow escorts (mission escorts?)

@tehhowch : what you may try is to implement (or even move) the functionality you successfully found in AI::UpdateKeys into AI::MovePlayer, Lines 2484+.

That should work imho, but I cant really test it right now.

**Comment by tehhowch** [comment] 2017-05-09 16:58
Good call, Endros.

PR incoming

**Closed** 2017-05-12 02:50 UTC
