### ISSUE TITLE
Escorts in infinite "ask for help" cycle after landing on wormhole

### ISSUE THREAD

**Issue by flaviojs** [endless-sky/endless-sky#3012] opened 2017-09-07 14:37 UTC
Me and my fleet are using jump drives.
My travel plan was Mirfak (take off), Volax, Ultima Thule (unexplored) and Alheka (unexplored, mission target).
When discovering Ultima Thule I noticed the wormhole and landed on it, discovering Waypoint, and then my escorts started an endless cycle of calling for help and ignoring my orders.

The same happens if I cancel my travel plan after reaching Ultima Thule (by clicking Ultima Thule on the map) and land on the wormhole.

Changing my travel plan to end at Ultima Thule before arriving there makes the escorts behave normally after I land on the wormhole.

**Comment by tehhowch** [comment] 2017-09-07 15:12
this wasn't fixed by https://github.com/endless-sky/endless-sky/pull/2839 ?

**Comment by tehhowch** [comment] 2017-09-07 15:14
Ah, I suspect this is caused by having an invalid travel plan... though I thought I had addressed that in #2845 

Are all of your escorts in system when you land on the wormhole? or still routing to your system?

**Comment by flaviojs** [comment] 2017-09-07 15:39
They are all in system, they travel at the same time as me since I'm the slowest.

Telling them to hold position before I arrive in Ultima Thule makes the escorts behave normally after I land on the wormhole.

**Comment by tehhowch** [comment] 2017-09-07 15:56
Alright, this happened because you used a travel plan, and then a wormhole not on that travel plan. Because your escorts are as fast or faster than you, they always hit the parentIsHere branch of MoveEscort:
https://github.com/endless-sky/endless-sky/blob/35eb0e760f2763b0ea453c3ce8aa84210fe2a387/source/AI.cpp#L1258-L1276

This gave them a target system as soon as everyone arrived (since your travel plan set your target system as soon as you entered Ultima Thule), but as escorts, they nicely wait for you to be ready to jump before they jump to their target system. Since you then change your mind and land, they also gain a target stellarobject:
https://github.com/endless-sky/endless-sky/blob/35eb0e760f2763b0ea453c3ce8aa84210fe2a387/source/AI.cpp#L1249-L1255 
Once they've gone through the wormhole, that target system is completely inaccessible, causing the same stranded behavior I identified in #2839  and #2829

**Comment by tehhowch** [comment] 2017-09-07 15:58
Should be fixed with #3013

**Comment by flaviojs** [comment] 2017-09-07 16:11
I confirm the PR fixes this issue.

**Comment by endless-sky** [comment] 2017-09-09 21:22
Fixed by merging #3013.

**Comment by ratsrolocosx** [comment] 2018-08-01 04:15
Sorry, but I've been having the same issue and I'm a bit lost - I see that you've said it's fixed #3013, but what do with that to fix the issue?

**Comment by MessyMix** [comment] 2018-08-01 05:25
So, err, you won't receive this fix until you get the latest version of Endless Sky (i.e. when the developer pushes version 0.9.9 to Steam). So you might have to wait a while to actually get the fix.

If you're competent at Git, then you could compile the most updated / current version from this repository to get the fix. Or maybe someone could guide you through those steps. Unfortunately I don't think I'm experienced enough to do it—even if I weren't as rusty as I am :P

**Comment by MCOfficer** [comment] 2018-08-01 09:25
[shameful self-advertising]
just gonna throw in the possibility of using [inofficial Nightly Builds](https://steamcommunity.com/app/404410/discussions/0/1700542332319963311/)

**Comment by DingusShingleton** [comment] 2018-08-01 14:47
I was mucking about for a couple hours trying to compile (it's been a while) and then the clouds parted and your nightly builds appeared like the holy grail. Thanks

**Closed** 2019-06-01 20:57 UTC
Labels: bug
