### ISSUE TITLE
0.9.13 is marked as [Latest release] and not as [Pre-release]

### ISSUE THREAD

**Issue by core-code** [endless-sky/endless-sky#5856] opened 2021-04-18 13:17 UTC
if its 'unstable' it should be properly marked as such in the github release feed

**Comment by MCOfficer** [comment] 2021-04-18 13:35
TL;DR: No, it's not that unstable.

We handle releases differently between steam and github. "Unstable" releases are more for feature testing, and may contain bugs, but still nothing gamebreaking and crashing. The reasons for this convention is mostly historical, but basically unstable releases aren't unstable enough to be considered pre-releases.

**Comment by Zitchas** [comment] 2021-04-18 13:39
I don't know if it is practical to do so, but if we can, it might be worth switching to Feature and Polish instead of Unstable / Stable, just to avoid confusion and provide clarity.

**Comment by tehhowch** [comment] 2021-04-18 14:35
Duplicate of #4874

**Closed** 2021-04-18 14:35 UTC
Labels: documentation, duplicate, question

**Comment by core-code** [comment] 2022-10-05 10:07
same issue applies to yesterday's 0.9.15 release which is called "unstable" but marked as "latest" instead of "pre-release".

**Comment by MCOfficer** [comment] 2022-10-05 10:12
Same answer applies.

**Comment by quyykk** [comment] 2022-10-05 10:14
> > I don't know if it is practical to do so, but if we can, it might be worth switching to Feature and Polish instead of Unstable / Stable, just to avoid confusion and provide clarity.
> 
> Changing our phrasing could definitely help.

maybe we should have done that?
