### ISSUE TITLE
Support for other languages

### ISSUE THREAD

**Issue by pyccl** [endless-sky/endless-sky#10089] opened 2024-05-20 15:08 UTC
### Problem Description

Now there is only English and no other language, which is not convenient for people who are not good at English. Hope to add support for other needs.

### Related Issue Links

I tried to change the text content to Chinese, but when I entered the game, I found that Chinese could not be displayed at all

### Desired Solution

Provide support for other languages, such as adding a "language" option in the settings, or allowing users to modify their own needs.

### Alternative Approaches

If setting up multiple languages is not very realistic, we hope to provide the necessary interfaces or files for modification, so that users can modify them to their own language.

**Comment by tibetiroka** [comment] 2024-05-20 15:29
Duplicate of #558. Unicode support is tracked in #8572. We first need to sort things out internally, as some messages are hardcoded in the engine, and we can't display unicode characters yet.

**Closed by tibetiroka** 2024-05-20 15:29 UTC
