### ISSUE TITLE
Violin Spider has incorrect hardpoints

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1659] opened 2016-10-01 22:23 UTC
https://github.com/endless-sky/endless-sky/blob/master/data/hai%20ships.txt#L527

**Comment by endless-sky** [comment] 2016-10-02 02:15
Fixed in 329d302.

**Comment by Bladewood** [comment] 2016-10-02 03:30
Reopening because of Local's comment on https://github.com/endless-sky/endless-sky/commit/329d3022d77ee8644f07bda285c45426d260c8e5.

**Comment by Bladewood** [comment] 2016-10-02 03:41
Apparently, the pulse cannon was accidentally left out, but the anti-missile turret was supposed to be "integrated" into the violin spider.

**Comment by LocalGod79** [comment] 2016-10-02 06:23
indeed - i was trying to get a "Tier 1.1" fighter without availing a Quad Blaster Turret (and avoiding similarity with the Barb).

the integrated a/m was supposed to be a "distinguishing characteristic" of the Hai Fighters (given their beasty missile systems)

**Comment by Bladewood** [comment] 2016-10-02 19:05
https://github.com/endless-sky/endless-sky/commit/ace5f37b5c325ddfa4670f2910db8a8d3d7ed3c7 Not what Local and Amazinite wanted, but at least it has a turret mount again.

**Comment by LocalGod79** [comment] 2016-10-02 20:42
the "permanent turret" was intended to bring the Violin Spider a small step up from the human Fighters (to really justify the price point)...

it wouldn't be terribly out of place for the Unfettered to have built crude Fighters, though...

**Closed** 2016-10-05 22:25 UTC
Labels: bug
