### ISSUE TITLE
Alive ships should move in Outfitter/Shipyard/Map side panels

### ISSUE THREAD

**Issue by opusforlife2** [endless-sky/endless-sky#10604] opened 2024-10-15 20:29 UTC
### Problem Description

You can see an alive ship move while in space. But there are only static images everywhere else.

### Related Issue Links

N/A

### Desired Solution

Alive ships' move animation loops should play while in the Outfitter and Shipyard screens too.

If possible, the images in the Map side panel for those two could also be made to move.

### Alternative Approaches

There could be a Play button shown somewhere in the corner of the image, which can be clicked in order to make the ship move once or twice through its animation loop.

**Comment by TomGoodIdea** [comment] 2024-10-15 20:32
duplicate of #5524

**Closed** 2024-10-15 20:33 UTC
Labels: duplicate
