### ISSUE TITLE
Missions to guard pleasure cruises instantly fail

### ISSUE THREAD

**Issue by KeronCyst** [endless-sky/endless-sky#1476] opened 2016-08-22 01:11 UTC
When taking a pleasure-cruise job involving another ship, the mission fails because the ship never even manifests the moment you depart from the planet. To reproduce this:

- Accept mission
- Leave planet
- Text will instantly say the ship was lost and the mission failed.

This has happened to me many times now.

**Comment by jafdy** [comment] 2016-08-22 07:54
Do you have space in cargo for the mission cargo and is this space in a boxwing?

**Comment by KiLEdEnNis** [comment] 2016-08-22 13:42
I think he means something similar to an escort mission?

**Comment by KeronCyst** [comment] 2016-08-22 13:54
Hm, I did carry an idle Boxwing around in a fighter bay at the time for its cargo. But as KiLEdEnNis said, I don't think these pleasure cruise missions ever require any cargo space, and are meant to be escort missions with an NPC.

**Comment by KiLEdEnNis** [comment] 2016-08-22 15:37
launch the game and look if you have any mission cargo (and look if it's not another mission), if you still have the mission

**Comment by jafdy** [comment] 2016-08-22 15:38
`mission "Provide security for pleasure cruise"
	name "Provide security for pleasure cruise"
	job
	repeat
	cargo "Luxury Goods" 10 20`

Lifted from jobs.txt.
You would be surprised, at lest we now know what the problem is.

**Comment by KiLEdEnNis** [comment] 2016-08-22 15:39
if he didn't have enough cargo, that's the issue
isn't that fixed in some commit though?

**Comment by jafdy** [comment] 2016-08-22 15:40
It's the boxwing-cargo issue here and I honestly can't remember if it has.

**Comment by KiLEdEnNis** [comment] 2016-08-22 15:45
found it, #1339

**Comment by KeronCyst** [comment] 2016-08-23 01:19
Oops. I lost the Boxwing when I traded in my Mule for a Behemoth, and now I'm getting bounty-hunting instead of cruise-guarding jobs. ¯\_(ツ)_/¯ Also my bad for missing the bit about the luxuries!

**Comment by KiLEdEnNis** [comment] 2016-08-23 10:40
if the problem was because the goods were in the Boxwing, you can close the issue, since that's fixed next update

**Comment by KeronCyst** [comment] 2016-08-23 15:18
Got it, thank you!

**Closed** 2016-08-23 15:17 UTC
