### ISSUE TITLE
Main Zoom Factor reset after Alt+Tab

### ISSUE THREAD

**Issue by dufferzafar** [endless-sky/endless-sky#2642] opened 2017-06-17 17:55 UTC
1. Set main zoom factor to 150. 
2. Alt+Tab to some other application. 
3. Alt+Tab back to the game. 
4. Zoom factor reset to 100.

ES 0.9.7 on Ubuntu 16.04 (KDE Neon) Using packages from the PPA.

**Comment by endless-sky** [comment] 2017-06-17 17:59
This is a duplicate of #1903 / #1901. The zoom factor is automatically reduced if you make the window too small to display the full UI at a higher zoom level. The threshold is a raw UI height of 700 pixels, which is equivalent to 1050 screen pixels at 150% zoom.

**Comment by dufferzafar** [comment] 2017-06-17 18:44
@endless-sky Thoughts on this? https://github.com/endless-sky/endless-sky/issues/1903#issuecomment-267512656

**Comment by Pointedstick** [comment] 2017-06-18 03:44
https://github.com/endless-sky/endless-sky/issues/1903 was not resolved, sadly. It's definitely worth resolving IMHO since the exact number of vertical pixels that you've chosen as the minimum window height happens to trigger this "why did my zoom level get reset?" issue for anyone with a1080p screen and a UI with a top or bottom bar that's more than 30 pixels tall:

`700 pixels * 1.5x zoom level = window height of 1050 pixels`

That only leaves 30 pixels available before the window needs to drop the zoom level; with a bar that's 31 pixels tall, alt-tabbing would result in the window needing to be 1081 pixels, which is impossible by one pixel, so the zoom level gets jarringly and mysteriously reset and people file issues here and waste your time.

I see two possible solutions:
1. Make the zoom level in full-screen mode get remembered so that when you alt-tab back, it re-zooms if necessary
2. Make the minimum window height, say, 690 pixels, which will make the issue go away for a large percentage of currently affected people (since most top or bottom bars aren't 45 pixels tall).

**Closed** 2018-01-17 04:36 UTC
Labels: duplicate

**Comment by Pointedstick** [comment] 2018-01-17 04:50
Why don't you want to fix this?
