### ISSUE TITLE
Escorts Invincible WHen Not in Same System as Player

### ISSUE THREAD

**Issue by McloughlinGuy** [endless-sky/endless-sky#5297] opened 2020-09-06 23:45 UTC
**Is your feature request related to a problem? Please describe.**
I noticed that you can cheese escort missions by going fast enough to avoid being in the same system as them.

**Related Issue Links**
Has anyone else had this issue or idea? Share some links to those [Issues](https://github.com/endless-sky/endless-sky/issues), [Google Group threads](https://groups.google.com/forum/#!categories/endless-sky), or [Steam forum posts](https://steamcommunity.com/app/404410/discussions/)

**Describe the solution you'd like**
I think escorts should have a chance to be disabled while not in the same system as you, depending on a number of things. Each weapon on a ship would decrease its chance of being destroyed, the piracy rate in the sector would also play a big factor, and the spawn rate of Navy/Militia ships that could defend them.

**Describe alternatives you've considered**
An alternative would to just make it so the chance is based entirely off the piracy rate, but that would be taking a major shortcut.

**Additional context**
Some other factors would be the speed of your ship, the weapons on ships that spawn in the system, and the weapons on the pirates that spawn in the system. It's one giant overly complicated math problem.

**Comment by Amazinite** [comment] 2020-09-07 00:25
Duplicate of #2446.

**Closed by Amazinite** 2020-09-07 00:25 UTC
