### ISSUE TITLE
[balance] Change hull-to-shield ratio (or hull damage to shield damage ratio)

### ISSUE THREAD

**Issue by egilburg** [endless-sky/endless-sky#511] opened 2015-12-27 07:33 UTC
I mentioned this before on other discussions, but I feel it's worthy it's own thread.

Currently hull takes damage so much quicker compared to shields, it might as well not even be there. The difference between "shields at 0%" and "ship disabled or destroyed" is almost instant.

IMO most weapons should take at least as long to destroy hull as they do to destroy shield, and better yet take about twice a long to destroy hull as they do to destroy ship.

It would balance out tactical gamplay of weak-but-recharging shields (hit and run tactics, or blitzkrieg assault tactics) vs long drawn-out fights (lose shields and tank with hull, while staying in combat longer and doing more damage too).

It would also allow more creative hull-to-shield distribution on different ship types. For example, large freighters should have lots of hull points but proportionally weaker shields; dedicated interceptors and hit-and-run ships would have small hulls but strong shields for defense; a heavy warship would balance hull and shields.

Beyond being more balanced, it would allow more creative use of downed shields, which don't currently make sense because hulls are so fragile:

- Allow special EMP weapons which do huge damage to shield but little/no damage to hull. Currently such weapons would be too OP since taking down shield is so much harder than hull, so *everyone* would carry a few to complement their normal guns.
- Conversely, allow special armor-piercing weapons good against hull and bad against shields. Currently they'd be pointless because hull is an eggshell anyways so why sacrifice shield damage.
- Make shields go down during warp/jump, making escaper more exposed while they try to run away. Currently it'd be too severe because no shield = pretty much dead from just a few shots.
- Allow additional "hull plating" outfits  you'd buy to increase proportion of your hull, taking up outfit space, for a more tanky build. Currently it'd be pointless because doubling the hull for some outfit points is pointless when hull would still be weak anyways.
- Make hull repairs cost money (or, make hull repairs up to 25% be free and the rest cost money). Currently there are too few cases where you survive with significant hull damage and not just die outright.

**Comment by natangold** [comment] 2015-12-27 09:21
It depends how you're defining "more balanced". It would be more balanced - and your enemies would be far more likely and able to warp out of a system before you could disable them. The more hull a ship has, the longer they have between "crap, my shields are down" and the silent void of space; as soon as their shields are down, a [non-heroic] ship starts thinking about warping out of the system. The more time they have, the more time they have to slow down, stop, align themselves, and jump to safety.

Just for fun, I went through ships.txt and doubled the hull rating for every ship, without changing anything else. Then I went pirate hunting with my fleet of a half-dozen or so heavy warships: all the small fry died with no more fuss than before, and every ship larger than an interceptor escaped. Every bloody one.

**Comment by egilburg** [comment] 2015-12-27 10:47
@natangold that's a concern about AI logic rather than shield-hull balance. If currently AI jumps at certain percentage of their hull down (say, 50%), it could just be adjusted to make them jump at 25%, to compensate for the hull changes, while still addressing my other points.

**Comment by johndh** [comment] 2015-12-27 13:52
ES is pretty much a constant bloodbath right now, so toughening ships up and letting them get away sometimes sounds to me like a good change.  Having everyone fight to the death is just crazy.

**Comment by Nightmareman** [comment] 2015-12-27 15:50
Traditionally weapons tech quickly out advances armor tech so it makes sense that almost all the weapons cut through the ships hulls so quickly. Making super advance and thick armor to withstand all the different types of weapons would make the ships cost and weigh much more. While the shields are more cost effective and add far less to the weight of the ship as the shield matrix (which is the emitters and are hull integrated) and the generator which charges the shield are the only parts that add weight to the ship. I like the current dynamic as it emphasizes just how important your shields are if you are silly enough to go up against something that can take out your shields in only a few seconds what can I say you deserve to be exposed to the vacuum of space.

**Comment by thenerdfreak** [comment] 2015-12-27 15:52
different weapons do damage to Hull, Shield differently. It's already relatively balanced. You must be using something that does a lot of damage to Hull and not much damage to Shields (Thus the instant disablement after their shields run out) like lasers

**Comment by endless-sky** [comment] 2015-12-28 04:09
I think it would be reasonable to just double the hull amount for every ship, but to leave the AI behavior the same. After all, ships always fighting until they're way too damaged to escape makes very little sense. And, if there's a higher rate of ships escaping, that makes missiles and particle cannons suddenly much more useful as a strategic way to interrupt ships jumping.

But, that would be a big enough balance change that all the story line battles would need to be tested and possibly rebalanced, so it's probably something I'll save for the 0.9 series rather than the 0.8.9 release.

**Comment by thenerdfreak** [comment] 2015-12-28 04:15
That would make battles more drawn out and interesting ^ what if the player got the choice? like there was a slider, that set the multiplier of every ship's hull in the game. It wouldn't really affect the outcome of a fight since it affects EVERY ship, but it would make fights longer

**Comment by bobafetthotmail** [comment] 2015-12-28 17:47
>"But, that would be a big enough balance change that all the story line battles would need to be tested"

Story line battles can be fought by ships that don't escape (there are AI attributes right?), since either FW or Repubblic or whatever will have captains that will be more ready to die for the cause than the captain in an average pirate stomping party.

**Comment by thenerdfreak** [comment] 2015-12-28 17:50
The Republic Generals said themselves, they'll fight until all chance of WINNING is gone. Meaning when they know they'll lose, they'll flea.

**Comment by bobafetthotmail** [comment] 2015-12-28 18:06
Winning the war or the battle?

Because you can win a war by losing a battle too. "Phyrric victory" is the name of a battle that is technically won, but by expending so much resources that the rest of the war is lost.

**Comment by thenerdfreak** [comment] 2015-12-28 18:37
They said that about a specific hypothetical battle

**Comment by bobafetthotmail** [comment] 2015-12-29 13:33
Hmm... looked at the source.

I see only this

"Although, based on what Alondo said, the Navy hinted that if we made such a show of force that there was no way they could win the battle, they could honorably choose to retreat. So, if they start trying to retreat, let them go."

Easy way would be to not care about it at all, but you can also change it too.

**Comment by endless-sky** [comment] 2016-04-02 17:18
Addressed in 423450f. Also, this is a duplicate of #73.

**Closed by endless-sky** 2016-04-02 17:18 UTC
Labels: balance
