### ISSUE TITLE
log doubling if game is reloaded

### ISSUE THREAD

**Issue by downRightCoder256** [endless-sky/endless-sky#4618] opened 2019-10-23 18:04 UTC
player log entries and additional planet info will be doubled if the player reloads game during a conversation
To Reproduce:
     1:start an mission that will create a log entry or update planet name (eg: Pact Questioning)
     2:exit to main screen and load to the last save before finishing the conversation
     3:finish the conversation
     4:press "i", then "l" to open log
expected results: the log entry "Apparently the Navy is suspicious of anyone who worked with the Southern Mutual Defense Pact; got questioned about it by an officer. It was unclear what his rank or position in the Navy was." will appear once in the log

actual results: the mentioned log entry will appear twice in the log

 - OS: MacOSX 10.14.6Mojave 
 - Game Source: GitHub .dmg download
 - Version: 0.9.10

**Comment by downRightCoder256** [comment] 2019-10-23 18:10
I do know how to fix this bug: move all the "log" call to the end of the interaction. it is a simple solution, but annoyingly repetitive knowing the number of log calls in the whole game.

**Comment by Amazinite** [comment] 2019-10-23 18:22
Duplicate of #3746.

**Comment by downRightCoder256** [comment] 2019-10-23 18:27
> Duplicate of #3746.
ah, thanks for pointing out. didn't notice it first time

**Closed** 2019-10-23 18:30 UTC
Labels: duplicate
