### ISSUE TITLE
Add ramscoop values to ship information displays

### ISSUE THREAD

**Issue by williaji** [endless-sky/endless-sky#6739] opened 2022-04-17 16:48 UTC
### Problem Description

There is currently no way to see the ramscoop value for a ship except by looking in the save file or ship definitions. I can see energy, heat, speed, and turning, but not my ramscoop values. While I can add up the total value of installed ramscoops in my head, I really shouldn't have to. In addition, the automata and Remnant ships have integrated ramscoops whose values are not displayed anywhere. I only discovered the Remnant ones when it was mentioned in discord and the Korath ones when I read the ship definitions. Having these values displayed would make it easier for a player to make choices around the number and type of ramscoops needed for a particular job, whether that's getting to Hai space, exploring Korath worlds, or maintaining a cloak at Mesuket.

### Related Issue Links

I've not seen this discussed and I found no open requests for this enhancement.

### Desired Solution

Display the current ramscoop total in the ship display, along with shield, hull, fuel, etc.

### Alternative Approaches

I can't think of an alternative approach as to my knowledge this information is not displayed at all in game.

**Comment by Hecter94** [comment] 2022-04-17 17:34
I think merging https://github.com/endless-sky/endless-sky/pull/6587 would partially resolve this.

**Comment by Amazinite** [comment] 2022-04-17 21:13
Duplicate of #4215.

**Closed** 2022-05-25 20:10 UTC
Labels: duplicate
