### ISSUE TITLE
Fleet grouping and Roles.

### ISSUE THREAD

**Issue by RedLucidity** [endless-sky/endless-sky#3862] opened 2018-07-28 22:43 UTC
Thought it would be good to add fleet grouping to the ships in the outfitter, shipyard and player info areas... that is.
This part of my fleet is rouge squadron. Collapsable arrow drop with ship type highlighting... Ship type being Heavy Warship, Freighter... etc. 
Create groups and selecting ships to add to or remove from groups listed in the ship yard or outfitter to more easily outfit ships for specific purposes and assign group combat roles.  
such as the the ability to say this group protects this selected ship. Or this selected ship is assigned the fleet/group leader, or convoy ship. So on Default these ships perform specific behavior without the player designating it every time when entering a system. and will be able to build out ships for certain roles. or park whole groups. such as none combat groups when doing combat missions. or unpacking combat groups when expecting such. and or designing groups to fight specific species, or for bounty hunting or piracy/capturing. 

Groups should stay together instead of being pulled various dirrections.

Roles could be.
**Protector**: protects selected/assigned ship, cannot be pulled. that is gathers to that ship.
**Opportunist:** auto attacks any enemy ships as a group near leader. Cannot be pulled.
**Aggressive:** auto attacks any enemy ships nearby and will chase. 
**Hunter**: specifically attacks type of ship such as Freighter, Leader, Heavy Warship, and chases.
**Specific:** Attacks enemy targets of selected ship type, before attacking ships of lesser/greater type.
**Ranged:** enter systems edge and fight from a distance. keep distance from system center using only weapons that can reach target. Until called for by landing, or group to gather.
**Close combat**: move directly toward and engage ships with all weapon systems. 
**Hold**: when entering system holds position until called, by jump, landing, group gather, all gather.
**Follow**: follows selected ship as group leader or protected ship.

The ability to apply commands to mission assigned ships from the player Info screen. Such as protect this ship or group of ships. This is so it doesn't have to be only applied while landed. Mission assigned ships should be indicated in the screen. Perhaps as a seperate group, or highlighted a different color, and moved to the top or its own box section.

**Comment by ghoulavenger** [comment] 2018-07-29 00:49
I don't mind groupping ships within the panels, and I'm sure that it has been mentioned before, quite possibly even by myself. But the roles bit is a little excessive. If the combat were slower then maybe some of this would make some sense. But fleet combat as it is, is extremely swift, so a lot of this stuff just doesn't make any sense. 

As an alternative I might propose something like a fleet formation instead. Line to make your ships go in columns or rows, square to do order your ships go in four different directions from the center, standard formation which just follows the flagship (similar to the group mechannic already in game), no formation which would be the default behavior (also already in game).

**Comment by endless-sky** [comment] 2018-08-31 18:12
The game is mainly intended to be played with a single ship or a small fleet; there's no limit on fleet size, but there's also no intention to turn this into a game where managing a large fleet is expected or required. So, a feature like this is unlikely to be added.

Note that you can already use numeric hotkeys (control + number to bind, then press that number to select) to define groups of ships.

**Comment by Pointedstick** [comment] 2018-11-20 16:45
Yeah, basically a duplicate of https://github.com/endless-sky/endless-sky/issues/302.

**Closed by Pointedstick** 2018-11-20 16:45 UTC
Labels: unlikely
