### ISSUE TITLE
Game crashes when unknown attributes used

### ISSUE THREAD

**Issue by AlbertNewton** [endless-sky/endless-sky#3987] opened 2018-11-09 06:56 UTC
I have a number of worlds in Endless Sky.
One of them is one I use to test content in plugins I get or make; it has near-infinite money and a fleet of sixteen Bactrians.
For this world I wanted to be able to get around quicker, so I created a plugin with a "Cheat Drive," assuming there would be some kind of "jump distance" attribute. There was not, and the game repeatedly crashed when I tried to open it, until I removed the new outfit.
From this I inferred that it was the unknown attribute that was killing the game.

**Comment by Amazinite** [comment] 2018-11-09 07:08
Could you attach a file of this plugin so that others may test it?

**Comment by AlbertNewton** [comment] 2018-11-10 07:47
outfit "Cheat Drive"
	thumbnail "outfit/jump drive"
	cost 1
	"outfit space" 1
	"jump drive" 1
	"jump fuel" 1
	"jump distance" 100000

**Comment by KiLEdEnNis** [comment] 2018-11-10 10:47
first, they meant actually send your files so we can look, not just a few lines of code that's not even all of what you made

second, you're missing the line `category "Systems"`, so assuming you wouldn't crash, it wouldn't show up in the outfitter without this

third (not really relevant), your drive adds 1 outfit space once installed, unlike others that remove space, but that line isn't required at all, if you leave it out, you have an outfit that takes 0 space

fourth, you're missing the line `"jump speed"`, so if you have the drive installed, you can never jump with it, for reference, the Jump Drive has `"jump speed" .3`, but another "cheat drive" has `"jump speed" 500`, you may want to do that too

fifth, I don't seem to crash with your few lines of code you did send, neither before nor after I added the 2 missing lines

```outfit "Cheat Drive"
	category "Systems"
	thumbnail "outfit/jump drive"
	cost 1
	"outfit space" 1
	"jump speed" 500
	"jump drive" 1
	"jump fuel" 1
	"jump distance" 100000```
this works fine for me (you may want to copy-paste it, it's just your version with the 2 missing lines)

so whatever the issue is, it's probably not what you claim it is
would you mind sending all the relevant .txt files that cause you to crash?

**Comment by AlbertNewton** [comment] 2018-11-10 11:03
Yeah, I deleted the file to get it to work. That was my best guess at what I'd done. I'll take it out of my recycle bin and send it now. I copied and pasted the Jump Drive text in the actual thing, made it cost 1 and use 1 space, and added "jump distance" 10000. The game would crash just when the loading circle was about to meet itself in the centre. What you gave me does work.
[outfits.txt](https://github.com/endless-sky/endless-sky/files/2568329/outfits.txt)

**Comment by KiLEdEnNis** [comment] 2018-11-10 11:06
so you added the 2 lines and you didn't crash?

can you try adding only 1 of the 2 lines and launch the game, so we know which of the 2 missing lines caused it?
and could you tell us what operating system you use? since me on my Windows 10 doesn't get whatever error you get

**Comment by AlbertNewton** [comment] 2018-11-11 17:19
windows 10. I have tried removing all my plugins and the game works.

**Comment by gunqqer** [comment] 2018-11-11 19:56
if removing all the plugins fixed it, that means the problem isnt the game. Please close this issue

**Comment by KiLEdEnNis** [comment] 2018-11-11 20:57
as for more detailed help with your bug, you can ask around on the ES Discord (https://discord.gg/ZeuASSx)
either way, indeed close this issue, as it's not relevant to nor caused by the base game

**Comment by KiLEdEnNis** [comment] 2018-11-11 23:02
as far as I'm aware myself from the limited response I got in this issue, it was apparently caused by missing lines in a new outfit he tried to make
source:
> What you gave me does work.

where it was just 2 lines I added (no jump speed wouldn't cause this, so I'd say a missing category made him crash)

if that's the case, you can at most try to prevent a crash when such an error happens (like, "error? ignore this whole outfit")
but unless we get another response, we won't know

**Closed** 2020-07-21 11:22 UTC
Labels: unconfirmed
