### ISSUE TITLE
Targets missing in mission "Wanderers: Sestor: Kill Southern Remnant"

### ISSUE THREAD

**Issue by damerell** [endless-sky/endless-sky#3956] opened 2018-09-24 06:05 UTC
I am playing a trunk build from the 4th September.

I found it sufficiently difficult to find all the targets for this mission that I went and peeked in the savefile. This showed me that the surviving Kor Sestor ships were in Capella, but I'd been there; I returned there more than once but couldn't see them. I eventually resorted to editing the savefile to change their hull to a negative number, and on loading the edited save was told "All of the Kor Sestor ships in this system have been eliminated." and could proceed.

I attach a copy of the affected savefile.

[Kirsty M'stellid.txt~](https://github.com/endless-sky/endless-sky/files/2409740/Kirsty.M.stellid.txt)

**Comment by TechnoNinja64** [comment] 2018-09-24 06:09
Did you make sure you didn't just disable the ships? You need to kill them completely

**Comment by damerell** [comment] 2018-09-24 06:27
Yes. It may surprise you to learn that at this stage of the game I have done one or two "kill ships" missions already and, since I'm not a blithering idiot, do know the difference between blowing a ship up and disabling it.

Is there any chance you could reply to an issue without insulting my intelligence?

**Comment by TechnoNinja64** [comment] 2018-09-24 06:49
A possibility is that they followed you after you jumped out of the system, since they have hyperdrives, this method is useful if you don't have a strong enough fleet. (course yours could probably handle a quarg onslaught).

Very sorry, I'm simply not a very social person, with extremely bad communication skills, I wouldn't find my own comment offensive if it was sent to me.

**Comment by damerell** [comment] 2018-09-24 06:59
Obviously they didn't follow me since the savefile shows them still being in Capella.

**Comment by TechnoNinja64** [comment] 2018-09-24 07:13
Hmm, try it again, all I get is a fleet of Sestor drones which after killing all of them the message pops up

**Comment by TechnoNinja64** [comment] 2018-09-24 08:18
It could have happened to me without me noticing since I don't usually keep track of the amount of enemies on screen, a significant decrease I would notice, Especially with capital ships. On those missions I did reload a lot, mainly to losing some of my fleet.

**Comment by Amazinite** [comment] 2018-09-24 13:29
Using the save file you provided, I'm immediately met by a swarm of Sestor fighters when I depart the planet. Killing all of them gives the dialog as expected. Is this not the behavior you're experiencing? Are the ships just not appearing? It may be that there's a fighter left alive after you've fought them all, The default key for selecting the nearest hostile ship is R, and pressing R whenever you need to make sure all enemy ships are dead is a good strategy; if nothing pops up when you press R, you should be good.

**Comment by damerell** [comment] 2018-09-24 22:42
As discussed, I already checked repeatedly for the missing ships. I am not on 0.9.8, as mentioned in the first line of the original issue. Also as discussed, on loading the savefile the missing ships reappear.

**Comment by Amazinite** [comment] 2018-09-25 01:01
So is this in any way reproducible? And if not, how are we to fix whatever it is?

**Comment by damerell** [comment] 2018-09-25 01:05
As already discussed, I managed to make it happen a second time. I feel this would be easier if I were not constantly repeating things already in the issue.

I appreciate it may be tricky to identify the cause and fix it but it still seems better to report it than to ignore it.

**Comment by jafdy** [comment] 2018-09-25 10:03
Can you check for a file called `errors.txt` in should be near the save files.

**Comment by tehhowch** [comment] 2018-09-25 13:31
The `errors.txt` file will only relate issues from parsing game files on load; I doubt it will have anything useful. What will be most useful is to post an exact reproduction instruction, and a save file from which to start it.

Even better would be to identify the specific commit which introduces the issue (be sure to back up your save before using earlier game versions). You can use `git bisect` to speed up the commit traversal. You will need to be able to build the game from source to do this.

**Comment by jafdy** [comment] 2018-09-25 15:07
It would also let us eliminate the possibility that the ships simply aren't working for this one person.
So far neither the current build or 0.9.8 is able to reproduce the errors and reproducing it is looking tough, I am simply trying to eliminate every possibility I can.

**Comment by damerell** [comment] 2018-09-25 18:55
errors.txt contains only:

Skipping unrecognized root object:
file "L:/games/endless-sky-win64-0.9.8/data/combat ratings.txt"
  "combat ratings"

Just did it again. Here's what I did - I don't know which steps are significant, of course.
Load that save, undock in Capella, blow the ships up. Return to Farpoint. Ask for Oathkeeper assistance at Alnilam.
Go to Alnilam. All Oathkeepers destroyed/disabled in ensuing battle. Capture a Kor Sestor Met Par Tek 53. Land (the constant stream of pirates at Alnilam, who apparently care nothing for the alien invasion, makes it hard to preserve captures without landing immediately). On departure, the Kor Sestor ships have vanished.

Unfortunately I don't know if it does this consistently because the odds of making a capture are small so it is hard to check.

**Comment by TechnoNinja64** [comment] 2018-09-26 06:05
Last two times it happened, did you capture a ship?

**Comment by damerell** [comment] 2018-09-26 09:38
I think so, but I'm not completely sure. Sorry. The combination of revisiting Capella several times and trying to reproduce it several times means I couldn't say for sure.

**Comment by Amazinite** [comment] 2019-09-04 15:35
Closing because I'm fairly certain that this was #4130, especially given my comment that loading the provided save file resulted in me only finding stray fighters, which was the same experience as #4130.

**Closed by Amazinite** 2019-09-04 15:35 UTC
Labels: unconfirmed
