### ISSUE TITLE
Bug: Pirate AI getting stuck while plundering after big battle

### ISSUE THREAD

**Issue by flaviojs** [endless-sky/endless-sky#2972] opened 2017-08-27 19:54 UTC
While dominating pirate systems with my current permanent fleet (Mule and 7 Headhunters) I stumbled upon the Korath in Almach. I was able to disable the Korath Raiders after adding another Headhunter, so now I'm in this system capturing ships and plundering Korath outfits to prepare a heavier fleet in order to explore or raid or dominate Jump Drive accessible systems.

Since my current fleet is fast and not very durable, I avoid fighting too many opponents at a time and stay away from the main battle when different factions are fighting each other (Syndicate, Pirates, Korath).

**After the Pirates win** a big battle they **will start to plunder** disabled Syndicate ships (destroying the disabled ship after plundering?) and sometimes **get stuck circling the same spot**, which I presume is where the disabled ship was. To "fix" this I get close enough for them to target me and either run or destroy them.

Is there anything you want me to try the next time this happens?

**Comment by tehhowch** [comment] 2017-08-27 22:10
The "shooting after plundering" is normal behavior.

Reproducibility questions:
 - How close do these pirates get before they get locked in as "buzzards", even when the target is destroyed and no longer there? Almost boarded it? Still thrusting towards it? Turned around and slowing down?
 - Is this particular models of ships, or all?
 - Does this happen even if you've tributed the Pirate government so they don't consider you a foe?

**Comment by Amazinite** [comment] 2017-08-27 22:55
Something I've noticed is that sometimes pirates will circle disabled ships, but this is only when there are a bunch of pirates in the system. There has always been at least one ship that will go and board the disabled ship, then resulting in all the pirates circling the disabled ship to destroy it. It's almost as if one of the pirates called dips on a ship and the rest are just circling around to guard it. 

Although, I've never witnessed pirates circling disabled ships and never boarding them or circling empty space.

**Comment by tehhowch** [comment] 2017-08-27 23:09
![image](https://user-images.githubusercontent.com/20871346/29754823-e166ef42-8b52-11e7-89ca-0fecc37e0543.png)
"We dare you to move!"

**Comment by tehhowch** [comment] 2017-08-28 00:24
The issue is that the circling ships have already filled their cargo holds, but have not boarded their current target.
PR to fix this shortly

**Comment by flaviojs** [comment] 2017-08-28 17:57
I confirm that the Pull Request fixes the problem.

As for the case where there was nothing in the location they were hovering, the ship probably got destroyed when they started shooting at my fleet as I approached.

Should I close this issue now or wait for the PR to be merged?

**Comment by tehhowch** [comment] 2017-08-28 17:58
Wait for the PR to be merged, and for this to receive a milestone

**Comment by endless-sky** [comment] 2017-08-31 14:35
Fixed by merging #2974.

**Closed** 2017-08-31 14:51 UTC
Labels: bug
