### ISSUE TITLE
AppImages for ES v0.10.7+ Fail to Mount on Linux Earlier than Ubuntu 22.04 (instructions for older versions included)

### ISSUE THREAD

**Issue by mathwhiz1212** [endless-sky/endless-sky#10297] opened 2024-07-04 09:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I try to open the Linux AppImage file and for v0.10.7 and v0.10.8, it does nothing. For v0.10.6 and earlier, it works just fine. 

If I run it using the command line `./Endless_Sky-v0.10.8-x86_64.AppImage` , I get the following errors:

```
fuse: failed to exec fusermount: Permission denied

Cannot mount AppImage, please check your FUSE setup.
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
open dir error: No such file or directory
```

I tried extracting it using the `--appimage-extract` option and tried to use the Endless Sky application shortcut in the resulting folder, but it says "There was an error launching the application."

I tried using ESLauncher2 to install ES v0.10.8 and saw the same behavior. If I hit the play button, nothing happens. If I find the AppImage file and open it, nothing happens. If I run it via command line, I get the exact same error.

`./endless-sky.AppImage`

```
fuse: failed to exec fusermount: Permission denied

Cannot mount AppImage, please check your FUSE setup.
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
open dir error: No such file or directory
```

### Steps to Reproduce

1. Get a Linux PC.
2. Download an AppImage of Endless Sky.
3. Give the AppImage file permission to launch `sudo chmod +x ./Endless_Sky-v0.10.8-x86_64.AppImage`
4. Launch it via CLI to get error messages, `./Endless_Sky-v0.10.8-x86_64.AppImage`
5. See the same errors shown above.

### Expected Behavior

The game would start when the AppImage file was opened (as it does before v0.10.7)

### Operating System

Linux Mint 20 (based on Ubuntu 20.04 LTS)

### Game Source

GitHub Releases

### Game Version

v0.10.8

**Comment by TheGiraffe3** [comment] 2024-07-04 10:00
I believe there was a recently-merged PR that made the lowest Ubuntu version be 22. @tibetiroka, am I correct?

**Comment by tibetiroka** [comment] 2024-07-04 11:57
Can you run other appimages? The error message suggests there is a permission misconfiguration on your system somewhere.

**Comment by tibetiroka** [comment] 2024-07-04 11:58
> I believe there was a recently-merged PR that made the lowest Ubuntu version be 22. @tibetiroka, you made the PR. Am I correct? #10218 did this, I think.

That is only on continuous. It isn't in 0.10.7/8, so it cannot possibly be causing this issue.

**Comment by mathwhiz1212** [comment] 2024-07-05 05:06
> Can you run other modern appimages? The error message suggests there is a permission misconfiguration on your system somewhere.

Yes. I tested the most recent AppImages for Audacity, Etcher, and Endless Sky prior to v0.10.7 and they appear to work fine.

**Comment by mathwhiz1212** [comment] 2024-07-05 05:23
I was able to launch Endless Sky v0.10.8 after fiddling with the extracted AppImage.

The `Endless Sky` shortcut within the extracted AppImage appears to try to execute `squashfs-root/usr/share/applications/io.github.endless_sky.endless_sky.desktop` which does nothing. It appears to be some kind of configuration file with the name and description of the game.

Executing `squashfs-root/AppRun` from the command line launches the game. That shortcut points to `squashfs-root/usr/bin/endless-sky`, which I can also launch successfully from the command line.

There appears to be two problems:

1. It seems like it's trying to mount the AppImage and failing to get permission (perhaps the command needs sudo permissions and didn't get them).
2. There may or may not be a shortcut off in the AppImage, I couldn't say because I'm not familiar with the internal structure of AppImages.

**Comment by mathwhiz1212** [comment] 2024-07-05 05:49
Going to the link mentioned in the error and reading about Fuse, it seems like this error is because I'm using an older version of Linux.

Ubuntu <= 21.10 uses `fuse`, but in Ubuntu 22.04+ installing `fuse` may break your system so you must only use `libfuse2` while Ubuntu >= 24.04 uses `libfuse2t64`

My best guess is that ES updated to use `libfuse2` only instead of `libfuse2` and `fuse` both because that will work fine on Ubuntu 22.04+

https://github.com/AppImage/AppImageKit/wiki/FUSE

**Comment by mathwhiz1212** [comment] 2024-07-05 05:50
> > I believe there was a recently-merged PR that made the lowest Ubuntu version be 22. @tibetiroka, you made the PR. Am I correct? #10218 did this, I think.
> 
> That is only on continuous. It isn't in 0.10.7/8, so it cannot possibly be causing this issue.

Please see: https://github.com/endless-sky/endless-sky/issues/10297#issuecomment-2210223142

**Comment by Samueru-sama** [comment] 2024-07-15 18:07
@mathwhiz1212 you can also run the appimage with the `--appimage-extract-and-run` flag and that way you don't have to be running the AppRun manually.

There is also a env variable that makes all appimages launch that way though it is no recommended.

Can you launch the [cemu](https://github.com/cemu-project/Cemu/releases) emulator appimage? that one uses a appimagetool that might fix your issue.

**Comment by Samueru-sama** [comment] 2024-07-15 21:50
> I installed Ubuntu 20.04 in a virtual machine and tried running the 0.10.8 appimage and had no issues. Could this be Mint specific?

There has been some changes in debian which also affect mint with the name of the libfuse package and all of that. maybe not  sure.

All these fuse2 issues are a nightmare and that is why I asked @mathwhiz1212 to test the cemu appimage which if it works I will post a script that turns the existing appimage into an appimage that has the static runtime (doesn't need fuse2) and should fix the issue for good.

**Comment by mathwhiz1212** [comment] 2024-07-15 23:23
> you can also run the appimage with the `--appimage-extract-and-run` flag and that way you don't have to be running the AppRun manually.

Thank you. I prefer the faster startup times of launching it directly.

**Comment by mathwhiz1212** [comment] 2024-07-15 23:24
> Can you launch the [cemu](https://github.com/cemu-project/Cemu/releases) emulator appimage? that one uses a appimagetool that might fix your issue.

It appears that this produces the same error message. Is this perhaps a problem unique to my system?

```
fuse: failed to exec fusermount: Permission denied

Cannot mount AppImage, please check your FUSE setup.
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
open dir error: No such file or directory
```

**Comment by Samueru-sama** [comment] 2024-07-15 23:30
> > Can you launch the [cemu](https://github.com/cemu-project/Cemu/releases) emulator appimage? that one uses a appimagetool that might fix your issue.
> 
> It appears that this produces the same error message. Is this perhaps a problem unique to my system? If so, we could close the issue now that I have a way to launch ES.
> 
> Though if I'm going to encounter this with some other AppImages then perhaps I should investigate further.
> 
> ```
> fuse: failed to exec fusermount: Permission denied
> 
> Cannot mount AppImage, please check your FUSE setup.
> You might still be able to extract the contents of this AppImage 
> if you run it with the --appimage-extract option. 
> See https://github.com/AppImage/AppImageKit/wiki/FUSE 
> for more information
> open dir error: No such file or directory
> ```

Can I see the output of `which fusermount` and also the output of `readlink $(which fusermount)`?

**Comment by mathwhiz1212** [comment] 2024-07-15 23:40
> > > Can you launch the [cemu](https://github.com/cemu-project/Cemu/releases) emulator appimage? that one uses a appimagetool that might fix your issue.
> > 
> > 
> > It appears that this produces the same error message. Is this perhaps a problem unique to my system? If so, we could close the issue now that I have a way to launch ES.
> > Though if I'm going to encounter this with some other AppImages then perhaps I should investigate further.
> > ```
> > fuse: failed to exec fusermount: Permission denied
> > 
> > Cannot mount AppImage, please check your FUSE setup.
> > You might still be able to extract the contents of this AppImage 
> > if you run it with the --appimage-extract option. 
> > See https://github.com/AppImage/AppImageKit/wiki/FUSE 
> > for more information
> > open dir error: No such file or directory
> > ```
> 
> Can I see the output of `which fusermount` and also the output of `readlink $(which fusermount)`?

`which fusermount`

```
/bin/fusermount
```

`readlink $(which fusermount)` returns nothing, with `-v` it returns an invalid argument error.

`readlink -f $(which fusermount)` returns

```
/bin/fusermount
```

**Comment by Samueru-sama** [comment] 2024-07-15 23:47
> > > > Can you launch the [cemu](https://github.com/cemu-project/Cemu/releases) emulator appimage? that one uses a appimagetool that might fix your issue.
> > > 
> > > 
> > > It appears that this produces the same error message. Is this perhaps a problem unique to my system? If so, we could close the issue now that I have a way to launch ES.
> > > Though if I'm going to encounter this with some other AppImages then perhaps I should investigate further.
> > > ```
> > > fuse: failed to exec fusermount: Permission denied
> > > 
> > > Cannot mount AppImage, please check your FUSE setup.
> > > You might still be able to extract the contents of this AppImage 
> > > if you run it with the --appimage-extract option. 
> > > See https://github.com/AppImage/AppImageKit/wiki/FUSE 
> > > for more information
> > > open dir error: No such file or directory
> > > ```
> > 
> > 
> > Can I see the output of `which fusermount` and also the output of `readlink $(which fusermount)`?
> 
> `which fusermount`
> 
> ```
> /bin/fusermount
> ```
> 
> `readlink $(which fusermount)` returns nothing, with `-v` it returns an invalid argument error.
> 
> `readlink -f $(which fusermount)` returns
> 
> ```
> /bin/fusermount
> ```

That's okay that readlink returns nothing, it means fusermount is not symlinked.

Run `sudo ln -s /bin/fusermount /usr/bin/` and now the appimages should work, let me know because there is more to this story lol.

**Comment by mathwhiz1212** [comment] 2024-07-15 23:58
> > > > > Can you launch the [cemu](https://github.com/cemu-project/Cemu/releases) emulator appimage? that one uses a appimagetool that might fix your issue.
> > > > 
> > > > 
> > > > It appears that this produces the same error message. Is this perhaps a problem unique to my system? If so, we could close the issue now that I have a way to launch ES.
> > > > Though if I'm going to encounter this with some other AppImages then perhaps I should investigate further.
> > > > ```
> > > > fuse: failed to exec fusermount: Permission denied
> > > > 
> > > > Cannot mount AppImage, please check your FUSE setup.
> > > > You might still be able to extract the contents of this AppImage 
> > > > if you run it with the --appimage-extract option. 
> > > > See https://github.com/AppImage/AppImageKit/wiki/FUSE 
> > > > for more information
> > > > open dir error: No such file or directory
> > > > ```
> > > 
> > > 
> > > Can I see the output of `which fusermount` and also the output of `readlink $(which fusermount)`?
> > 
> > 
> > `which fusermount`
> > ```
> > /bin/fusermount
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `readlink $(which fusermount)` returns nothing, with `-v` it returns an invalid argument error.
> > `readlink -f $(which fusermount)` returns
> > ```
> > /bin/fusermount
> > ```
> 
> That's okay that readlink returns nothing, it means fusermount is not symlinked.
> 
> Run `sudo ln -s /bin/fusermount /usr/bin/` and now the appimages should work, let me know because there is more to this story lol.

I ran that command and the AppImage for ES 0.10.8 works normally Thank you!

What is the "more to this story"?

**Comment by Samueru-sama** [comment] 2024-07-16 00:03
@mathwhiz1212 When the type2 runtime was updated they hardcoded the path to fusermount to `/usr/bin` due to security concerns, at that time pretty much every single linux distribution had fusermount in `/usr/bin` (and most distros actually symlink `/bin` to `/usr/bin` so this cannot even happen if you try to manually place the binary in `/bin` in most distros).

Welp, turns out there are a few distros that still keep that separation, one is alpine linux, and TIL that older versions of linuxmint have that as well. 

There is a [PR restoring the look in path](https://github.com/AppImage/type2-runtime/pull/32) but it seems to have stalled LOL, I didn't think it was that much of a deal because in the end very few appimages even work in alpine linux, but now that it turns out that mint is affected it is bad.

**Comment by mathwhiz1212** [comment] 2024-07-16 00:15
> @mathwhiz1212 When the type2 runtime was updated they hardcoded the path to fusermount to `/usr/bin` due to security concerns, at that time pretty much every single linux distribution had fusermount in `/usr/bin` (and most distros actually symlink `/bin` to `/usr/bin` so this cannot even happen if you try to manually place the binary in `/bin` in most distros).
> 
> Welp, turns out there are a few distros that still keep that separation, one is alpine linux, and TIL that older versions of linuxmint have that as well.
> 
> There is a [PR restoring the look in path](https://github.com/AppImage/type2-runtime/pull/32) but it seems to have stalled LOL, I didn't think it was that much of a deal because in the end very few appimages even work in alpine linux, but now that it turns out that mint is affected it is bad.

Interesting. I intend to test this on a recent version of Linux Mint (21.2) and see if it's exclusively an issue with older installs like mine.

**Comment by Samueru-sama** [comment] 2024-07-16 00:18
> Interesting. I intend to test this on a recent version of Linux Mint (21.2) and see if it's exclusively an issue with older installs like mine.

You would just have to check if `fusermount` or `fusermount3` is in `/usr/bin` instead of `/bin`.

**Comment by TomGoodIdea** [comment] 2024-07-16 07:01
So, this isn't a problem with Endless Sky?

**Comment by Samueru-sama** [comment] 2024-07-16 07:21
> So, this isn't a problem with Endless Sky, but with AppImages? I mean, is there anything we can do on our end?

Yes and not much can be done.

**Comment by warp-core** [comment] 2024-07-16 17:46
Closing since the issue has been established as not a bug in Endless Sky.

**Closed by warp-core** 2024-07-16 17:46 UTC
Labels: bug, unconfirmed

**Comment by mathwhiz1212** [comment] 2024-07-18 00:54
> I didn't think it was that much of a deal because in the end very few appimages even work in alpine linux, but now that it turns out that mint is affected it is bad.

@Samueru-sama This is no longer an issue in Linux Mint 21.3. It was just my old Linux Mint install that newer ES versions have trouble with before your `sudo ln -s /bin/fusermount /usr/bin/` fix. Thanks for the help.
