### ISSUE TITLE
Passenger assignment to ship not preserved in savegames

### ISSUE THREAD

**Issue by AMDmi3** [endless-sky/endless-sky#4600] opened 2019-10-16 02:42 UTC
So I've had a decent fleet and a lot of cargo/passenger delivery missions taken, when I went onto wormhole exploration mission (e.g. remnant space). Only my flagship had a crystal, so the rest of the fleet was left at the wormhole entrance. I was able to land on and depart from remnant worlds without problems, then I've loaded a recent savegame (on remnant world) and discovered that I cannot take off any more without cancelling some missions first, as the flagship had -20 free bunks.

It looks like a state of which or even just how many passengers are assigned to each ship is not saved, so after loading everybody ended up on a flagship. It doesn't look like correct behavior.

**Comment by tehhowch** [comment] 2019-10-16 03:31
Duplicate of https://github.com/endless-sky/endless-sky/issues/1624

**Closed** 2019-10-16 03:38 UTC
