### ISSUE TITLE
Have fighters return to their mothership if nearly dead

### ISSUE THREAD

**Issue by mdsmestad** [endless-sky/endless-sky#664] opened 2016-01-13 22:52 UTC
At this point in the game I've found fighters to be pretty useless. It would be a lot better if the game instructed the fighters to return to the fighter bay when there health hits 50%, then return to combat. Fighters should replenish hp in the bays as well of course (not sure if this is already implemented).

Perhaps fighter bays should also act like munitions, and auto replenish at the outfitter.

**Comment by brick96** [comment] 2016-01-13 23:07
health as in shields or health as in hull? they are disabled when under 50% hull

**Comment by endless-sky** [comment] 2016-01-13 23:46
Fighters in bays can use their mothership's excess shield capacity to recharge their shields.

I could look into what it would take to adjust the AI, but the main problem is that fighters evaporate so quickly that they might not have time to flee from battle anyway.

**Comment by Pointedstick** [comment] 2016-01-14 03:04
Yeah, fighter and interceptor sized craft are pretty useless right now unless there are like 15 or more, and you can still expect half or more of them to get blown up.Seems like it's more effective and efficient to use an equivalent amount of money to buy larger, more durable, more versatile ships.

**Comment by Pointedstick** [comment] 2016-01-14 03:13
Honestly I think part of the problem is fighters' low weapons capacity and inappropriate default armament. The whole point of a fighter-sized craft is to jam as much long-range weaponry as possible into a small, fast, maneuverable package so it can reach and destroy its target before the target can strike back. Fighters armed with nothing but a pair of beam lasers suck at everything, because by the time they're close enough to use their weapons, they're easy prey for the defensive fire of larger ships. Give those fighters meteor missile launchers or rockets launchers, with a single large cannon like a proton gun or a Javelin launcher as a last-ditch close range weapon, and they might be more intimidating and truer to their logical real world role.

**Comment by Oeleo** [comment] 2016-01-14 08:09
You can give them one heavy laser. Yeah that's sad that we can't give them something like proton gun, but they will be able to have a torpedo luncher, so maybe they will become too much strong ? I don't know, they are too weak in defense I think, poor fighters.

**Comment by DingusShingleton** [comment] 2016-01-14 17:27
Is there some way that fighters could reduce the accuracy of guns shooting at them, to represent their agility? Or maybe just give fighters a flat %miss chance? Cause really what makes them so useless, by and large, is laser turrets. They track instantly and unerringly, and fighters just don't stand a chance. Even other turrets are a bit more forgiving because they aren't hitscan.

Sometimes as a smaller, more agile ship, you can outmaneuver a larger more heavily armed ship by staying out of its firing arc, a difficult but extremely satisfying feat. But if you are facing something with a heavy laser turret, no amount of fancy piloting can save you. That's why I personally think having a tracking speed stat for turrets would be a great idea, but that's another topic entirely

**Comment by mdsmestad** [comment] 2016-01-14 22:34
I like the idea of fighters haven't a high %miss chance. I even think they should have the ability to pass throw turret and gun fire a cirtain % of the the time. Also they need more fire power. If you coupled those things fighters might be usefull. 

Imagine fighters that have a high chance of passing right through enemy fire. I like this idea.

**Comment by LocalGod79** [comment] 2016-03-11 18:18
to resurrect this in light of development, perhaps make them immune to 'piercing' damage?

the piercing mechanic development in particular exacerbates this issue.

**Comment by DingusShingleton** [comment] 2016-03-12 18:51
Not really. Any amount of damage that will deal a fighter a significant amount of hull damage via piercing will outright blew it out of the sky anyway

**Comment by tehhowch** [comment] 2017-09-29 22:48
This is implemented in #1971

**Comment by Pointedstick** [comment] 2018-08-02 18:47
@mdsmestad, if you're still around, you can close this now.

**Comment by Pointedstick** [comment] 2018-11-20 22:59
Done now.

**Closed by Pointedstick** 2018-11-20 22:59 UTC
Labels: enhancement

**Comment by Amazinite** [comment] 2018-11-21 00:02
Where at? Tehhowch mentioned #1971, which he closed for #3791, but #3791 isn't merged yet.
(When you close something and say "this is done," it'd be helpful to link to where it was done, either the merged PR or the commit hash.)

**Comment by Pointedstick** [comment] 2018-11-21 00:07
In https://github.com/endless-sky/endless-sky/commit/24cab842a9f3a66c1b5fb862e1139707c9dd2ee4

**Comment by Amazinite** [comment] 2018-11-21 00:08
(This is why giving the commit hash is important. 😄)
