### ISSUE TITLE
First set of attacking ships in early "Escort" missions gets confused when you get disabled

### ISSUE THREAD

**Issue by SolraBizna** [endless-sky/endless-sky#1617] opened 2016-09-24 02:32 UTC
I've been doing low-level Escort missions on a new playthrough. Since I'm in a mostly-stock Clipper, the pirate ships that follow me from the start of the mission frequently disable me. When they do, they stop deliberately turning or thrusting, and usually stop firing as well a moment later once their velocity carries them away. They'll happily remain comatose even when being attacked by other ships. They "wake up" again if I get repaired.

The ones waiting in the _destination_ system, on the other hand, behave as expected.

**Comment by endless-sky** [comment] 2016-09-24 02:52
This is a duplicate of #1451.

**Closed by endless-sky** 2016-09-24 02:52 UTC
