### ISSUE TITLE
Ship wear and tear restored when buying an identical ship

### ISSUE THREAD

**Issue by michel-slm** [endless-sky/endless-sky#5052] opened 2020-05-09 23:35 UTC
**Describe the bug**
When I buy an identical ship (e.g. I'm now up to 7 Scouts), the older ships should sell for cheaper since their prices have depreciated. Instead, the multiplier seems to be reset to 100%.

**To Reproduce**
1. Fly around with the current ship to lower its value
2. Buy an identical ship
3. Check the percentage multipliers

**Expected behavior**
Older ship keeps its multiplier, newer ship is at 100%

**Screenshots**

**System (please complete the following information):**
 - OS: CentOS 8
 - Game Source: Flathub
 - Version: 0.9.12

**Link to save file**
[Michel Lind~allshipsame.txt](https://github.com/endless-sky/endless-sky/files/4604893/Michel.Lind.allshipsame.txt)

**Additional context**
I don't have a save from exactly after buying my last ship, so they're all at 91% now.

**Comment by tehhowch** [comment] 2020-05-10 01:33
You always sell the most expensive fungible item.

**Comment by tehhowch** [comment] 2020-05-10 03:02
Duplicate of https://github.com/endless-sky/endless-sky/issues/2258

**Comment by michel-slm** [comment] 2020-05-10 15:21
Ah, thanks! That makes the process pleasantly free of micro management

**Closed** 2020-05-10 15:20 UTC
