### ISSUE TITLE
Feature Request: Meteri Messages

### ISSUE THREAD

**Issue by kaiser-dg** [endless-sky/endless-sky#3084] opened 2017-09-27 14:20 UTC
So, around midway through the Wanderers campaign, you discover that the Kor Meteri drones now believe themselves to be Wanderers and are apparently able to speak your language.
Even so, if you attempt to contact a Meteri ship, you get the standard alien voice message.
Perhaps, since the Meteri can now speak you language, they should radio messages similar to that of the Wanderers?

**Comment by Amazinite** [comment] 2017-09-27 14:25
Duplicate of #1937
Please close this issue.

**Closed** 2017-09-27 20:07 UTC
