### ISSUE TITLE
Some cargo state info lost when exiting game?

### ISSUE THREAD

**Issue by astronomertom** [endless-sky/endless-sky#5441] opened 2020-10-12 23:23 UTC
My ship with escort has cargo split between them.
My escort ship was disabled in a star system just as I was jumping to destination so when I land on the destination, I can't complete the cargo delivery since some is left on the escort ship.
I jump back to the previous star system to rescue my escort and successfully board.  However, before getting out of the system, I get badly shot-up, so I exit the game before I have a chance to die.
Usually when I restart, I can pick up from my last landing location (where previously I could not complete the delivery since I didn't have all the cargo).  However, on restart, it seems to think my ship has all the cargo and it lets me complete the delivery.  Note that from this restart, I had not yet returned to my escort ship so the cargo could not have been transferred when I boarded to repair.

**Comment by Rakete1111** [comment] 2020-10-13 13:13
Thanks for reporting! This is a known bug caused by the fact that the save file doesn't store which ships carry what mission cargo. Duplicate of pinned issue #1624.

**Comment by astronomertom** [comment] 2020-10-13 23:02
Thanks.  I looked back a ways looking for an earlier report, but not that far back.  :^)

**Closed** 2020-10-19 03:49 UTC
Labels: duplicate
