### ISSUE TITLE
Feature request: auto-aim button

### ISSUE THREAD

**Issue by SolraBizna** [endless-sky/endless-sky#166] opened 2015-11-07 21:38 UTC
My playstyle frequently has me in highly reflex-critical situations with relatively fragile ships. In those situations, precise control over my ship's attitude is more important than landing hits on my _selected_ target with my fixed weapons, and therefore I don't want auto-aim enabled. However, that's not always the case.

I propose adding a key to Endless Sky that performs "Automatic aiming" behavior while pressed, regardless of the current setting. The nearest equivalent is the EV "autopilot" key which simply points your ship toward the target.

**Comment by Pointedstick** [comment] 2015-11-09 00:33
Seconded. I often want to point my ship in the direction of a selected but non-visible ship and reflexively hit the 'a' key--which does this in EV.

**Comment by dplepage** [comment] 2015-11-23 02:33
A few times I've had auto-aiming kick in even when I wasn't holding fire, and on at least two occasions this has killed me - I hit the key to hyperjump but when enemy fighters got close my ship started tracking them instead of turning to make the jump. This is probably a bug in and of itself, but I haven't yet figured out how to reliably reproduce it.

Making automatic aiming an explicit button would certainly prevent that from happening.

**Comment by endless-sky** [comment] 2015-11-23 03:27
@dplepage, is it possible you had automatic firing active as well as automatic aiming?

**Comment by dplepage** [comment] 2015-11-23 15:00
@endless-sky No, I checked that - I have automatic aiming but not automatic firing. The bug seems to happen regardless of whether or not I'm holding the jump button.

**Comment by SolraBizna** [comment] 2015-11-23 19:52
For what it's worth, I disabled automatic aiming immediately after I first noticed its effects, and I am maybe 40% confident that I was not holding the fire button when it happened.

**Comment by endless-sky** [comment] 2015-11-23 19:56
Are you certain that the reason your ship turned toward approaching enemies
was not that you had been hit with a projectile that imparts momentum (like
a particle cannon or a missile) and your ship was having to turn around in
order to attempt to bring itself to a stop again?

**Comment by dplepage** [comment] 2015-11-23 20:31
@endless-sky Oh, that hadn't occurred to me. That probably is what was going on, and it only seemed like auto-aiming because "towards the target" is both the auto-aiming direction AND the direction opposite the momentum imparted by the target's missiles. Thanks!

**Comment by dplepage** [comment] 2015-11-29 16:15
I have a patch for this in #314; @gchapyzh suggested that maybe it should be a toggle so that you don't have to hold down the key while you're fighting. I'm not sure if I'd like that more - does anyone else have feelings about holding a key vs. a sticky key?

**Comment by airtroop392** [comment] 2015-11-29 17:55
I concur with @gchapyzh. I sometimes get lost when there are a lot of things happening on the screen, and I would absolutely forget. A toggle would be nice.

**Comment by dplepage** [comment] 2015-11-30 04:08
When would you want this to clear? Only if you hit the key again? All the other autopilot features (landing, boarding, etc.) turn off the moment you hit any steering keys, but you generally want to move while using auto-steering; if you hit a turn key, should that turn it off, or should you resume pointing at your target as soon as you stop turning yourself?

**Comment by airtroop392** [comment] 2015-11-30 04:11
User input in the form of turning should make the most sense. Right? I think?

**Comment by gchapyzh** [comment] 2015-11-30 04:37
@airtroop392  yes

**Comment by LocalGod79** [comment] 2016-01-30 07:38
perhaps this is the function of the caps lock?  i've seen more requests for this than for frame rate doubling (ev key).

**Comment by LocalGod79** [comment] 2016-03-30 03:11
pull #314

**Comment by Logicaluser** [comment] 2017-09-23 22:47
Any chance of this being added?

As a longtime former EV player, I repeatedly find myself trying to hold A to point the nose towards a targeted ship, only to realize later that it's doing nothing.

Seems like the only aspect of Escape Velocity's ship combat controls that is missing at this point.

**Comment by gunqqer** [comment] 2017-09-24 00:50
I'm pretty sure we have an auto aim and auto fire (but you have to be facing with in certen degrees of the target) Check your general settings

**Comment by tehhowch** [comment] 2017-09-24 16:27
Autoaim requires autofire be active, or the player be firing.
Autosteer requires neither

**Comment by ChamEV** [comment] 2019-06-08 22:33
Wrote a new version of this, works on everything target-able now.  https://github.com/endless-sky/endless-sky/pull/4349

**Comment by Zitchas** [comment] 2019-06-08 22:45
Looking forward to having this. I definitely am looking forward to having a triggerable auto-steer.

**Comment by Zitchas** [comment] 2023-01-29 19:14
It seems that the auto-aim button keeps getting mentioned... Hopefully someday someone can get it merged.

**Comment by UnorderedSigh** [comment] 2023-03-06 05:05
The long wait is over: #8508

**Comment by warp-core** [comment] 2023-05-01 12:26
https://github.com/endless-sky/endless-sky/commit/db145474dc9d4cf8326b3ff8239039825934d6b0

**Closed by warp-core** 2023-05-01 12:26 UTC
Labels: enhancement
