### ISSUE TITLE
cannot load stored outfits into cargo in latest continuous release

### ISSUE THREAD

**Issue by garabato14** [endless-sky/endless-sky#6668] opened 2022-04-02 11:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am using ES with the launcher, type = continuous, using Debian 11. A few days ago there was an upgrade that added a storage box choice but now I cannot buy an outfit into cargo. Same if I have the outfit in storage, cannot add outfit to cargo.

### Steps to Reproduce

1. Go to 'any outfit'
2. try loading any outfit to cargo

### Expected Behavior

Add outfit to cargo. 

### Operating System

Debian 11

### Game Source

ESLauncher2

### Game Version

Continuous

**Comment by petervdmeer** [comment] 2022-04-02 16:04
Please try to select no ships at all (by Ctrl + Click on the selected ships until no ship is selected). Does that allow buying to cargo?

**Comment by garabato14** [comment] 2022-04-02 18:03
Yes, unselecting all ships did work.

**Comment by quyykk** [comment] 2022-04-02 18:14
This change is probably going to cause a lot of confusion, a few people on the Discord where also caught by surprise when the way they stored outfits in cargo no longer worked.

**Comment by petervdmeer** [comment] 2022-04-02 19:31
> This change is probably going to cause a lot of confusion, a few people on the Discord where also caught by surprise when the way they stored outfits in cargo no longer worked.

Yes, I'm afraid so too. Initially I was also confused because I also didn't know about the option to de-select all ships using the control button.
What we could do to mitigate this is to change the trigger for the Outfitter help-text; it will then pop-up for existing players and it does explain the control+click method to go for cargo-mode.

**Comment by Amazinite** [comment] 2022-04-02 21:13
This should be addressed before the next release.

**Comment by quyykk** [comment] 2022-04-02 23:18
Or we could reimplement the old behavior.

**Comment by petervdmeer** [comment] 2022-04-03 15:37
> Or we could reimplement the old behavior.

Yes, re-implementing the old behavior shouldn't be too difficult, and we can even revert the merged PR if we urgently need to handle this.

But if we do have a few weeks to solve this, then I would like to focus first on implementing a more intuitive UI; with an additional button below the ships-list for explicitly selecting "buy to cargo", in the same way as that ships are selected. Maybe also prepare a bit for another "buy to storage" button.

**Comment by pepoluan** [comment] 2022-04-04 05:02
IMHO the issue is that showing "Cargo only" is not the same level as showing "Ship Outfit".

Maybe a button above the ship list, "Show Cargo Only", rather than a small checkbox at lower left?

**Comment by samrocketman** [comment] 2022-04-13 23:51
This bug has two key issues

* No longer able to purchase outfits directly into cargo.
* No longer able to move outfits stored on a planet into cargo.

**Comment by samrocketman** [comment] 2022-04-13 23:53
I found the root cause of this bug by using git bisect.  Bug was introduced by commit https://github.com/endless-sky/endless-sky/commit/949760972eb3053173f2c89001b4ab936e29c500

**Comment by thewierdnut** [comment] 2022-04-21 20:58
Whatever ends up being the permanent fix, it would be nice if it did not depend on the keyboard.

**Comment by quyykk** [comment] 2022-04-26 13:40
I believe this can be closed now, since the old behavior was reinplemented in #6718. We can always change it in the future with better UX.

**Closed by quyykk** 2022-04-26 13:40 UTC
Labels: mechanics
