### ISSUE TITLE
"fail" command appears to...(fail) [bug]

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#2226] opened 2017-03-06 04:11 UTC
posted as job;
```
mission money
	name "Need Cash?"
	repeat
	job
	source
		attributes forge
	description "I need a credit, a credit is what i need...  here, have one billion"
	on accept
		payment 1000000000
		fail
```
should not ever appear in my active missions list, yet...

**Comment by Amazinite** [comment] 2017-03-06 04:23
I think that this is essentially a duplicate of #1938

**Comment by MessyMix** [comment] 2017-03-06 04:30
@Amazinite does this apply if the ship is already landed?

**Comment by Amazinite** [comment] 2017-03-06 04:59
Yes. You have to land again. If you're landed and a mission is set to fail (either by another mission or by itself upon offer) or you fail while in flight, you need to land for the mission and whatever was part of it (e.g. cargo, passengers, NPCs) to despawn. This makes sense for when a mission fails while in flight, but it doesn't work out well for when landed.

**Closed** 2017-05-29 17:06 UTC
Labels: question
