### ISSUE TITLE
Wrong Outfits Showing in Outfitter

### ISSUE THREAD

**Issue by NewprogramerD** [endless-sky/endless-sky#4973] opened 2020-04-04 15:13 UTC
When I am looking through multiple ships in the outfitter I see that they have outfits installed that shouldn't be shown as installed. This only seems to happen after I sell those very same outfits only a short time previously or have them installed in other ships.

Go to an outfitter with multiple ships that you have just captured, select those ships by shift-clicking on the captured ships, look through the outfits, you will find things that shouldn't be there. If you go through the ships individually, you will find that they have the normal outfits, but with all of them selected, I can uninstall those outfits into cargo, providing me an easy route to get rarer outfits.

As I have just captured these ships from human space, I do not expect to find system cores and broken jump drives in ships that were previously pirates. 

**Screenshots**
![Outfitter Issues](https://user-images.githubusercontent.com/39568284/78454071-01a25380-7653-11ea-9786-f79473be19fb.png)

**System (please complete the following information):**
 - OS: Windows 10 pro, 10.0.18363 Build 18363
 - Game Source: Steam
 - Version: 0.9.11

Save File
[Random Pilot.txt](https://github.com/endless-sky/endless-sky/files/4431772/Random.Pilot.txt)

I have noticed this only a couple of times, and it only seems to happen after I have captured several pirate ships. Smaller groups- 2-3 ships, do not seem to display this behavior.

**Comment by starmlerp** [comment] 2020-04-04 15:22
Duplicate of #4887

**Comment by NewprogramerD** [comment] 2020-04-04 15:33
I just checked, and yes, it is a duplicate. Is there a way to fix the issue?

**Comment by beccabunny** [comment] 2020-04-04 15:38
The issue is already fixed in the nightly, please close this

**Closed** 2020-04-04 15:50 UTC

**Comment by starmlerp** [comment] 2020-04-04 18:31
for clarification, it was fixed in 6dea115
