### ISSUE TITLE
Simple fix for #1231: [Collapse All] button

### ISSUE THREAD

**Issue by DingusShingleton** [endless-sky/endless-sky#1651] opened 2016-09-30 15:48 UTC
Going through all my notifications since I haven't been around in a long time, didn't want to necro a closed issue from 3 months ago. (#1231)

I think a simple [Collapse All] button would solve both the issue of signaling to new players that the categories can be collapsed, and make it trivially easy to quickly get to the bottom sections of the menu without having to start them out collapsed. Donezo.

**Comment by ssokolow** [comment] 2016-10-08 18:21
My main concern there would be ensuring that I don't have to click "Collapse All" every time I open the thing when I'm just starting a game and mainly want to buy local maps... so I'd argue that "Collapse/Expand All" should be a toggle-button which, internally, is implemented as "set default collapse/expand state".

**Comment by Lineth** [comment] 2016-10-08 18:23
Could just leave a little icon next to each section that tells the player they're collapsible. Like the minimize/maximize icon on browsers. And a Collapse All toggle would be nice, if it wouldn't be a bother to include.

**Comment by endless-sky** [comment] 2016-10-12 22:42
You can already use shift+click on any category name to collapse all.

**Comment by ssokolow** [comment] 2016-10-12 22:55
@Lineth So the issue is discoverability then?

(Question mark because I'm currently at a PC without a copy of Endless Sky to test it out on)

**Comment by Lineth** [comment] 2016-10-12 23:08
Seems to be, as I had no idea about the shift-click thing MZ pointed out.

**Comment by DingusShingleton** [comment] 2016-10-12 23:49
Wow, I have played what i would consider quite a bit of ES, and I also had no idea that this was a thing. I think something as simple as a small 50% grey bit of text at the top of the list saying "Shift-click a category to collapse all" would do the trick

**Comment by KiLEdEnNis** [comment] 2016-10-13 07:49
I played maybe 500 hours & got bored of the game without knowing this? :(

**Comment by Bladewood** [comment] 2016-10-13 11:30
A thousand to two thousand hours without knowledge of this function for me.

**Comment by DingusShingleton** [comment] 2016-10-13 12:29
Well I think we have established beyond a reasonable doubt that this feature could use some delineation :P . So what's the most elegant and long-term unobtrusive way to do so?

**Comment by retrue** [comment] 2016-10-13 17:07
The less unobtrusive way of doing it is outside of the game.
That is, creating a list of keys and tips with info about features like collapsing panels, searching for a planet, renaming ships, etc. It could be on the wiki, in a help file, etc.

**Comment by KiLEdEnNis** [comment] 2016-10-13 17:12
or teach the player about the I key and have a shortcut there linking to a wiki (or an in-game guide)

**Comment by Amazinite** [comment] 2016-10-13 17:19
A section in preferences that tells you about all the shortcuts and features?

**Comment by ssokolow** [comment] 2016-10-13 17:20
@retrue @KiLEdEnNis
Unfortunately, both of those fail the "users only read manuals if they can't avoid it" UI-design test.

I'd suggest a square `-` button in the top right corner with a tooltip that says "Collapse All (Ctrl+Click)". It's compact and unobtrusive but easy to notice when you're looking for it and it follows a similar design philosophy to putting keyboard shortcuts on the right end of menu items to make them discoverable.

**Comment by jafdy** [comment] 2016-10-13 21:07
Put it in a list when you exit the tutorial mission? In addition to @Amazinite list. Then everyone who starts the game will notice it. It couldn't be a long term solution but it would be better than nothing.

**Comment by Amazinite** [comment] 2016-10-13 21:47
@ssokolow I think that gets into the territory of if someone doesn't want to read what's given to them, then it's their own fault for not knowing. The addition of such a list in the preferences would obviously be in the change logs (and hopefully MZ would put it in the top changes so people don't actually need to read through the entire change log to see it), so even most people who have already set their custom preferences would likely see it.

**Comment by ssokolow** [comment] 2016-10-13 21:55
I'm just trying to failsafe the design. Everyone has bad days, when they're too tired or busy or stressed or make an honest mistake and miss something they shouldn't.

That's part of the reason the keyboard shortcuts are put into menus in a traditional GUI. If you miss it once, you'll have plenty of other opportunities.

**Comment by Amazinite** [comment] 2016-12-24 01:30
Should this be closed now that the collapse feature is easy to notice and shift+click collapses all anyways?

**Comment by endless-sky** [comment] 2017-01-18 23:40
Closing this because 0.9.5 is released now.

**Closed by endless-sky** 2017-01-18 23:40 UTC
Labels: mechanics
