### ISSUE TITLE
escorts unresponsive

### ISSUE THREAD

**Issue by Huesco** [endless-sky/endless-sky#4013] opened 2018-11-19 13:08 UTC
Some of my escort are not responding, instead they just slowly drift away from the planet. Also when I move to another planet, they just slowly drift further away. I read somewhere that it might have something to do with not recognizing the flagship, however, they also don't respond to enemies. 

Just to be clear, I tried almost anything I can think of, even making one of them my flagship. Still frozen.

edit:
**System (please complete the following information):**
 - OS: mac os10.14. 2.6ghz. 8GB
 - Game Source: steam
 - Version:0.98

**Link to save file**
[Lord of Thunder~Frozen ships.txt](https://github.com/endless-sky/endless-sky/files/2595793/Lord.of.Thunder.Frozen.ships.txt)

**Additional context**
I've been playing this game for 100's of hours. This time the problem occurred after ~30 hours or so. 
Last year I've been playing the game while it was installed on an flash drive, not on my actual computer. The problem also occurred before this.
This time the 4 cruiser ships respond for 10 seconds and then become unresponsive.

Edit 2: in waypoint there are 3 more cruisers frozen.

**Comment by MCOfficer** [comment] 2018-11-19 14:01
the save directory on OSX is `~/Library/ApplicationSupport/endless-sky/saves`; for future reference you can check the [CreatingPlugins](https://github.com/endless-sky/endless-sky/wiki/CreatingPlugins#mac-os-x) wiki page, just replace `plugins` with `saves`.

also, some more information about your system may prove useful (we now have fancy issue templated, [hint hint](https://github.com/endless-sky/endless-sky/blob/master/.github/ISSUE_TEMPLATE/bug_report.md))

**Comment by Zireael07** [comment] 2018-11-19 14:06
I believe a very similar issue has already been reported, if you're on 0.9.8, it's probably duplicate of that extant issue.

**Comment by Huesco** [comment] 2018-11-19 15:10
i edited my post. now it gives more info.

@Zireael07 where is this post/issue? as far as I can tell there is only an issue of NPC's being frozen. not escorts (or flagship when you select the escort to become the flagship).

**Comment by tehhowch** [comment] 2018-11-19 15:32
Sounds a lot like "I didn't give my escorts power generation"

**Comment by Huesco** [comment] 2018-11-19 15:36
#@%@$@C You might be right....

**Comment by tehhowch** [comment] 2018-11-19 15:45
v0.9.9 will include warning icons in the outfitter to alert you of such possible errors. There are nightly builds available in the Steam forum if you do not wish to wait for that unknown future day.
c.f.
https://github.com/endless-sky/endless-sky/pull/3040#issuecomment-331478509
https://github.com/endless-sky/endless-sky/commit/abf8b78afe42476fec700004049020ae4985a231

**Comment by Pointedstick** [comment] 2018-11-20 16:19
Thanks for the clarification. :)

**Closed by Pointedstick** 2018-11-20 16:19 UTC
