### ISSUE TITLE
Sprites with dimensions that are odd numbers are blurry

### ISSUE THREAD

**Issue by Anarchist2** [endless-sky/endless-sky#5456] opened 2020-10-17 10:22 UTC
**Describe the bug**
Any sprite that has dimensions that are not a multiple of two show up blurry in-game (at least, in the outfitter/shipyard). However, there are some that do not have dimensions divisible by two, namely the Archon thumbnail, all Firebird thumbnails (including marauder sprites), the Geocoris thumbnail, the Grasshopper thumbnail, the Penguin thumbnail, the Petrel thumbnail, the Maboro thumbnail, the Tern thumbnail, the Wardragon thumbnail, the Marauder Fury thumbnail, the Dragonflame thumbnail and the Jump Drive (Broken) thumbnail. 

A comparison of the clean Marauder Bounder (Weapons) next to the blurry Marauder Fury:
![image](https://user-images.githubusercontent.com/60202690/96334701-1bb6f700-10b6-11eb-9695-78806832045b.png)

An image of the blurry Broken Jump Drive next to the crisp images of other outfits:
![image](https://user-images.githubusercontent.com/60202690/96334600-61bf8b00-10b5-11eb-9a09-f5b94af9f104.png)

**Proposed solutions**
Either:
a) Make sprites that have dimensions that are not even not be blurry.
b) Change all the aforementioned sprites to have dimensions that are even.

**Comment by Zitchas** [comment] 2020-10-17 12:03
Hmmm... That seems like an odd bug. Are things that are not multiples of 10 being stretched or otherwise distorted?

**Comment by oo13** [comment] 2020-10-25 02:59
An odd number of the size would cause the blurry. IMO, it's not a bug because the SpriteShader shrinks the sprites to half size.

<table>
<tr><th>70x80</th><th>71x81</th><th>72x72</th><th>73x83</th><th>74x84</th></tr>
<tr>
<td>![capture0](https://user-images.githubusercontent.com/22392249/97097824-0c890800-16b9-11eb-8c70-93c285faddd0.png)
</td>
<td>
![capture1](https://user-images.githubusercontent.com/22392249/97097829-1874ca00-16b9-11eb-9d85-035540993e65.png)
</td>
<td>
![capture2](https://user-images.githubusercontent.com/22392249/97097831-1f9bd800-16b9-11eb-80d9-130d944c88b4.png)
</td>
<td>
![capture3](https://user-images.githubusercontent.com/22392249/97097833-262a4f80-16b9-11eb-96d4-968a6e884edd.png)
</td>
<td>
![capture4](https://user-images.githubusercontent.com/22392249/97097839-2cb8c700-16b9-11eb-9d50-e7621f62dd1e.png)
</td>
</tr>
</table>

We should create the sprite with the size of the even number, and the High DPI sprite is exactly the double size of the normal one.

**Comment by Pointedstick** [comment] 2021-09-12 13:56
Fixed with https://github.com/endless-sky/endless-sky/pull/6248 and https://github.com/endless-sky/endless-sky-high-dpi/pull/188.

**Closed by Pointedstick** 2021-09-12 13:56 UTC
Labels: content
