### ISSUE TITLE
Hold position should actually stop the ship.

### ISSUE THREAD

**Issue by Nightmareman** [endless-sky/endless-sky#479] opened 2015-12-17 05:20 UTC
When I tell my fleet to hold position they don't actually hold position they all end up drifting away in different directions. This problem gets even worse if they destroy a ship that explodes near them causing them to drift away faster then they did before. It would be nice if the ships would actually stay where you told them to stay and if they get knocked away by weapons fire or explosions they would return to the location you told them to hold at.

Another issue is it would be nice to be able to give different orders to different ships such as have my fast corvettes go chase down the missile ships at the edge of the system while the rest of my ships stay with me or at positions I told them to stay at before hand.

**Comment by Wrzlprnft** [comment] 2015-12-17 09:53
Similar issue: #451

**Comment by endless-sky** [comment] 2015-12-17 13:57
This is basically a duplicate of #400.

**Closed by endless-sky** 2015-12-17 13:57 UTC
Labels: duplicate
