### ISSUE TITLE
NPCs can follow cloaked ships while scanning

### ISSUE THREAD

**Issue by tibetiroka** [endless-sky/endless-sky#8303] opened 2023-02-05 23:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

NPCs can follow ships - or at least the player's flagship - while it is cloaked, if the NPC is attempting to scan the player.

### Steps to Reproduce

Use the provided save file; it'll spawn in a remnant ship for you. Wait for it to begin scanning, then cloak and move away. When you uncloak, the NPC will be close to you, also uncloaking, and still scanning.

### Expected Behavior

Cloaked ships should be hidden.

### Link to save file

[Test Pilot.txt](https://github.com/endless-sky/endless-sky/files/10614124/Test.Pilot.txt)

### Operating System

EndeavourOS (kernel: 6.1.9.zen1-1)

### Game Source

Built from source

### Game Version

latest contiuous

**Comment by RisingLeaf** [comment] 2023-02-05 23:34
will look at this rn

**Comment by RisingLeaf** [comment] 2023-02-05 23:35
save file is missing though

**Comment by tibetiroka** [comment] 2023-02-05 23:37
Fixed it. Thanks!

**Comment by tibetiroka** [comment] 2023-02-05 23:37
It's a test save I'm using to debug the remnant boarding behaviour, that's how I ran into this issue.

**Comment by Amazinite** [comment] 2023-02-05 23:45
#5739

**Comment by tibetiroka** [comment] 2023-02-05 23:50
I think this one is easier to fix, because the game already knows the npc shouldn't scan you (the sound stops playing), so it's probably just a matter of resetting the targetShip at the same place.

**Comment by RisingLeaf** [comment] 2023-02-05 23:52
I can confirm that the issue exists, I will need to investigate further why though.

**Comment by RisingLeaf** [comment] 2023-02-05 23:57
found the issue, we are checking if a ship should cloak, before we are checking if it should find another target, in this case the starling cloaks when the player cloaks and therefore bypasses the target check, at least that is what I think.

**Comment by tibetiroka** [comment] 2023-02-05 23:57
It seems like some NPCs just freeze in place while you are cloaked? I think it depends on whether or not they can cloak themselves.

**Comment by RisingLeaf** [comment] 2023-02-06 00:11
I correct myself, the starling that follows you has your flagship as parent for some reason, I will investigate further.

**Comment by tibetiroka** [comment] 2023-02-06 00:14
I think the save file has them without that?

**Comment by RisingLeaf** [comment] 2023-02-06 00:14
> I think the save file has them without that?

yes, no escort personality in the save

**Comment by tibetiroka** [comment] 2023-02-06 00:16
I tried a fix that would make FindTarget respect IsTargetable when looking for scanning targets, but even that doesn't seem to be enough.

**Comment by RisingLeaf** [comment] 2023-02-06 00:19
Well, the easiest fix would be to add uninterested, as the logic error happens in line 461 of engine.cpp:

```c++
			// Only the flagship of an NPC considers the
			// player: the rest of the NPC track it.
			if(npcFlagship && ship != npcFlagship)
				ship->SetParent(npcFlagship);
			else if(!ship->GetPersonality().IsUninterested())
				ship->SetParent(flagship);
			else
				ship->SetParent(nullptr);
```

combined with this part of docloak in line 2696 of ai.cpp:
```c++
		// If your parent has chosen to cloak, cloak and rendezvous with them.
		const shared_ptr<const Ship> &parent = ship.GetParent();
		if(parent && parent->Commands().Has(Command::CLOAK) && parent->GetSystem() == ship.GetSystem()
				&& !parent->GetGovernment()->IsEnemy(ship.GetGovernment()))
		{
			command |= Command::CLOAK;
			KeepStation(ship, command, *parent);
			return true;
		}
```

**Comment by tibetiroka** [comment] 2023-02-06 00:21
That sounds about right. I still think we should fix the code, instead of changing the personalities of the fleet.

**Comment by RisingLeaf** [comment] 2023-02-06 00:21
yes, I just do not know what exactly we should do.
Probably add a priority target member to ship class

**Comment by tibetiroka** [comment] 2023-02-06 00:24
When handling these ships, what's the state of `npcFlagship`? If the issue is caused by `npcFlagship` being the ship, just add a proper `if` inside the first one, instead of having an `&&`.

**Comment by tibetiroka** [comment] 2023-02-06 00:27
Yes, that seems to work.

**Comment by RisingLeaf** [comment] 2023-02-06 00:30
> When handling these ships, what's the state of `npcFlagship`? If the issue is caused by `npcFlagship` being the ship, just add a proper `if` inside the first one, instead of having an `&&`.

the issue is that we internally add the player flagship as the parent f the flagship of the npc fleet so that itis easier to make them follow the player.

**Comment by tibetiroka** [comment] 2023-02-06 00:30
No, even the combination of this and the targeting thing doesn't stop some FIGHTERS; they just stop and don't do anything. `npcflagship` needs more work.

**Comment by tibetiroka** [comment] 2023-02-06 00:31
> the issue is that we internally add the player flagship as the parent f the flagship of the npc fleet so that itis easier to make them follow the player.
When I tried it out, the ships could still approach the player. Does it actually break anything?

**Comment by RisingLeaf** [comment] 2023-02-06 00:31
I did not test it, can you show me the changes you made?

**Comment by tibetiroka** [comment] 2023-02-06 00:32
https://github.com/tibetiroka/endless-sky/tree/cloaking-target-fix

This is the branch I'm working on.

**Comment by tibetiroka** [comment] 2023-02-06 00:33
Oh, and pushed.

**Comment by RisingLeaf** [comment] 2023-02-06 00:35
ok, so this does not change anything

**Comment by tibetiroka** [comment] 2023-02-06 00:36
To be clear: this fails only when singular fighters spawn, since those don't have parents. I guess I could add a check for that. Any regular ships or fighters from a mothership seems to work better.

**Comment by tibetiroka** [comment] 2023-02-06 00:37
> ok, so this does not change anything

Previously, the mission ship 'Test Boarder' was cloaking and following me; now it breaks off instead. Can you confirm?

**Comment by RisingLeaf** [comment] 2023-02-06 00:37
> > the issue is that we internally add the player flagship as the parent f the flagship of the npc fleet so that itis easier to make them follow the player.
> 
> When I tried it out, the ships could still approach the player. Does it actually break anything?

you did this:

<img width="620" alt="Screenshot 2023-02-05 at 4 36 02 PM" src="https://user-images.githubusercontent.com/85687254/216856312-666f6434-3cad-43fd-98d6-2d6977989534.png">

but the problem is this:

<img width="384" alt="Screenshot 2023-02-05 at 4 36 38 PM" src="https://user-images.githubusercontent.com/85687254/216856370-9ec9d5cb-65dd-40f7-8c2d-073b210e8046.png">

The changes you did make no difference, it is the same.
The problem is in the part I showed, which sets the player flagship as the parent of the flagship of the npc fleet.

**Comment by tibetiroka** [comment] 2023-02-06 00:39
Yes, but in this test the code doesn't go to the `else if` case; it goes into the `if` instead, just skips setting it.

I'm definitely detecting changes in NPC behaviour. Does it stay the same on your side?

**Comment by tibetiroka** [comment] 2023-02-06 00:41
(I see how this breaks npc flagships following the player, but does it help the issue?)

**Comment by RisingLeaf** [comment] 2023-02-06 00:42
I think it is the right direction, now we need something that makes npcs target the player when the player is targetable

**Comment by RisingLeaf** [comment] 2023-02-06 00:44
we probably want something like this:
```c++
if(npcFlagship && ship != npcFlagship)
	ship->SetParent(npcFlagship);

 if(!ship->GetPersonality().IsUninterested())
	ship->SetPriorityTarget(flagship);
```

**Comment by tibetiroka** [comment] 2023-02-06 00:50
What would `SetPriorityTarget` do? Override `target` if it exists, while allowing the parent to be handled separately?

**Comment by RisingLeaf** [comment] 2023-02-06 01:02
I think when searching for a new target it should be considered first

**Comment by tibetiroka** [comment] 2023-02-06 01:03
The player only has one flagship, so we could just add that to FindTarget. Right?

**Comment by tibetiroka** [comment] 2023-02-06 01:15
Do we hold a reference to the player's flagship that can be accessed from pretty much anywhere?

**Comment by RisingLeaf** [comment] 2023-02-06 01:38
> Do we hold a reference to the player's flagship that can be accessed from pretty much anywhere?

we could just make it a boolean and then access PlayerInfo.FlagshipPtr()

**Comment by RisingLeaf** [comment] 2023-02-06 01:38
> The player only has one flagship, so we could just add that to the beginning of FindTarget. Right?

yes

**Comment by tibetiroka** [comment] 2023-02-06 01:40
I ended up passing PlayerInfo to FindTarget. Was that unnecessary?

Still can't get the Smew to work properly, but working on it.

**Comment by RisingLeaf** [comment] 2023-02-06 01:46
we can fix details on the PR

**Comment by Hurleveur** [comment] 2023-02-06 06:18
Cant we call this a feature since its just for remnant ships?

**Comment by UnorderedSigh** [comment] 2023-02-08 19:54
The fix is to de-target ships that are not targetable: #8324. (I found this when finalizing 8323.)

**Comment by UnorderedSigh** [comment] 2023-02-08 19:58
> Cant we call this a feature since its just for remnant ships?

It affects more than just cloaked ships, and it affects anyone who is trying to scan you.

**Comment by UnorderedSigh** [comment] 2023-02-08 20:16
Actually, I'm not convinced my fix in #8324 works, so I'm closing that PR for now.

**Comment by UnorderedSigh** [comment] 2023-02-08 20:38
Re-opening. Sorry about that. I found the one spot I forgot: uninterested cloaking NPCs should not cloak and follow you.

**Comment by UnorderedSigh** [comment] 2023-02-08 20:50
I should apologize for jumping on this so quickly. If someone else has a fix already, please let me know, and I'll close my PR. I have too many PRs open, and I should have waited for one of you to fix this.

**Comment by movingpictures** [comment] 2023-02-20 00:35
FYI, still an issue with 0.10.0

![Screenshot from 2023-02-19 20-30-42](https://user-images.githubusercontent.com/77249988/219985260-e69a628c-51c5-452c-b4b2-2a5834586dc4.png)

**Comment by UnorderedSigh** [comment] 2023-02-20 00:36
That is because the fix was never merged. I have tested it, and it still works:

https://github.com/endless-sky/endless-sky/pull/8324

**Comment by movingpictures** [comment] 2023-02-20 00:38
Ah. I thought I'd seen it merged somewhere. Sorry, I'm trying to be a good human being by breaking as many things as I can in the name of progress, and it's hard for this old fart to remember what it was I may have been trying to break.

**Comment by UnorderedSigh** [comment] 2023-02-20 00:39
> Ah. I thought I'd seen it merged somewhere. Sorry, I'm trying to be a good human being by breaking as many things as I can in the name of progress, and it's hard for this old fart to remember what it was I may have been trying to break.

Please keep reporting these! It is good to have someone other than me point out that this is still broken.

**Closed** 2023-02-24 01:40 UTC
Labels: bug, mechanics
