### ISSUE TITLE
"require <outfit>" needs to be in an "on" block; should be able to put it in "to offer" instead

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#3341] opened 2017-12-03 04:42 UTC
This feels weird:

```
to offer
		random < 50
on offer
		require "Brig"
```

I feel like this would intuitively make more sense:

```
to offer
		random < 50
		require "Brig"
```

It would also let you do something like this, which currently isn't possible:
```
to offer
	or
		and
			require not "Brig"
			random < 75
		and
			require "Brig"
			random < 10
```

**Comment by VonZorch** [comment] 2019-06-09 05:04
Fully agree, it should be testable in a branch statement too.

**Comment by Amazinite** [comment] 2021-05-03 16:57
Looks like this is actually a duplicate of #2494.

**Closed by Amazinite** 2021-05-03 16:57 UTC
Labels: duplicate
