### ISSUE TITLE
0.9.8 reordering ships causes crash

### ISSUE THREAD

**Issue by aonilsson** [endless-sky/endless-sky#3027] opened 2017-09-10 01:03 UTC
in Mac OS 10.12.6, no plugins:

I have a dozen or so ships, and reordering them in the "I" (player info) screen causes an immediate crash. I can reorder them fine in the outfitter screen.

**Comment by Amazinite** [comment] 2017-09-10 01:24
Duplicate of #2796

**Comment by Bladewood** [comment] 2017-09-10 01:25
Duplicate of https://github.com/endless-sky/endless-sky/issues/2796

**Comment by gunqqer** [comment] 2017-09-12 16:28
btw issue has been resolved, it no longer crashes (tested by myself on 10.11.5) 

Please close this issue.

**Closed** 2018-01-18 02:35 UTC
Labels: duplicate
