### ISSUE TITLE
albert2910@msn.com

### ISSUE THREAD

**Issue by pogopossum3** [endless-sky/endless-sky#8567] opened 2023-03-21 01:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

arrow keys no longer control ship movement in Endless Sky 0.10.0.

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected Behavior

Ship to be controlled in steering right and left.

### Operating System

Ventura 13.2.1 

### Game Source

Steam

### Game Version

0.10.0

**Comment by bene-dictator** [comment] 2023-03-21 01:51
This is a duplicate of #8419.

Tap the right alt key; if the right alt key is tapped, you switch between key steering and mouse steering (new feature in 0.10.0).

**Closed** 2023-03-21 02:03 UTC
Labels: bug, unconfirmed
