### ISSUE TITLE
Having ships with 0 cargo space in fleet makes them be assigned arbitrary high cargo when departing planet

### ISSUE THREAD

**Issue by Cat-Lady** [endless-sky/endless-sky#4550] opened 2019-09-23 21:57 UTC
1. If you have a ship with 0 available cargo space in your fleet (like a ship that, originally, had 20 cargo space, and got outfit extension installed, resulting in 0 cargo space), the code in game that makes your flagship be preffered to have least cargo assigned, makes all the cargo from your flagship gets assigned to the 0-cargo capable ship. See attached screenshot.

![2019-09-23-21:38:13](https://user-images.githubusercontent.com/6075406/65465927-c6ca9200-de5d-11e9-9758-f2bec220dc80.png)

2. Having such 0-cargo available ship in fleet makes you always depart planet with 0 cargo on flagship - even if just before start, you had 100% cargo capacity of your fleet full.

3. If you pickup any cargo in space with your flagship, you end up with more cargo than you could really have (confirmed by landing, exiting game, loading, and immediately trying to depart - message about having not enough cargo space appears).

**System (please complete the following information):**
 - OS: Debian Buster, amd-64
 - Game Source: 0.9.9 self-compiled
 
**Link to save file**
[Catlane Estel.txt](https://github.com/endless-sky/endless-sky/files/3644325/Catlane.Estel.txt)

**Comment by Amazinite** [comment] 2019-09-23 22:07
Duplicate of #4305. Already fixed in https://github.com/endless-sky/endless-sky/commit/8e0d8167403de689132a08406b9d7f3211beebf4.

**Closed** 2019-09-23 22:33 UTC
Labels: duplicate
