### ISSUE TITLE
Outfit lost on manual snapshot

### ISSUE THREAD

**Issue by adamsnd** [endless-sky/endless-sky#96] opened 2015-09-08 21:10 UTC
I took a manual snapshot while on a planet. Upon leaving the planet, the game informed me that I failed a transport mission because I did not have enough available bunks. Upon inspection at the Outfitter tab, I saw that I no longer had a "Small Bunk Room" installed on the ship. I had not sold it; it seemed to have disappeared. Unfortunately since I already left the planet, the autosnapshot overwrote my latest ship outfits.

This appears to be a bug similar to issues #85 and #33, although not as serious since only one outfit seems to have disappeared.

I inspected the manual snapshot file and compared my Outfits to an earlier manual snapshot. The only difference appeared to be the loss of the "Small Bunk Room". No outfits other than star maps had been purchased between these two snapshots.

I manually inserted "Small Bunk Room" into the manual snapshot and entered the ship. I was able to take off from the planet without losing the outfit and without failing the transport mission.

**Comment by endless-sky** [comment] 2015-09-08 21:31
Is it possible that you had recently failed a different mission (either due to running out of time, or aborting the mission) before this happened? I've been wondering if this bug could be connected to the one I fixed in commit d78ccec.

Also, when you took a manual snapshot, did you then "Enter Ship" in the Load / Save... panel (which would reload the game from the file you just saved), or did you go "Back" from the Load / Save panel? If your outfit disappeared without reloading from file, that would indicate memory corruption, but if you loaded from the snapshot, that could indicate an error when writing the snapshot file. The fact that this happened in a manual snapshot (which does not get automatically overwritten ever) means the bug happened when the file was written, not when it was read, which helps this down considerably.

And, did you see anything odd in your ship's outfit list when you manually edited the snapshot file (e.g. a blank line with nothing but "", or garbled names, or anything like that)?

**Comment by adamsnd** [comment] 2015-09-09 15:36
> Is it possible that you had recently failed a different mission (either due to running out of time, or aborting the mission) before this happened? I've been wondering if this bug could be connected to the one I fixed in commit d78ccec.

I recall completing a (rush?) delivery mission on the planet I had landed on before losing the Small Bunk Room. The transport mission was 2 systems away. It appears that the code addressed in d78ccec8cb29f23b3df08712ea46f0c725726b34 worked properly - I should have failed and did fail the transport mission due to insufficient bunks (although I shouldn't have lost the Small Bunk Room).

> Also, when you took a manual snapshot, did you then "Enter Ship" in the Load / Save... panel (which would reload the game from the file you just saved), or did you go "Back" from the Load / Save panel? If your outfit disappeared without reloading from file, that would indicate memory corruption, but if you loaded from the snapshot, that could indicate an error when writing the snapshot file. The fact that this happened in a manual snapshot (which does not get automatically overwritten ever) means the bug happened when the file was written, not when it was read, which helps this down considerably.

The method for taking snapshots that I have been using has been: Esc (to menu) -> Load/Save -> Add Snapshot -> either "Enter Ship" while the last snapshot is selected or select main pilot file -> Enter Ship. I don't recall ever clicking Back.

Upon losing the outfit, I tried both the autosnapshot and the manual snapshot. Both files had lost the outfit, so I wonder if it had been lost at some point prior to saving (and prior to leaving the planet).

> And, did you see anything odd in your ship's outfit list when you manually edited the snapshot file (e.g. a blank line with nothing but "", or garbled names, or anything like that)?

I only closely examined the Outfits section. There were no blank or garbled lines. Upon adding "Small Bunk Room" to the list (in the same order as a previous manual snapshot with the same outfits), I was able to complete the mission.

**Comment by endless-sky** [comment] 2015-11-17 01:00
This is probably a duplicate of #33, which in turn was probably due to the effects of plundering being delayed until the game was reloaded.

**Closed by endless-sky** 2015-11-17 01:00 UTC
