### ISSUE TITLE
Pluggins Names can overlap text box

### ISSUE THREAD

**Issue by mdsmestad** [endless-sky/endless-sky#3394] opened 2017-12-10 23:14 UTC
Just put the T's there to test it out. Here's an example
![screenshot from 2017-12-10 17-12-02](https://user-images.githubusercontent.com/16338814/33810680-8130fdfc-ddcd-11e7-9d77-bc67d506d4e8.png)

**Comment by tehhowch** [comment] 2017-12-10 23:52
Should be an easy fix with Font::TruncateMiddle function.

Though, is the preferred behavior to truncate it, or scroll it?

**Comment by mdsmestad** [comment] 2017-12-10 23:53
@tehhowch Truncate would look better I think

**Comment by Amazinite** [comment] 2017-12-11 02:02
Essentially a duplicate of #2022

**Comment by tehhowch** [comment] 2017-12-11 03:52
I had done some of the needed truncation in #3070 but that's currently a ways from merging as I need to come up with a nice way to convey the per-system stellar wind and luminosity differences.

I won't add scroll to the plugin's about text but I can add the needed truncation to the plugin name.

**Comment by KiLEdEnNis** [comment] 2017-12-11 11:24
I remember MZ said one should just pick a shorter name (if ya get rid of the 2nd g in "pluggin" it'd be fine)
the only decent fix I can come up with (and I think that's what Tehh meant?) is to get the name cut off (end with a ...) and/or have a side scrolling bar at the bottom
example:
random-plugin-name-that's-unnec...
and if ya scroll ya may see ...ame that's-unnecesarily-long
that's not really a nice change though as it looks a bit... clunky

**Closed** 2019-05-28 04:35 UTC
Labels: enhancement
