### ISSUE TITLE
Mission wont complete properly

### ISSUE THREAD

**Issue by comnom** [endless-sky/endless-sky#4281] opened 2019-05-14 22:11 UTC
In [this save](https://github.com/endless-sky/endless-sky/files/3180061/Gerald.Lightseeker.txt), the mission [Paradise Fortune 3](https://github.com/endless-sky/endless-sky/blob/master/data/transport%20missions.txt#L2778) wont complete when landing on Bourne even though all conditions are fulfilled. (there's room for the passenger, and the evade fleet is elsewhere).

Replicate by landing on Bourne, then reading the save.

I _was_ able to get it to complete by landing on Bourne, then restarting the game and departing/landing on Bourne again, but it should complete the first time.

I tried to dig into it, but gdb keeps crashing on me. The only additional info I have is that one of the epilogue missions offers at the same time, but I blocked that and still had to do the quit/reload to get it to complete.

Edit:
Game version: various, but i tested on a build at 938f68d.

**Comment by Amazinite** [comment] 2019-05-15 02:58
Yeah, I've been seeing reports about this mission being messed up. Not sure on the cause myself either.

**Comment by tehhowch** [comment] 2019-05-15 03:11
I'm curious if it may be related to the fleet having fighters and those fighters being docked. I wouldn't think that would have persisted as a bug until now, but it's possible my changes to tracking actions for NPC ships last year affected this. I can dig in deeper later this week.

You can add `escort` to the NPC personality to have them show up in your list to help debug this (NPC fighters won't show there though)

**Comment by comnom** [comment] 2019-05-15 15:08
>I'm curious if it may be related to the fleet having fighters and those fighters being docked.

Right on the money. If [this branch](https://github.com/endless-sky/endless-sky/compare/master...comnom:evade-fighters) is kosher, I'll pr it.

**Comment by tehhowch** [comment] 2019-05-16 03:40
Closed via https://github.com/endless-sky/endless-sky/commit/87981a4e6d62ffef5f2a66b798136e3e6ab690ae

**Closed by tehhowch** 2019-05-16 03:40 UTC
Labels: bug
