### ISSUE TITLE
[Feature request] Better flight dynamics

### ISSUE THREAD

**Issue by mdziczkowski** [endless-sky/endless-sky#6309] opened 2021-10-28 18:19 UTC
### Problem Description

I would like to propose that the flight dynamics would become fixed, because (among other):

- there is a too big delay in between key press and reaction
- the steering is very hard (in compare, it's like you need a level to lift a big object)
- the hiperdrive has a too long reaction time from enabling
- there should be a possibility that after selecting a route to an target and enabling hiperdrive, then the ship should not stop in each system it passess
- the usage of power (? - the nuclear symbol) is not proportional to the flight length

### Related Issue Links

n/a

### Desired Solution

there need to be thought out a workaround for above ;-)

### Alternative Approaches

optimization of ship parameters and some flight parameters

**Comment by mdziczkowski** [comment] 2021-10-29 19:47
ad. a) how about pre-setting it to a as low as possible (and usefull) value? for less experienced users it could be difficult to do that correctly

ad. b) and c)  this could be also adjusted ;-)

and one it was missed: the ship steering need to be fixed because it working very badly

**Comment by MCOfficer** [comment] 2021-10-29 19:54
> and one it was missed: the ship steering need to be fixed because it working very badly

Can you elaborate on that, because "very badly" isn't helpful.

**Comment by mdziczkowski** [comment] 2021-10-29 20:10
for example: it I want to turn, accelerate or brake then I need to hold the propper quite long before the ship start to even react on the key press

**Comment by tehhowch** [comment] 2021-10-29 23:22
There is no intentional added delay between when you press a key on your keyboard, and when the game reads the input: this will happen as fast as possible on your system, up to 60 times per second. There's nothing to fix here except perhaps check that your monitor framerate is not too slow.

How long it takes for your _ship_ to react to an issued _command_ depends on your ship's current power reserves and the required power for the requested command. If you don't have the power needed, then your ship is going to seem very sluggish since most commands will end up ignored due to lack of power to perform them.  
(We have implemented fractional thrusting, so your ship will use whatever power it has left to perform a requested manuever, should it not have enough to thrust or turn.)

**Comment by mdziczkowski** [comment] 2021-10-31 18:38
@tehhowch I asked because I'm suprised of that behaviour.

My monitor isn't too slow (some more demanding were working fine) and my ship had full enough fuel. Even then it has problems with (for example) turning.

Does anyone got any ideas or clues ?

**Comment by quyykk** [comment] 2021-10-31 18:42
> Does anyone got any ideas or clues ?

If you buy a brand new ship and without modifying anything does it have the same problem?

**Comment by HTMLPhoton** [comment] 2022-01-22 05:34
> the usage of power (? - the nuclear symbol) is not proportional to the flight length
@mdziczkowski : They yellow vertical bar on the very right is not you power, it is your hyperspace fuel, and aside from a few other uses, it is used only to perform hyperspace jumps. Your power stored is the white bar.
![image](https://user-images.githubusercontent.com/61311312/150626321-8db3f3fe-414a-4b67-8db6-89c54085800e.png)

**Comment by mdziczkowski** [comment] 2022-01-23 08:19
@HTMLPhoton To check the possible reason, I had exited the ship's parameters and maxes out the engines power, cooking, shild, etc., and even lowered it'sweight, but this didn't helped. The ship still acted like it wouldn't have any energy in the engines, were having an huge weight and damaged any controls.

This way it was like an sitting duck and a shooting sield target for anyone else

**Comment by ixPost** [comment] 2022-03-07 12:04
> the steering is very hard (in compare, it's like you need a level to lift a big object)

I think that eider your running out of electricity (Plasma trusters & steering trusters  use electricity instead of hyperspace fuel.) (In order to avoid running out of electricity you need bigger/more batterys/supercapacitors or more generators or a bigger generator.) or - if it happens when some one is attacking you then your jumping to and from "_fighting_" mode. "_Fighting mode_" as I call it is that you "_lock_" with the ship that is attacking/fighting you.

**Comment by mdziczkowski** [comment] 2022-03-07 14:10
> I think that eider your running out of electricity (Plasma trusters & steering trusters use electricity instead of hyperspace fuel.) (In order to avoid running out of electricity you need bigger/more batterys/supercapacitors or more generators or a bigger generator.) or - if it happens when some one is attacking you then your jumping to and from "_fighting_" mode. "_Fighting mode_" as I call it is that you "_lock_" with the ship that is attacking/fighting you.

Actually, you are not correct. I had experimented and even after changing the values of energy, etc. in the propper files, the ship was still reacting same way, like the values wouldn't have much influence on the ship's movement

**Comment by ixPost** [comment] 2022-03-09 09:46
How did you figure out my email?

**Comment by Zitchas** [comment] 2022-03-12 13:41
I'm not sure what you are referring to, but if you suddenly got an email with a reply to this thread, then no-one figured out your email, it's just github deciding that - since you participated in this issue - to email replies from this thread to your email. You can change this in your preferences.

**Comment by mdziczkowski** [comment] 2022-03-12 19:37
Hello. I fon't know any participant't e-mail. I'm just this ticket's author. I don't know why it has been closed, because it hasn't become solved

**Comment by MCOfficer** [comment] 2022-03-12 21:33
To clarify: This started as a bit of a mess of several issues. Some of those are intended features, some are simply not possible without user error. Several educated guesses were made, none found the issue - and with what few information we have, nothing could be reproduced. For instance, we don't even know what version of the game you're running.

Based on that, the only assumption one can make is that there is in fact no issue, and the error is somewhere on your end. Providing more information could change this assumption.

For starters:
- What's your game version? Where did you get it from?
- What's your OS?
- In what circumstances do you experience the issue?
- What behavior do you expect, and what is happening instead?
- Can you reproduce this on an uptodate version with no plugins installed?

**Comment by mdziczkowski** [comment] 2022-03-15 08:03
@MCOfficer To clarify: Because the issue was too complex to write it strightly, I attempted to describe the "symptoms" of what was happening, answering on the asked questions.

All described in the issue problems are connected with it and I'm not sure if they should be also as separate ones.

> * What's your game version? Where did you get it from?

* Version:  0.9.12
* Downloaded from: https://endless-sky.github.io

> * What's your OS?

Debian  based Linux

> * In what circumstances do you experience the issue?

After starting the game, in the cosmos view

> * What behavior do you expect, and what is happening instead?

* Expected: possibility to do normal flight
* Current: except turning around, the ship has difficulties to move from the place and when starting the "jump", the message that is beeing started appear, but nothing more happens

> * Can you reproduce this on an uptodate version with no plugins installed?

I use the game without any plugins installed

**Comment by MCOfficer** [comment] 2022-03-15 11:02
Hm. We've never heard of movement issues on this scale before, so there's either a mistake or your system is one hell of an edge case.

Does this happen with an entirely new pilot too? Just create a clean pilot, choose any ship, decline the tutorial and launch. Same behavior? 
Providing a screen recording would also help us understand the issue a bit better.


Also, 0.9.12 is a rather dated release and there have been some changes to movement since then. Can you reproduce the issue with 0.9.14 or ideally the Continuous Build? Both can be found [here](https://github.com/endless-sky/endless-sky/releases).

**Comment by ixPost** [comment] 2022-03-16 18:34
Debian based Linux
Great!!!

**Comment by ixPost** [comment] 2022-03-16 18:41
You mean that GitHub sent my email to you? or did it show the conversation
in my inbox?

**Comment by Zireael07** [comment] 2022-03-16 19:04
@ixPost: Both, I suppose, since we can see your two latest comments with a mail icon.

**Comment by mdziczkowski** [comment] 2022-03-18 19:23
Sorry for the delay, but my pc has broke up and I'm temporary unable to test it on the newest version and from the phone is impossible to compile it from the sources ;-p

Currently it's in the service and I should get something know about it in between 21 and 25 March

**Comment by ixPost** [comment] 2022-04-03 17:10
Thank you for clearing that up \).

**Comment by petervdmeer** [comment] 2024-06-30 10:28
Closing: this issue hasn't received updates in 2 years, and we seem to have insufficient information to reproduce the reported issue.

**Closed by petervdmeer** 2024-06-30 10:28 UTC
Labels: bug, unconfirmed, waiting on OP
