### ISSUE TITLE
Variability to Outfitters Inventory

### ISSUE THREAD

**Issue by VonZorch** [endless-sky/endless-sky#2720] opened 2017-07-06 18:48 UTC
Please add parameters to the outfit line in an outfitter block to be able to have a chance of being on stock, the amount on hand and a price modifier.
For instance.
outfitter Junkyard
     outfit Gizmo a20 c10 p1.5
     outfit Doohickey a75 c 5,10
Where Gizmo is available 20% of the time, when available there are only 10 for sale and cost one and a half times normal cost.  And Doohickey is available 75% of the time with a random 5 to 10 on hand at normal cost.
Of course anything not specified will use the current default behavior.
This could be applied to shipyards too.  A pirate or refurbisher shipyard might have any ship, just not very often.

**Comment by Bladewood** [comment] 2017-07-06 18:49
I can see this creating a lot of frustration.

**Comment by Amazinite** [comment] 2017-07-06 18:52
Duplicate of a few issues. #1823

**Comment by endless-sky** [comment] 2017-07-06 18:59
Imagine how annoying it would be if you are trying to outfit a new ship, and in addition to having to fly around to various outfitters to collect whatever you need, you also occasionally have to wait around for a particular outfit to appear in that particular outfitter. All it would add to the game would be an artificial barrier that makes it harder to buy certain outfits, and that would make the game less fun, not more fun.

**Comment by VonZorch** [comment] 2017-07-06 21:42
@endless-sky
I wasn't seeing it to change what outfitters normally had on hand but a way to have very small outfitters to have a chance of having something better than normal on hand.  Like the outfitter on New Boston or Clark having, very rarely, an AR500 or 800 series engine in taken off a ship someone else sold.

I am getting an idea on how to do the chance of availibility with missions.  Are there any hooks to outfitter in stock attribute usable from missions?

Of course it is your game, if you don't want to deal with it close the issue.

But what are the source files for outfitters and shipyards?  I may try to do the change myself.

**Comment by tehhowch** [comment] 2017-07-06 22:00
Right now, only events can modify the contents of shipyards and outfitters, and those are only removed by other events. You could have a weekly recurring event (handled by invisible missions) to add or remove certain outfits from certain locations.
This is generally in map.txt and sales.txt

**Comment by gunqqer** [comment] 2017-07-07 15:56
I like the idea of smaller outfitters having the chance of having outfits that they don't normaly have. So nothing like you have a 1/10 chance of being able to buy the outfit you want, just go to a place where it's normaly sold.


Now, is it worth doing? Maybe not

**Closed** 2017-09-01 14:36 UTC
Labels: unlikely
