### ISSUE TITLE
Teleporter Bay?

### ISSUE THREAD

**Issue by Mark11110** [endless-sky/endless-sky#6251] opened 2021-09-15 09:22 UTC
### Problem Description

The purpose of this outfit is improve quality of life of a starfleet captain and to protect the captain from losing his life during a boarding operation.

### Related Issue Links

n/a

### Desired Solution

What do you guys think of a Teleporter Bay outfit?
Application includes:
1. Switching flagship: Player can teleport to another ship without having to land on a planet.
2. Less risky boarding: Whenever enemies shields are down, you can teleport your crew to board that ship without risking your own life
3. Move crew around: Need more crew, replenish your own by beaming crews from your own fleet.
4. Beam enemy outfits into your cargo without boarding provided the shields are down.
5. Beam asteroids you mined!
6. Beam enemy crews out into space without fighting (joke)

Note: Beware! Enemy ships can also use this strategy against you. Gives you more reason to keep your shields up.
### Alternative Approaches
Some other things in mind
Anti-teleportation devices to prevent ambush
Advance teleportation device that bypass shields (of course, they will only target the player and not his fleet, because... game logic)

### Additional Context

maybe your fleet can also board enemy crews using the teleporter bay?

**Comment by Zitchas** [comment] 2021-09-15 12:28
While a teleportation outfit would be entertaining, it is very unlikely to be implemented for a variety of reasons:

A. Requires a bunch of extra coding to allow boarding to be triggered in situations that normally don't allow it (at range, when not disabled)
B. Boarding and the attendant looting & capturing area already the best money making activity in the game for most of the game. (only commodity trading with massive fleets exceeds it in terms of profit) Making salvaging and capturing easier would make these completely OP, especially when they can be done on ships that aren't even disabled yet.
C. The game-breakingness of how easy it would be to capture *anything* using a fleet is one of the key reasons that mechanics allowing us to change ships in-flight hasn't been implemented. Anything that allows us to move crew around would be equally problematic. Yes, this would be realistic. Just as it would be realistic to allow us to gang-board a ship with a dozen star queen's worth of troops in order to swarm defenders under. But ensuring that anything can be captured by anything (if only you have enough of them) isn't something that is particularly desirable.
D. The risk of the captain (player) dying is one of the few balancing elements of the current boarding operations that discourages players from trying to capture things too big for them. 
E. On the lore side, nowhere in the game does any faction mention teleportation technology of any kind. That being said, it is widely believed that the Quarg ringworlds are capable of teleporting ships between them, but this has never been seen to happen and is just a supposition. So even if such an outfit were created, the lore would only support it being found on Quarg or possibly the "high level" pug ships (not the ones encountered during the FW pug invasion, but rather the ones that would theoretically come out for a war against the Quarg). So even if implemented, there's no-one that would a suitable place for the players to acquire said technology.

**Comment by Amazinite** [comment] 2021-09-15 13:26
Most of the mechanics that this teleporter would allow have been requested individually in the past, many of which have been rejected.

1. Can't find a specific issue for this one, but I know this idea has been rejected on similar grounds to point 3.
2. Mechanically similar to and rejected by #2185.
3. Rejected by #808.
4. That'd just be busted, and would essentially make hull a worthless stat as soon as teleporters come into play. 
5. Duplicate of #4699.
6. Rejected by #1503.

**Closed** 2021-09-19 15:42 UTC
Labels: unlikely
