### ISSUE TITLE
If selected shop item becomes hidden, arrow keys select wrong item

### ISSUE THREAD

**Issue by tehhowch** [endless-sky/endless-sky#3088] opened 2017-09-28 07:03 UTC
If using the checkboxes to filter the displayed Outfitter inventory (e.g. to only outfits installed on ships) and then sell the last of the selected outfit that is equipped on your ship / in cargo, the selected outfit disappears from view, but remains selected. No matter the relative position of this outfit when installed on your ship, attempting to advance to (what would have been) the next item via the Right arrow key will result in selection of the first outfit in the list.

Expected behavior: selection of the next visible item when the last of a visible item is sold.

One possible fix is to use an iterator to find the selectedOutfit in the relevant "container" (player.Cargo().Outfits() or the pooled outfits from selected ships), and then advancing this iterator if the outfit is no longer to be displayed. This does have an issue though, as the iterator order is not alphabetical like the outfitter (e.g. the newly selected outfit appears to be randomly picked).

**Comment by endless-sky** [comment] 2017-10-08 20:36
This does have some useful effects. For example, if you're viewing only your ship's outfits and you click "sell" on an outfit by accident, it's handy to be able to just click "buy" to get it back, even though it has disappeared from the view.

**Comment by tehhowch** [comment] 2017-10-09 15:11
Indeed, I have used that aspect of it in the past. I don't see a simple and easy-to-understand solution to both keeping that "oops I sold one too many" behavior, and adding the behavior of auto-selecting the next outfit in the list. My thoughts were that a timeout could be used - e.g. if rapidly clicking sell, keep advancing through the outfits that are shown, but if the user pauses for X seconds, keep the selection the same even if not displayed.

This issue still remains though:
 - Right-arrow does not select the would-have-been next outfit, but instead it selects the first outfit.

**Comment by IsocratesGrey** [comment] 2023-03-10 18:26
This has been fixed as of 0.10.0. Now the arrow keys do not allow you to move away from the sold item if you can't see it in your current view. Recommend we close this issue, as it is not a bug any more, but is now a feature.

**Comment by flowers9** [comment] 2023-07-29 21:18
>This does have some useful effects. For example, if you're viewing only your ship's outfits and you click "sell" on an outfit by accident, it's handy to be able to just click "buy" to get it back, even though it has disappeared from the view.

It is certainly true that a solution like #9091 eliminates the convenience of easily rebuying outfits you accidentally sold.  However, it does offer one in return - since the selection advances to the next item when one becomes hidden, you can sell everything from a ship just by holding down 's' (when viewing only your ship's outfits).

**Closed** 2024-01-20 23:30 UTC
Labels: bug
