### ISSUE TITLE
Vanguard hardpoints are off

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1791] opened 2016-10-29 20:07 UTC
![vanguardfail](https://cloud.githubusercontent.com/assets/16506683/19832448/d09b6976-9df1-11e6-982f-9ee6b046f6e2.png)

**Comment by toilethinges** [comment] 2016-10-29 21:14
...uhhhh, yeah...

**Comment by jafdy** [comment] 2016-10-29 21:39
Looks fine to me.

**Comment by Amazinite** [comment] 2016-10-29 21:45
@jafdy the hardpoint coordinates are located ahead of the actual guns on the sprites, same as the Rainmaker.

**Comment by Bladewood** [comment] 2016-10-29 21:50
You should have at least noticed the floating thruster flare sprites :|

**Comment by jafdy** [comment] 2016-10-29 22:00
I've found the problem. The engines need to move by -15 in y the weapons except the central gun needs to move by +10 in y.

**Comment by Pointedstick** [comment] 2016-10-30 01:26
This was my bad, sorry. I didn't realize there was a visual tool to do the hardpoints way back when I created the Vanguard, and the problem isn't obvious unless you use beam-type guns.

**Comment by toilethinges** [comment] 2016-10-30 03:07
@Pointedstick, it looks great with the guns it normally uses (Proton/Particle cannons)!

(Unrelated, does anyone else use the Vanguard? I like its appearance and, with 7 Particle Cannons, it can do some good damage to Korath Raiders.)

**Comment by Amazinite** [comment] 2016-10-30 03:16
(If not Bactrian then usually Vanguard for me, in terms of human warships).

**Comment by Bladewood** [comment] 2016-10-30 03:17
Dreadnought.
If you want particle cannon spam, go for a Kestrel.

**Comment by Pointedstick** [comment] 2016-10-30 03:47
Derecho with quad Sunbeam turrets for me. I often run around in a Vanguard with 7 Proton cannons during earlier parts of the Free Worlds campaign, though. It's a heck of a lot more fun than the Protector (which is why I made it).

**Comment by Johny-Cash** [comment] 2016-10-30 18:42
All flamethrower suicide troop. The Vanguard is great for this.

**Comment by KiLEdEnNis** [comment] 2016-10-30 19:03
full Flamethrower & Dual Sunbeam, & fuel pods
lolk Vanguard > Korath

**Comment by Bladewood** [comment] 2016-10-30 19:14
But... shield beetle...

**Comment by Admiral-Danforth** [comment] 2016-10-30 19:44
But... Pug Maboro

**Comment by KiLEdEnNis** [comment] 2016-10-30 22:44
but... Archon
lolk

**Comment by Admiral-Danforth** [comment] 2016-10-30 23:06
Archon makes a great ship, but if you use more than one they end up killing each other.

**Comment by Bladewood** [comment] 2016-10-30 23:19
They do not :|
(yes, I tried this, and in fact I did it a few hours ago)

**Comment by LocalGod79** [comment] 2016-10-31 04:21
@Bladewood, a fix has been implemented.

if you are finished your misplaced Steam-talk, would you be so kind as to close this issue?

**Comment by Bladewood** [comment] 2016-10-31 11:21
Of course.

**Comment by Bladewood** [comment] 2017-06-17 17:34
Post-turret hardpoint sprite additions.

What we have **now**:
![vanguardfail3](https://user-images.githubusercontent.com/16506683/27254954-abefb4c6-5361-11e7-8a1b-1276320ab752.png)
(Closer to) what we **should** have:
![vanguardfail4](https://user-images.githubusercontent.com/16506683/27254955-b1808ed8-5361-11e7-94ec-72f8746669d9.png)

**Comment by endless-sky** [comment] 2017-06-17 18:32
Fixed in 4596382.

**Closed** 2017-06-17 20:09 UTC
Labels: content
