### ISSUE TITLE
Logbook Faction entries repeating themselves

### ISSUE THREAD

**Issue by shitwolfymakes** [endless-sky/endless-sky#4355] opened 2019-06-10 04:05 UTC
**Describe the bug**
In the Logbook, the initial faction description for Syndicate, Republic, and Pirate are each repeated 3 times

**To Reproduce**
1. Go to 'Logbook'
2. Click on 'Factions'
3. Scroll down to Syndicate, Republic, and Pirate

**Expected behavior**
It's only supposed to print this once each

**Screenshots**
<img width="389" alt="Pirate log entry" src="https://user-images.githubusercontent.com/18581815/59171904-8b03fa80-8b02-11e9-8222-93dbad9091ce.png">
<img width="402" alt="Republic log entry" src="https://user-images.githubusercontent.com/18581815/59171905-8b03fa80-8b02-11e9-9fd3-3590f500a971.png">
<img width="395" alt="Syndicate log entry" src="https://user-images.githubusercontent.com/18581815/59171906-8b03fa80-8b02-11e9-887f-d36047b7781b.png">

**System (please complete the following information):**
 - OS: Mac OS Mojave 10.14.5
 - Game Source: Steam beta
 - Version: 0.9.9

**Link to save file**
[Silas Wolf.txt](https://github.com/endless-sky/endless-sky/files/3270526/Silas.Wolf.txt)

**Comment by Amazinite** [comment] 2019-06-10 04:06
Duplicate of https://github.com/endless-sky/endless-sky/issues/3746.

**Comment by shitwolfymakes** [comment] 2019-06-10 04:07
It is not

**Comment by Amazinite** [comment] 2019-06-10 04:09
I just started a new pilot and only get one of each entry. This looks like it's just a duplicate of #3746.
It doesn't need to be in a `to offer` to be repeated under the conditions of #3746.

**Comment by shitwolfymakes** [comment] 2019-06-10 04:10
Hmmm. Okay, I hadn't started a new pilot

**Comment by Amazinite** [comment] 2019-06-10 04:12
The logs you're showing as repeated are from the `on offer` of `Intro [0]`. I even mention in #3746 that I got them to repeat under the same conditions.

**Closed** 2019-06-10 04:17 UTC
Labels: duplicate
