### ISSUE TITLE
[feature request] Warehouse to store outfits

### ISSUE THREAD

**Issue by SkyFire512** [endless-sky/endless-sky#5166] opened 2020-07-19 14:22 UTC
With the depreciation mechanics in place, it is no longer feasible to convert all your looted assets to credits. While pirate hunting, I sometimes capture ships with outfits that I do not require immediately but will require later. The only way to keep these outfits safe is to either haul them in your cargo (not scalable) or to attach them to a defunct warship and park said ship. I now effectively own multiple 'warehouse warships' that serve no purpose but to hold outfits so I do not have to buy them at full price later.

Desired solution:
A way to store outfits. Il leave the exact implementation upto the experts.

Alternatives:
In the outfit menu, add a 'ship' icon denoting your warehoused goods on that spaceport. You may freely store and retrieve outfits out of this warehouse.

Screeshot:
Here is an example of one my warehouse warships.
![image](https://user-images.githubusercontent.com/30810454/87876957-dde1fe00-c9f4-11ea-828f-cc9ba43511c6.png)

**Comment by Amazinite** [comment] 2020-07-19 14:25
Duplicate of #3879, #3874, #724. Already have an open PR for outfit storage with #4443.

**Comment by SkyFire512** [comment] 2020-07-19 14:53
Hi, thanks for linking those, I feel silly now :P

**Closed** 2020-07-19 14:52 UTC
Labels: duplicate
