### ISSUE TITLE
Flycatchers can be hailed but fail to repair disabled ships

### ISSUE THREAD

**Issue by retrue** [endless-sky/endless-sky#2174] opened 2017-02-23 14:29 UTC
Version 0.96 stable.
If you are disabled you can hail a flycatcher and ask for help and it answers that help is coming. Then it tries to board you to repair your ship but if fails, staying around trying. It cannot repair other disabled ships either. If there is a combat and they cannot repair they should be attacking/defending instead.
If flycatchers are deemed too small to repair ships, the AI of the flycatcher should be changed so they don't try to board and repair and a message should be provided.
Sugestion: maybe flycatchers could repair small ships like other drones and small fighters.

**Comment by Amazinite** [comment] 2017-02-23 14:31
> the AI of the flycatcher 

drone in general*

**Comment by MCOfficer** [comment] 2017-02-23 16:06
maybe i'm already known to think very realistic (and comment on any post there is), but i think drones (or robot ships in general) should not be able to repair anything, unless a korach systems core or something similiar is installed. a drone is built for flying, shooting and scanning, there is no way it could repair anything. 
(furthermore, a sparrow should not be able to repair a bactrian. but that is offtopic)
however, given that a drone can't repair anything, it shouldn't answer a help call. true that.

**Comment by KiLEdEnNis** [comment] 2017-02-23 16:07
everything in the category drone is already supposed to not be able to repair (if I remember correctly)

**Comment by MCOfficer** [comment] 2017-02-23 16:36
sorry for the wording used, i guess i was a bit unclear. i was referring to the OP, not the current state of the game.

**Comment by endless-sky** [comment] 2017-03-23 02:53
What's happening is that because it's a "Drone," it's trying to fly into your ship instead of repairing you. I think the simplest solution would be to just not allow fighters and drones to make repairs.

**Comment by Bladewood** [comment] 2017-03-23 11:37
*Korath raider*

**Comment by endless-sky** [comment] 2017-03-25 00:48
Fixed in commit 857740e.

**Comment by Bladewood** [comment] 2017-03-25 00:50
The nightmares of constantly killing Korath raiders while trying to get to their chasers are over.

**Comment by endless-sky** [comment] 2017-03-25 01:29
Yes, the Chaser thing was never intended behavior in the first place. I just didn't bother to fix it before now because it was sort of humorous.

**Comment by Bladewood** [comment] 2017-03-25 01:32
tch.

**Closed** 2017-07-21 21:00 UTC
Labels: mechanics
